scaleway/docs-content

tutorials/install-docker-ubuntu-jammy-jellyfish/index.mdx
=> docs(tutorial): Install Docker Engine on Ubuntu 22.04

storage/object/api-cli/bucket-policy.mdx, storage/object/api-cli/object-lock.mdx, storage/object/concepts.mdx
=> fix(S3): remove mentions of IAM not available MTA-3527

compute/instances/concepts.mdx
=> docs(instances): update instances concept

containers/kubernetes/how-to/monitor-cluster.mdx
=> docs(fix): fix typo

containers/kubernetes/how-to/change-container-runtime-interface.mdx, containers/kubernetes/reference-content/version-support-policy.mdx, dedibox-network/network/reference-content/anti-ddos.mdx, network/domains-and-dns/how-to/manage-external-domain.mdx, serverless/containers/how-to/secure-a-container.mdx, serverless/functions/how-to/secure-a-function.mdx
=> docs(review): review content

contribute.mdx
Updated wording write for community program
=> docs(fix): wording writers program

console/my-account/reference-content/products-availability.mdx
=> docs(console): available zones

bare-metal/apple-silicon/quickstart.mdx, compute/instances/troubleshooting/bootscript-eol.mdx, console/my-account/reference-content/account-quotas.mdx, menu/navigation.json, serverless/containers/reference-content/containers-limitations.mdx, serverless/functions/reference-content/functions-limitations.mdx, serverless/messaging/reference-content/limitations.mdx
Changed the term "account quotas" to "Organization"
updated: 
- title
- slug
- url
https://jira.infra.online.net/browse/WDOC-635
https://jira.infra.online.net/browse/MTA-3360
=> fix(uapi): url and wording update

compute/instances/api-cli/using-routed-ips.mdx
=> docs(fix): fix small typo

serverless/functions/reference-content/code-examples.mdx
fix serverless python body parsing example
=> doc(fix) - Serverless python example

changelog/august2023/2023-08-10-postgresql-and-mysql-added-managed-database-supports-now.mdx
=> feat(changelog): postgresql-and-mysql-added-managed-database-supports-now 2023-08-10

managed-databases/postgresql-and-mysql/concepts.mdx
Update PostgreSQL available versions
=> feat(rdb): bump PostgreSQL available versions

tutorials/configure-smtp-relay-tem/index.mdx
=> docs(tem): tutorial on configuring TEM's smtp relay

bare-metal/apple-silicon/quickstart.mdx, menu/navigation.json, serverless/containers/reference-content/containers-limitations.mdx, serverless/messaging/reference-content/limitations.mdx
Following [MTA-3360](https://jira.infra.online.net/browse/MTA-3360), the navigation label must also be updated. 
Moreover, all the references to "Account quotas" in the documentation must be changed to "Organization quotas".
=> fix(doc): navigation label update

serverless/sql-databases/concepts.mdx, serverless/sql-databases/how-to/connect-to-a-database.mdx, serverless/sql-databases/how-to/create-a-database.mdx, serverless/sql-databases/how-to/manage-permissions.mdx, serverless/sql-databases/quickstart.mdx
=> fix(SDB): fix misplaced bullet points MTA-3574

containers/kubernetes/how-to/edit-kosmos-cluster.mdx
preserve environment with sudo
=> fix(kosmos): agent command

tutorials/minikube-elastic-metal/index.mdx
=> docs(fix): misaligned lines

serverless/functions/api-cli/deploy-function-api.mdx, serverless/functions/api-cli/deploy-function-cli-api.mdx, serverless/functions/api-cli/deploy-function-cli.mdx, serverless/functions/reference-content/deploy-function.mdx
=> docs(FNC): add CLI/API procedures to deploy functions MTA-3589

changelog/august2023/2023-08-22-cockpit-changed-cockpit-feature-request-is.mdx
=> feat(changelog): cockpit-changed-cockpit-feature-request-is 2023-08-22

changelog/august2023/2023-08-22-instances-added-new-availability-zone-waw-3.mdx
=> feat(changelog): instances-added-new-availability-zone-waw-3 2023-08-22

managed-databases/postgresql-and-mysql/how-to/upgrade-version.mdx
=> fix(rdb): remove info message about RDB upgrade limitation

menu/navigation.json, serverless/functions/troubleshooting/common-errors.mdx, serverless/functions/troubleshooting/index.mdx
=> docs(FNC): add troubleshooting for Serverless functions MTA-3590

serverless/messaging/api-cli/python-node-sns.mdx, serverless/messaging/api-cli/python-node-sqs.mdx
Fixed anchors on messaging pages
=> docs(messaging): fix anchors

bare-metal/elastic-metal/api-cli/index.mdx, dedibox/kvm-over-ip/how-to/quantaplex.mdx, menu/navigation.json, serverless/functions/api-cli/index.mdx, serverless/functions/troubleshooting/common-errors.mdx, serverless/functions/troubleshooting/index.mdx, tutorials/deploy-clickhouse-database/index.mdx, tutorials/plausible-analytics-ubuntu/index.mdx
=> fix(doc): fix breaking error in metadata + typos MTA-3604

serverless/messaging/api-cli/python-node-sns.mdx
=> docs(fix): broken wording

compute/instances/api-cli/migrating-instances.mdx, console/my-project/how-to/generate-api-key.mdx, containers/kubernetes/how-to/enable-easy-deploy.mdx, identity-and-access-management/iam/how-to/create-api-keys.mdx, identity-and-access-management/iam/how-to/manage-api-keys.mdx, tutorials/abort-multipart-upload-minio/index.mdx, tutorials/configure-nodemcu-iot-hub/index.mdx, tutorials/configuring-loadbalancer-wordpress/index.mdx, tutorials/deploy-instances-packer-terraform/index.mdx, tutorials/deploy-laravel-on-serverless-containers/index.mdx, tutorials/deploy-saas-application/index.mdx, tutorials/get-started-containers-docker/index.mdx, tutorials/get-started-deploy-kapsule/index.mdx, tutorials/get-started-kubernetes-loadbalancer/index.mdx, tutorials/odoo-easy-deploy/index.mdx, tutorials/postman-api/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx, tutorials/use-container-registry-github-actions/index.mdx
Fixed typos and corrected the casing in 'API Key' > 'API key'.
=> fix(docs): wording correction

menu/navigation.json, serverless/containers/troubleshooting/common-errors.mdx, serverless/containers/troubleshooting/index.mdx, serverless/functions/troubleshooting/index.mdx
=> docs(SRV): add containers troubleshooting MTA-3603

compute/instances/reference-content/cost-optimized.mdx, identity-and-access-management/secret-manager/how-to/delete-secret.mdx, identity-and-access-management/secret-manager/how-to/delete-version.mdx, identity-and-access-management/secret-manager/how-to/manage-secret.mdx, identity-and-access-management/secret-manager/how-to/manage-version.mdx, serverless/functions/how-to/package-function-dependencies-in-zip.mdx, tutorials/ansible-bionic-beaver/index.mdx, tutorials/focalboard-project-management/index.mdx, tutorials/prometheus-monitoring-grafana-dashboard/index.mdx, tutorials/pulumi-functions/index.mdx, tutorials/wireguard-mesh-vpn/index.mdx, tutorials/wordpress-lemp-stack-ubuntu-jammy-jellyfish-22-04/index.mdx, tutorials/zammad-ticketing/index.mdx
=> docs(tutorials): content review week 35/2023

storage/object/concepts.mdx
=> fix(S3): fix broken link in concepts MTA-3613

serverless/functions/how-to/add-trigger-to-a-function.mdx
=> fix(srv): fix misleading term in function trigger how to MTA-3615

console/my-account/concepts.mdx
=> fix(CXP): add password concept + typo + links MTA-3616

storage/block/quickstart.mdx
Fixed fstab command for block storage in quickstart guide
=> docs(storage): block - fix quickstart

changelog/august2023/2023-08-31-postgresql-and-mysql-added-promote-a-read-replica.mdx
=> feat(changelog): postgresql-and-mysql-added-promote-a-read-replica 2023-08-31

containers/kubernetes/reference-content/version-support-policy.mdx
=> docs(k8s): add k8s 1.28

compute/instances/reference-content/production-optimized.mdx
=> docs(instances): add par3 and ams3 az to pop2 inst

faq/kubernetes.mdx
=> docs(k8s): fix wording

faq/kubernetes.mdx
=> docs(fix): wording k8s faq

changelog/august2023/2023-08-31-messaging-and-queueing-deprecated-sqs-and-sns-namespace.mdx
=> feat(changelog): messaging-and-queueing-deprecated-sqs-and-sns-namespace 2023-08-31

faq/serverless-functions.mdx
=> fix(SRV): update serverless functions billing example MTA-3622

tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
=> fix(tutorials): fix indexation issue with Functions tutorials MTA-3624

changelog/september2023/2023-09-01-kubernetes-added-new-availability-zone-waw-3.mdx
=> feat(changelog): kubernetes-added-new-availability-zone-waw-3 2023-09-01

tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
No way of checking if changes fixed issues with local build, it has to run through deploy pipeline.
Fix did not work as tutorials categories must contain "functions" and not only "serverless".
Therefore, adding "functions" to categories in meta header.
=> fix(tutorials): fix tutorials indexation (again) MTA-3625

changelog/september2023/2023-09-01-kubernetes-added-kubernetes-version-1.28-is.mdx
=> feat(changelog): kubernetes-added-kubernetes-version-1.28-is 2023-09-01

console/my-account/quickstart.mdx
Removed mention to marketing checkbox in account creation because we removed it
=> fix(console): remove mention of marketing checkbox in account creation

tutorials/proxy-protocol-v2-load-balancer/index.mdx
=> fix(tutorial): wrong annotations indent for proxy-protocol on kapsule

changelog/september2023/2023-09-04-object-storage-fixed-migration-to-hive-backend.mdx
=> feat(changelog): object-storage-fixed-migration-to-hive-backend 2023-09-04

.github/workflows/changelog-contribution.yml
Added Samy in the list of reviewers for the changelog
=> docs(add): added samy as reviewer

faq/objectstorage.mdx
=> fix(S3): remove mentions of old backend in FAQ MTA-3631

macros/console/region-and-az.mdx
=> fix(docs): update Region & AZ macro MTA-3643

serverless/functions/concepts.mdx, serverless/functions/how-to/add-trigger-to-a-function.mdx
=> fix(SRV): update functions trigger page and concepts MTA-3644

storage/object/api-cli/bucket-policy.mdx
=> fix(S3): fix typo in bucket policy version MTA-3649

observability/cockpit/api-cli/configuring-grafana-agent.mdx
Add the collectors like in this doc: https://www.scaleway.com/en/docs/observability/cockpit/reference-content/understanding-cockpit-usage/
=> fix(cockpit): Update agent configuration to prevent high bill

changelog/september2023/2023-09-06-kubernetes-added-dedicated-control-plane-offers.mdx
=> feat(changelog): kubernetes-added-dedicated-control-plane-offers 2023-09-06

compute/instances/concepts.mdx
=> fix(INS): instance definition MTA-3656

serverless/functions/how-to/create-a-function.mdx, serverless/functions/how-to/create-a-functions-namespace.mdx, serverless/functions/quickstart.mdx
=> docs(SRV): update doc following user flow revamp MTA-3654

console/my-account/reference-content/products-availability.mdx, menu/navigation.json, network/load-balancer/how-to/create-load-balancer.mdx, network/load-balancer/quickstart.mdx
Add AMS-3 as LB AZ, and correct grammar of Product Availability doc
=> fix(lb): add AMS3 availability

changelog/september2023/2023-09-07-kubernetes-changed-kapsule-and-kosmos-clusters.mdx
=> feat(changelog): kubernetes-changed-kapsule-and-kosmos-clusters 2023-09-07

storage/object/concepts.mdx, storage/object/how-to/manage-lifecycle-rules.mdx
=> fix(S3): add Tags and Prefix concepts and update Bucket policy doc MTA-3633

changelog/september2023/2023-09-13-load-balancers-added-load-balancer-is-now.mdx
=> feat(changelog): load-balancers-added-load-balancer-is-now 2023-09-13

network/public-gateways/how-to/configure-a-public-gateway.mdx
Tidy up PGW doc for changes brought to console during VPC GA
=> fix(pgw): add bits of new info

compute/instances/reference-content/learning.mdx
=> fix(instance): update learning/stardust info

changelog/september2023/2023-09-15-instances-added-stardust-learning-instances-in.mdx
=> feat(changelog): instances-added-stardust-learning-instances-in 2023-09-15

compute/gpu/concepts.mdx
=> docs(gpu): add concepts

compute/gpu/concepts.mdx, compute/gpu/how-to/use-nvidia-mig-technology.mdx, compute/gpu/how-to/use-preinstalled-env.mdx, compute/gpu/how-to/use-scratch-storage-h100-instances.mdx, menu/navigation.json
Added documentation about scratch storage on H100 Instances
=> docs(gpu):scratch-storage

compute/gpu/how-to/use-nvidia-mig-technology.mdx, compute/gpu/how-to/use-scratch-storage-h100-instances.mdx, menu/navigation.json
=> docs(gpu): fix broken link

changelog/september2023/2023-09-18-transactional-email-added-the-scaleway-blackhole-mx.mdx
=> feat(changelog): transactional-email-added-the-scaleway-blackhole-mx 2023-09-18

compute/instances/how-to/power-off-instance.mdx
=> docs(instances): fix wording

changelog/september2023/2023-09-18-object-storage-added-access-logs-now-available.mdx
=> feat(changelog): object-storage-added-access-logs-now-available 2023-09-18

serverless/sql-databases/how-to/add-users.mdx, serverless/sql-databases/how-to/configure-autoscaling.mdx, serverless/sql-databases/how-to/connect-to-a-database.mdx, serverless/sql-databases/how-to/create-a-database.mdx, serverless/sql-databases/how-to/delete-a-database.mdx, serverless/sql-databases/how-to/manage-permissions.mdx, serverless/sql-databases/quickstart.mdx
=> fix(sdb): add private beta registration as requirement MTA-3684

changelog/september2023/2023-09-19-postgresql-and-mysql-added-cross-availability-zone-read.mdx
=> feat(changelog): postgresql-and-mysql-added-cross-availability-zone-read 2023-09-19

network/load-balancer/how-to/create-load-balancer.mdx, network/load-balancer/how-to/use-with-private-network.mdx
=> fix(lb): fix validation dates

changelog/september2023/2023-09-19-load-balancers-deprecated-static-attachment-of-load.mdx
=> feat(changelog): load-balancers-deprecated-static-attachment-of-load 2023-09-19

changelog/september2023/2023-09-19-load-balancers-added-private-load-balancers-now.mdx
=> feat(changelog): load-balancers-added-private-load-balancers-now 2023-09-19

compute/instances/quickstart.mdx
Removed deprecated warning banner
=> docs(instances): removed deprecated warning

compute/gpu/how-to/use-mig-with-kubernetes.mdx, compute/gpu/how-to/use-nvidia-mig-technology.mdx, compute/gpu/how-to/use-scratch-storage-h100-instances.mdx, menu/navigation.json
=> docs(gpu): mig with k8s

serverless/sql-databases/how-to/connect-to-a-database.mdx, serverless/sql-databases/quickstart.mdx
=> fix(sdb): add command to check version in QS and how to MTA-3693

network/load-balancer/how-to/add-certificate.mdx
Add clarification and correction to LB certificate doc
=> fix(lb): add cert clarifications

compute/gpu/how-to/use-mig-with-kubernetes.mdx, compute/gpu/how-to/use-nvidia-mig-technology.mdx
=> docs(gpu): update warning message

changelog/september2023/2023-09-21-messaging-and-queuing-added-messaging-and-queuing-metrics.mdx
=> feat(changelog): messaging-and-queuing-added-messaging-and-queuing-metrics 2023-09-21

tutorials/deploy-big-blue-button/index.mdx, tutorials/deploy-instances-packer-terraform/index.mdx, tutorials/encrypt-volumes/index.mdx, tutorials/flask/index.mdx, tutorials/foreman-puppet/index.mdx, tutorials/gitlab-instant-app/index.mdx, tutorials/glpi/index.mdx, tutorials/hadoop/index.mdx, tutorials/powerdns-ubuntu-bionic/index.mdx, tutorials/scaleway-slack-community/index.mdx, tutorials/send-sms-iot-device-twilio/index.mdx, tutorials/setting-up-tunnel/index.mdx, tutorials/setup-cockroachdb-cluster/index.mdx, tutorials/setup-elastic-metal-proxmox-cluster-with-private-networks/index.mdx, tutorials/setup-postfix-ubuntu-bionic/index.mdx
=> docs(review): review docs

tutorials/openvpn-instant-app/index.mdx
Update openvpn instant app docs
=> docs(tutorials): update openvpn instantapp

compute/gpu/concepts.mdx
=> docs(gpu): add FP8,16,32,64 to concepts

serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx
=> fix(SDB): update max vCPU scaling MTA-3724

tutorials/manage-instances-with-terraform-and-functions/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
=> docs(srv): update tutorial title + typo MTA-3729

compute/instances/reference-content/learning.mdx
=> docs(instances): remove instantapps from learning instances

changelog/september2023/2023-09-25-secret-manager-added-secret-path---organize.mdx
=> feat(changelog): secret-manager-added-secret-path---organize 2023-09-25

compute/gpu/reference-content/understanding-nvidia-tao.mdx, menu/navigation.json
understanding nvidia tao tookit
=> docs(gpu): understanding nvidia tao tookit

compute/gpu/reference-content/understanding-nvidia-tao.mdx
=> docs(gpu): fix broken formatting

compute/gpu/reference-content/understanding-nvidia-tao.mdx
=> docs(fix): typo

console/my-account/how-to/close-account.mdx
=> fix(cxp): update orga deactivation procesure MTA-3716

storage/object/how-to/use-bucket-website.mdx
=> fix(s3): update bucket website doc MTA-3696

bare-metal/dedibox/how-to/activate-ipv6-block.mdx, bare-metal/elastic-metal/how-to/connect-to-server.mdx, dedibox/hardware/how-to/configure-dell-perc-h200.mdx, dedibox/hardware/how-to/configure-dell-perc-h310.mdx, dedibox/hardware/how-to/configure-dell-perc-h700.mdx, dedibox/hardware/how-to/configure-dell-perc-h800.mdx, dedibox/hardware/how-to/configure-hardware-raid-console.mdx, dedibox/hardware/how-to/configure-hp-smart-array-p410.mdx, dedibox/hardware/how-to/configure-hp-smart-array-p420.mdx, dedibox/hardware/how-to/configure-raid-kvm-h200.mdx, dedibox/hardware/how-to/configure-raid-kvm-h310.mdx, dedibox/hardware/how-to/configure-raid-kvm-p410.mdx, dedibox/hardware/how-to/configure-raid-kvm-p420.mdx, dedibox/hardware/troubleshooting/diagnose-defective-disk.mdx, managed-services/transactional-email/troubleshooting/delist-domain.mdx, network/vpc/how-to/attach-resources-to-pn.mdx, network/vpc/how-to/create-private-network.mdx, network/vpc/how-to/delete-private-network.mdx, network/vpc/troubleshooting/vpc-limitations.mdx, observability/cockpit/how-to/create-token.mdx, observability/cockpit/how-to/retrieve-grafana-credentials.mdx, tutorials/deploy-awstats/index.mdx, tutorials/deploy-nextcloud-s3/index.mdx, tutorials/get-started-containers-docker/index.mdx, tutorials/get-started-deploy-kapsule/index.mdx, tutorials/getting-started-with-kops-on-scaleway/index.mdx, tutorials/glusterfs/index.mdx, tutorials/python-lists-dicts/index.mdx, tutorials/self-hosted-repository-gitea/index.mdx, tutorials/setup-nomad-cluster/index.mdx
=> docs(review): docs content review

faq/new-object-storage-classes.mdx, storage/object/api-cli/import-copy.mdx, storage/object/api-cli/lifecycle-rules-api.mdx, storage/object/api-cli/migrating-buckets.mdx, storage/object/api-cli/object-lock.mdx, storage/object/api-cli/using-api-call-list.mdx, storage/object/concepts.mdx, storage/object/how-to/edit-storage-class.mdx, storage/object/how-to/restore-an-object-from-glacier.mdx, storage/object/quickstart.mdx
=> fix(s3): small doc updates MTA-3736

bare-metal/elastic-metal/how-to/configure-ipv6-hypervisor.mdx
=> docs(em): update ipv6 dns cache ips

faq/new-object-storage-classes.mdx, storage/object/api-cli/bucket-operations.mdx, storage/object/api-cli/installing-minio-client.mdx, storage/object/api-cli/managing-lifecycle-cliv2.mdx, storage/object/concepts.mdx, storage/object/how-to/use-obj-stor-with-private-networks.mdx
=> docs(S3): update default AZ with AMS + broken links MTA-3734

network/domains-and-dns/how-to/manage-dns-records.mdx
Add missing "all" strategy for dns records using healtcheck mode.
=> Add "all" strategy for dns records using healtcheck mode

changelog/september2023/2023-09-27-functions-changed-new-function-creation-workflow.mdx
=> feat(changelog): functions-changed-new-function-creation-workflow 2023-09-27

changelog/september2023/2023-09-27-functions-added-you-can-now-test.mdx
=> feat(changelog): functions-added-you-can-now-test 2023-09-27

tutorials/install-cockroachdb-scaleway-instances/index.mdx
=> docs(tutorials): installing cockroachdb on instance MTA-3608

changelog/october2023/2023-10-03-iot-changed-new-iot-platform-server.mdx
Reporter: Julien Viard de Galbert
=> feat(changelog): iot-changed-new-iot-platform-server 2023-10-03

tutorials/strapi/index.mdx
Update tutorial strapi with latest release
=> docs(tutorial): update tutorial strapi

managed-databases/postgresql-and-mysql/reference-content/autohealing.mdx, managed-databases/postgresql-and-mysql/reference-content/index.mdx, menu/navigation.json
=> fix(fdb): menu MTA-3758

managed-databases/postgresql-and-mysql/troubleshooting/disk-full.mdx, managed-databases/postgresql-and-mysql/troubleshooting/index.mdx
=> fix(fdb): menu again

faq/messaging-and-queuing.mdx
=> fix(mnq): modify faq for GA

serverless/containers/how-to/add-trigger-to-a-container.mdx, serverless/functions/how-to/add-trigger-to-a-function.mdx
Modify doc on Serverless Functions & Containers triggers for new M&Q
=> feat(mnq): fixed serverless stuff

tutorials/collecting-visualizing-logs-elastic-stack/index.mdx
=> docs(tutorials): elk stack

console/my-account/reference-content/organization-quotas.mdx
Add H100 Instances to quotas page
=> (docs): gpu add H100 Instances to quotas table

serverless/sql-databases/reference-content/known-differences.mdx
=> fix(SDB): update content

serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx
=> fix(sdb): update max connections to DB MTA-3781

compute/instances/api-cli/using-routed-ips.mdx
Add information for routed IP via Scaleway CLI
=> docs(instances): add cli information for routed ip

console/my-account/reference-content/products-availability.mdx, network/load-balancer/how-to/create-load-balancer.mdx, network/load-balancer/quickstart.mdx
=> fix(lb): add waw3

compute/instances/api-cli/using-routed-ips.mdx
=> docs(instances): add warning for routed ip migration

faq/messaging-and-queuing.mdx
=> feat(mnq): modify faq pricing wording

compute/instances/how-to/create-an-instance.mdx, compute/instances/quickstart.mdx
=> docs(instances): fix typo

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx
=> docs(k8s): fix broken link

serverless/messaging/how-to/migrate-to-new-mnq.mdx
=> fix(mnq): fix date

containers/kubernetes/how-to/edit-kosmos-cluster.mdx
Add instructions on how to upgrade a Kosmos node
=> docs(kosmos): Add instructions on how to upgrade a Kosmos node ext-add-kosmos

bare-metal/elastic-metal/how-to/use-private-networks.mdx, containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx, faq/public-gateways.mdx, faq/vpc.mdx, network/public-gateways/concepts.mdx, network/public-gateways/how-to/configure-a-public-gateway.mdx, network/public-gateways/how-to/create-a-public-gateway.mdx, network/public-gateways/troubleshooting/gw-limitations.mdx, network/vpc/concepts.mdx, network/vpc/reference-content/vpc-migration.mdx
Update doc to describe legacy vs ipam gateways.
Another PR will be opened in the future once the tags of legacy or ipam are available in the console.
=> fix(pgw): updates for ipam

changelog/october2023/2023-10-18-kubernetes-added-cloud-controller-manager-now-supports-.mdx
=> feat(changelog): kubernetes-added-cloud-controller-manager-now-supports- 2023-10-18

compute/instances/how-to/migrate-routed-ips.mdx
Updated wording for "routed IP" feature
=> docs(ins): updt word routed ip migration warning

compute/instances/api-cli/using-routed-ips.mdx
=> docs(ins): update wording

changelog/october2023/2023-10-20-containers-added-trigger-private-containers-from-messag.mdx
=> feat(changelog): containers-added-trigger-private-containers-from-messag 2023-10-20

changelog/october2023/2023-10-20-functions-added-trigger-private-functions-from-messagin.mdx
=> feat(changelog): functions-added-trigger-private-functions-from-messagin 2023-10-20

tutorials/use-container-registry-github-actions/index.mdx
For this page : https://www.scaleway.com/en/docs/tutorials/use-container-registry-github-actions/
Bump github actions tools :
- https://github.com/docker/login-action/releases/tag/v3.0.0
- https://github.com/actions/checkout
=> docs: container github action - bump versions docker login / checkout

menu/navigation.json, serverless/containers/concepts.mdx, serverless/containers/how-to/add-trigger-to-a-container.mdx, serverless/functions/concepts.mdx, serverless/functions/how-to/add-trigger-to-a-function.mdx
Now that NATS triggers are available, here is the doc.
Thanks!
=> feat(serverless): add docs about NATS triggers

faq/new-object-storage-classes.mdx
=> fix(s3): update storage class faq MTA-3819

containers/kubernetes/reference-content/multi-az-clusters.mdx
=> docs(k8s): fix typo

serverless/messaging/how-to/migrate-to-new-mnq.mdx, serverless/messaging/reference-content/migration.mdx
I've added a section on triggers in the new mnq migration docs, to tell users they have to recreate their triggers after migration.
Thanks!
=> feat(mnq): add reference to triggers in new mnq migration doc

bare-metal/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
Add information about firewall configuration to apple silicon docs
=> docs(aps): add firewall information

changelog/october2023/2023-10-24-messaging-and-queuing-changed-messaging-and-queuing-is-.mdx
=> feat(changelog): messaging-and-queuing-changed-messaging-and-queuing-is- 2023-10-24

changelog/october2023/2023-10-25-kubernetes-added-support-for-kubernetes-kapsule-multi-a.mdx
=> feat(changelog): kubernetes-added-support-for-kubernetes-kapsule-multi-a 2023-10-25

changelog/october2023/2023-10-26-functions-changed-serverless-functions-triggers-now-in-.mdx
=> feat(changelog): functions-changed-serverless-functions-triggers-now-in- 2023-10-26

changelog/october2023/2023-10-26-containers-changed-serverless-containers-triggers-now-i.mdx
=> feat(changelog): containers-changed-serverless-containers-triggers-now-i 2023-10-26

console/account/concepts.mdx
Fixing a link in account concepts to the adequate page on console
=> fix(accountconcepts): small fix on link to console on quotas

containers/kubernetes/reference-content/lb-ingress-controller.mdx, containers/kubernetes/reference-content/wildcard-dns.mdx, menu/navigation.json
Update Kubernetes reference content
=> docs(k8s): update docs

docs/CONTRIBUTING.md
=> fix(docs): update contributing file with clear procedure MTA-3685

faq/serverless-containers.mdx
=> fix(srv): update containers billing with correct unit MTA-3831

changelog/october2023/2023-10-27-load-balancers-added-load-balancer-is-now-available-in-.mdx
=> feat(changelog): load-balancers-added-load-balancer-is-now-available-in- 2023-10-27

changelog/october2023/2023-10-27-load-balancers-added-load-balancer-is-now-available-in-.mdx, tutorials/deploy-k3s-cluster-with-cilium/index.mdx
Fixed broken date in changelog entry.
=> docs(changelog): fix broken date

tutorials/prestashop-dedibox/index.mdx
Update tuto Prestashop to PHP8.1
=> docs(tutorial): update prestashop tuto

containers/kubernetes/reference-content/managed-kubernetes-service-definition.mdx
=> docs(k8s): add second warning

bare-metal/dedibox/how-to/attach-detach-failover-ip.mdx, bare-metal/dedibox/how-to/configure-failover-ip.mdx, bare-metal/dedibox/how-to/order-failover-ip.mdx, compute/instances/how-to/use-flexips.mdx, dedibox-network/ip-failover/how-to/assign-failover-ip.mdx, dedibox-network/ip-failover/how-to/create-virtual-mac.mdx, dedibox-network/ip-failover/how-to/order-failover-ip.mdx, dedibox-network/ip-failover/quickstart.mdx, macros/network/failover-ip-limitations.mdx, macros/network/flexible-ip-limitations.mdx, network/public-gateways/how-to/use-flexible-ips.mdx
Add a note about flexible IPs where required
=> docs(gen): add note about flexible ips

serverless/functions/reference-content/functions-lifecycle.mdx
=> docs(serverless): update functions runtimes status

faq/dedibox-in-scaleway-console.mdx
Update FAQ DDX in Scaleway console
=> docs(faq): update faq dedibox2elts

tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
=> docs(nodejs): Comments are inside codeblock

containers/kubernetes/reference-content/version-support-policy.mdx
updated version support policy page
=> docs(k8s): updated version support policy page

containers/kubernetes/reference-content/version-support-policy.mdx
=> docs(k8s): fix CNI information

containers/kubernetes/how-to/enable-disable-ssh.mdx, dedibox-console/classic-hosting/how-to/access-logcenter.mdx, dedibox-console/classic-hosting/how-to/access-statistics.mdx, dedibox-console/classic-hosting/how-to/change-email-account-password.mdx, dedibox-console/classic-hosting/how-to/change-ftp-account-password.mdx, dedibox-console/classic-hosting/how-to/change-password-mysql-database.mdx, dedibox-console/classic-hosting/how-to/change-password-postgresql-database.mdx, dedibox-console/classic-hosting/how-to/check-emails.mdx, dedibox-console/classic-hosting/how-to/configure-backup-option.mdx, dedibox-console/classic-hosting/how-to/configure-htaccess-file.mdx, dedibox-console/classic-hosting/how-to/configure-outlook.mdx, dedibox-console/classic-hosting/how-to/configure-php.mdx, dedibox-console/classic-hosting/how-to/connect-via-ftp.mdx, dedibox-console/classic-hosting/how-to/create-email-account.mdx, network/load-balancer/how-to/add-certificate.mdx, observability/cockpit/how-to/activate-cockpit.mdx, tutorials/configure-apache-kafka/index.mdx, tutorials/create-openwrt-image-for-scaleway/index.mdx, tutorials/deploy-openproject-database-postgresql/index.mdx, tutorials/get-started-crossplane-kubernetes/index.mdx
=> docs(review): docs review

dedibox-console/classic-hosting/how-to/configure-htaccess-file.mdx
=> docs(fix): broken date

storage/object/how-to/monitor-consumption.mdx
=> docs(s3): add link to cockpit MTA-3869

containers/kubernetes/api-cli/exposing-services.mdx
=> docs(fix): conflicting date

console/account/how-to/close-account.mdx, console/account/how-to/verify-identity.mdx, faq/account.mdx
=> fix(cns): update verify id procedure MTA-3818

faq/coldstorage.mdx
=> docs(s3): update glacier faq with billing MTA-3872

managed-services/webhosting/how-to/migrate-webhosting-plan.mdx
Added banner to warn customers to add a payment method to their scaleway account before launching web hosting migration
=> docs(webhosting): add payment requirement info

changelog/november2023/2023-11-07-transactional-email-added-smtp-login-authentication-met.mdx
=> feat(changelog): transactional-email-added-smtp-login-authentication-met 2023-11-07

containers/kubernetes/reference-content/exposing-services.mdx, containers/kubernetes/reference-content/kubernetes-load-balancer.mdx, faq/loadbalancer.mdx, tutorials/deploy-saas-application/index.mdx, tutorials/proxy-protocol-v2-load-balancer/index.mdx
=> fix(k8s): fix links

labs/ipfs-naming/api-cli/index.mdx, labs/ipfs-naming/api-cli/ipfs-manage-keys.mdx, labs/ipfs-naming/api-cli/name-operations.mdx, labs/ipfs-naming/api-cli/names-operations.mdx, labs/ipfs-pinning/api-cli/getting-started-with-ipfs-cli.mdx, labs/ipfs-pinning/api-cli/pin-operations.mdx, labs/ipfs-pinning/api-cli/volumes-operations.mdx, menu/navigation.json
=> docs(ipfs): add ipns cli command to manage records

changelog/november2023/2023-11-07-cockpit-added-beta-traces.mdx
=> feat(changelog): cockpit-added-beta-traces 2023-11-07

serverless/containers/how-to/create-a-containers-namespace.mdx, serverless/containers/quickstart.mdx
=> docs(srv): update container quickstart userflow MTA-3874

menu/navigation.json, serverless/containers/how-to/add-trigger-to-a-container.mdx, serverless/containers/how-to/delete-a-container.mdx, serverless/containers/how-to/delete-a-containers-namespace.mdx, serverless/containers/how-to/secure-a-container.mdx, serverless/functions/concepts.mdx, serverless/functions/how-to/create-a-function.mdx, serverless/functions/how-to/delete-a-function.mdx, serverless/functions/how-to/delete-a-functions-namespace.mdx, serverless/functions/how-to/package-function-dependencies-in-zip.mdx, serverless/functions/quickstart.mdx
=> fix(srv): miscellaneous fixes in srv doc MTA-3877

changelog/november2023/2023-11-08-object-storage-added-new-bucket-policy-version-allowing.mdx
=> feat(changelog): object-storage-added-new-bucket-policy-version-allowing 2023-11-08

storage/object/api-cli/combining-iam-and-object-storage.mdx
Small fix - we left out old versions in the documentation
=> fix(bucketpolicies): fix on version

tutorials/get-started-containers-docker/index.mdx, tutorials/get-started-deploy-kapsule/index.mdx, tutorials/get-started-kubernetes-loadbalancer/index.mdx
Added navigation buttons to three part series of k8s tutorials
=> docs(tutorials): add navigation buttons

faq/coldstorage.mdx
=> fix(s3): remove section on glacier hardware from faq

changelog/september2023/2023-09-06-kubernetes-added-dedicated-control-plane-offers.mdx, containers/kubernetes/how-to/enable-disable-ssh.mdx
=> docs(k8s): update ssh documentation

developer-tools/scaleway-sdk/go-sdk.mdx
Added docs for Scaleway Go SDK
=> docs(devtools): add docs for sdk go

developer-tools/scaleway-sdk/index.mdx, developer-tools/scaleway-sdk/python-sdk.mdx, menu/navigation.json
=> docs(devtools): add docs for sdk python

compute/instances/troubleshooting/fix-unreachable-ipv6-rhel-based-instance.mdx
- [ x] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).
Add a troubleshooting document on how to fix unreachable IPv6 routed ip on RHEL based distro
=> docs(instances): Fix unreachable IPv6 after routed ip migration (int-add-instances)

menu/navigation.json
Add link to navigation for Instance troubleshooting
=> docs(fix): add link to navigation

containers/kubernetes/how-to/deploy-image-from-container-registry.mdx, containers/kubernetes/how-to/enable-easy-deploy.mdx, containers/kubernetes/quickstart.mdx, storage/object/api-cli/bucket-website-api.mdx, storage/object/api-cli/setting-cors-rules.mdx, tutorials/abort-multipart-upload-minio/index.mdx, tutorials/access-mac-mini-with-reemo/index.mdx, tutorials/configure-nodemcu-iot-hub/index.mdx, tutorials/configuring-loadbalancer-wordpress/index.mdx, tutorials/install-github-actions-runner-mac/index.mdx, tutorials/jump-desktop/index.mdx, tutorials/odoo-easy-deploy/index.mdx
=> docs(fix): fixed 404s

storage/object/how-to/monitor-consumption.mdx
=> docs(s3): update monitoring doc with cockpit MTA-3911

changelog/november2023/2023-11-20-transactional-email-added-domain-reputation-score.mdx
=> feat(changelog): transactional-email-added-domain-reputation-score 2023-11-20

developer-tools/scaleway-cli/quickstart.mdx
=> docs: Update Arch Linux package URL in quickstart.mdx

changelog/november2023/2023-11-21-load-balancers-added-load-balancer-logs-are-now-availab.mdx
=> feat(changelog): load-balancers-added-load-balancer-logs-are-now-availab 2023-11-21

compute/gpu/reference-content/understanding-nvidia-fp8.mdx, menu/navigation.json
=> docs(gpu): understanding nvidia fp8 format

tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
=> docs(srv): remove mention of vim

bare-metal/apple-silicon/concepts.mdx, bare-metal/apple-silicon/how-to/connect-to-mac-mini.mdx, bare-metal/apple-silicon/how-to/create-mac-mini.mdx, bare-metal/apple-silicon/how-to/delete-mac-mini.mdx, bare-metal/apple-silicon/how-to/reboot-mac-mini.mdx, bare-metal/apple-silicon/how-to/reinstall-mac-mini.mdx, bare-metal/apple-silicon/quickstart.mdx, bare-metal/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx, bare-metal/apple-silicon/troubleshooting/filevault-preventing-system-boot.mdx, bare-metal/apple-silicon/troubleshooting/need-package-manager.mdx, bare-metal/apple-silicon/troubleshooting/need-to-update-os.mdx, compute/instances/concepts.mdx, macros/compute/apple-silicon-m1.mdx, macros/console/region-and-az.mdx
=> docs(aps): content review and update

serverless/jobs/how-to/create-job-from-external-registry.mdx, serverless/jobs/how-to/create-job-from-scaleway-registry.mdx, serverless/jobs/how-to/delete-job.mdx, serverless/jobs/how-to/monitor-job.mdx, serverless/jobs/how-to/run-job.mdx
forgot to add PB access as a requirement
=> docs(SRV): add beta access in requirements

compute/gpu/how-to/use-scratch-storage-h100-instances.mdx
Update scratch storage for H100 Instances
=> docs(gpu): update scratch h100

serverless/messaging/reference-content/limitations.mdx
=> fix(mnq): improve tags for limitations

changelog/november2023/2023-11-23-secret-manager-changed-secret-manager-console-pages-hav.mdx
=> feat(changelog): secret-manager-changed-secret-manager-console-pages-hav 2023-11-23

developer-tools/scaleway-sdk/js-sdk.mdx, menu/navigation.json
=> doc(devtools): js sdk

bare-metal/dedibox/how-to/connect-to-dedibox.mdx, bare-metal/elastic-metal/how-to/connect-to-server.mdx, compute/instances/how-to/connect-to-instance.mdx, compute/instances/reference-content/learning.mdx, dedibox/dedicated-servers/how-to/connect-to-server.mdx
Add links to linux command line tuto
=> fix(docs): add links to linux command line tuto

storage/object/api-cli/lifecycle-rules-api.mdx, storage/object/how-to/manage-lifecycle-rules.mdx
=> docs(S3): add warning on lifecycle rule transition order MTA-3927

changelog/november2023/2023-11-27-iam-added-iam-audit-logs.mdx
=> feat(changelog): iam-added-iam-audit-logs 2023-11-27

faq/coldstorage.mdx
=> docs(S3): update glacier faq

network/load-balancer/concepts.mdx
Fixed a concept that was open in the middle of the page
=> fix(lb): open tags

serverless/messaging/concepts.mdx, serverless/messaging/how-to/get-started.mdx, serverless/messaging/how-to/manage-credentials.mdx, serverless/messaging/how-to/migrate-to-new-mnq.mdx, serverless/messaging/quickstart.mdx, serverless/messaging/reference-content/migration.mdx
Content revision and correction.
=> fix(MNQ): content revision

storage/object/api-cli/object-operations.mdx
=> docs(s3): add VersionId to DeleteObjects MTA-3938

serverless/jobs/concepts.mdx, serverless/jobs/how-to/monitor-job.mdx, serverless/jobs/how-to/run-job.mdx
=> fix(sls): update job statuses MTA-3939

menu/navigation.json, serverless/sql-databases/troubleshooting/connection-timeout.mdx, serverless/sql-databases/troubleshooting/index.mdx
=> docs(sdb): add connection timeout troubleshooting MTA-3908

storage/object/api-cli/lifecycle-rules-api.mdx
=> fix(s3): remove note on 0 value for transition on lifecycle rule MTA3942

console/account/reference-content/products-availability.mdx
Update the Region availability for Messaging and Queuing
=> fix(mnq): add messaging Region availability

tutorials/terraform-quickstart/index.mdx
update terraform version to 1.6.5 and S3 backend
=> feat(tutorials): update terraform and S3 Backend config

changelog/november2023/2023-11-30-postgresql-and-mysql-added-postgresql-pgvector-is-now-a.mdx
=> feat(changelog): postgresql-and-mysql-added-postgresql-pgvector-is-now-a 2023-11-30

menu/navigation.json, storage/object/reference-content/optimize-object-storage-performance.mdx
=> docs(S3): perf optimization guidelines MTA-3845

changelog/november2023/2023-11-30-postgresql-and-mysql-added-managed-databases-latest-ver.mdx
=> feat(changelog): postgresql-and-mysql-added-managed-databases-latest-ver 2023-11-30

tutorials/k8s-kapsule-multi-az/index.mdx
Fix typo in terraform example for multi-az kapsule
=> docs(kapsule): fix typo in terraform example for multi-az kapsule

storage/object/reference-content/optimize-object-storage-performance.mdx
=> fix(s3): dead link on Object Storage perf optimization guidelines

changelog/december2023/2023-12-01-object-storage-added-our-warsaw-region-is-now-multi-az-.mdx
=> feat(changelog): object-storage-added-our-warsaw-region-is-now-multi-az- 2023-12-01

menu/changelogs.json
Added Serverless SQL Databases and Jobs  and Document Databases to the changelog menu
=> fix(changelog): added new menu entries MTA-3961

tutorials/k8s-kapsule-multi-az/index.mdx
To fix #2478
Fix healtcheck configuration for kapsule multi-az doc
=> docs(k8s): fix healtcheck configuration for kapsule multi-az doc

storage/object/api-cli/combining-iam-and-object-storage.mdx
Created following https://github.com/scaleway/docs-content/issues/2482
=> fix(s3): fix error in Bucket policy example

changelog/december2023/2023-12-04-transactional-email-removed-no-more-tem-houry-quota.mdx
=> feat(changelog): transactional-email-removed-no-more-tem-hourly-quota 2023-12-04

changelog/december2023/2023-12-04-messaging-and-queuing-deprecated-api-v1alpha1-to-be-mig.mdx
=> feat(changelog): messaging-and-queuing-deprecated-api-v1alpha1-to-be-mig 2023-12-04

compute/instances/how-to/use-placement-groups.mdx
Fixed wording on Documentation about placement groups management. Wording on the console is changing.
=> fix(ins): fixed wording on placement groups

faq/serverless-sql-databases.mdx, menu/navigation.json, serverless/sql-databases/how-to/configure-autoscaling.mdx, serverless/sql-databases/how-to/delete-a-database.mdx, serverless/sql-databases/how-to/manage-backups.mdx
=> docs(sdb): add backups documentation MTA-3963

identity-and-access-management/iam/reference-content/permission-sets.mdx, serverless/sql-databases/how-to/manage-backups.mdx
=> docs(sdb): add permission sets to iam ref content MTA-3964

changelog/december2023/2023-12-07-transactional-email-added-weekly-activity-report-and-bo.mdx
=> feat(changelog): transactional-email-added-weekly-activity-report-and-bo 2023-12-07

changelog/december2023/2023-12-07-elastic-metal-added-beryllium-offers-b112x-and-b212x-av.mdx
=> feat(changelog): elastic-metal-added-beryllium-offers-b112x-and-b212x-av 2023-12-07

changelog/december2023/2023-12-08-document-databases-added-document-database-is-available.mdx
=> feat(changelog): document-databases-added-document-database-is-available 2023-12-08

faq/messaging-and-queuing.mdx, serverless/messaging/reference-content/migration.mdx, serverless/messaging/reference-content/nats-overview.mdx, serverless/messaging/reference-content/sns-overview.mdx, serverless/messaging/reference-content/sqs-overview.mdx
v1alpha1 API is deleted, all links should be removed
=> fix(mnq): update doc to delete old api

storage/object/how-to/restore-an-object-from-glacier.mdx
=> fix(s3): add note on s3cmd restore MTA-3972

faq/objectstorage.mdx, storage/object/how-to/monitor-consumption.mdx
=> docs(s3): cockpit available in all regions MTA-3980

macros/serverless/difference-jobs-functions-containers.mdx, menu/navigation.json, serverless/containers/reference-content/difference-jobs-functions-containers.mdx, serverless/functions/reference-content/difference-jobs-functions-containers.mdx, serverless/jobs/reference-content/difference-jobs-functions-containers.mdx
=> docs(srv): add differences to functions and containers MTA-3951

changelog/december2023/2023-12-01-object-storage-changed-the-75gb-free-tier-is-replaced-b.mdx, faq/objectstorage.mdx
=> fix(s3): update free trial unit for clarity MTA-3981

faq/kubernetes.mdx
Fixed formatting that was keeping two queries from appearing on the page.
Updated content.
=> fix(k8s): fixed formatting and content update

identity-and-access-management/secret-manager/concepts.mdx, identity-and-access-management/secret-manager/how-to/create-folder.mdx, identity-and-access-management/secret-manager/how-to/create-secret.mdx
=> fix(sem): content review

compute/instances/reference-content/understanding-differences-x86-arm.mdx, menu/navigation.json
=> docs(ins): arm vs x86

changelog/december2023/2023-12-08-sql-databases-added-serverless-sql-database-is-availabl.mdx
=> feat(changelog): sql-databases-added-serverless-sql-database-is-availabl 2023-12-08

changelog/december2023/2023-12-14-jobs-added-serverless-jobs-is-available-in-public-beta.mdx
=> feat(changelog): jobs-added-serverless-jobs-is-available-in-public-beta 2023-12-14

menu/navigation.json, serverless/jobs/how-to/create-job-from-external-registry.mdx, serverless/jobs/how-to/create-job-from-scaleway-registry.mdx, serverless/jobs/how-to/delete-job.mdx, serverless/jobs/how-to/monitor-job.mdx, serverless/jobs/how-to/run-job.mdx, serverless/jobs/how-to/stop-job.mdx, serverless/jobs/quickstart.mdx
=> docs(srv): jobs several updates before pb MTA-3999

managed-databases/postgresql-and-mysql/concepts.mdx, managed-databases/postgresql-and-mysql/how-to/change-volume-type.mdx, managed-databases/postgresql-and-mysql/how-to/clone-a-database-instance.mdx, managed-databases/postgresql-and-mysql/how-to/create-a-database.mdx, managed-databases/postgresql-and-mysql/how-to/create-read-replica.mdx, managed-databases/postgresql-and-mysql/how-to/enable-autobackup.mdx, managed-databases/postgresql-and-mysql/how-to/manage-snapshots.mdx, managed-databases/postgresql-and-mysql/how-to/upgrade-a-database.mdx, managed-databases/postgresql-and-mysql/quickstart.mdx, menu/navigation.json
=> fix(rdb): block low latency

bare-metal/elastic-metal/troubleshooting/reset-admin-password-windows-server.mdx, menu/navigation.json
Added information how to reset the Administrator password on Servers running Windows server.
=> feat(em): add info how to reset admin password windows

changelog/december2023/2023-12-14-postgresql-and-mysql-added-block-storage-low-latency-fo.mdx
=> feat(changelog): postgresql-and-mysql-added-block-storage-low-latency-fo 2023-12-14

changelog/december2023/2023-12-15-kubernetes-added-dedicated-control-plane-offers-now-ava.mdx
=> feat(changelog): kubernetes-added-dedicated-control-plane-offers-now-ava 2023-12-15

dedibox-network/ipv6/how-to/configure-ipv6-windows.mdx
=> docs(dedibox): add information to windows ipv6 docs

compute/instances/api-cli/using-routed-ips.mdx, compute/instances/concepts.mdx, compute/instances/how-to/create-an-instance.mdx, compute/instances/how-to/migrate-routed-ips.mdx, compute/instances/quickstart.mdx, tutorials/setup-mongodb-on-ubuntu/index.mdx
Updated wording routed IP documentation
=> fix(ins): update routed ip docs

dedibox-network/domains/how-to/change-ownership.mdx
Update DDX domain ownership change documentation
=> fix(ddx): change domain ownership

tutorials/get-started-deploy-kapsule/index.mdx
Add additional information to the `nodeport` part of the tutorial.
=> fix(k8s): update tutorial with vpc info

faq/iam.mdx
Added queries referring to quota limits for IAM resources, so Documentation is up-to-date with the upcoming Quota revamp.
=> fix(uapi): content update

compute/instances/concepts.mdx
=> fix(concept): fix broken concept

console/account/how-to/enforce-mfa.mdx, console/account/how-to/use-2fa.mdx, dedibox-console/account/how-to/disable-two-factor-authentication.mdx, dedibox-console/account/how-to/enable-two-factor-authentication.mdx, labs/ipfs-naming/api-cli/ipfs-manage-keys.mdx, managed-databases/document-database/troubleshooting/disk-full.mdx, managed-databases/postgresql-and-mysql/troubleshooting/disk-full.mdx, managed-services/transactional-email/how-to/add-spf-dkim-records-to-your-domain.mdx, managed-services/transactional-email/how-to/configure-domain-with-transactional-email.mdx, managed-services/transactional-email/how-to/delete-tem-domain.mdx, network/public-gateways/troubleshooting/gateway-services-not-working.mdx, network/vpc/how-to/create-vpc.mdx, network/vpc/how-to/delete-vpc.mdx, observability/cockpit/reference-content/understanding-cockpit-usage.mdx, storage/object/api-cli/bucket-operations.mdx, storage/object/api-cli/common-operations.mdx, storage/object/api-cli/generate-aws4-auth-signature.mdx, storage/object/api-cli/installing-minio-client.mdx, storage/object/api-cli/installing-rclone.mdx, storage/object/api-cli/manage-bucket-permissions-IP.mdx, storage/object/api-cli/migrating-buckets.mdx, storage/object/api-cli/object-lock.mdx, storage/object/api-cli/object-operations.mdx, storage/object/api-cli/object-storage-aws-cli.mdx, storage/object/api-cli/post-object.mdx, storage/object/how-to/delete-an-object.mdx
=> docs(review): docs content review pt 3

changelog/december2023/2023-12-19-messaging-and-queuing-added-sqs-supports-json-transport.mdx
=> feat(changelog): messaging-and-queuing-added-sqs-supports-json-transport 2023-12-19

tutorials/mlx-array-framework-apple-silicon/index.mdx
=> feat(aps): tutorial mlx on apple silicon

managed-services/webhosting/how-to/order-webhosting.mdx, managed-services/webhosting/reference-content/cpanel-reference-content.mdx, managed-services/webhosting/reference-content/index.mdx, managed-services/webhosting/reference-content/plesk-reference-content.mdx, managed-services/webhosting/reference-content/understanding-differences-cpanel-plesk.mdx, menu/navigation.json
=> docs(webhosting): cPanel and Plesk

managed-services/webhosting/concepts.mdx
=> docs(webhosting): add concepts

changelog/december2023/2023-12-20-billing-added-api-billing-v2-beta.mdx
=> feat(changelog): billing-added-api-billing-v2-beta 2023-12-20

changelog/december2023/2023-12-20-elastic-metal-added-new-nvme-beryllium-offers.mdx
=> feat(changelog): elastic-metal-added-new-nvme-beryllium-offers 2023-12-20

compute/instances/api-cli/migrating-instances.mdx
Fixed HTTP method for Instances stop procedure in migration documentation.
=> fix(instances): fixed instances migration docs

bare-metal/dedibox/reference-content/dedibox-datasheet.mdx, bare-metal/dedibox/reference-content/index.mdx, bare-metal/elastic-metal/reference-content/elastic-metal-datasheet.mdx, bare-metal/elastic-metal/reference-content/index.mdx, compute/instances/reference-content/choosing-instance-type.mdx, compute/instances/reference-content/instances-datasheet.mdx, menu/navigation.json
=> docs(compute): instances/elastic-metal/dedibox datasheet

menu/filters.json
Add tutorial filter for messaging category
=> fix(tutorials): add messaging filter

tutorials/backup-postgresql-pgbackrest-s3/index.mdx, tutorials/install-postgresql/index.mdx, tutorials/k8s-velero-backup/index.mdx, tutorials/manage-database-instance-pgadmin4/index.mdx, tutorials/mariadb-ubuntu-bionic/index.mdx, tutorials/migrate-databases-instance/index.mdx, tutorials/nvidia-triton/index.mdx, tutorials/odoo-easy-deploy/index.mdx, tutorials/setup-cockroachdb-cluster/index.mdx, tutorials/store-s3-transmit/index.mdx, tutorials/store-wp-mediacloud-s3/index.mdx, tutorials/visualize-timeseries-data-timescaledb-grafana/index.mdx
=> fix(tutorials): Update tags and categories MTA-4050

tutorials/mlx-array-framework-apple-silicon/index.mdx
Fix (404 error) external github link
=> feat(aps): fix llama external link in mlx page

serverless/messaging/concepts.mdx
Remove unsupported AMQP protocol from concepts as it may confuse users.
=> fix(messaging): remove unsupported AMQP protocol from concepts

storage/object/reference-content/optimize-object-storage-performance.mdx
=> docs(s3): add info on abort multipart in perf tuto MTA-3928

tutorials/jitsi-docker/index.mdx
The command `docker-compose` has been changed to `docker compose`
=> The command docker-compose has been changed to docker compose

labs/ipfs-pinning/api-cli/pin-operations.mdx, tutorials/create-wordpress-instances-cli/index.mdx
Remove indentation in an attempt to fix a broken table in [this page](https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/pin-operations/).
=>  fix(ipfspinning): remove indentation 

serverless/containers/how-to/create-auth-token-from-console.mdx, serverless/containers/how-to/secure-a-container.mdx, serverless/functions/how-to/create-auth-token-from-console.mdx, serverless/functions/how-to/secure-a-function.mdx
=> docs(srv): add info on auth token for private functions & containers MTA-4060

storage/object/api-cli/bucket-policy.mdx, storage/object/api-cli/combining-iam-and-object-storage.mdx
=> docs(s3): update BP examples with multiple statements MTA-4061

bare-metal/apple-silicon/how-to/connect-to-mac-mini.mdx, bare-metal/apple-silicon/how-to/reinstall-mac-mini.mdx, bare-metal/apple-silicon/quickstart.mdx
=> docs(aps): fix typos

bare-metal/dedibox/concepts.mdx, bare-metal/dedibox/quickstart.mdx, dedibox/dedicated-servers/concepts.mdx, managed-services/webhosting/how-to/configure-dns-webhosting.mdx, managed-services/webhosting/how-to/migrate-webhosting-plan.mdx
Fixed some typos in Web Hosting documentation.
=> docs(webhosting): fix typos

compute/gpu/how-to/create-manage-gpu-instance.mdx, compute/gpu/how-to/use-gpu-with-docker.mdx, compute/gpu/how-to/use-mig-with-kubernetes.mdx, compute/gpu/how-to/use-nvidia-mig-technology.mdx, compute/gpu/how-to/use-pipenv.mdx, compute/gpu/how-to/use-preinstalled-env.mdx, compute/gpu/how-to/use-scratch-storage-h100-instances.mdx, compute/gpu/quickstart.mdx, compute/gpu/reference-content/docker-images.mdx, compute/gpu/reference-content/understanding-nvidia-nemo.mdx
Updated GPU Instances documentation
=> docs(gpu): fixed docs

containers/kubernetes/how-to/delete-cluster.mdx, containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx, containers/kubernetes/how-to/use-scratch-storage-h100.mdx, menu/navigation.json
How to use scratch storage on H100 GPU Instances with Kubernetes Kapsule
=> docs(k8s): use scratch storage h100

changelog/january2024/2024-01-05-messaging-and-queuing-added-sns-topic-creation-availabl.mdx
=> feat(changelog): messaging-and-queuing-added-sns-topic-creation-availabl 2024-01-05

changelog/january2024/2024-01-09-kubernetes-added-proxy-registry.mdx
=> feat(changelog): kubernetes-added-proxy-registry 2024-01-09

console/account/how-to/use-billing-alerts.mdx, containers/container-registry/quickstart.mdx, labs/ipfs-pinning/api-cli/getting-started-with-ipfs-cli.mdx, managed-services/transactional-email/how-to/manage-email-activity.mdx, menu/navigation.json, network/vpc/how-to/activate-dhcp.mdx, network/vpc/troubleshooting/autoconfig-not-working.mdx, network/vpc/troubleshooting/resource-attached-no-ip.mdx, serverless/functions/how-to/create-a-function.mdx, serverless/functions/how-to/create-a-functions-namespace.mdx, tutorials/proxy-protocol-v2-load-balancer/index.mdx, tutorials/remote-desktop-with-xrdp/index.mdx, tutorials/ruby-on-rails/index.mdx, tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx, tutorials/s3-customize-url-cname/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
=> docs(review): docs content review week 02/24

serverless/functions/reference-content/deploy-function.mdx
=> int-fix-content

storage/block/api-cli/managing-a-volume.mdx, storage/block/concepts.mdx, storage/block/how-to/create-a-volume.mdx, storage/block/quickstart.mdx
=> docs(block): documentation rework #2449

console/account/how-to/create-an-account.mdx, console/account/quickstart.mdx, macros/console/create-account.mdx
=> docs(cxp): update account creation procedure MTA-4086

containers/container-registry/concepts.mdx, containers/container-registry/how-to/connect-docker-cli.mdx, containers/container-registry/how-to/create-namespace.mdx, containers/container-registry/how-to/delete-namespace.mdx, containers/container-registry/how-to/manage-namespace-privacy-policies.mdx, containers/container-registry/how-to/pull-images.mdx, containers/container-registry/quickstart.mdx, faq/containerregistry.mdx, macros/compute/container-registry.mdx, tutorials/deploy-umami-on-serverless-containers/index.mdx
=> fix(cr): content review

tutorials/create-serverless-scraping/index.mdx
=> [MNQ SQS Tutorial] Fix some typos

identity-and-access-management/iam/reference-content/permission-sets.mdx
=> add(permission sets): add three new permission sets

storage/object/api-cli/installing-minio-client.mdx
=> docs(s3): add note on minio doc on regions MTA-4088

storage/object/how-to/access-objects-via-https.mdx
=> docs(s3): add note on public links MTA-4089

storage/object/api-cli/lifecycle-rules-api.mdx, storage/object/api-cli/managing-lifecycle-cliv2.mdx, storage/object/api-cli/multipart-uploads.mdx, storage/object/how-to/manage-lifecycle-rules.mdx
Updated "Managing lifecycle of Object Storage with CLI" to "Managing object storage with CLI" as "lifecycle" is a specific concept related to objects that is not addressed in this page and is therefore misleading.
=> docs(s3): add note on lifecylcle limitations MTA-4087

bare-metal/elastic-metal/how-to/create-virtual-mac-group.mdx, dedibox-network/ip-failover/how-to/assign-failover-ip.mdx, dedibox-network/ip-failover/how-to/configure-debian-ubuntu.mdx, dedibox-network/ip-failover/how-to/configure-freebsd.mdx, dedibox-network/ip-failover/how-to/configure-multiip-virtualmac.mdx, dedibox-network/ip-failover/how-to/configure-network-virtual-machine.mdx, dedibox-network/ip-failover/how-to/configure-reverse-dns.mdx, dedibox-network/ip-failover/how-to/configure-windows.mdx, dedibox-network/ip-failover/how-to/create-virtual-mac.mdx, dedibox-network/ip-failover/how-to/order-failover-ip.mdx, dedibox-network/ip-failover/index.mdx, dedibox-network/ip-failover/quickstart.mdx, network/vpc/troubleshooting/private-dns-dhcp-not-working.mdx, serverless/functions/how-to/add-a-custom-domain-name-to-a-function.mdx, serverless/functions/how-to/create-auth-token-from-console.mdx, serverless/functions/how-to/delete-a-function.mdx, serverless/functions/how-to/delete-a-functions-namespace.mdx, serverless/functions/how-to/manage-a-function.mdx, serverless/functions/reference-content/code-examples.mdx, serverless/functions/reference-content/functions-lifecycle.mdx, serverless/functions/reference-content/functions-limitations.mdx, serverless/functions/reference-content/functions-runtimes-configuration.mdx, serverless/messaging/reference-content/sqs-support.mdx, tutorials/create-esxi-cluster-dedibox/index.mdx, tutorials/lb-firewall-haproxy-pfsense/index.mdx, tutorials/sem-terraform/index.mdx
Docs content review - Week 03/2024
=> docs(review): docs content review - week 03/2024

storage/object/api-cli/bucket-policy.mdx
=> docs(s3): update bucket policy example for referer MTA-4107

tutorials/abort-multipart-upload-minio/index.mdx
=> fix(docs): update tutorial category

serverless/jobs/reference-content/deploy-job.mdx
=> docs(srv): update links to sdks MTA-4093

console/account/reference-content/products-availability.mdx, managed-services/iot-hub/api-cli/cli-db-tips-tricks.mdx, serverless/functions/how-to/secure-a-function.mdx
=> fix(gen): fixed links and updated pdt availability

bare-metal/elastic-metal/how-to/add-virtual-mac-address.mdx, bare-metal/elastic-metal/how-to/attach-detach-flexible-ip.mdx, bare-metal/elastic-metal/how-to/configure-flexible-ipv6.mdx, bare-metal/elastic-metal/how-to/configure-ipv6-hypervisor.mdx, bare-metal/elastic-metal/how-to/configure-reverse-dns-flexible-ip.mdx, bare-metal/elastic-metal/how-to/create-server.mdx, bare-metal/elastic-metal/how-to/enable-smtp.mdx, bare-metal/elastic-metal/how-to/install-server.mdx, bare-metal/elastic-metal/how-to/order-flexible-ip.mdx, bare-metal/elastic-metal/how-to/reboot-server.mdx, bare-metal/elastic-metal/how-to/reinstall-server.mdx, bare-metal/elastic-metal/how-to/view-the-event-logs.mdx, dedibox-console/account/how-to/report-incident.mdx, dedibox-network/ip-failover/how-to/configure-centos.mdx, dedibox-network/ip-failover/how-to/order-failover-ip.mdx, storage/object/api-cli/using-api-call-list.mdx, storage/object/how-to/use-bucket-website.mdx, storage/object/videos.mdx
Docs content review calendar week 04/2024
=> chore(docs): docs content review

menu/navigation.json
=> ins(fix): add link to navigation

compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx
=> fix(gen): fix 404

faq/serverless-containers.mdx, faq/serverless-jobs.mdx
=> docs(srv): add jobs billing to faq MTA-4127

console/account/how-to/open-a-support-ticket.mdx
=> fix(cxp): updated ticket creation page MTA-4109

storage/object/api-cli/using-api-call-list.mdx
=> fix(s3): update year on api call list

bare-metal/elastic-metal/how-to/configure-flexible-ip.mdx, dedibox-console/account/how-to/accept-outsourcing.mdx, dedibox-console/account/how-to/add-payment-method.mdx, dedibox-console/account/how-to/contact-support.mdx, dedibox-console/account/how-to/create-a-dedibox-account.mdx, dedibox-console/account/how-to/manage-data-settings.mdx, dedibox-console/account/how-to/outsource-dedibox.mdx, dedibox-console/account/how-to/outsource-failover-ip.mdx, dedibox-console/account/how-to/recover-password-lost-email.mdx, dedibox-console/account/how-to/resolve-abuse.mdx, dedibox-console/account/how-to/revoke-outsourcing.mdx, dedibox-console/account/how-to/update-email.mdx, dedibox-console/account/how-to/update-password.mdx, dedibox-console/account/how-to/upload-an-ssh-key.mdx, managed-databases/document-database/quickstart.mdx, managed-databases/postgresql-and-mysql/how-to/add-users.mdx, managed-databases/postgresql-and-mysql/how-to/create-a-database.mdx, managed-databases/postgresql-and-mysql/how-to/delete-a-database.mdx, managed-databases/redis/how-to/delete-a-database-for-redis.mdx, managed-services/webhosting/how-to/terminate-webhosting.mdx, network/load-balancer/how-to/create-manage-acls.mdx, serverless/messaging/reference-content/sns-support.mdx, tutorials/deploying-a-documentation-website-with-docusaurus-on-scaleway/index.mdx
=> feat(gen): docs content review

contribute.mdx
Removed remaining <concept> markdowns.
=> fix(gen): remove remaining concept markdowns

dedibox-network/dns/how-to/configure-secondary-dns.mdx, developer-tools/scaleway-cli/quickstart.mdx, storage/object/reference-content/optimize-object-storage-performance.mdx
=> fix(gen): fix broken links

tutorials/large-messages/index.mdx
=> fix(tutorial): add tag

managed-databases/redis/api-cli/managing-username-and-password.mdx, managed-databases/redis/how-to/connect-to-redis-database-instance.mdx, managed-databases/redis/how-to/create-a-database-for-redis.mdx, managed-databases/redis/how-to/manage-allowed-ip-addresses-redis.mdx, managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx, managed-databases/redis/quickstart.mdx, managed-databases/redis/reference-content/default-user-permissions.mdx, managed-databases/redis/reference-content/ensuring-data-persistence.mdx
=> fix(RED): content revision

serverless/sql-databases/how-to/connect-to-a-database.mdx, serverless/sql-databases/how-to/create-a-database.mdx
=> fix(sdb): add mention of doublequotes

containers/kubernetes/how-to/upgrade-kubernetes-version.mdx
1. Bumped versions list
2. Removed managed ingresses (not relevant anymore)
=> docs(k8s): update how to upgrade CLI tips

storage/object/reference-content/ssl-tls-certificate.mdx
Add info for Let's Encrypt errors
=> fix(es): add cert error info

macros/vpc/pn-naming.mdx, network/vpc/how-to/create-private-network.mdx, network/vpc/quickstart.mdx, network/vpc/troubleshooting/pn-name.mdx
Add doc for TLD PN naming issue
=> feat(vpc): add troubleshooting for tld naming issue

menu/navigation.json
Add new troubleshooting doc to menu
=> fix(vpc): correct menu

faq/account.mdx, faq/apple-silicon-m1-as-a-service.mdx, faq/billing.mdx, faq/blockstorage.mdx, faq/cockpit.mdx, faq/containerregistry.mdx, faq/databases-for-postgresql-and-mysql.mdx, faq/databases-for-redis.mdx, faq/dedibox-in-scaleway-console.mdx, faq/dedibox.mdx, faq/domains-and-dns.mdx, faq/elastic-metal.mdx, faq/iam.mdx, faq/instances.mdx, faq/iothub.mdx, faq/kubernetes.mdx, faq/loadbalancer.mdx, faq/messaging-and-queuing.mdx, faq/objectstorage.mdx, faq/private-networks.mdx, faq/public-gateways.mdx, faq/secret-manager.mdx, faq/serverless-containers.mdx, faq/serverless-functions.mdx, faq/serverless-jobs.mdx, faq/serverless-sql-databases.mdx, faq/support.mdx, faq/transactional-email.mdx, faq/vpc.mdx
- WDOC-760
As a front developer, I need to add category entry in faq frontmatters to be able to sectioning faqs by categories in main faqs page
=> feat(faq): add category in frontmatter for sorting in main faq page

containers/kubernetes/how-to/access-audit-logs.mdx, faq/objectstorage.mdx
=> fix(gen): fixed broken links

managed-services/webhosting/how-to/order-webhosting.mdx
=> fix(wbh): fixed double steps in wh docs

network/vpc/troubleshooting/pn-name.mdx
Update Private Network name propagation time with new value
=> fix(vpc): update prop time

macros/iam/requirements.mdx
Responding to user feedback, we will reduce the size of the warning text for IAM on Documentation pages.
=> fix(iam): iam banner update

changelog/february2024/2024-02-05-kubernetes-deprecated-force-internal-ip-annotation-in-k.mdx
=> feat(changelog): kubernetes-deprecated-force-internal-ip-annotation-in-k 2024-02-05

changelog/february2024/2024-02-06-kubernetes-added-kubernetes-version-129-is-now-availabl.mdx
=> feat(changelog): kubernetes-added-kubernetes-version-129-is-now-availabl 2024-02-06

containers/kubernetes/reference-content/version-support-policy.mdx
- 1.29 release
- New support timeline at 14 months
- Simplified version information
=> docs(k8s): version policy edits

containers/kubernetes/index.mdx
=> [GEN] New index 

menu/navigation.json, serverless/containers/quickstart.mdx, serverless/containers/troubleshooting/common-errors.mdx, serverless/functions/quickstart.mdx, serverless/jobs/quickstart.mdx
=> docs(srv): update quickstarts MTA-4168

identity-and-access-management/secret-manager/concepts.mdx, identity-and-access-management/secret-manager/how-to/create-folder.mdx, identity-and-access-management/secret-manager/how-to/create-secret.mdx, identity-and-access-management/secret-manager/how-to/create-version.mdx, identity-and-access-management/secret-manager/quickstart.mdx
- Added the secret protection step in the secret/folder creation docs + quickstart
=> docs(sem): add secret protection step in different docs

containers/kubernetes/reference-content/version-support-policy.mdx
Reverts scaleway/docs-content#2690
=> Revert "docs(k8s): version policy edits"

containers/kubernetes/index.mdx
Fixed link to k8s quickstart in index file
=> fix(k8s): fix link to quickstart

console/account/reference-content/products-availability.mdx
=> docs(sdb): update product availability page

faq/cockpit.mdx, observability/cockpit/reference-content/cockpit-limitations.mdx
=> docs(cockpit): add new pricing plans information

storage/object/reference-content/cname-record.mdx, storage/object/reference-content/ssl-tls-certificate.mdx
Updated error info for Edge Services
=> fix(es): fix errors

containers/kubernetes/reference-content/version-support-policy.mdx
=> [K8S] update version support policy v1.29

changelog/february2024/2024-02-06-kubernetes-added-kubernetes-version-129-is-now-availabl.mdx
=> [K8S] Changelog - Kubernetes version 1.29

changelog/february2024/2024-02-12-containers-deprecated-deprecation-of-logs-endpoint.mdx, changelog/february2024/2024-02-12-functions-deprecated-deprecation-of-logs-endpoint.mdx
Serverless compute changelog 2024/02/12
=> docs(changelog): serverless compute changelog 2024/02/12

bare-metal/elastic-metal/how-to/activate-remote-access.mdx, bare-metal/elastic-metal/how-to/send-metrics-logs-to-cockpit.mdx, bare-metal/elastic-metal/how-to/view-the-event-logs.mdx, menu/navigation.json
How to send metrics and logs from BM servers to Cockpit
=> docs(em): sending logs to cockpit

dedibox-network/network/reference-content/anti-ddos.mdx, dedibox-network/network/troubleshooting.mdx, dedibox-network/rpn/how-to/use-rpn-san-proxmox.mdx, dedibox-network/rpn/quickstart.mdx, serverless/sql-databases/how-to/add-users.mdx, serverless/sql-databases/how-to/configure-autoscaling.mdx, serverless/sql-databases/how-to/create-a-database.mdx, serverless/sql-databases/how-to/delete-a-database.mdx, serverless/sql-databases/how-to/manage-permissions.mdx, serverless/sql-databases/quickstart.mdx
Docs content review 2024/02/12
=> [GEN] Docs content review

faq/serverless-sql-databases.mdx, menu/navigation.json, serverless/sql-databases/concepts.mdx, serverless/sql-databases/how-to/add-users.mdx, serverless/sql-databases/how-to/configure-autoscaling.mdx, serverless/sql-databases/how-to/connect-to-a-database.mdx, serverless/sql-databases/how-to/create-a-database.mdx, serverless/sql-databases/how-to/delete-a-database.mdx, serverless/sql-databases/how-to/manage-backups.mdx, serverless/sql-databases/how-to/manage-permissions.mdx, serverless/sql-databases/quickstart.mdx, serverless/sql-databases/reference-content/known-differences.mdx, serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx, serverless/sql-databases/troubleshooting/connection-errors.mdx, serverless/sql-databases/troubleshooting/failing-backup-restore.mdx, serverless/sql-databases/troubleshooting/unable-to-connect.mdx
=> docs(sdb): update faq and ref content MTA-4172

network/load-balancer/index.mdx, network/public-gateways/index.mdx, network/vpc/index.mdx, serverless/messaging/index.mdx
Add product pages for network core and edge products, and mnq
=> feat(doc): add product pages for NW Core, NW Edge and M&Q

network/load-balancer/concepts.mdx, network/load-balancer/how-to/set-up-s3-failover.mdx, network/load-balancer/reference-content/configuring-backends.mdx
Following user testing, add more information about S3 failover feature for LB.
=> fix(lb): add more info about S3 failover

containers/container-registry/index.mdx, containers/index.mdx, identity-and-access-management/iam/index.mdx, labs/ipfs-naming/index.mdx, labs/ipfs-pinning/index.mdx, managed-databases/document-database/index.mdx, managed-databases/postgresql-and-mysql/index.mdx, managed-databases/redis/index.mdx
Added and integrated content for the following products:
PostgreSQL and MySQL
Redis
Document Databases
IPFS Pinning
IPFS Naming
IAM
Container Registry
=> fix(gen): add product pages

serverless/containers/index.mdx, serverless/functions/index.mdx, serverless/jobs/index.mdx, serverless/sql-databases/index.mdx, storage/object/index.mdx
=> feat(doc): add S3, SRV & SDB product pages MTA-4099

network/load-balancer/index.mdx, network/vpc/index.mdx, serverless/messaging/index.mdx
Fix wording on merged product pages
=> fix(doc): fix product page wording

bare-metal/elastic-metal/reference-content/elastic-metal-stock-levels.mdx, menu/navigation.json
Elastic Metal Server stock levels explained
=> docs(em): stock levels

bare-metal/elastic-metal/how-to/send-metrics-logs-to-cockpit.mdx
=> docs(fix): broken link

identity-and-access-management/secret-manager/index.mdx, managed-services/transactional-email/index.mdx, network/domains-and-dns/index.mdx, observability/cockpit/index.mdx, serverless/containers/index.mdx, serverless/functions/index.mdx, serverless/jobs/index.mdx, serverless/sql-databases/index.mdx, storage/block/index.mdx, storage/object/index.mdx
=> fix(gen): fixed some index pages

managed-services/iot-hub/index.mdx
=> docs(iot): add iot hub index

changelog/february2024/2024-02-15-webhosting-added-email-forwading-enabled.mdx, menu/changelogs.json
=> docs(changelog): webhosting email forwarding enabled

changelog/february2024/2024-02-15-webhosting-added-dedicated-ip-for-web-hosting.mdx
=> feat(changelog): webhosting-added-dedicated-ip-for-web-hosting 2024-02-15

containers/kubernetes/reference-content/lb-ingress-controller.mdx
Add information about security group configuration to additional content
=> docs(k8s): add information for sg

compute/gpu/reference-content/docker-images.mdx
Change link to broken changelog absolute path to use a relative path instead.
=> fix(instances): broken link

faq/instances.mdx
- Improve readability by adding extra spacing between queries.
- Correct color of an informational banner.
- Change H2/H3 headers.
=> fix(ins): improve spacing and readability

blocks/mainLinks.json
---
- New file for navbar v1
- No impact on current codebase
- header.json will be deleted in navbar v2
=> feat(navbar): New file for main links

storage/object/how-to/create-a-bucket.mdx, storage/object/quickstart.mdx
=> docs(s3): update bucket creation with use case MTA-3205

managed-services/webhosting/index.mdx
Added Changelog to Web Hosting product index
=> docs(wbh): add changelog to webhosting index

network/load-balancer/how-to/add-certificate.mdx, network/load-balancer/reference-content/ssl-bridging-offloading-passthrough.mdx
Following user testing, add more info about certificates
=> fix(lb): add info for certificates

changelog/february2024/2024-02-20-object-storage-added-object-storage-now-offers-sla.mdx
=> feat(changelog): object-storage-added-object-storage-now-offers-sla 2024-02-20

managed-services/transactional-email/index.mdx
=> docs(tem): fix typo

faq/objectstorage.mdx
=> fix(s3): update faq MTA-4217

changelog/february2024/2024-02-20-kubernetes-fixed-dns-fix-to-resolve-occasional-resoluti.mdx
=> feat(changelog): kubernetes-fixed-dns-fix-to-resolve-occasional-resoluti 2024-02-20

changelog/february2024/2024-02-20-object-storage-added-object-storage-introduces-bucket-u.mdx
=> feat(changelog): object-storage-added-object-storage-introduces-bucket-u 2024-02-20

storage/object/reference-content/cname-record.mdx
Update error documentation again for Edge Services
=> fix(es): update errors

index.mdx
=> [GEN] New home test

network/load-balancer/reference-content/configuring-backends.mdx, network/load-balancer/reference-content/configuring-health-checks.mdx
Improve info for max simultaneous connections based on user testing
=> fix(lb): improve info for max simultaneous connections

changelog/february2024/2024-02-22-messaging-and-queuing-added-sns-subscriptions-creation-.mdx
=> feat(changelog): messaging-and-queuing-added-sns-subscriptions-creation- 2024-02-22

changelog/february2024/2024-02-22-messaging-and-queuing-added-messaging-and-queuing-is-av.mdx
=> feat(changelog): messaging-and-queuing-added-messaging-and-queuing-is-av 2024-02-22

network/load-balancer/reference-content/configuring-health-checks.mdx
Improve information about configuring HTTP health checks
=> fix(lb): improve info for HTTP health checks

tutorials/collecting-visualizing-logs-elastic-stack/index.mdx
=> docs(tutorial): fix review date

dedibox/dedicated-servers/how-to/rescue-your-data.mdx
=> docs(ddx): add information for dedibackup

serverless/jobs/how-to/run-job.mdx
=> docs(SRV): add contextual options to job run MTA-4216

serverless/jobs/concepts.mdx
=> docs(srv): add ephemeral storage concept MTA-4221

compute/gpu/how-to/create-manage-gpu-instance.mdx, compute/gpu/quickstart.mdx, compute/instances/how-to/create-an-instance.mdx, compute/instances/quickstart.mdx
=> [INS] Update Instance creation with routed IP feature

console/billing/quickstart.mdx
=> docs(bil): Added Quickstart MTA-4073

dedibox/dedicated-servers/how-to/change-root-password.mdx, dedibox/dedicated-servers/how-to/install-a-server.mdx, dedibox/dedicated-servers/how-to/order-a-server.mdx
Fixed indentions to make numbered steps working again
=> chore(ddx): fix numbered steps

storage/object/how-to/get-started-edge-services.mdx, storage/object/reference-content/cname-record.mdx
Add information for auto-CNAME creation to Edge Services doc
=> fix(es): add info for auto-cname creation

changelog/february2024/2024-02-28-secret-manager-changed-a-new-version-of-secret-manager-.mdx
=> feat(changelog): secret-manager-changed-a-new-version-of-secret-manager- 2024-02-28

faq/serverless-sql-databases.mdx
=> fix(sdb): fix broken link MTA-4251

changelog/february2024/2024-02-29-billing-changed-new-billing-space.mdx
=> feat(changelog): billing-changed-new-billing-space 2024-02-29

faq/serverless-containers.mdx, faq/serverless-functions.mdx, faq/serverless-jobs.mdx, serverless/containers/concepts.mdx, serverless/functions/concepts.mdx, serverless/jobs/concepts.mdx
=> fix(srv): correct consumption units in faq and add concepts MTA-4253

console/account/reference-content/organization-quotas.mdx
=> docs(account): update L4 quotas

bare-metal/elastic-metal/api-cli/elastic-metal-with-cli.mdx
Command is erroneously for reboot.
Fix the deletion command. Probably a copy-paste error from above.
=> docs(bare-metal): Fix deletion command

serverless/containers/how-to/create-a-containers-namespace.mdx, serverless/containers/how-to/manage-a-containers-namespace.mdx, serverless/containers/reference-content/containers-limitations.mdx, serverless/containers/troubleshooting/common-errors.mdx
=> docs(SRV): review content MTA-4236

menu/navigation.json
=> docs(gen): fix menu

tutorials/ansible-bionic-beaver/index.mdx, tutorials/ansible-galaxy/index.mdx, tutorials/bash-christmas-tree/index.mdx, tutorials/configure-nagios-monitoring/index.mdx, tutorials/create-models-django/index.mdx, tutorials/deploy-saas-application/index.mdx, tutorials/django-ubuntu-focal-fossa/index.mdx, tutorials/load-testing-vegeta/index.mdx, tutorials/setup-mongodb-on-ubuntu/index.mdx, tutorials/wireguard-mesh-vpn/index.mdx, tutorials/wordpress-lemp-stack-ubuntu-jammy-jellyfish-22-04/index.mdx
=> chore(tutorials): content review

faq/support.mdx
=> gen(fix): removed live chat mention

changelog/march2024/2024-03-05-jobs-added-serverless-jobs-contextual-parameters.mdx
=> feat(changelog): jobs-added-serverless-jobs-contextual-parameters 2024-03-05

console/account/how-to/open-a-support-ticket.mdx, console/project/how-to/change-project-name.mdx, console/project/how-to/delete-a-project.mdx, identity-and-access-management/organizations-and-projects/how-to/add-resources-project.mdx, identity-and-access-management/organizations-and-projects/how-to/change-project-name.mdx, identity-and-access-management/organizations-and-projects/how-to/create-a-project.mdx, identity-and-access-management/organizations-and-projects/how-to/delete-a-project.mdx
=> docs(cns): docs content review MTA-4239

containers/kubernetes/api-cli/managing-storage.mdx
=> docs(k8s): update information encrypted volumes

console/account/index.mdx
=> docs(cns): add account product page MTA-4293

managed-services/webhosting/how-to/migrate-webhosting-plan.mdx, managed-services/webhosting/reference-content/classic-hosting-migration-information.mdx, menu/navigation.json
=> [WBH] Documentation migration of web hosting classic

storage/object/troubleshooting/api-key-does-not-work.mdx
=> fix(s3): add link to IAM API keys doc

menu/navigation.json
Add link to product FAQ to navigation bar
=> [GEN] add faq to navigation

changelog/march2024/2024-03-12-postgresql-and-mysql-added-postgresql-pgaudit-extension.mdx
=> feat(changelog): postgresql-and-mysql-added-postgresql-pgaudit-extension 2024-03-12

serverless/messaging/concepts.mdx
Update DLQ concept on Product Doc page
=> fix(mnq) : update DLQ concept definition

compute/instances/how-to/migrate-routed-ips.mdx, faq/instances.mdx
=> [INS] Update docs IP Mobility

macros/iam/requirements.mdx
=> fix(docs): requirements macro

containers/kubernetes/reference-content/kubernetes-control-plane-offers.mdx
Editing offers table to bring audit logs into the dedicated plan
=> docs(k8s): audit logs added to dedicated

changelog/march2024/2024-03-12-gpu-instances-added-new-h100-instances.mdx, changelog/october2023/2023-10-06-gpu-instances-added-new-h100-instances.mdx
=> feat(changelog): gpu-instances-added-new-h100-instances 2024-03-12

console/account/how-to/manage-billing-information.mdx, containers/kubernetes/how-to/connect-cluster-kubectl.mdx, faq/billing.mdx, storage/object/api-cli/object-operations.mdx, tutorials/get-started-kubernetes-loadbalancer/index.mdx, tutorials/install-apache-ansible/index.mdx, tutorials/install-pgbouncer/index.mdx, tutorials/nginx-reverse-proxy/index.mdx
I've developed a Python script that leverages an LLM to enrich the meta descriptions of our documentation pages. The aim is to extend these descriptions, making them more detailed and informative. This enhancement is anticipated to improve the SEO performance of our documentation website.
The script is ready and can be executed across all our documentation pages to update their meta descriptions, should you find this proposal valuable. I believe this improvement could contribute to the visibility and accessibility of our documentation.
Looking forward to your feedback and happy to discuss further!
=> Update 8 most consulted pages meta description

containers/kubernetes/api-cli/changing-control-plane-offer.mdx, containers/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
=> [K8S] Content review

containers/kubernetes/how-to/delete-cluster.mdx, containers/kubernetes/how-to/deploy-x86-arm-images.mdx, containers/kubernetes/how-to/enable-disable-ssh.mdx, containers/kubernetes/how-to/use-scratch-storage-h100.mdx, containers/kubernetes/troubleshooting/containers-not-starting-arm-instances.mdx, containers/kubernetes/troubleshooting/index.mdx, menu/navigation.json
=> [K8S] Added - ARM information to docs

changelog/march2024/2024-03-12-jobs-fixed-serverless-jobs-fix-usage-of-cached-images.mdx
=> feat(changelog): jobs-fixed-serverless-jobs-fix-usage-of-cached-images 2024-03-12

managed-services/webhosting/how-to/migrate-webhosting-plan.mdx, managed-services/webhosting/reference-content/classic-hosting-migration-information.mdx
=> docs(webhosting): add warning

faq/instances.mdx
=> docs(faq): add question to instance faq

changelog/march2024/2024-03-12-gpu-instances-changed-h100-now-available-in-poland.mdx
=> feat(changelog): gpu-instances-changed-h100-now-available-in-poland 2024-03-12

tutorials/nextjs-app-serverless-functions-sqldb/index.mdx
=> docs(SDB): add ReactJS x Serverless DB/Containers tutorial MTA-4243

changelog/march2024/2024-03-12-gpu-instances-added-new-gpu-l4-instances.mdx
=> feat(changelog): gpu-instances-added-new-gpu-l4-instances 2024-03-12

serverless/sql-databases/index.mdx
=> fix(SDB): fix Serverless DB index links

tutorials/get-started-kubernetes-storage/index.mdx
=> fix(tuto): fix filename

tutorials/create-serverless-scraping/index.mdx
Moved the code repository to serverless-examples. 
Integrated some suggestions, including full automated terraform deployment (no more need to manually zip functions)
=> Int fix mnqsqsserverlessscraping

containers/kubernetes/videos.mdx
=> fix(k8s): correct indentation

containers/kubernetes/reference-content/version-support-policy.mdx
1.23 removed
1.24 CNI information
=> docs(k8s): 1.23 is EOS

developer-tools/scaleway-cli/reference-content/cli-reference.mdx, developer-tools/scaleway-cli/reference-content/console-keyboard-shortcuts.mdx, storage/object/how-to/get-started-edge-services.mdx
=> docs(gen): doc review MTA-4339

bare-metal/elastic-metal/reference-content/elastic-metal-datasheet.mdx, console/account/reference-content/products-availability.mdx
=> docs(em): update product availability

bare-metal/elastic-metal/how-to/use-private-networks.mdx
=> fix(em): added important message box

tutorials/get-started-kubernetes-storage/index.mdx
=> chore(k8s): typo

changelog/march2024/2024-03-19-block-storage-added-block-storage-new-user-journey-and-.mdx
=> feat(changelog): block-storage-added-block-storage-new-user-journey-and- 2024-03-19

changelog/march2024/2024-03-19-kubernetes-added-kubernetes-kapsule-and-kubernetes-kosm.mdx
=> feat(changelog): kubernetes-added-kubernetes-kapsule-and-kubernetes-kosm 2024-03-19

changelog/march2024/2024-03-19-kubernetes-changed-container-storage-interface-v03-now-.mdx
=> feat(changelog): kubernetes-changed-container-storage-interface-v03-now- 2024-03-19

storage/object/api-cli/bucket-policy.mdx
=> fix(s3): fix wrong wording MTA-4346

macros/serverless/difference-jobs-functions-containers.mdx
=> fix(srv): remove incorrect diagram

changelog/march2024/2024-03-20-jobs-added-custom-ephemeral-storage-on-serverless-jobs.mdx
=> feat(changelog): jobs-added-custom-ephemeral-storage-on-serverless-jobs 2024-03-20

bare-metal/elastic-metal/how-to/kubernetes-on-riscv.mdx
Add an how to to run kubernetes nodes on RISC-V using the new EM-RV1 server and Kosmos
=> docs(elastic-metal): add how-to run kubernetes nodes on RISC-V int-add-elastic-metal

menu/navigation.json
=> fix(em): add RISCV nav

managed-services/iot-hub/reference-content/networks.mdx
=> fix(iot): add missing word

tutorials/nextjs-app-serverless-functions-sqldb/index.mdx
=> fix(tutorials): fix broken link and indentation

identity-and-access-management/iam/api-cli/managing-projects.mdx, identity-and-access-management/iam/how-to/accept-invitation-to-orga.mdx, identity-and-access-management/iam/how-to/create-api-keys.mdx, identity-and-access-management/iam/how-to/create-application.mdx, identity-and-access-management/iam/how-to/create-group.mdx, identity-and-access-management/iam/how-to/create-policy.mdx, identity-and-access-management/iam/how-to/invite-user-to-orga.mdx, identity-and-access-management/iam/how-to/manage-api-keys.mdx, identity-and-access-management/iam/how-to/manage-applications.mdx, identity-and-access-management/iam/how-to/manage-groups.mdx, identity-and-access-management/iam/how-to/manage-policies.mdx, identity-and-access-management/iam/how-to/manage-users.mdx, identity-and-access-management/iam/how-to/view-logs.mdx, identity-and-access-management/iam/quickstart.mdx, identity-and-access-management/iam/reference-content/overview.mdx, identity-and-access-management/iam/reference-content/reproduce-roles-project-api-keys.mdx, identity-and-access-management/iam/reference-content/users-groups-and-applications.mdx
IAM and Requirements sections update.
=> docs(iam): requirements update

containers/kubernetes/api-cli/changing-control-plane-offer.mdx, containers/kubernetes/api-cli/cluster-monitoring.mdx, containers/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx, containers/kubernetes/api-cli/managing-storage.mdx, containers/kubernetes/api-cli/managing-tags.mdx, containers/kubernetes/how-to/access-audit-logs.mdx, containers/kubernetes/how-to/access-kubernetes-dashboard.mdx, containers/kubernetes/how-to/change-container-runtime-interface.mdx, containers/kubernetes/how-to/connect-cluster-kubectl.mdx, containers/kubernetes/how-to/create-cluster.mdx, containers/kubernetes/how-to/create-kosmos-cluster.mdx, containers/kubernetes/how-to/delete-cluster.mdx, containers/kubernetes/how-to/deploy-image-from-container-registry.mdx, containers/kubernetes/how-to/deploy-ingress-controller.mdx, containers/kubernetes/how-to/deploy-x86-arm-images.mdx, containers/kubernetes/how-to/edit-cluster.mdx, containers/kubernetes/how-to/edit-kosmos-cluster.mdx, containers/kubernetes/how-to/enable-disable-ssh.mdx, containers/kubernetes/how-to/enable-easy-deploy.mdx, containers/kubernetes/how-to/monitor-cluster.mdx, containers/kubernetes/how-to/upgrade-kubernetes-version.mdx, containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx, containers/kubernetes/how-to/use-scratch-storage-h100.mdx
Requirements section updated on API/CLI and How-to pages.
=> docs(k8s): requirements update part 1

containers/kubernetes/quickstart.mdx, containers/kubernetes/reference-content/introduction-to-kubernetes.mdx, containers/kubernetes/reference-content/kubernetes-cheatsheet.mdx, containers/kubernetes/reference-content/kubernetes-control-plane-offers.mdx, containers/kubernetes/reference-content/kubernetes-load-balancer.mdx, containers/kubernetes/reference-content/lb-ingress-controller.mdx, containers/kubernetes/reference-content/managed-kubernetes-service-definition.mdx, containers/kubernetes/reference-content/managing-load-balancer-ips.mdx, containers/kubernetes/reference-content/multi-az-clusters.mdx, containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx, containers/kubernetes/reference-content/using-load-balancer-annotations.mdx, containers/kubernetes/reference-content/version-support-policy.mdx, containers/kubernetes/reference-content/wildcard-dns.mdx, containers/kubernetes/troubleshooting/containers-not-starting-arm-instances.mdx
Updated requirements on Reference Content and Troubleshooting Kubernetes pages.
=> docs(k8s): requirements update part 2

ai-data/llm-inference/reference-content/wizardlm-70b.mdx
=> docs(llm): fix typo

bare-metal/elastic-metal/how-to/configure-flexible-ip.mdx
=> docs(em): add link to netplan config

bare-metal/elastic-metal/reference-content/elastic-metal-understanding-rv1-usage.mdx
- explain the boot process of EM-RV1
- add a tutorial to boot a custom kernel on EM-RV1
=> feat(bare-metal): add tutorial to boot a custom kernel on EM-RV1

managed-services/transactional-email/how-to/add-mx-record-to-your-domain.mdx, managed-services/transactional-email/how-to/add-spf-dkim-records-to-your-domain.mdx, managed-services/transactional-email/how-to/configure-domain-with-transactional-email.mdx, managed-services/transactional-email/how-to/delete-tem-domain.mdx, managed-services/transactional-email/how-to/generate-api-keys-for-tem-with-iam.mdx, managed-services/transactional-email/how-to/manage-email-activity.mdx, managed-services/transactional-email/quickstart.mdx, managed-services/transactional-email/reference-content/dmarc-configuration.mdx, managed-services/transactional-email/reference-content/protecting-your-domain-reputation.mdx, managed-services/transactional-email/reference-content/understanding-tem-reputation-score.mdx, managed-services/transactional-email/troubleshooting/delist-domain.mdx
TEM requirements section updated.
=> docs(mas): tem requirements update

bare-metal/elastic-metal/how-to/use-private-networks.mdx, bare-metal/elastic-metal/troubleshooting/enable-ssh-virtualization-distribution.mdx, compute/gpu/reference-content/understanding-nvidia-tao.mdx, dedibox-network/dns/how-to/configure-reverse-dns.mdx, dedibox-network/dns/how-to/configure-secondary-dns.mdx, dedibox-network/domains/how-to/enable-dnssec.mdx, dedibox-network/domains/how-to/file-contact-info.mdx, dedibox-network/domains/quickstart.mdx
=> docs(compute): review docs

menu/navigation.json
=> chore(em): add link to rv1 content

console/account/concepts.mdx, console/account/how-to/close-account.mdx, console/account/how-to/manage-my-personal-data-gdpr.mdx, console/account/how-to/report-incident.mdx, console/account/how-to/resolve-abuse.mdx, dedibox-console/account/concepts.mdx, dedibox-console/account/how-to/report-incident.mdx, dedibox-console/account/how-to/resolve-abuse.mdx, faq/support.mdx, menu/navigation.json
=> [ACCOUNT] New abuse handling process

menu/navigation.json
=> docs(fix): fixed broken file

serverless/jobs/how-to/create-job-from-external-registry.mdx, serverless/jobs/how-to/create-job-from-scaleway-registry.mdx, serverless/jobs/how-to/delete-job.mdx, serverless/jobs/how-to/manage-job-schedule.mdx, serverless/jobs/how-to/monitor-job.mdx, serverless/jobs/how-to/run-job.mdx, serverless/jobs/how-to/stop-job.mdx, serverless/jobs/quickstart.mdx
Serverless Jobs requirements section updated.
=> docs(srv): serverless jobs requirements update

identity-and-access-management/secret-manager/api-cli/create-secret-path-migrate.mdx, identity-and-access-management/secret-manager/api-cli/external-secrets.mdx, identity-and-access-management/secret-manager/how-to/create-secret.mdx, identity-and-access-management/secret-manager/how-to/create-version.mdx, identity-and-access-management/secret-manager/how-to/delete-secret.mdx, identity-and-access-management/secret-manager/how-to/delete-version.mdx, identity-and-access-management/secret-manager/how-to/manage-secret.mdx, identity-and-access-management/secret-manager/how-to/manage-version.mdx, identity-and-access-management/secret-manager/quickstart.mdx
=> docs(sem): requirements update

network/load-balancer/how-to/create-load-balancer.mdx, network/load-balancer/how-to/use-with-private-network.mdx, network/load-balancer/reference-content/configuring-backends.mdx, network/vpc/quickstart.mdx
Review NW doc pages scheudled for review by reviewbot
=> fix(nw): review bot update

tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx, tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
=> fix(tutorial): update tutorial for new M&Q flow

menu/navigation.json, network/domains-and-dns/concepts.mdx, network/domains-and-dns/how-to/renew-domain.mdx, network/domains-and-dns/how-to/trade-domain.mdx, network/domains-and-dns/how-to/unlock-internal-domain.mdx
- Trade concept 
- Trade documentation
=> add(domains): add trade documentation

managed-services/webhosting/how-to/configure-dns-webhosting.mdx, managed-services/webhosting/how-to/manage-webhosting.mdx, managed-services/webhosting/how-to/migrate-webhosting-plan.mdx, managed-services/webhosting/how-to/order-dedicated-ip.mdx, managed-services/webhosting/how-to/order-webhosting.mdx, managed-services/webhosting/how-to/terminate-webhosting.mdx, managed-services/webhosting/quickstart.mdx, managed-services/webhosting/reference-content/classic-hosting-migration-information.mdx, managed-services/webhosting/reference-content/cpanel-reference-content.mdx, managed-services/webhosting/reference-content/plesk-reference-content.mdx, managed-services/webhosting/reference-content/understanding-differences-cpanel-plesk.mdx
=> docs(mas): web hosting requirements update

ai-data/llm-inference/quickstart.mdx
=> fix(llm): fixed page title

menu/navigation.json, serverless/containers/concepts.mdx, serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx, serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx, serverless/containers/reference-content/containers-concurrency.mdx
=> docs(srv): add concurrency docs and update deploy page MTA-4361

compute/instances/reference-content/identify-devices.mdx, menu/navigation.json
=> docs(ins): add indentify devices docs

faq/loadbalancer.mdx, network/load-balancer/concepts.mdx, network/load-balancer/how-to/create-load-balancer.mdx, network/load-balancer/how-to/create-manage-flex-ips.mdx, network/load-balancer/quickstart.mdx, network/load-balancer/troubleshooting/load-balancer-limitations.mdx
Add IPv6 doc for Load Balancer.
=> feat(lb): add ipv6 doc

menu/navigation.json
Added product index pages to the main navigation menu.
=> docs(gen): add index pages to navigation menu

compute/gpu/troubleshooting/install-nvidia-drivers-ubuntu.mdx, compute/gpu/troubleshooting/updating-gpu-instance-with-cloud-init.mdx, menu/navigation.json
=> feat(gpu): add driver install doc

console/billing/how-to/use-the-cost-manager.mdx
=> feat(bil): fix images MTA-4356s

changelog/march2024/2024-03-28-billing-added-discover-our-cost-manager-tool.mdx
=> feat(changelog): billing-added-discover-our-cost-manager-tool 2024-03-28

changelog/march2024/2024-03-28-jobs-added-serverless-jobs-is-now-in-ga.mdx
=> feat(changelog): jobs-added-serverless-jobs-is-now-in-ga 2024-03-28

faq/cockpit.mdx
Content displayed weirdly in the preview.
=> docs(cpt): fixed weird display in preview

managed-databases/postgresql-and-mysql/reference-content/security-and-reliability.mdx
=> feat(rdb): fix indent

serverless/messaging/index.mdx, tutorials/create-serverless-scraping/index.mdx, tutorials/large-messages/index.mdx, tutorials/sns-instances-notification-system/index.mdx
Add SEO optimized descriptions for M&Q tutorials
Add latest tutorial to M&Q home page
=> fix(tutorials): add seo descriptions for tutorials

menu/navigation.json, serverless/jobs/reference-content/jobs-limitations.mdx, serverless/jobs/troubleshooting/common-errors.mdx
=> docs(srv): add jobs troubleshooting and limitations MTA-4365

menu/navigation.json
=> Update navigation.json to fix prettier error

macros/iam/requirements.mdx, managed-services/transactional-email/how-to/add-dmarc-record.mdx
Small update on macro requirements.
=> docs(gen): requirement macro small update

managed-services/webhosting/quickstart.mdx
=> fix(webhosting): typo

docs/CONTRIBUTING.md
=> docs(gen): Update contributing guidelines with fork instructions

bare-metal/dedibox/concepts.mdx, bare-metal/dedibox/how-to/activate-ipv6-block.mdx, bare-metal/dedibox/how-to/attach-detach-failover-ip.mdx, bare-metal/dedibox/how-to/configure-failover-ip.mdx, bare-metal/dedibox/how-to/configure-ipv6-dedibox.mdx, bare-metal/dedibox/how-to/configure-reverse-failover-ip.mdx, bare-metal/dedibox/how-to/connect-to-dedibox.mdx, bare-metal/dedibox/how-to/install-dedibox.mdx, bare-metal/dedibox/how-to/link-dedibox-account.mdx, bare-metal/dedibox/how-to/modify-server-options.mdx, bare-metal/dedibox/how-to/order-dedibox.mdx, bare-metal/dedibox/how-to/order-failover-ip.mdx, bare-metal/dedibox/how-to/reinstall-dedibox.mdx, bare-metal/dedibox/how-to/terminate-dedibox.mdx, bare-metal/dedibox/how-to/use-rescue-mode.mdx, bare-metal/dedibox/quickstart.mdx, dedibox-console/classic-hosting/how-to/configure-backup-option.mdx, dedibox/kvm-over-ip/how-to/supermicro.mdx, developer-tools/terraform/quickstart.mdx, managed-services/iot-hub/api-cli/cli-db-tips-tricks.mdx, managed-services/iot-hub/api-cli/iot-hub-routes.mdx, tutorials/python-lists-dicts/index.mdx
Updated some missing requirement sections that still featured the old macro.
=> docs(ddx): requirement section update

managed-services/transactional-email/troubleshooting/delist-domain.mdx
Reviewed weekly doc review content
=> fix(tem): content review

changelog/april2024/2024-04-03-block-storage-added-low-latency-offers-integration-in-c.mdx
=> feat(changelog): block-storage-added-low-latency-offers-integration-in-c 2024-04-03

dedibox-network/network/index.mdx
=> fix(ddx): fixed typo

ai-data/llm-inference/how-to/create-deployment.mdx, bare-metal/dedibox/how-to/activate-ipv6-block.mdx, compute/gpu/reference-content/understanding-nvidia-nemo.mdx, containers/kubernetes/reference-content/kubernetes-control-plane-offers.mdx, dedibox/hardware/how-to/configure-dell-perc-h200.mdx, dedibox/hardware/how-to/configure-dell-perc-h310.mdx, dedibox/hardware/how-to/configure-dell-perc-h700.mdx, dedibox/hardware/how-to/configure-dell-perc-h800.mdx, dedibox/hardware/how-to/configure-hp-smart-array-p410.mdx, dedibox/hardware/how-to/configure-hp-smart-array-p420.mdx, dedibox/hardware/troubleshooting/diagnose-defective-disk.mdx
=> chore(ddx): update docs

network/vpc/how-to/attach-resources-to-pn.mdx, network/vpc/how-to/create-private-network.mdx, network/vpc/how-to/delete-private-network.mdx, network/vpc/troubleshooting/vpc-limitations.mdx
=> fix(vpc): review

changelog/april2024/2024-04-04-load-balancers-added-public-ipv6-addresses-are-now-avai.mdx
=> feat(changelog): load-balancers-added-public-ipv6-addresses-are-now-avai 2024-04-04

changelog/april2024/2024-04-04-webhosting-added-web-hosting-migration-between-online-a.mdx
=> feat(changelog): webhosting-added-web-hosting-migration-between-online-a 2024-04-04

changelog/april2024/2024-04-04-webhosting-added-all-regions-are-now-available.mdx
=> feat(changelog): webhosting-added-all-regions-are-now-available 2024-04-04

network/vpc/how-to/delete-private-network.mdx, network/vpc/troubleshooting/vpc-limitations.mdx
=> fix(vpc): bad date

changelog/april2024/2024-04-04-cockpit-added-transactional-email-dashboard-is-now-avai.mdx
=> feat(changelog): cockpit-added-transactional-email-dashboard-is-now-avai 2024-04-04

changelog/april2024/2024-04-04-cockpit-added-metrics-degrissivity.mdx
=> feat(changelog): cockpit-added-metrics-volume-discounts 2024-04-04

changelog/april2024/2024-04-04-cockpit-changed-traces-are-now-in-ga.mdx
=> feat(changelog): cockpit-changed-traces-are-now-in-ga 2024-04-04

changelog/april2024/2024-04-04-webhosting-added-web-hosting-migration-between-online-a.mdx
=> fix(changelog): fixed wording

identity-and-access-management/secret-manager/api-cli/create-secret-with-type.mdx, identity-and-access-management/secret-manager/index.mdx, menu/navigation.json
SEM-677
With the addition of new types for secrets, documentation on the expected json format for each type has become necessary.
=> feat(secret-manager): add new tutorial for secret types

identity-and-access-management/secret-manager/api-cli/create-secret-with-type.mdx
- Fixed indentation errors
- Other things that were causing build issues
=> docs(sem): fixes

storage/object/how-to/restore-an-object-from-glacier.mdx
=> docs(s3): update object restore procedure MTA-4395

storage/object/how-to/restore-an-object-from-glacier.mdx
=> fix(s3): remove old markup that breaks build

changelog/april2024/2024-04-05-postgresql-and-mysql-added-block-low-latency-general-av.mdx
=> feat(changelog): postgresql-and-mysql-added-block-low-latency-general-av 2024-04-05

changelog/april2024/2024-04-05-postgresql-and-mysql-added-complete-db-pro2-offer-avail.mdx
=> feat(changelog): postgresql-and-mysql-added-complete-db-pro2-offer-avail 2024-04-05

network/public-gateways/how-to/move-to-routed-ip.mdx
=> fix(pgw): remove unwanted macro

bare-metal/elastic-metal/how-to/install-server.mdx
=> docs(em): add info for custom partitioning

menu/navigation.json
=> fix(k8s): add missing link

containers/kubernetes/concepts.mdx
=> feat(k8s): add link

tutorials/backup-dedicated-server-s3-duplicity/index.mdx, tutorials/deploy-nextcloud-s3/index.mdx, tutorials/glusterfs/index.mdx, tutorials/install-cockroachdb-scaleway-instances/index.mdx, tutorials/setup-lamp-stack-ubuntu2204/index.mdx, tutorials/setup-moodle/index.mdx, tutorials/setup-nginx-reverse-proxy-s3/index.mdx, tutorials/socket-io/index.mdx, tutorials/strapi/index.mdx
=> chore(tutorial): content review

bare-metal/dedibox/how-to/attach-detach-failover-ip.mdx, bare-metal/dedibox/how-to/configure-failover-ip.mdx, bare-metal/dedibox/how-to/configure-ipv6-dedibox.mdx, bare-metal/dedibox/how-to/configure-reverse-failover-ip.mdx, bare-metal/dedibox/how-to/install-dedibox.mdx, bare-metal/dedibox/how-to/link-dedibox-account.mdx, bare-metal/dedibox/how-to/modify-server-options.mdx, bare-metal/dedibox/how-to/order-dedibox.mdx, bare-metal/dedibox/how-to/order-failover-ip.mdx, bare-metal/dedibox/how-to/reinstall-dedibox.mdx, bare-metal/dedibox/how-to/terminate-dedibox.mdx, bare-metal/dedibox/how-to/use-rescue-mode.mdx, compute/gpu/troubleshooting/updating-gpu-instance-with-cloud-init.mdx, compute/instances/api-cli/managing-instance-snapshot-via-cli.mdx, containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx, dedibox-network/ip-failover/how-to/configure-freebsd.mdx
=> chore(review): docs content review

serverless/containers/how-to/add-trigger-to-a-container.mdx
=> fix(srv): typos in serverless containers doc

compute/instances/api-cli/creating-backups.mdx
=> feat(ins): add instructions for backup via cli

serverless/messaging/api-cli/connect-aws-cli.mdx, serverless/messaging/api-cli/nats-cli.mdx, serverless/messaging/api-cli/python-node-sns.mdx, serverless/messaging/api-cli/python-node-sqs.mdx, serverless/messaging/how-to/monitor-mnq-cockpit.mdx, serverless/messaging/reference-content/limitations.mdx, serverless/messaging/reference-content/nats-overview.mdx, serverless/messaging/reference-content/sns-overview.mdx, serverless/messaging/reference-content/sqs-overview.mdx
=> fix(mnq): review doc

compute/instances/api-cli/migrating-instances.mdx
=> feat(ins): add instructions for cli

network/vpc/how-to/manage-routing.mdx
I thought I had taken these out, but something chelou must have happened in a rebase
=> fix(vpc): fix see more

serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx
We released the support for 1000 client connections this morning on Serverless SQL Database, so I update the value.
=> docs(fix): update-technical-value

compute/instances/concepts.mdx, compute/instances/how-to/use-security-groups.mdx
=> [INS] update security group docs

network/public-gateways/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx
=> fix(pgw): fix typo in title

changelog/april2024/2024-04-15-transactional-email-security-dmarc-policy.mdx
=> feat(changelog): transactional-email-security-dmarc-policy 2024-04-15

containers/kubernetes/reference-content/understanding-differences-kapsule-kosmos.mdx, faq/kubernetes.mdx
* Node pools upgrade difference
=> docs(kapsule): added few details about kapsule/kosmos differences

tutorials/sns-instances-notification-system/index.mdx
add(requirement): scaleway CLI requirement needed for terraform organization_id
Change of terraform blocks regarding the instances docker images and requirement of the CLI
=> add(requirement): scaleway CLI requirement needed for terraform

serverless/containers/how-to/add-a-custom-domain-to-a-container.mdx, serverless/functions/how-to/add-a-custom-domain-name-to-a-function.mdx
=> fix(SRV): Removed Cloudfare notice

tutorials/deploying-qdrant-vectordb-kubernetes/index.mdx
=> [TUTORIAL] Qdrant Hybrid Cloud

labs/ipfs-naming/how-to/delete-key.mdx, labs/ipfs-naming/quickstart.mdx, managed-databases/postgresql-and-mysql/api-cli/verify-ca-postgresql.mdx
=> fix(rdb): review + labs review MTA-4440

containers/kubernetes/concepts.mdx
=> docs(kapsule): add link page kapsule kosmos differences

tutorials/deploying-qdrant-vectordb-kubernetes/index.mdx
=> (fix): fixed link to qdrant tutorial

console/account/how-to/use-the-search-bar.mdx
=> fix(cxp): update search bar resources list

containers/kubernetes/reference-content/understanding-differences-kapsule-kosmos.mdx
Kosmos was mentioned in the Kapsule part
=> fix(k8s): reviewed Kapsule desc

observability/cockpit/reference-content/cockpit-limitations.mdx
Added serverless jobs to cockpit integrations
=> feat(cockpit): add Serverless Jobs in integrations

compute/instances/troubleshooting/fix-long-delays-booting-without-public-ip.mdx
=> ins(fix): update wrong filename

ai-data/llm-inference/quickstart.mdx
Current list isn't scalable, replacing by a link showing all model cards
=> chore(llm): Update quickstart

compute/instances/reference-content/production-optimized.mdx
=> feat(ins): add note about pop2 and ent1 instances

identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx, serverless/messaging/reference-content/limitations.mdx
Move the usage limitations info from M&Q section to dedicated quotas section in Organization & Projects.
=> fix(mnq): move limits to quotas

menu/navigation.json
=> feat(llm): add overview link to menu

changelog/april2024/2024-04-19-transactional-email-added-xml-attachments-are-now-avail.mdx
=> feat(changelog): transactional-email-added-xml-attachments-are-now-avail 2024-04-19

.github/CODEOWNERS
=> feat(gen): update codeowners

console/billing/additional-content/reading-an-invoice.mdx
=> billing(feat): review billing docs

tutorials/configure-chef-ubuntu-xenial/index.mdx, tutorials/configure-graphite/index.mdx, tutorials/configure-ipv6-virtual-machine-esxi/index.mdx, tutorials/sinatra/index.mdx, tutorials/systemd-essentials/index.mdx, tutorials/terraform-quickstart/index.mdx, tutorials/traefik-v2-cert-manager/index.mdx, tutorials/trigger-ifttt-actions/index.mdx, tutorials/wordpress-lemp-stack-focal/index.mdx
=> [TUTORIAL] Doc content review

ai-data/llm-inference/how-to/create-deployment.mdx
=> [LLM-INFERENCE]: Add link to Llama-2-7b-chat model and fix other links

menu/navigation.json, storage/object/concepts.mdx, storage/object/how-to/use-bucket-versioning.mdx
Updating this URL as the content will be updated soon and the URL is needed for the console
=> fix(S3): update versioning doc URL

menu/navigation.json, serverless/containers/how-to/monitor-container.mdx, serverless/functions/how-to/monitor-function.mdx, serverless/jobs/how-to/monitor-job.mdx
=> docs(SRV): add monitoring doc to faas & caas MTA-4473

developer-tools/scaleway-cli/reference-content/environment-variables.mdx, developer-tools/scaleway-cli/reference-content/scaleway-configuration-file.mdx, developer-tools/scaleway-sdk/reference-content/environment-variables.mdx, developer-tools/scaleway-sdk/reference-content/scaleway-configuration-file.mdx, developer-tools/terraform/reference-content/environment-variables.mdx, developer-tools/terraform/reference-content/scaleway-configuration-file.mdx, macros/developer-tools/scaleway-configuration-file.mdx, macros/developer-tools/scaleway-environment-variables.mdx, menu/navigation.json
=> docs(DVT): Add config.yaml doc and update CLi doc MTA-4434

changelog/april2024/2024-04-23-gpu-instances-added-new-gpu-l40s-instances.mdx
=> feat(changelog): gpu-instances-added-new-gpu-l40s-instances 2024-04-23

serverless/containers/reference-content/configure-trigger-inputs.mdx
=> chore(SRV): content review MTA-4523

tutorials/traefik-v2-cert-manager/index.mdx
=> [TUTORIAL] Update tutorial traefik

serverless/sql-databases/reference-content/known-differences.mdx
I add these know limitations after customers raised the issue and we reproduced them.
=> feat(serverless-sql-db): Add known client incompatibilities

changelog/april2024/2024-04-25-messaging-and-queuing-changed-increased-messaging-resou.mdx
=> feat(changelog): messaging-and-queuing-changed-increased-messaging-resou 2024-04-25

tutorials/nvidia-triton/index.mdx
=> fix(docs): updated command to run triton server

identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx, serverless/messaging/reference-content/sqs-support.mdx
- ReceiveMessageWaitTimeSeconds is now supported
- updated limits following changes on the platform
=> docs(mnq): documentation update linked to changes int-fix-mnq

faq/blockstorage.mdx
=> docs(faq): update block storage faq

containers/kubernetes/reference-content/kubernetes-load-balancer.mdx, containers/kubernetes/reference-content/lb-ingress-controller.mdx, containers/kubernetes/reference-content/managing-load-balancer-ips.mdx, containers/kubernetes/reference-content/multi-az-clusters.mdx, containers/kubernetes/reference-content/using-load-balancer-annotations.mdx, containers/kubernetes/reference-content/wildcard-dns.mdx
=> [REVIEW] Kubernetes product documentation review 29/04/2024

changelog/april2024/2024-04-29-elastic-metal-added-ubuntu-2404-lts-noble-numbat-now-av.mdx
=> feat(changelog): elastic-metal-added-ubuntu-2404-lts-noble-numbat-now-av 2024-04-29

tutorials/configure-plex-s3/index.mdx, tutorials/deploy-k3s-cluster-with-cilium/index.mdx, tutorials/store-s3-transmit/index.mdx, tutorials/visualize-timeseries-data-timescaledb-grafana/index.mdx, tutorials/vuls-security-scanner/index.mdx, tutorials/wordpress-lemp-stack/index.mdx, tutorials/zabbix-monitoring/index.mdx, tutorials/zulip/index.mdx
=> [REVIEW] Tutorials content review 29/04/2024

changelog/april2024/2024-04-29-object-storage-added-versioning-activation-at-bucket-cr.mdx
=> feat(changelog): object-storage-added-versioning-activation-at-bucket-cr 2024-04-29

console/account/how-to/report-abuse.mdx, menu/navigation.json
=> fix(AXP): replace incident by abuse MTA-4545

console/account/how-to/change-console-appearance.mdx, developer-tools/terraform/quickstart.mdx, serverless/containers/how-to/create-auth-token-from-console.mdx
=> chore(gen): docs content review MTA-4541

storage/object/how-to/use-bucket-versioning.mdx
=> docs(s3): update versioning doc MTA-4547

changelog/april2024/2024-04-30-console-added-console-search.mdx
=> feat(changelog): console-added-console-search 2024-04-30

labs/ipfs-pinning/api-cli/getting-started-with-ipfs-cli.mdx, labs/ipfs-pinning/api-cli/volumes-operations.mdx
=> fix(ipfs): fix broken docs

menu/navigation.json
=> feat(aps): fix link

changelog/may2024/2024-05-03-postgresql-and-mysql-added-self-apply-scheduled-mainten.mdx
=> feat(changelog): postgresql-and-mysql-added-self-apply-scheduled-mainten 2024-05-03

bare-metal/dedibox/how-to/link-dedibox-account.mdx
=> fix(ddx): remove outdated screenshots

ai-data/llm-inference/reference-content/openai-compatibility.mdx
Quick change after proofreading online
=> chore(llm): better structure and default values

containers/kubernetes/api-cli/changing-control-plane-offer.mdx, tutorials/configure-dvc-with-object-storage/index.mdx
A couple of files had erroneous validation dates, this PR fixes them.
=> fix(tutorials): fix validation dates

compute/gpu/reference-content/kubernetes-gpu-time-slicing.mdx, containers/kubernetes/api-cli/cluster-monitoring.mdx, containers/kubernetes/api-cli/managing-tags.mdx, containers/kubernetes/how-to/connect-cluster-kubectl.mdx, dedibox-network/rpn/how-to/find-rpn-gateway.mdx
=> chore(docs): review docs

dedibox-console/classic-hosting/how-to/change-password-mysql-database.mdx, developer-tools/terraform/quickstart.mdx
=> fix(web): docs content review

managed-databases/postgresql-and-mysql/troubleshooting/disk-full.mdx
Explain how to purge Database Engine logs from a RDB instance
Add information about Database Engine logs in RDB disk full troubleshooting page and how to deal with it using Scaleway CLI.
=> fix(rdb): update documentation about RDB disk full troubleshooting

console/account/how-to/verify-identity.mdx
Added: users must have added a payment method before validating their ID.
=> fix(acc): updated doc on id verification

network/load-balancer/how-to/add-certificate.mdx
Reviewed the doc that had reached its validation date
=> fix(lb): review doc

faq/public-gateways.mdx, faq/vpc.mdx, network/vpc/concepts.mdx, network/vpc/how-to/attach-resources-to-pn.mdx, network/vpc/troubleshooting/private-dns-dhcp-not-working.mdx, network/vpc/troubleshooting/resource-attached-no-ip.mdx
Update doc in light of recent questions on the Slack Community
=> fix(vpc): update with community qs

managed-databases/postgresql-and-mysql/how-to/upgrade-version.mdx
Add details about advanced settings when migrating from one major version to another on RDB
Add more details on advanced settings when migrating from one major version to another on RDB
=> fix(rdb): update RDB major version upgrade page

console/account/reference-content/scaleway-network-information.mdx, console/account/troubleshooting/cannot-log-into-my-account.mdx, developer-tools/terraform/quickstart.mdx, serverless/containers/reference-content/use-cases.mdx, serverless/functions/reference-content/use-cases.mdx, storage/object/api-cli/combining-iam-and-object-storage.mdx, storage/object/api-cli/create-bucket-policy.mdx
=> chore(docs): content review MTA-4574

storage/object/how-to/create-a-bucket.mdx
=> docs(s3): add mention of free trial and versioning in bucket creation page MTA-4596

serverless/jobs/reference-content/jobs-limitations.mdx
=> feat(jobs): update timeout limit

dedibox/vps/concepts.mdx, dedibox/vps/how-to/connect-vps.mdx, dedibox/vps/how-to/create-vps.mdx, dedibox/vps/how-to/delete-vps.mdx, dedibox/vps/how-to/index.mdx, dedibox/vps/how-to/manage-vps.mdx, dedibox/vps/how-to/reinstall-vps.mdx, dedibox/vps/index.mdx, dedibox/vps/quickstart.mdx, faq/dedibox.mdx, menu/navigation.json
=> feat(doc): doc updates

console/account/troubleshooting/cannot-log-into-my-account.mdx
=> fix(account): fix message tag

changelog/may2024/2024-05-15-dedibox-added-dedibox-vps-are-now-in-general-availabili.mdx
=> feat(changelog): dedibox-added-dedibox-vps-are-now-in-general-availabili 2024-05-15

changelog/may2024/2024-05-15-dedibox-added-dedibox-vps-are-now-in-general-availabili.mdx
=> fix(changelog): fix wording

storage/object/api-cli/bucket-website-api.mdx, storage/object/api-cli/migrating-buckets.mdx, storage/object/api-cli/object-lock.mdx, storage/object/api-cli/setting-cors-rules.mdx, storage/object/api-cli/share-buckets-read-only.mdx
=> fix(s3): add missing CLI requirements to CLI pages MTA-4582

changelog/may2024/2024-05-15-dedibox-added-dedibox-vps-are-now-in-general-availabili.mdx
=> fix(DDX): remove emoji that may cause UTF8 issue in console

changelog/may2024/2024-05-15-domains-and-dns-changed-increase-in-the-cost-of-the-fr-.mdx
=> feat(changelog): domains-and-dns-changed-increase-in-the-cost-of-the-fr- 2024-05-15

serverless/jobs/how-to/create-job-from-external-registry.mdx, serverless/jobs/how-to/create-job-from-scaleway-registry.mdx, serverless/jobs/quickstart.mdx
=> chore(docs): content review MTA-4586

network/public-gateways/concepts.mdx, network/vpc/concepts.mdx
=> fix(pgw): improve concepts

bare-metal/elastic-metal/reference-content/elastic-metal-datasheet.mdx, faq/elastic-metal.mdx
=> chore(em): remove titanium range from docs

ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
Users reported an error `invalid model \"mixtral-8x7B-instruct-v0.1\"` as our validation is case sensitive. Removed all uppercase Bs to avoid this trap.
=> fix(ifr): change to lower case b

network/public-gateways/concepts.mdx, network/vpc/concepts.mdx
=> fix(pgw): update info on dns

console/billing/how-to/add-billing-contact.mdx, console/billing/how-to/add-payment-method.mdx, console/billing/how-to/change-billing-information.mdx, console/billing/how-to/change-payment-method.mdx, console/billing/how-to/download-an-invoice.mdx, console/billing/how-to/redeem-voucher-code.mdx, console/billing/how-to/use-billing-alerts.mdx, console/billing/how-to/use-the-cost-manager.mdx, faq/billing.mdx
- Some recurrent support queries added to the FAQs;
- Updated the **How to add a payment method** page so both the credit card and SEPA sections can work individually, for better Algolia indexation and search placement.
=> docs(bil): faq and how to update

serverless/jobs/how-to/create-job-from-external-registry.mdx, serverless/jobs/how-to/create-job-from-scaleway-registry.mdx, serverless/jobs/quickstart.mdx
Fix some validation dates in wrong format
=> fix(docs): fix validation dates

compute/instances/reference-content/workload-optimized.mdx, dedibox-network/ipv6/how-to/configure-ipv6-windows.mdx, dedibox-network/ipv6/how-to/enable-ipv6-slaac.mdx, dedibox-network/ipv6/how-to/request-prefix.mdx, tutorials/cloud-controller-manager/index.mdx, tutorials/dhclient-dedibox/index.mdx, tutorials/first-steps-linux-command-line/index.mdx, tutorials/install-medusa/index.mdx, tutorials/install-rkhunter/index.mdx
=> chore(gen): docs content review 20/05/24

containers/kubernetes/concepts.mdx
Bringing clarity to zonal, multi AZ and regional availability types for k8s clusters, based on industry practices.
=> docs(k8s): introducing availability types

index.mdx
=> fix(docs): fix wrong link on landing page

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx
Migration is completed, 100% of Kapsule clusters are attached to a PN. Simplifying the documentation for better readability.
=> chore(k8s): cleaning PN migration instructions

console/account/troubleshooting/cannot-erase-account.mdx, console/account/troubleshooting/protecting-yourself-fraud-phishing.mdx, menu/navigation.json
=> feat(console): added phising and fraud guidelines

menu/navigation.json
=> fixed navigation

faq/databases-for-postgresql-and-mysql.mdx
update the RDB FAQ with new product features
Update RDB FAQ with product update
=> fix(rdb): Update FAQ for managed RDB

faq/dedibox.mdx
=> feat(ddx): add vps throttled bandwidth

developer-tools/scaleway-sdk/go-sdk.mdx, developer-tools/scaleway-sdk/js-sdk.mdx, developer-tools/scaleway-sdk/python-sdk.mdx, serverless/jobs/how-to/run-job.mdx, serverless/jobs/how-to/stop-job.mdx
=> chore(docs): docs review MTA-4618

dedibox-network/ipv6/how-to/request-prefix.mdx
=> fix(ddx): removed warsaw from ipv6 info

compute/instances/api-cli/creating-backups.mdx, compute/instances/api-cli/migrating-instances.mdx, dedibox-console/cpanel-hosting/index.mdx, dedibox-network/network/index.mdx, identity-and-access-management/secret-manager/index.mdx, labs/ipfs-naming/index.mdx, storage/object/index.mdx
=> fix(all): fixed broken links

changelog/may2024/2024-05-24-cockpit-added-orderable-data-source-for-cockpit.mdx
=> feat(changelog): cockpit-added-orderable-data-source-for-cockpit 2024-05-24

changelog/may2024/2024-05-24-cockpit-added-cockpit-available-in-all-region.mdx
=> feat(changelog): cockpit-added-cockpit-available-in-all-region 2024-05-24

managed-services/webhosting/how-to/manage-webhosting.mdx, tutorials/deploy-chatwoot-self-care/index.mdx, tutorials/install-kvm-elastic-metal/index.mdx, tutorials/install-openlitespeed-wordpress/index.mdx, tutorials/install-openvpn/index.mdx, tutorials/install-pgbouncer/index.mdx, tutorials/install-php-composer/index.mdx, tutorials/install-postgresql/index.mdx, tutorials/install-wireguard/index.mdx
=> chore(all): docs content review

storage/block/api-cli/managing-a-volume.mdx, storage/block/api-cli/unmounting-a-volume.mdx, storage/block/how-to/attach-a-volume.mdx, storage/block/how-to/create-a-snapshot.mdx, storage/block/how-to/create-a-volume.mdx, storage/block/how-to/create-volume-from-snapshot.mdx, storage/block/how-to/delete-a-snapshot.mdx, storage/block/how-to/delete-a-volume.mdx, storage/block/how-to/detach-a-volume.mdx, storage/block/how-to/increase-block-volume.mdx, storage/block/how-to/unmount-a-volume.mdx, storage/block/quickstart.mdx
- Improved descriptions with SEO content
- Changed validation dates 
- General review of wording, content, typos, etc.
=> docs(block-storage): content review

dedibox-network/ip-failover/how-to/configure-debian-ubuntu.mdx
Fixed outdated netplan configuration example
=> fix(ddx): fix netplan configuration

bare-metal/elastic-metal/api-cli/elastic-metal-with-api.mdx, compute/instances/index.mdx, dedibox-console/classic-hosting/how-to/configure-backup-option.mdx, dedibox-console/classic-hosting/quickstart.mdx, dedibox-console/cpanel-hosting/reference-content.mdx, dedibox-network/rpn/reference-content/private-networks-overview.mdx, network/domains-and-dns/quickstart.mdx, storage/object/api-cli/lifecycle-rules-api.mdx, storage/object/api-cli/setting-cors-rules.mdx, tutorials/ansible-bionic-beaver/index.mdx, tutorials/run-messaging-platform-with-rocketchat/index.mdx, tutorials/store-wp-mediacloud-s3/index.mdx, tutorials/zulip/index.mdx
=> fix(gen): fixed 301s

faq/dedibox.mdx
=> feat(faq): add question ddx vps

ai-data/managed-inference/reference-content/openai-compatibility.mdx
- Expanding support to more libraries as validated by beta testers
- Sharing support to /v1/models API
- Asking for further feedback
=> chore(ifr): support /v1/models API

containers/kubernetes/reference-content/move-kubernetes-nodes-routed-ip.mdx, menu/navigation.json
=> feat(k8s): routed ips

containers/kubernetes/reference-content/move-kubernetes-nodes-routed-ip.mdx
Aligning dates with client communications upcoming
=> chore(k8s): updating dates

storage/object/api-cli/enable-sse-c.mdx
=> fix(s3): missing title

storage/object/api-cli/enable-sse-c.mdx
=> fix(s3): add warning on closed beta

compute/gpu/concepts.mdx
=> fix(gpu): fix typo

changelog/june2024/2024-06-03-kubernetes-deprecated-kubernetes-worker-nodes-with-nat-.mdx
=> feat(changelog): kubernetes-deprecated-kubernetes-worker-nodes-with-nat- 2024-06-03

bare-metal/elastic-metal/how-to/create-server.mdx, bare-metal/elastic-metal/quickstart.mdx, console/account/reference-content/products-availability.mdx, faq/elastic-metal.mdx
=> feat(ems): add new az and region

storage/object/api-cli/bucket-policy.mdx
=> docs(s3): update Bucket policy reference MTA-4667

changelog/june2024/2024-06-03-jobs-added-serverless-jobs-allows-smtp-traffic.mdx
=> feat(changelog): jobs-added-serverless-jobs-allows-smtp-traffic 2024-06-03

changelog/june2024/2024-06-03-containers-added-serverless-containers-allows-smtp-traf.mdx
=> feat(changelog): containers-added-serverless-containers-allows-smtp-traf 2024-06-03

changelog/june2024/2024-06-03-functions-added-serverless-functions-allows-smtp-traffi.mdx
=> feat(changelog): functions-added-serverless-functions-allows-smtp-traffi 2024-06-03

compute/instances/how-to/manage-volumes.mdx, containers/kubernetes/reference-content/move-kubernetes-nodes-routed-ip.mdx, dedibox-network/ipv6/how-to/debug-ipv6.mdx, managed-services/webhosting/reference-content/plesk-reference-content.mdx, managed-services/webhosting/reference-content/understanding-differences-cpanel-plesk.mdx
=> fix(gen): product content review

tutorials/gitlab-instant-app/index.mdx
=> fix(tuto): updated gitlab instantapp tutorial

storage/object/how-to/upload-files-into-a-bucket.mdx
=> fix(s3): removed screenshots

dedibox/vps/index.mdx
Swap illustration for Dedibox VPS to the good one. 
To be merged after the next release of docs.
=> fix(ddx): swap dedibox vps illustaration

containers/container-registry/how-to/connect-docker-cli.mdx, containers/container-registry/how-to/create-namespace.mdx, containers/container-registry/how-to/delete-image.mdx, containers/container-registry/how-to/delete-namespace.mdx, containers/container-registry/how-to/display-image-versions.mdx, containers/container-registry/how-to/manage-image-privacy-settings.mdx, containers/container-registry/how-to/manage-namespace-privacy-policies.mdx, faq/iam.mdx, labs/ipfs-pinning/api-cli/ipfs-cli.mdx, labs/ipfs-pinning/api-cli/ipfs-get-content.mdx, labs/ipfs-pinning/api-cli/pin-operations.mdx, labs/ipfs-pinning/quickstart.mdx
=> fix(cr): reviews

partners/partner-space/how-to/lock-client-organization.mdx
=> fix(partners): fix typo

partners/partner-space/index.mdx
=> fix(acc): partner space links

changelog/june2024/2024-06-04-console-added-login-sso-google-and-microsoft.mdx
=> feat(changelog): console-added-login-sso-google-and-microsoft 2024-06-04

storage/object/api-cli/enable-sse-c.mdx
=> fix(s3): update SSE-C commands

network/public-gateways/how-to/create-a-public-gateway.mdx, network/public-gateways/how-to/delete-a-public-gateway.mdx, network/public-gateways/how-to/use-flexible-ips.mdx, network/public-gateways/how-to/use-ssh-bastion.mdx, network/public-gateways/quickstart.mdx, network/public-gateways/troubleshooting/gw-limitations.mdx
Review Public Gateways documentation
=> fix(pgw): review docs

blocks/mainLinks.json
=> fix(home): fix learning link

ai-data/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx, menu/navigation.json
=> docs(ifr): add data processing information

changelog/june2024/2024-06-10-domains-and-dns-changed-update-pricing-for-art-at-de-it.mdx
=> feat(changelog): domains-and-dns-changed-update-pricing-for-art-at-de-it 2024-06-10

changelog/june2024/2024-06-10-domains-and-dns-changed-update-pricing-for-art-at-de-it.mdx
=> fix(changelog): fix typo domain prcing

serverless/jobs/reference-content/jobs-limitations.mdx
Add blocked ports for Serverless Jobs
=> feat(jobs): add config restrictions

serverless/messaging/reference-content/nats-overview.mdx
=> fix(mnq): add TLS mention

network/load-balancer/how-to/create-manage-flex-ips.mdx
=> fix(lb): review flex IP doc

tutorials/docker-instantapp/index.mdx, tutorials/gitlab-instant-app/index.mdx, tutorials/jitsi-ubuntu-focal-fossa/index.mdx, tutorials/nextcloud-instantapp/index.mdx, tutorials/openvpn-instant-app/index.mdx, tutorials/wordpress-instantapp/index.mdx
=> chore(tuto): review content jitsi

bare-metal/dedibox/how-to/link-dedibox-account.mdx
=> chore(ddx): add link to link ddx + minor improvements

network/load-balancer/api-cli/configuring-balancing-rules.mdx
Fix bad validation meta, stopping review bot from working properly
=> fix(lb): fix validation date

ai-data/managed-inference/quickstart.mdx
Autoscaler being far in the roadmap, I put an emphasis on what we've been really nailing lately: our compatibility with OpenAI APIs.
Also providing links to new resources.
=> fix(ifr): introducing interoperability

console/account/reference-content/products-availability.mdx
=> fix(cns): fix typo

serverless/containers/reference-content/containers-limitations.mdx
=> feat(containers): update max scale doc

compute/instances/troubleshooting/fix-unreachable-noble-after-reboot.mdx
- [ x] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).
Add a troubleshooting document to explain how to fix unreachable Ubuntu Noble instances.
Added a new document
=> docs(instances): Fix Ubuntu Noble not reachable after reboot (int-add-instances)

compute/instances/how-to/connect-to-instance.mdx, compute/instances/how-to/create-an-instance.mdx, compute/instances/quickstart.mdx, identity-and-access-management/organizations-and-projects/how-to/create-ssh-key.mdx
=> docs(instances): add info for rsa keys for windows instances

serverless/functions/reference-content/functions-runtimes-configuration.mdx
=> docs(srv): add PHP runtime info to doc MTA-4686

compute/instances/how-to/create-an-instance.mdx
=> fix(ins): fix wording
