scaleway/docs-content

- serverless/sql-databases/how-to/index.mdx
> fix(sdb): updated SDB how-tos index title

- bare-metal/apple-silicon/how-to/connect-to-mac-mini.mdx
- bare-metal/apple-silicon/how-to/create-mac-mini.mdx
- bare-metal/apple-silicon/how-to/delete-mac-mini.mdx
- bare-metal/apple-silicon/how-to/reboot-mac-mini.mdx
- bare-metal/apple-silicon/how-to/reinstall-mac-mini.mdx
- bare-metal/apple-silicon/troubleshooting/cant-connect-using-ssh.mdx
- bare-metal/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
- bare-metal/apple-silicon/troubleshooting/filevault-preventing-system-boot.mdx
- bare-metal/apple-silicon/troubleshooting/need-package-manager.mdx
- bare-metal/apple-silicon/troubleshooting/need-to-update-os.mdx
- menu/navigation.json
> feat(aps): add ssh troubleshooting

- tutorials/pihole-vpn/index.mdx
- tutorials/plausible-analytics-ubuntu/index.mdx
- tutorials/postgis-managed-databases/index.mdx
- tutorials/postman-api/index.mdx
- tutorials/powerdns-ubuntu-bionic/index.mdx
- tutorials/prestashop-dedibox/index.mdx
- tutorials/prometheus-monitoring-grafana-dashboard/index.mdx
- tutorials/protect-server-fail2ban/index.mdx
- tutorials/protect-server-using-crowdsec/index.mdx
- tutorials/proxmox-softraid/index.mdx
- tutorials/proxy-protocol-v2-load-balancer/index.mdx
- tutorials/pushing-metrics-logs-from-scw-instance/index.mdx
- tutorials/python-for-loops/index.mdx
- tutorials/python-lists-dicts/index.mdx
- tutorials/remote-desktop-with-xrdp/index.mdx
- tutorials/restic-s3-backup/index.mdx
- tutorials/rtmp-self-hosted-streaming/index.mdx
- tutorials/ruby-on-rails/index.mdx
- tutorials/run-manage-linux-vm-on-apple-silicon-tart/index.mdx
- tutorials/run-messaging-platform-with-rocketchat/index.mdx
- tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
- tutorials/run-python-flask-server-on-serverless-container/index.mdx
Cleaning up tags from tutorial pages (pages from P-R, in this batch).
Up to 5 tags
Content-specific tags.
Fixed eventual typos in these pages.
> fix(gen): tutorials tags cleanup p to r

- faq/elastic-metal.mdx
> chore(faq): reorder faq elastic metal

- faq/account.mdx
- faq/apple-silicon.mdx
- faq/billing.mdx
- faq/blockstorage.mdx
- faq/cockpit.mdx
- faq/containerregistry.mdx
- faq/databases-for-postgresql-and-mysql.mdx
- faq/databases-for-redis.mdx
- faq/dedibox-in-scaleway-console.mdx
- faq/dedibox.mdx
- faq/domains-and-dns.mdx
- faq/iam.mdx
- faq/instances.mdx
- faq/iothub.mdx
- faq/kubernetes.mdx
- faq/loadbalancer.mdx
- faq/messaging-and-queuing.mdx
- faq/objectstorage.mdx
- faq/private-networks.mdx
- faq/public-gateways.mdx
- faq/secret-manager.mdx
- faq/serverless-containers.mdx
- faq/serverless-functions.mdx
- faq/serverless-jobs.mdx
- faq/serverless-sql-databases.mdx
- faq/support.mdx
- faq/transactional-email.mdx
- faq/vpc.mdx
> feat(faq): updated titles

- faq/dedibox-in-scaleway-console.mdx
> feat(ddx): review faq ddx in scw

- changelog/june2024/2024-06-17-containers-fixed-serverless-contaienrs-cpu-usage-fix.mdx
> feat(changelog): containers-fixed-serverless-containers-cpu-usage-fix 2024-06-17

- changelog/june2024/2024-06-17-functions-fixed-serverless-functions-cpu-usage-fix.mdx
> feat(changelog): functions-fixed-serverless-functions-cpu-usage-fix 2024-06-17

- storage/object/api-cli/enable-sse-c.mdx
> fix(s3): update sse-c command

- compute/gpu/troubleshooting/fix-driver-issues.mdx
- containers/kubernetes/api-cli/managing-storage.mdx
- containers/kubernetes/how-to/create-cluster.mdx
- containers/kubernetes/how-to/create-kosmos-cluster.mdx
- containers/kubernetes/how-to/edit-cluster.mdx
- containers/kubernetes/how-to/edit-kosmos-cluster.mdx
- containers/kubernetes/how-to/enable-easy-deploy.mdx
- containers/kubernetes/how-to/upgrade-kubernetes-version.mdx
- containers/kubernetes/reference-content/introduction-to-kubernetes.mdx
- dedibox-console/classic-hosting/how-to/solve-email-account-connection-problems.mdx
- dedibox-console/cpanel-hosting/quickstart.mdx
- dedibox-network/domains/how-to/change-ownership.mdx
- dedibox/kvm-over-ip/how-to/quanta-computer.mdx
> docs(ins): review content

- tutorials/index.mdx
> Update tutorials page description for SEO

- partners/partner-space/how-to/edit-client-information.mdx
- partners/partner-space/how-to/lock-client-organization.mdx
- partners/partner-space/how-to/unlock-client-organization.mdx
Removed unwanted spaces in the requirements section + added information
> fix(acc): fixed spaces and added info

- serverless/jobs/how-to/delete-job.mdx
- serverless/jobs/how-to/monitor-job.mdx
- serverless/sql-databases/troubleshooting/connection-timeout.mdx
- storage/object/api-cli/bucket-policy.mdx
- storage/object/api-cli/lifecycle-rules-api.mdx
- storage/object/api-cli/managing-lifecycle-cliv2.mdx
- storage/object/api-cli/multipart-uploads.mdx
- storage/object/api-cli/object-storage-aws-cli.mdx
- storage/object/api-cli/setting-cors-rules.mdx
- storage/object/how-to/create-a-bucket.mdx
- storage/object/how-to/delete-a-bucket.mdx
- storage/object/how-to/download-files-from-a-bucket.mdx
- storage/object/how-to/edit-storage-class.mdx
- storage/object/how-to/manage-lifecycle-rules.mdx
- storage/object/how-to/manage-object-visibility.mdx
- storage/object/how-to/monitor-consumption.mdx
- storage/object/how-to/restore-an-object-from-glacier.mdx
- storage/object/how-to/upload-files-into-a-bucket.mdx
- storage/object/how-to/use-bucket-versioning.mdx
- storage/object/how-to/use-obj-stor-with-private-networks.mdx
- storage/object/quickstart.mdx
- storage/object/reference-content/optimize-object-storage-performance.mdx
- tutorials/s3cmd/index.mdx
> chore(docs): doc review MTA-4643

- network/vpc/concepts.mdx
- network/vpc/how-to/attach-resources-to-pn.mdx
Improve DNS resolution info for resources on PNs, after user feedback
> fix(vpc): improve DNS info

- changelog/june2024/2024-06-18-load-balancers-changed-static-private-network-attachmen.mdx
> feat(changelog): load-balancers-changed-static-private-network-attachmen 2024-06-18

- observability/cockpit/api-cli/querying-logs-with-logcli.mdx
- observability/cockpit/concepts.mdx
- observability/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
- observability/cockpit/how-to/activate-managed-alerts.mdx
- observability/cockpit/how-to/activate-push-traces.mdx
- observability/cockpit/how-to/add-contact-points.mdx
- observability/cockpit/how-to/configure-alerts-for-scw-resources.mdx
- observability/cockpit/how-to/create-external-data-sources.mdx
- observability/cockpit/how-to/create-token.mdx
- observability/cockpit/how-to/delete-external-data-sources.mdx
- observability/cockpit/how-to/enable-alert-manager.mdx
- observability/cockpit/how-to/retrieve-grafana-credentials.mdx
- observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx
- observability/cockpit/quickstart.mdx
- observability/cockpit/reference-content/cockpit-limitations.mdx
- observability/cockpit/reference-content/understanding-cockpit-usage.mdx
- observability/cockpit/troubleshooting/pusher-does-not-support-custom-http-headers.mdx
- observability/cockpit/troubleshooting/resetting-grafana-password-via-the-api.mdx
- Added SEO to descriptions 
- Clarified information on token secret key in the Send metrics and logs to Cockpit documentation page
> docs(cockpit): added seo to descriptions

- network/load-balancer/api-cli/configuring-balancing-rules.mdx
- network/load-balancer/api-cli/setting-up-ssl-offloading.mdx
- network/load-balancer/how-to/create-frontends-backends.mdx
- network/load-balancer/reference-content/configuring-frontends.mdx
- network/load-balancer/reference-content/configuring-health-checks.mdx
- network/load-balancer/troubleshooting/load-balancer-limitations.mdx
Reviewed and updated Load Balancer docs.
> fix(lb): review docs

- faq/domains-and-dns.mdx
- network/domains-and-dns/concepts.mdx
- network/domains-and-dns/how-to/add-external-domain.mdx
- network/domains-and-dns/how-to/configure-autorenew.mdx
- network/domains-and-dns/how-to/configure-dns-zones.mdx
- network/domains-and-dns/how-to/configure-dnssec-internal-domain.mdx
- network/domains-and-dns/how-to/delete-external-domain.mdx
- network/domains-and-dns/how-to/manage-dns-records.mdx
- network/domains-and-dns/how-to/manage-external-domain.mdx
- network/domains-and-dns/how-to/manage-nameservers-internal-domain.mdx
- network/domains-and-dns/how-to/register-internal-domain.mdx
- network/domains-and-dns/how-to/renew-domain.mdx
- network/domains-and-dns/how-to/test-dns-zones-with-dig.mdx
- network/domains-and-dns/how-to/trade-domain.mdx
- network/domains-and-dns/how-to/transfer-external-domain.mdx
- network/domains-and-dns/how-to/unlock-internal-domain.mdx
- network/domains-and-dns/quickstart.mdx
- network/domains-and-dns/reference-content/understanding-dns-records.mdx
- network/domains-and-dns/reference-content/understanding-domains-and-dns.mdx
- Changed descriptions to improve SEO
> docs(domains): added seo descriptions

- faq/secret-manager.mdx
- identity-and-access-management/secret-manager/api-cli/create-secret-path-migrate.mdx
- identity-and-access-management/secret-manager/api-cli/create-secret-with-type.mdx
- identity-and-access-management/secret-manager/api-cli/external-secrets.mdx
- identity-and-access-management/secret-manager/concepts.mdx
- identity-and-access-management/secret-manager/how-to/create-secret.mdx
- identity-and-access-management/secret-manager/how-to/create-version.mdx
- identity-and-access-management/secret-manager/how-to/delete-secret.mdx
- identity-and-access-management/secret-manager/how-to/delete-version.mdx
- identity-and-access-management/secret-manager/how-to/manage-secret.mdx
- identity-and-access-management/secret-manager/how-to/manage-version.mdx
- identity-and-access-management/secret-manager/quickstart.mdx
- identity-and-access-management/secret-manager/reference-content/data-encryption-with-secret-manager.mdx
- identity-and-access-management/secret-manager/reference-content/secret-manager-capabilities-limits.mdx
- Improved descriptions for SEO
> docs(sem): seo descriptions

- faq/blockstorage.mdx
- storage/block/api-cli/managing-a-volume.mdx
- storage/block/api-cli/unmounting-a-volume.mdx
- storage/block/concepts.mdx
- storage/block/how-to/attach-a-volume.mdx
- storage/block/how-to/create-a-snapshot.mdx
- storage/block/how-to/create-a-volume.mdx
- storage/block/how-to/create-volume-from-snapshot.mdx
- storage/block/how-to/delete-a-snapshot.mdx
- storage/block/how-to/delete-a-volume.mdx
- storage/block/how-to/detach-a-volume.mdx
- storage/block/how-to/increase-block-volume.mdx
- storage/block/how-to/unmount-a-volume.mdx
- storage/block/quickstart.mdx
- Updated descriptions to improve SEO
> docs(block-storage): added seo descriptions

- compute/instances/troubleshooting/fix-noble-wrong-ppa-configuration.mdx
- menu/navigation.json
> feat(instances): Fix wrong PPA configuration on Ubuntu Noble (int-add-instances)

- menu/navigation.json
> fix(gen): fix typo navigation

- compute/instances/reference-content/identify-devices.mdx
Add an explanation on how to identify SBS volumes in instances.
> feat(instances): explain how to identify SBS volumes

- containers/kubernetes/api-cli/cluster-monitoring.mdx
- tutorials/manage-k8s-logging-loki/index.mdx
> fix(k8s): add warning about deprecated content

- tutorials/snapshot-instances-jobs/index.mdx
> docs(tutorial): instances snapshots with Serverless Jobs MTA-4622

- faq/objectstorage.mdx
> docs(s3): add command to FAQ MTA-4746

- containers/kubernetes/reference-content/kubernetes-load-balancer.mdx
- network/load-balancer/reference-content/kubernetes-load-balancer.mdx
- network/load-balancer/reference-content/ssl-bridging-offloading-passthrough.mdx
Add new troubleshooting section for Kuberentes Load Balancers, from user contribution.
> fix(k8s): add troubleshooting section

- menu/navigation.json
Removed link to deleted page. Needs to be merged together with #3369.
> fix(mnq): remove page from navigation

- faq/messaging-and-queuing.mdx
> feat(mnq) : update for SNS GA

- serverless/messaging/concepts.mdx
> fix(mnq) update SNS concepts for GA

- contribute.mdx
What was asked to the contributor was relatively low compared to the money offered. I've changed characters to words.
> docs(contribute): update message to make consistent with the offer

- changelog/december2023/2023-12-04-messaging-and-queuing-deprecated-api-v1alpha1-to-be-mig.mdx
- changelog/october2023/2023-10-24-messaging-and-queuing-changed-messaging-and-queuing-is-.mdx
- faq/messaging-and-queuing.mdx
- serverless/messaging/concepts.mdx
Corrections to updates to doc for SNS GA
> fix(mnq): fix GA updates

- changelog/march2024/2024-03-19-kubernetes-changed-container-storage-interface-v03-now-.mdx
Edited legacy class indicated in changelog
> chore(k8s): fix class

- changelog/june2024/2024-06-24-iam-changed-new-console-page-for-quotas.mdx
> feat(changelog): iam-changed-new-console-page-for-quotas 2024-06-24

- compute/instances/how-to/use-flexips.mdx
> fix(ins): update flex ip description

- bare-metal/dedibox/reference-content/dedibox-datasheet.mdx
- bare-metal/elastic-metal/api-cli/elastic-metal-with-api.mdx
- bare-metal/elastic-metal/api-cli/elastic-metal-with-cli.mdx
- bare-metal/elastic-metal/how-to/activate-remote-access.mdx
- bare-metal/elastic-metal/how-to/get-use-loyalty-reward.mdx
- bare-metal/elastic-metal/how-to/shutdown-server.mdx
- bare-metal/elastic-metal/how-to/use-rescue-mode.mdx
- bare-metal/elastic-metal/quickstart.mdx
- bare-metal/elastic-metal/reference-content/elastic-metal-datasheet.mdx
- bare-metal/elastic-metal/troubleshooting/replace-failed-drive-software-raid.mdx
- bare-metal/elastic-metal/troubleshooting/reset-admin-password-windows-server.mdx
- compute/gpu/troubleshooting/fix-driver-issues.mdx
- compute/instances/api-cli/attaching-a-volume.mdx
- compute/instances/api-cli/creating-a-volume.mdx
- compute/instances/api-cli/creating-backups.mdx
- compute/instances/api-cli/detaching-a-volume.mdx
- compute/instances/api-cli/using-cloud-init.mdx
- compute/instances/api-cli/using-routed-ips.mdx
- compute/instances/how-to/create-a-snapshot.mdx
- compute/instances/how-to/send-emails-from-your-instance.mdx
- compute/instances/how-to/use-protected-instance.mdx
- compute/instances/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx
- compute/instances/troubleshooting/fix-cloud-init-debian12.mdx
- compute/instances/troubleshooting/reboot-from-faulty-kernel.mdx
- menu/navigation.json
> chore(ins): review instances documentation

- ai-data/managed-inference/index.mdx
> fix(infr): update link to managed inference api

- changelog/june2024/2024-06-25-vpc-added-vpc-routing-is-now-in-general-availability.mdx
> feat(changelog): vpc-added-vpc-routing-is-now-in-general-availability 2024-06-25

- menu/navigation.json
- storage/object/concepts.mdx
- storage/object/how-to/get-started-edge-services.mdx
Edge Services x Object Storage is going into public beta.
- Add doc to menu
- Remove mentions of private beta
- Add a concept
> chore(es): prepare for public beta

- tutorials/configuring-gitlab-scaleway-elements-database/index.mdx
- tutorials/deploy-static-website-with-hugo-and-github-runners-to-object-storage/index.mdx
- tutorials/install-ispconfig/index.mdx
- tutorials/jitsi-docker/index.mdx
- tutorials/k8s-velero-backup/index.mdx
- tutorials/librenms-monitoring/index.mdx
- tutorials/manage-database-instance-pgadmin4/index.mdx
- tutorials/mist-streaming-server/index.mdx
- tutorials/mlx-array-framework-apple-silicon/index.mdx
- tutorials/object-storage-s3fs/index.mdx
- tutorials/run-messaging-platform-with-rocketchat/index.mdx
- tutorials/run-python-flask-server-on-serverless-container/index.mdx
- tutorials/scaleway-packer-plugin/index.mdx
- tutorials/waypoint-plugin-scaleway/index.mdx
> chore(tuto): content review

- changelog/june2024/2024-06-25-messaging-and-queuing-changed-messaging-and-queuing-sns.mdx
> feat(changelog): messaging-and-queuing-changed-messaging-and-queuing-sns 2024-06-25

- serverless/messaging/concepts.mdx
- serverless/messaging/reference-content/limitations.mdx
- tutorials/create-serverless-scraping/index.mdx
Fix queueing --> queuing spellings
> fix(mnq): fix bad instances of spelling

- tutorials/mist-streaming-server/index.mdx
> fix(tuto): metadata

- network/load-balancer/api-cli/configuring-balancing-rules.mdx
- network/public-gateways/how-to/configure-a-public-gateway.mdx
- network/public-gateways/troubleshooting/gateway-services-not-working.mdx
- network/vpc/how-to/create-vpc.mdx
- network/vpc/how-to/delete-vpc.mdx
> fix(network): review docs

- menu/navigation.json
- split navigation menu in four section
- modify regexp to check for slug in order to match url with dots and recursive path
> feat(menu): reshape navigation menu in four sections

- tutorials/snapshot-instances-jobs/index.mdx
> fix(SRV): fix wrong cron schedule

- console/account/how-to/use-the-search-bar.mdx
> docs(AXP): update search resources MTA-4786

- partners/partner-space/index.mdx
> fix(partners): typo

- serverless/functions/reference-content/code-examples.mdx
- serverless/functions/reference-content/functions-lifecycle.mdx
- Update available runtimes for serverless functions.
- Update Rust handler example
> docs(serverless): update available runtimes

- changelog/july2024/2024-07-01-managed-inference-added-managed-inference-is-available-.mdx
> feat(changelog): managed-inference-added-managed-inference-is-available- 2024-07-01

- storage/object/api-cli/create-bucket-policy.mdx
> fix(s3): correct delete bucket policy command

- serverless/messaging/concepts.mdx
- serverless/messaging/how-to/create-credentials.mdx
- serverless/messaging/how-to/create-manage-queues.mdx
- serverless/messaging/how-to/create-manage-subscriptions.mdx
- serverless/messaging/how-to/create-manage-topics.mdx
- serverless/messaging/how-to/deactivate-delete-messaging.mdx
- serverless/messaging/how-to/get-started.mdx
- serverless/messaging/how-to/manage-credentials.mdx
- serverless/messaging/how-to/monitor-mnq-cockpit.mdx
- serverless/messaging/index.mdx
- serverless/messaging/quickstart.mdx
Add SEO descriptions for main M&Q content.
> fix(mnq): add seo descriptions

- tutorials/encode-videos-using-serverless-jobs/index.mdx
> fix(srv): add missing tags to ffmpeg tutorials

- changelog/june2024/2024-06-28-functions-added-node-22-runtime.mdx
> feat(changelog): functions-added-node-22-runtime 2024-06-28

- serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx
Updating Serverless SQL Database technical overview with changes implemented for General Availability
> fix(serverless db): update serverless-sql-databases-overview

- tutorials/install-openvpn/index.mdx
> fix(tuto): update tutorial openvpn

- macros/console/create-account.mdx
> fix(AXP): update captcha link and name MTA-4780

- changelog/july2024/2024-07-02-object-storage-added-bucket-policies-can-now-be-configu.mdx
> feat(changelog): object-storage-added-bucket-policies-can-now-be-configu 2024-07-02

- compute/gpu/how-to/use-scratch-storage-h100-instances.mdx
> feat(gpu): add L40S to documentation

- compute/instances/how-to/send-emails-from-your-instance.mdx
- compute/instances/reference-content/learning.mdx
- compute/instances/troubleshooting/reboot-from-faulty-kernel.mdx
- console/account/how-to/enforce-mfa.mdx
- console/account/how-to/use-2fa.mdx
- containers/kubernetes/how-to/enable-disable-ssh.mdx
- containers/kubernetes/how-to/use-scratch-storage-h100.mdx
- containers/kubernetes/quickstart.mdx
- containers/kubernetes/reference-content/exposing-services.mdx
- containers/kubernetes/reference-content/managed-kubernetes-service-definition.mdx
- dedibox/hardware/reference-content/server-comparison-table.mdx
- identity-and-access-management/iam/api-cli/managing-projects.mdx
- labs/ipfs-naming/api-cli/ipfs-manage-keys.mdx
- tutorials/load-overflow-proxmox-and-elastic-metal/index.mdx
- tutorials/set-up-spf-dkim-for-dns-providers/index.mdx
> docs(gen): content review

- changelog/july2024/2024-07-03-functions-added-php-83-runtime-now-available.mdx
> feat(changelog): functions-added-php-83-runtime-now-available 2024-07-03

- changelog/july2024/2024-07-03-transactional-email-fixed-email-filtering-bug-fix.mdx
> feat(changelog): transactional-email-fixed-email-filtering-bug-fix 2024-07-03

- changelog/july2024/2024-07-03-functions-added-go-122-runtime-now-available.mdx
> feat(changelog): functions-added-go-122-runtime-now-available 2024-07-03

- changelog/july2024/2024-07-03-functions-added-rust-179-runtime-now-available.mdx
> feat(changelog): functions-added-rust-179-runtime-now-available 2024-07-03

- network/vpc/reference-content/vpc-migration.mdx
> fix(vpc): review doc

- changelog/july2024/2024-07-03-kubernetes-security-mitigated-openssh-vulnerability-cve.mdx
> feat(changelog): kubernetes-security-mitigated-openssh-vulnerability-cve 2024-07-03

- serverless/sql-databases/reference-content/serverless-sql-databases-overview.mdx
> docs(sdb): add link to prepared statements doc MTA-4771

- managed-databases/postgresql-and-mysql/how-to/connect-database-private-network.mdx
This is a really small typo but it's been long time since I updated the doc so I wanted to be up-to-date on how to do it
> fix(rdb): fix a small typo

- bare-metal/apple-silicon/how-to/connect-to-mac-mini.mdx
> feat(aps): add information for vnc clients

- compute/gpu/how-to/use-mig-with-kubernetes.mdx
- compute/gpu/how-to/use-nvidia-mig-technology.mdx
- compute/gpu/how-to/use-pipenv.mdx
- compute/gpu/how-to/use-preinstalled-env.mdx
- compute/gpu/how-to/use-scratch-storage-h100-instances.mdx
- containers/kubernetes/how-to/use-scratch-storage-h100.mdx
- managed-services/webhosting/how-to/configure-dns-webhosting.mdx
- managed-services/webhosting/how-to/migrate-webhosting-plan.mdx
- tutorials/manage-zigbee-devices-with-iot/index.mdx
- tutorials/proxmox-softraid/index.mdx
- tutorials/python-for-loops/index.mdx
> chore(gen): review documentations

- tutorials/manage-instances-with-terraform-and-functions/index.mdx
Fix Serverless Functions formatting
> fix(functions): formatting code

- tutorials/veeam-backup-replication-s3/index.mdx
> docs(s3): add troubleshooting to veeam tutorial MTA-4808b

- menu/navigation.json
- serverless/sql-databases/troubleshooting/maximum-prepared-statements-reached.mdx
> docs(SDB): add troubleshooting on prepared statements MTA-4818

- menu/navigation.json
- serverless/sql-databases/reference-content/planned-maintenance.mdx
> docs(SDB): add planned maintenance doc MTA-4837

- containers/kubernetes/reference-content/version-support-policy.mdx
> [K8S] feat: add 1.30 to version support information

- changelog/july2024/2024-07-09-kubernetes-added-kubernetes-version-130-is-now-availabl.mdx
> feat(changelog): kubernetes-added-kubernetes-version-130-is-now-availabl 2024-07-09

- serverless/sql-databases/api-cli/import-data-to-serverless-sql-databases.mdx
Fixing a link not working and updating a description from PostgreSQL COPY command to psql \copy command
> fix:import-data-to-serverless-sql-databases.mdx

- serverless/sql-databases/reference-content/planned-maintenance.mdx
> fix(sdb): update sdb maintenance duration

- changelog/july2024/2024-07-11-functions-added-reduce-cold-starts-with-sandbox-v2.mdx
> feat(changelog): functions-added-reduce-cold-starts-with-sandbox-v2 2024-07-11

- changelog/july2024/2024-07-12-transactional-email-added-microsoft-excel-attachments-a.mdx
> feat(changelog): transactional-email-added-microsoft-excel-attachments-a 2024-07-12

- identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx
> fix(aps): fix quotas

- bare-metal/elastic-metal/how-to/configure-ipv6-hypervisor.mdx
- bare-metal/elastic-metal/troubleshooting/enable-ssh-virtualization-distribution.mdx
- dedibox-network/ip-failover/how-to/configure-network-virtual-machine.mdx
- dedibox-network/rpn/how-to/configure-rpnv2.mdx
- dedibox-network/rpn/how-to/use-rpn-san-esxi-v7.mdx
- dedibox-network/rpn/how-to/use-rpn-san-esxi.mdx
- tutorials/add-disk-configure-datastore-esxi/index.mdx
- tutorials/configure-ipv6-virtual-machine-esxi/index.mdx
- tutorials/configure-virtual-machine-esxi/index.mdx
- tutorials/create-esxi-cluster-dedibox/index.mdx
> fix(ddx): add deprecation warning to esxi docs

- compute/gpu/how-to/use-gpu-with-docker.mdx
- compute/gpu/reference-content/docker-images.mdx
- tutorials/remote-desktop-with-xrdp/index.mdx
- tutorials/ruby-on-rails/index.mdx
- tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
- tutorials/s3-customize-url-cname/index.mdx
> chore(gen): docs review

- tutorials/ruby-on-rails/index.mdx
Error on build, seems produced by tabulations. Checked on on local build
> Update ruby-on-rails index.mdx

- changelog/july2024/2024-07-16-transactional-email-fixed-verify-domain-button-issue-fi.mdx
> feat(changelog): transactional-email-fixed-verify-domain-button-issue-fi 2024-07-16

- bare-metal/apple-silicon/reference-content/index.mdx
- bare-metal/elastic-metal/reference-content/shared-responsibility-model.mdx
- menu/navigation.json
> docs(bmaas): add shared responsibility model

- bare-metal/elastic-metal/reference-content/shared-responsibility-model.mdx
> fix(bmaas): fix sla typo

- index.mdx
> fix(gen): fix homepage description

- macros/console/create-account.mdx
Updated the doc on how to create an account + added info regarding the 4-digit code (aka Magic code)
> fix(account): updated account creation doc

- compute/instances/troubleshooting/fix-unreachable-focal-with-two-public-ips.mdx
Added a HowTo which documents how to fix unreachable Ubuntu Focal instances when they have multiple IP addresses attached.
> fea(instances): Fix unreachable Focal instance with multiple IP adresses

- console/account/how-to/switch-account-to-corporate.mdx
> fix(gen): fixed indention

- compute/instances/troubleshooting/fix-unreachable-focal-with-two-public-ips.mdx
- menu/navigation.json
> fix(ins): added links to navigation

- observability/cockpit/how-to/activate-push-traces.mdx
> fix(cockpit): update push trace path

- console/account/reference-content/products-availability.mdx
- network/vpc/how-to/attach-resources-to-pn.mdx
Amend DNS info and add PAR3 for PGW
> fix(vpc): update DNS info and add PGW PAR3

- serverless/sql-databases/api-cli/import-data-to-serverless-sql-databases.mdx
- tutorials/nats-rdb-offload/index.mdx
> fix(SDB): fix before you start and syntax coloration MTA-4840

- bare-metal/elastic-metal/how-to/create-virtual-mac-group.mdx
- dedibox-network/ip-failover/how-to/assign-failover-ip.mdx
- dedibox-network/ip-failover/how-to/configure-debian-ubuntu.mdx
- dedibox-network/ip-failover/how-to/configure-network-virtual-machine.mdx
- dedibox-network/ip-failover/how-to/configure-reverse-dns.mdx
- dedibox-network/ip-failover/how-to/configure-windows.mdx
> chore(ddx): content review dedibox

- network/ipam/concepts.mdx
- network/ipam/how-to/list-ips.mdx
Add CIDR notation info to IPAM doc after user confusion
> fix(ipam): add cidr info

- menu/navigation.json
Updating the Partner Space menu icon
> fix(partners): add new icon

- identity-and-access-management/secret-manager/concepts.mdx
- identity-and-access-management/secret-manager/how-to/create-secret.mdx
- identity-and-access-management/secret-manager/how-to/create-version.mdx
- identity-and-access-management/secret-manager/how-to/filter-secrets.mdx
- identity-and-access-management/secret-manager/quickstart.mdx
- menu/navigation.json
Added secret types concept
Updated quickstart for secret creation, how to create a secret, how to create a version.
Added how to filter secrets page.
Added info that versions must be of the same type as the secret they belong to.
> feat(secret-manager): add secret types content

- changelog/july2024/2024-07-25-secret-manager-added-secret-types-are-available-on-cons.mdx
> feat(changelog): secret-manager-added-secret-types-are-available-on-cons 2024-07-25

- changelog/july2024/2024-07-25-ipam-added-ipam-ip-address-manager-is-available-in-publ.mdx
> feat(changelog): ipam-added-ipam-ip-address-manager-is-available-in-publ 2024-07-25

- bare-metal/elastic-metal/how-to/use-private-networks.mdx
> fix(em): remove PN limitations from EM docs

- compute/instances/how-to/use-flexips.mdx
> fix(ins): fix typo

- containers/kubernetes/reference-content/kubernetes-load-balancer.mdx
Troubleshooting for LB 400 Error when using  TCP Proxy and Nginx Ingress
> type(Kubernetes): Error 400 using TCP proxy and nginx ingress

- bare-metal/apple-silicon/how-to/upgrade-macos-to-beta.mdx
- menu/navigation.json
> feat(aps): add macos beta upgrade doc

- network/load-balancer/api-cli/setting-up-ssl-offloading.mdx
> fix(lb): fix bug

- dedibox/dedicated-servers/how-to/use-dedibackup-ftp-backup.mdx
> fix(ddx): update docs

- changelog/july2024/2024-07-30-apple-silicon-changed-some-apple-silicon-updates.mdx
> feat(changelog): apple-silicon-changed-some-apple-silicon-updates 2024-07-30

- console/account/how-to/change-language.mdx
- console/account/how-to/configure-support-plans.mdx
- console/account/how-to/create-an-account.mdx
- console/account/how-to/manage-my-personal-data-gdpr.mdx
- console/account/how-to/verify-identity.mdx
- console/account/quickstart.mdx
- serverless/containers/reference-content/cron-schedules.mdx
- serverless/functions/how-to/add-a-custom-domain-name-to-a-function.mdx
- serverless/functions/how-to/create-a-function.mdx
- serverless/functions/how-to/create-auth-token-from-console.mdx
- serverless/functions/how-to/delete-a-function.mdx
- serverless/functions/how-to/delete-a-functions-namespace.mdx
- serverless/functions/how-to/manage-a-function.mdx
- serverless/functions/quickstart.mdx
- serverless/functions/reference-content/code-examples.mdx
- serverless/functions/reference-content/functions-handlers.mdx
- serverless/functions/reference-content/functions-lifecycle.mdx
- serverless/functions/reference-content/functions-limitations.mdx
- serverless/functions/reference-content/functions-runtimes-configuration.mdx
- storage/object/api-cli/manage-bucket-permissions-ip.mdx
- storage/object/api-cli/migrating-buckets.mdx
- storage/object/api-cli/object-storage-aws-cli.mdx
- storage/object/api-cli/share-buckets-read-only.mdx
> chore(gen): content review

- changelog/july2024/2024-07-30-apple-silicon-changed-some-apple-silicon-updates.mdx
> fix(aps): fix changelog

- containers/kubernetes/reference-content/move-kubernetes-nodes-routed-ip.mdx
> feat(k8s): add routed ip migration dates

- compute/instances/troubleshooting/cant-connect-ssh.mdx
- menu/navigation.json
> fix(ins): fix troubleshooting

- tutorials/traefik-v2-cert-manager/index.mdx
> fix(tuto): fix treafik tuto

- faq/public-gateways.mdx
> feat(pgw): add new pgw type

- changelog/august2024/2024-08-02-public-gateways-added-new-pgw-l-offer.mdx
> feat(changelog): public-gateways-added-new-pgw-l-offer 2024-08-02

- changelog/august2024/2024-08-02-postgresql-and-mysql-added-encryption-at-rest-available.mdx
> feat(changelog): postgresql-and-mysql-added-encryption-at-rest-available 2024-08-02

- dedibox-console/account/how-to/accept-outsourcing.mdx
- dedibox-console/account/how-to/add-payment-method.mdx
- dedibox-console/account/how-to/contact-support.mdx
- dedibox-console/account/how-to/create-a-dedibox-account.mdx
- dedibox-console/account/how-to/disable-two-factor-authentication.mdx
- dedibox-console/account/how-to/enable-two-factor-authentication.mdx
- dedibox-console/account/how-to/manage-data-settings.mdx
- dedibox-console/account/how-to/outsource-dedibox.mdx
- dedibox-console/account/how-to/recover-password-lost-email.mdx
- dedibox-console/account/how-to/report-incident.mdx
- dedibox-console/account/how-to/revoke-outsourcing.mdx
- dedibox-console/account/how-to/update-password.mdx
- dedibox-console/account/how-to/upload-an-ssh-key.mdx
- dedibox-console/account/quickstart.mdx
- dedibox-console/classic-hosting/how-to/change-email-account-password.mdx
- dedibox-console/classic-hosting/how-to/configure-htaccess-file.mdx
- dedibox-console/classic-hosting/how-to/configure-outlook.mdx
- dedibox-console/classic-hosting/how-to/connect-via-ftp.mdx
- dedibox-console/classic-hosting/how-to/create-alias.mdx
- dedibox-console/classic-hosting/how-to/create-email-account.mdx
- dedibox-console/classic-hosting/how-to/create-ftp-account.mdx
- dedibox-console/classic-hosting/how-to/delete-email-account.mdx
- dedibox-console/classic-hosting/how-to/manage-email-filter.mdx
- dedibox-console/classic-hosting/how-to/retrieve-headers-of-email.mdx
- dedibox-network/ip-failover/how-to/configure-centos.mdx
- dedibox-network/ip-failover/how-to/order-failover-ip.mdx
- dedibox/dedicated-servers/how-to/manage-packages.mdx
- dedibox/dedicated-servers/how-to/migrate-server.mdx
- dedibox/dedicated-servers/how-to/use-dedibackup-ftp-backup.mdx
- managed-services/webhosting/how-to/terminate-webhosting.mdx
> feat(ddx): review documentations dedibox and webhosting

- bare-metal/dedibox/concepts.mdx
- bare-metal/elastic-metal/concepts.mdx
- bare-metal/elastic-metal/how-to/add-virtual-mac-address.mdx
- bare-metal/elastic-metal/how-to/attach-detach-flexible-ip.mdx
- bare-metal/elastic-metal/how-to/configure-flexible-ip.mdx
- bare-metal/elastic-metal/how-to/configure-flexible-ipv6.mdx
- bare-metal/elastic-metal/how-to/configure-reverse-dns-flexible-ip.mdx
- bare-metal/elastic-metal/how-to/create-server.mdx
- bare-metal/elastic-metal/how-to/enable-smtp.mdx
- bare-metal/elastic-metal/how-to/install-server.mdx
- bare-metal/elastic-metal/how-to/order-flexible-ip.mdx
- bare-metal/elastic-metal/how-to/reboot-server.mdx
- bare-metal/elastic-metal/how-to/reinstall-server.mdx
- bare-metal/elastic-metal/how-to/view-the-event-logs.mdx
- compute/gpu/concepts.mdx
- compute/instances/api-cli/cli-cheatsheet.mdx
- compute/instances/api-cli/using-placement-groups.mdx
- compute/instances/concepts.mdx
- compute/instances/how-to/connect-to-instance.mdx
- compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx
- compute/instances/troubleshooting/fix-lost-ip-connectivity-on-debian-buster.mdx
- dedibox-network/rpn/concepts.mdx
- dedibox/kvm-over-ip/how-to/quantaplex.mdx
- dedibox/kvm-over-ip/how-to/supermicro.mdx
> feat(baremetal): review docs

- changelog/august2024/2024-08-05-jobs-added-metrics-available-on-serverless-jobs.mdx
> feat(changelog): jobs-added-metrics-available-on-serverless-jobs 2024-08-05

- changelog/august2024/2024-08-05-containers-added-serverless-containers-more-cpu-and-ram.mdx
> feat(changelog): containers-added-serverless-containers-more-cpu-and-ram 2024-08-05

- bare-metal/elastic-metal/how-to/use-private-networks.mdx
> fix(em): fix howto

- changelog/august2024/2024-08-07-console-fixed-quota-consumption-is-now-displayed-at-org.mdx
> feat(changelog): console-fixed-quota-consumption-is-now-displayed-at-org 2024-08-07

- ai-data/managed-inference/reference-content/sentence-t5-xxl.mdx
Fix typo in quantization for Sentence model
> fix(inference): fix quantization typo

- compute/instances/how-to/use-security-groups.mdx
> fix(ins): update doc security groups

- compute/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx
- menu/navigation.json
> feat(ins): added volumes to sbs migration documentation

- bare-metal/elastic-metal/concepts.mdx
- bare-metal/elastic-metal/how-to/create-server.mdx
- compute/instances/concepts.mdx
- compute/instances/reference-content/choosing-instance-type.mdx
- compute/instances/reference-content/manual-configuration-private-ips.mdx
- compute/instances/reference-content/preventing-outgoing-ddos.mdx
- compute/instances/reference-content/understanding-differences-x86-arm.mdx
- compute/instances/reference-content/understanding-instance-pricing.mdx
- containers/kubernetes/how-to/access-kubernetes-dashboard.mdx
- containers/kubernetes/how-to/monitor-cluster.mdx
- dedibox-console/account/how-to/create-a-dedibox-account.mdx
- dedibox-console/account/how-to/outsource-failover-ip.mdx
- dedibox-console/classic-hosting/how-to/change-ftp-account-password.mdx
- dedibox-console/classic-hosting/how-to/configure-outlook.mdx
- dedibox-console/classic-hosting/how-to/retrieve-headers-of-email.mdx
- dedibox-console/cpanel-hosting/reference-content.mdx
- dedibox-network/dns/how-to/add-dns-delegation.mdx
- dedibox-network/ip-failover/how-to/configure-multiip-virtualmac.mdx
- dedibox-network/ipv6/how-to/create-subnet.mdx
- dedibox-network/network/how-to/subscribe-to-jmrp.mdx
- dedibox-network/rpn/how-to/connect-rpn-san-windows.mdx
- dedibox-network/rpn/how-to/connect-rpn-san.mdx
- dedibox-network/rpn/how-to/use-rpn-san-esxi-v7.mdx
- dedibox-network/rpn/how-to/use-rpn-san-esxi.mdx
- dedibox-network/rpn/how-to/use-rpn-vpn.mdx
- managed-services/webhosting/how-to/order-dedicated-ip.mdx
- managed-services/webhosting/reference-content/cpanel-reference-content.mdx
> chore(gen): docs content review

- compute/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx
> fix(ins): fix broken link

- compute/instances/how-to/snapshot-import-export-feature.mdx
> feat(ins): update snapshot docs

- tutorials/manage-instances-with-terraform-and-functions/index.mdx
- Fix small typo
- Fix of the python script
> Update index.mdx: Fix typo + Fix python script

- ai-data/managed-inference/quickstart.mdx
User reported a gap between doc and reality.
This PR brings a wording update, since we don't talk about tokens but API keys in the console.
> chore(inf): auth wording update

- guidelines.mdx
> fix(guidelines): fix typo

- serverless/jobs/how-to/monitor-job.mdx
> docs(srv): update monitor job doc MTA-4928

- console/account/index.mdx
> fix(acc): typo

- managed-services/webhosting/concepts.mdx
- managed-services/webhosting/how-to/protect-webhosting.mdx
- menu/navigation.json
> feat(wbh): protected hosting

- developer-tools/scaleway-cli/reference-content/environment-variables.mdx
- developer-tools/scaleway-sdk/reference-content/environment-variables.mdx
- developer-tools/terraform/reference-content/environment-variables.mdx
> docs(dvt): add variables precedence rule to doc MTA-4901

- storage/object/api-cli/object-storage-aws-cli.mdx
> docs(s3): update aw cli v2 documentation MTA-4911

- tutorials/create-deploy-staging-site-cpanel/index.mdx
- tutorials/deploy-big-blue-button/index.mdx
- tutorials/easydeploy-argocd/index.mdx
- tutorials/easydeploy-gitlab-server/index.mdx
- tutorials/easydeploy-grafana/index.mdx
- tutorials/easydeploy-vault/index.mdx
- tutorials/getting-started-with-kops-on-scaleway/index.mdx
- tutorials/install-cockroachdb-scaleway-instances/index.mdx
- tutorials/install-golang-ubuntu-bionic/index.mdx
- tutorials/install-php-composer/index.mdx
- tutorials/installation-jekyll/index.mdx
- tutorials/jitsi-debian/index.mdx
- tutorials/jitsi-ubuntu-bionic/index.mdx
- tutorials/matomo-analytics/index.mdx
- tutorials/minikube-elastic-metal/index.mdx
- tutorials/proxmox-softraid/index.mdx
- tutorials/run-messaging-platform-with-rocketchat/index.mdx
- tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
- tutorials/run-python-flask-server-on-serverless-container/index.mdx
- tutorials/setup-ampere-ai-framework-arm-instances/index.mdx
- tutorials/stop-outgoing-spam/index.mdx
- tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
> fix(tutorials): validation schedule

- tutorials/configuring-gitlab-scaleway-elements-database/index.mdx
> fix(tuto): fix tutorial

- containers/kubernetes/reference-content/kubernetes-control-plane-offers.mdx
> feat(k8s): add documentation for etcd quotas

- contribute.mdx
Add links to guidelines from contribute page
> fix(contribute): add links to guidelines

- compute/instances/troubleshooting/fix-unreachable-focal-with-two-public-ips.mdx
Fixed broken symlink in documentation
> fix(ins): fix broken symlink in doc

- changelog/august2024/2024-08-26-managed-inference-added-chat-and-embedding-apis-now-ret.mdx
> feat(changelog): managed-inference-added-chat-and-embedding-apis-now-ret 2024-08-26

- storage/object/how-to/get-started-edge-services.mdx
Remove warning about bucket website: this has been stabilized in prod
> fix(edge): remove bucket website warning

- console/billing/how-to/download-an-invoice.mdx
- console/billing/quickstart.mdx
> fix(bil): reviews 27/08

- menu/navigation.json
Add links to API ref for each product from main doc site menu
> feat(menu): add links to API doc

- ai-data/generative-apis/concepts.mdx
- ai-data/generative-apis/reference-content/openai-compatibility.mdx
> feat(genapi): add Generative APIs concepts

- tutorials/collecting-visualizing-logs-elastic-stack/index.mdx
- tutorials/configure-graphite/index.mdx
- tutorials/configure-smtp-relay-tem/index.mdx
- tutorials/deploy-phpmyadmin-with-docker/index.mdx
- tutorials/deploy-ubuntu-20-04-instance-scaleway-elements/index.mdx
- tutorials/deploy-ubuntu-22-04-instance/index.mdx
- tutorials/focalboard-project-management/index.mdx
- tutorials/mariadb-ubuntu-bionic/index.mdx
- tutorials/mastodon-community/index.mdx
- tutorials/migrate-databases-instance/index.mdx
- tutorials/migrate-dedibox-to-elastic-metal/index.mdx
- tutorials/minikube-elastic-metal/index.mdx
- tutorials/nextcloud-instantapp/index.mdx
- tutorials/plausible-analytics-ubuntu/index.mdx
- tutorials/scaleway-slack-community/index.mdx
- tutorials/setup-k8s-cluster-rancher/index.mdx
> docs(gen): review tutorials 2024-08-27

- ai-data/generative-apis/quickstart.mdx
- ai-data/generative-apis/reference-content/openai-compatibility.mdx
> feat(genapi): added quickstart

- ai-data/generative-apis/how-tos/query-embedding-models.mdx
- ai-data/generative-apis/how-tos/query-text-models.mdx
- ai-data/generative-apis/reference-content/openai-compatibility.mdx
Added content for how to section
> feat(genapi): add how-tos

- faq/billing.mdx
Added that we accept SEPA as a payment method
> fix(bil): update docs

- managed-services/data-lab/quickstart.mdx
Fix wording and descriptions of actions
Changes in the wording to improve accuracy
> fix(Data Lab):Update quickstart.mdx

- managed-services/data-lab/index.mdx
> fix(DLB): fix 404 on index page

- ai-data/managed-inference/how-to/create-deployment.mdx
- ai-data/managed-inference/how-to/delete-deployment.mdx
- ai-data/managed-inference/how-to/manage-allowed-ips.mdx
- ai-data/managed-inference/how-to/managed-inference-with-private-network.mdx
- ai-data/managed-inference/how-to/monitor-deployment.mdx
- ai-data/managed-inference/quickstart.mdx
Added or fixed missing requirements for Managed Inference
> fix(ifr): fix requirements

- storage/object/api-cli/object-storage-aws-cli.mdx
Fix not working aws-cli s3 configuration
> fix(doc): aws-cli s3 configuration

- console/account/how-to/report-abuse.mdx
- console/account/how-to/resolve-abuse.mdx
- serverless/containers/api-cli/deploy-container-api.mdx
- serverless/containers/api-cli/deploy-container-cli.mdx
- serverless/containers/how-to/delete-a-container.mdx
- serverless/containers/how-to/delete-a-containers-namespace.mdx
- serverless/containers/how-to/modify-container-privacy.mdx
- serverless/functions/api-cli/deploy-function-api.mdx
- serverless/functions/api-cli/deploy-function-cli.mdx
- serverless/sql-databases/how-to/add-users.mdx
- serverless/sql-databases/how-to/configure-autoscaling.mdx
- serverless/sql-databases/how-to/connect-to-a-database.mdx
- serverless/sql-databases/how-to/delete-a-database.mdx
- serverless/sql-databases/how-to/manage-permissions.mdx
- serverless/sql-databases/quickstart.mdx
> chore(GEN): content review MTA-4966

- ai-data/generative-apis/how-to/query-embedding-models.mdx
- ai-data/generative-apis/how-to/query-text-models.mdx
Added tutorials for Generative APIs. 
Need review by @tgenaitay
> feat(ifr): added tutorials for generative apis

- managed-services/data-lab/quickstart.mdx
> docs(DLB): update quickstart MTA-4984

- dedibox-network/domains/how-to/change-ownership.mdx
- managed-services/webhosting/how-to/protect-webhosting.mdx
> docs(fix): fix broken links

- changelog/september2024/2024-09-02-domains-and-dns-changed-pricing-update-for-some-tlds.mdx
> feat(changelog): domains-and-dns-changed-pricing-update-for-some-tlds 2024-09-02

- managed-databases/redis/how-to/connect-to-redis-database-instance.mdx
- managed-databases/redis/how-to/create-a-database-for-redis.mdx
> fix(rdb): add note

- console/account/how-to/manage-my-personal-data-gdpr.mdx
Since there is no longer a section to opt out of the newsletter in the My privacy tab, there is no need for this documentation.
> (fix)account: remove deprecated section

- console/account/how-to/change-language.mdx
Removed steps that were repeated twice.
> fix(account): update how to change the account language

- changelog/september2024/2024-09-03-kubernetes-changed-new-size-limits-for-etcd-stores-in-k.mdx
> feat(changelog): kubernetes-changed-new-size-limits-for-etcd-stores-in-k 2024-09-03

- ai-data/generative-apis/quickstart.mdx
- ai-data/generative-apis/reference-content/supported-models.mdx
> fix(ai): fix metadata

- ai-data/managed-inference/reference-content/llama-3.1-70b-instruct.mdx
- ai-data/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
- Brought license to model overview
- Updated context length according to new quantization options
> fix(ifr): updated quant and context for Llama3.1 release

- index.mdx
Updated suggested keywords from the docs landing page to match the most searched keywords from the past 3 months: ipv6, rpn, and proxmox.
> docs(gen): update suggested keywords from doc landing page

- menu/navigation.json
> feat(ins): fix menu

- faq/public-gateways.mdx
- menu/navigation.json
- network/public-gateways/how-to/upgrade-public-gateway.mdx
Document the new button for upgrading a PGW from the Scaleway console.
> feat(pgw): upgrade pgw

- console/account/how-to/verify-identity.mdx
https://jira.infra.online.net/browse/MTA-5012
Docs update - users can also verify their ID from the Settings tab of their Organization
> fix(account): docs update

- console/billing/additional-content/understanding-savings-plans.mdx
> feat(bil): gp and dev mention

- faq/serverless-functions.mdx
> chore(serverless): clean unecessary memory tier references

- console/account/quickstart.mdx
Console tour Guideflow added to Quickstart
> fix(account): added guideflow to quickstart

- changelog/september2024/2024-09-11-ipam-added-ipam-is-now-in-general-availability.mdx
> feat(changelog): ipam-added-ipam-is-now-in-general-availability 2024-09-11

- changelog/september2024/2024-09-11-public-gateways-added-public-gateway-upgrade.mdx
> feat(changelog): public-gateways-added-public-gateway-upgrade 2024-09-11

- menu/navigation.json
- storage/object/api-cli/multipart-uploads.mdx
- storage/object/how-to/abort-incomplete-mpu.mdx
- storage/object/how-to/manage-lifecycle-rules.mdx
> docs(s3): update lifecycle rule & MPU documentation MTA-5049

- console/billing/how-to/purchase-savings-plan.mdx
> (docs)billing: fix

- changelog/september2024/2024-09-16-object-storage-added-lifecycle-rules-now-allow-to-abort.mdx
> feat(changelog): object-storage-added-lifecycle-rules-now-allow-to-abort 2024-09-16

- changelog/september2024/2024-09-16-object-storage-added-uncomplete-multipart-uploads-are-n.mdx
> feat(changelog): object-storage-added-uncomplete-multipart-uploads-are-n 2024-09-16

- changelog/september2024/2024-09-13-vpc-added-vpc-custom-routes-are-now-in-general-availabi.mdx
> feat(changelog): vpc-added-vpc-custom-routes-are-now-in-general-availabi 2024-09-13

- tutorials/ark-server/index.mdx
> fix(tutorial): fix broken format

- faq/instances.mdx
Added prices for POP2-WIN Instances types to FAQ
> docs(instances): add pop2-win instances to faq

- menu/navigation.json
Updated the navigation menu overview titles so they don't display the products' names.
Before: `[Product name] Overview`
Now: `Overview`
> docs(gen): update navigation menu overview titles

- ai-data/generative-apis/api-cli/using-chat-api.mdx
- ai-data/generative-apis/api-cli/using-generative-apis.mdx
- ai-data/generative-apis/concepts.mdx
- ai-data/generative-apis/how-to/query-embedding-models.mdx
- ai-data/generative-apis/how-to/query-text-models.mdx
- ai-data/generative-apis/how-to/use-structured-outputs.mdx
- ai-data/generative-apis/quickstart.mdx
- ai-data/managed-inference/concepts.mdx
- ai-data/managed-inference/reference-content/openai-compatibility.mdx
- menu/navigation.json
Added documentation for structured outputs
> feat(ai): add structured outputs

- identity-and-access-management/organizations-and-projects/how-to/add-resources-project.mdx
Moved this sentence to a warning section to draw attention to it:
> Make sure that you are editing the correct Project before adding new [resources](https://www.scaleway.com/en/docs/identity-and-access-management/iam/concepts/#resource) to it.
> style(fix): warning

- storage/object/how-to/edit-storage-class.mdx
> fix(s3): fix storage class procedure

- ai-data/managed-inference/reference-content/openai-compatibility.mdx
> fix(ai): fix unsupported parameters

- faq/iothub.mdx
> chore(faq): review faq iothub

- serverless/containers/concepts.mdx
- serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
- serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx
> docs(srv): update container ephemeral storage documentation

- serverless/jobs/how-to/monitor-job.mdx
> docs(s3): update monitor job documentation MTA-5034

- changelog/april2024/2024-04-04-cockpit-added-metrics-degrissivity.mdx
- changelog/may2024/2024-05-24-cockpit-added-orderable-data-source-for-cockpit.mdx
- faq/cockpit.mdx
- menu/navigation.json
- observability/cockpit/api-cli/querying-logs-with-logcli.mdx
- observability/cockpit/concepts.mdx
- observability/cockpit/how-to/activate-push-traces.mdx
- observability/cockpit/how-to/create-external-data-sources.mdx
- observability/cockpit/how-to/delete-external-data-sources.mdx
- observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx
- observability/cockpit/index.mdx
- observability/cockpit/quickstart.mdx
- observability/cockpit/reference-content/understanding-cockpit-usage.mdx
- tutorials/pushing-metrics-logs-from-scw-instance/index.mdx
- tutorials/use-cockpit-with-terraform/index.mdx
Removed all mentions of external/internal metrics, logs, traces, and data sources
> docs(cockpit): wording changes

- ai-data/generative-apis/reference-content/data-privacy.mdx
> fix(genapi): fix typo

- changelog/september2024/2024-09-19-containers-added-ephemeral-storage-customisable.mdx
> feat(changelog): containers-added-ephemeral-storage-customisable 2024-09-19

- changelog/september2024/2024-09-19-functions-changed-serverless-functions-default-sandbox-.mdx
> feat(changelog): functions-changed-serverless-functions-default-sandbox- 2024-09-19

- changelog/september2024/2024-09-19-containers-changed-serverless-containers-default-sandbo.mdx
> feat(changelog): containers-changed-serverless-containers-default-sandbo 2024-09-19

- compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx
Fix YAML indentation in troubleshooting article.
Relates to #3746
> fix(instances): fix YAML indentation in code block

- changelog/september2024/2024-09-25-transactional-email-added-webhooks-ga-release-track-and.mdx
> feat(changelog): transactional-email-added-webhooks-ga-release-track-and 2024-09-25

- changelog/september2024/2024-09-25-managed-inference-added-analyze-images-with-mistrals-vi.mdx
> feat(changelog): managed-inference-added-analyze-images-with-mistrals-vi 2024-09-25

- managed-services/data-lab/index.mdx
> fix(datalab): index file

- changelog/september2024/2024-09-25-managed-inference-added-analyze-images-with-mistrals-vi.mdx
> fix(changelog): remove apostrophe from title to avoid console issue

- index.mdx
Updating the content of 'Getting started' cards of the landing page to feature more beginner-friendly pages.
> docs(gen): lading page getting started cards update

- changelog/september2024/2024-09-26-object-storage-changed-all-requests-now-go-though-scale.mdx
> feat(changelog): object-storage-changed-all-requests-now-go-though-scale 2024-09-26

- changelog/september2024/2024-09-26-object-storage-changed-increase-of-object-storage-defau.mdx
> feat(changelog): object-storage-changed-increase-of-object-storage-defau 2024-09-26

- changelog/september2024/2024-09-26-elastic-metal-added-new-public-bandwidth-increasing-opt.mdx
> feat(changelog): elastic-metal-added-new-public-bandwidth-increasing-opt 2024-09-26

- faq/messaging-and-queuing.mdx
> fix(error): fix

- changelog/september2024/2024-09-27-billing-added-discover-our-new-compute-savings-plan-off.mdx
> feat(changelog): billing-added-discover-our-new-compute-savings-plan-off 2024-09-27

- faq/edge-services.mdx
- menu/navigation.json
- network/edge-services/reference-content/understanding-ga.mdx
> feat(edge): add info about General Availability

- changelog/september2024/2024-09-27-billing-added-discover-our-new-compute-savings-plan-off.mdx
> fix(changelog): typo

- changelog/september2024/2024-09-30-managed-inference-changed-public-endpoints-have-moved-t.mdx
> feat(changelog): managed-inference-changed-public-endpoints-have-moved-t 2024-09-30

- faq/elastic-metal.mdx
Fixed small typos on Elastic Metal FAQ page.
> fix(em): fix small typos on faq page

- console/account/how-to/change-language.mdx
> docs(fix): numbering

- changelog/october2024/2024-10-01-jobs-added-cost-estimator-when-updating-resources.mdx
> feat(changelog): jobs-added-cost-estimator-when-updating-resources 2024-10-01

- tutorials/configure-apache-lets-encrypt/index.mdx
- tutorials/deploy-big-blue-button/index.mdx
- tutorials/deploy-instances-packer-terraform/index.mdx
- tutorials/encrypt-volumes/index.mdx
- tutorials/erpnext/index.mdx
- tutorials/flask/index.mdx
- tutorials/get-started-kubernetes-loadbalancer/index.mdx
- tutorials/glpi/index.mdx
- tutorials/gpu-super-resolution/index.mdx
- tutorials/host-github-runner/index.mdx
- tutorials/install-cassandra/index.mdx
- tutorials/install-configure-couchdb/index.mdx
- tutorials/install-docker-ubuntu-bionic/index.mdx
- tutorials/install-golang-ubuntu-bionic/index.mdx
- tutorials/odoo-easy-deploy/index.mdx
- tutorials/postgis-managed-databases/index.mdx
- tutorials/postman-api/index.mdx
- tutorials/protect-server-fail2ban/index.mdx
- tutorials/protect-server-using-crowdsec/index.mdx
- tutorials/set-up-yunohost-debian/index.mdx
- tutorials/setting-up-tunnel/index.mdx
- tutorials/setup-cockroachdb-cluster/index.mdx
- tutorials/setup-mysql/index.mdx
- tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx
- tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
- tutorials/visualize-timeseries-data-timescaledb-grafana/index.mdx
> chore(gen): tutorials content review 2024-10-03

- console/billing/how-to/purchase-savings-plan.mdx
> fix(bil): fix saving plan options

- network/edge-services/reference-content/understanding-ga.mdx
Add more info about pricing after user feedback
> fix(edge): add more pricing info

- bare-metal/apple-silicon/how-to/shutdown-mac-mini.mdx
> fix(aps): update wording mac mini shutdown

- bare-metal/dedibox/how-to/activate-ipv6-block.mdx
- compute/gpu/reference-content/understanding-nvidia-nemo.mdx
- containers/kubernetes/reference-content/using-kapsule-autoheal-feature.mdx
> chore(compute): review docs 2024-10-07

- network/ipam/concepts.mdx
- network/ipam/how-to/reserve-ip.mdx
- network/ipam/quickstart.mdx
Add info about IPs that can't be reserved/used by users
> fix(ipam): add unreservable ip info

- identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx
> fix(mnq): update quotas documentation

- network/edge-services/reference-content/understanding-ga.mdx
> fix(edge): fix

- compute/instances/reference-content/add-instance-specific-ssh-keys-using-tags.mdx
- menu/navigation.json
- serverless/jobs/troubleshooting/common-errors.mdx
> feat(ins): add docs for ssh key tags

- managed-services/data-lab/how-to/create-data-lab.mdx
- managed-services/data-lab/quickstart.mdx
> docs(DLB): update doc with info on zero worker nodes MTA-5131

- changelog/october2024/2024-10-08-messaging-and-queuing-added-queues-subscription-availab.mdx
> feat(changelog): messaging-and-queuing-added-queues-subscription-availab 2024-10-08

- bare-metal/dedibox/how-to/attach-detach-failover-ip.mdx
- bare-metal/dedibox/how-to/configure-ipv6-dedibox.mdx
- bare-metal/dedibox/how-to/configure-reverse-failover-ip.mdx
- bare-metal/dedibox/how-to/modify-server-options.mdx
- bare-metal/dedibox/how-to/order-dedibox.mdx
- bare-metal/dedibox/how-to/order-failover-ip.mdx
- bare-metal/dedibox/how-to/reinstall-dedibox.mdx
- bare-metal/dedibox/how-to/terminate-dedibox.mdx
- bare-metal/dedibox/how-to/use-rescue-mode.mdx
- compute/gpu/reference-content/choosing-gpu-instance-type.mdx
- compute/gpu/reference-content/understanding-nvidia-fp8.mdx
- compute/gpu/troubleshooting/updating-gpu-instance-with-cloud-init.mdx
- compute/instances/api-cli/managing-instance-snapshot-via-cli.mdx
- console/account/reference-content/products-availability.mdx
- containers/kubernetes/reference-content/lb-ingress-controller.mdx
- containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx
- containers/kubernetes/reference-content/understanding-differences-kapsule-kosmos.mdx
- dedibox-network/ip-failover/how-to/configure-freebsd.mdx
- managed-services/transactional-email/troubleshooting/delist-domain.mdx
Docs content review 2024-10-14
> docs(ddx): docs content review 2024-10-14

- changelog/october2024/2024-10-14-transactional-email-added-autoconfig-is-now-available.mdx
> feat(changelog): transactional-email-added-autoconfig-is-now-available 2024-10-14

- changelog/october2024/2024-10-14-sql-databases-added-extension-support.mdx
> feat(changelog): sql-databases-added-extension-support 2024-10-14

- identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx
> fix(aps): update quotas

- managed-databases/postgresql-and-mysql/concepts.mdx
- managed-databases/postgresql-and-mysql/how-to/change-volume-type.mdx
- managed-databases/postgresql-and-mysql/reference-content/autohealing.mdx
- managed-databases/postgresql-and-mysql/reference-content/security-and-reliability.mdx
- managed-databases/postgresql-and-mysql/troubleshooting/extension-errors.mdx
- managed-databases/redis/api-cli/managing-username-and-password.mdx
Review documentation for Managed Databases
> chore(dbaas): review docs 2024-10-16

- macros/bare-metal/dedibox-scaleway-migration.mdx
> fix(ddx): fix migration macro

- containers/kubernetes/reference-content/move-kubernetes-nodes-routed-ip.mdx
> feat(k8s): add information about routed ip migration completed

- compute/instances/how-to/create-an-instance.mdx
- compute/instances/quickstart.mdx
> feat(ins): update create instance

- managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx
> fix(tem): fix missing closing tag

- identity-and-access-management/iam/reference-content/overview.mdx
- identity-and-access-management/iam/reference-content/policy.mdx
- identity-and-access-management/iam/reference-content/reproduce-roles-project-api-keys.mdx
- identity-and-access-management/iam/reference-content/users-groups-and-applications.mdx
- identity-and-access-management/organizations-and-projects/additional-content/organization-quotas.mdx
- identity-and-access-management/organizations-and-projects/concepts.mdx
- labs/ipfs-naming/concepts.mdx
- labs/ipfs-pinning/concepts.mdx
- labs/ipfs-pinning/reference-content/install-ipfs-desktop.mdx
Content review for IAM and Labs
> chore(gen): review iam and labs 2024-10-16

- changelog/october2024/2024-10-17-transactional-email-changed-increase-in-minimum-quotas.mdx
> feat(changelog): transactional-email-changed-increase-in-minimum-quotas 2024-10-17

- managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx
> fix(tem): fix wrong validation date

- compute/instances/how-to/create-an-instance.mdx
- compute/instances/quickstart.mdx
> fix(ins): fix create doc for windows and typos

- bare-metal/dedibox/how-to/configure-failover-ip.mdx
- bare-metal/dedibox/how-to/install-dedibox.mdx
- compute/instances/troubleshooting/fix-long-delays-booting-without-public-ip.mdx
- dedibox-network/ipv6/how-to/configure-ipv6-linux.mdx
> chore(ddx): review docs compute

- console/account/reference-content/scaleway-network-information.mdx
Removed legacy NTP server from documentation and added more recent ones
> fix(ddx): update ip addresses of ntp servers

- changelog/october2024/2024-10-23-elastic-metal-added-disk-partitioning-configuration-now.mdx
> feat(changelog): elastic-metal-added-disk-partitioning-configuration-now 2024-10-23

- network/edge-services/reference-content/ssl-tls-certificate.mdx
Fix duplicate anchor issue in E.S. page
> fix(edge): fix duplicate anchors

- managed-services/webhosting/how-to/manage-databases.mdx
- managed-services/webhosting/how-to/manage-email-accounts.mdx
- managed-services/webhosting/how-to/manage-ftp-accounts.mdx
> fix(wbh): fix meta information

- managed-services/webhosting/reference-content/php-version-overview.mdx
> fix(wbh): fix date from future

- labs/ipfs-pinning/quickstart.mdx
- API endpoint URL with double slash
- Rephrase "How to retreive your data" part
> docs(ipfs-pinning): fix quickstart

- network/public-gateways/how-to/create-a-public-gateway.mdx
> fix(pgw): remove duplicate H2

- menu/navigation.json
> fix(ai): add missing link

- menu/navigation.json
Fixed double link in navigation.
> fix(ai): fix double link in navigation

- managed-services/data-lab/index.mdx
Updated Distributed Data Lab description on Overview page
> fix(datalab): wording overview page

- compute/instances/reference-content/understanding-qemu-guest-agent.mdx
> fix(ins): add posted date

- ai-data/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx
- ai-data/managed-inference/reference-content/function-calling-support.mdx
- ai-data/managed-inference/reference-content/llama-3-70b-instruct.mdx
- ai-data/managed-inference/reference-content/llama-3-8b-instruct.mdx
- ai-data/managed-inference/reference-content/llama-3.1-70b-instruct.mdx
- ai-data/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
- ai-data/managed-inference/reference-content/mistral-7b-instruct-v0.3.mdx
- ai-data/managed-inference/reference-content/mistral-nemo-instruct-2407.mdx
- ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
- ai-data/managed-inference/reference-content/openai-compatibility.mdx
- ai-data/managed-inference/reference-content/pixtral-12b-2409.mdx
- ai-data/managed-inference/reference-content/sentence-t5-xxl.mdx
- ai-data/managed-inference/reference-content/wizardlm-70b-v1.0.mdx
- menu/navigation.json
> fix(ai): added missing posted dates

- developer-tools/scaleway-cli/quickstart.mdx
> fix(devtools): fix small typo

- menu/navigation.json
> feat(ifr): add moshi to navigation

- ai-data/generative-apis/api-cli/using-generative-apis.mdx
> fix(genapi): remove private beta notice

- changelog/november2024/2024-11-04-edge-services-added-edge-services-is-now-in-general-ava.mdx
> feat(changelog): edge-services-added-edge-services-is-now-in-general-ava 2024-11-04

- network/load-balancer/reference-content/acls.mdx
- network/load-balancer/reference-content/http2-http3.mdx
- network/load-balancer/reference-content/kubernetes-load-balancer.mdx
- network/load-balancer/reference-content/sni-route-deprecation.mdx
- network/load-balancer/reference-content/ssl-bridging-offloading-passthrough.mdx
- network/public-gateways/concepts.mdx
> fix(nw): review docs

- changelog/november2024/2024-11-05-containers-added-serverless-network-metrics.mdx
> feat(changelog): containers-added-serverless-network-metrics 2024-11-05

- changelog/november2024/2024-11-05-functions-added-serverless-network-metrics.mdx
> feat(changelog): functions-added-serverless-network-metrics 2024-11-05

- storage/object/api-cli/enable-sse-c.mdx
> docs(s3): remove mention of privatebeta for SSE-C

- changelog/november2024/2024-11-05-generative-apis-added-generative-apis-now-available-in-.mdx
> feat(changelog): generative-apis-added-generative-apis-now-available-in- 2024-11-05

- changelog/november2024/2024-11-06-object-storage-added-sse-c-encryption-is-now-in-ga-for-.mdx
> feat(changelog): object-storage-added-sse-c-encryption-is-now-in-ga-for- 2024-11-06

- ai-data/generative-apis/reference-content/data-privacy.mdx
This alignment make it clear that Scaleway does not rely on an external actor like AWS/Azure subject to Cloud Act with servers in EU
> fix(ai-data): align Generative IA data security with Managed Inference

- storage/object/api-cli/enable-sse-c.mdx
> fix(s3): update SSE-C date

- changelog/november2024/2024-11-12-containers-changed-incoming-change-for-dns-resolution.mdx
> feat(changelog): containers-changed-incoming-change-for-dns-resolution 2024-11-12

- faq/dedibox.mdx
> fix(ddx): update ranges names

- console/account/reference-content/products-availability.mdx
> fix(edge): add to product availability

- storage/object/api-cli/enable-sse-c.mdx
Fix the command to test s3 sse-c
> [Update enable-sse-c.mdx] Fix (optionnal) download object command

- tutorials/migrating-docker-workloads-to-kubernetes-kapsule/index.mdx
> feat(k8s): add migration documentation

- network/load-balancer/concepts.mdx
- storage/object/reference-content/optimize-object-storage-performance.mdx
Correct / add links to Edge Services from LB and OS
> fix(edge): add links

- faq/ipam.mdx
- network/ipam/concepts.mdx
- network/vpc/how-to/attach-resources-to-pn.mdx
You can now use reserved IPs with Elastic Metal.
> fix(ipam): add doc for reserved IPs for EM

- compute/instances/how-to/create-image-from-snapshot.mdx
- compute/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx
> fix(ins): migration sbs

- tutorials/deploy-angular-application/index.mdx
> fix(tuto): fixed broken frontmatter

- tutorials/migrate-data-rclone/index.mdx
Feel free to remove the ovh block if it does not fit your internal policy.
> doc(tuto): add example for offsite backup between regions or clouders

- network/edge-services/reference-content/ssl-tls-certificate.mdx
Add caveat that CA must be trusted
> fix(edge): fix sentence

- storage/object/troubleshooting/low-performance.mdx
> fix(s3): update object storage troubleshooting H1

- changelog/november2024/2024-11-21-functions-added-ipv6-for-functions.mdx
> feat(changelog): functions-added-ipv6-for-functions 2024-11-21

- changelog/november2024/2024-11-21-containers-added-ipv6-for-containers.mdx
> feat(changelog): containers-added-ipv6-for-containers 2024-11-21

- changelog/november2024/2024-11-21-transactional-email-added-integration-with-zapier.mdx
> feat(changelog): transactional-email-added-integration-with-zapier 2024-11-21

- bare-metal/elastic-metal/reference-content/end-of-support-esxi.mdx
- menu/navigation.json
End of support of ESXi Images on Scaleway Elastic Metal and Dedibox servers
> docs(em): end of support esxi

- containers/kubernetes/troubleshooting/configuring-sql-storage-backend-helm.mdx
- menu/navigation.json
Added troubleshooting Guide: Configuring a SQL storage backend in Helm
> docs(k8s): Configuring a SQL storage backend in Helm

- changelog/november2024/2024-11-26-containers-added-dns-query-rate-limiting-update.mdx
> feat(changelog): containers-added-dns-query-rate-limiting-update 2024-11-26

- changelog/november2024/2024-11-25-jobs-fixed-ephemeral-storage-min-value-decreased.mdx
> feat(changelog): jobs-fixed-ephemeral-storage-min-value-decreased 2024-11-25

- menu/navigation.json
> fix(ipam): add to menu

- observability/cockpit/reference-content/cockpit-limitations.mdx
- [] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).
Updated the section listing all products integration to Cockpit to reflect current state.
> docs(cockpit): update product integration list in cockpit-limitations.mdx

- faq/audit-trail.mdx
- identity-and-access-management/audit-trail/index.mdx
Added icons for audit trail after front merged them this morning
> docs(add): add icons

- changelog/november2024/2024-11-28-secret-manager-added-audit-trail-is-in-public-beta-with.mdx
> feat(changelog): secret-manager-added-audit-trail-is-in-public-beta-with 2024-11-28

- changelog/november2024/2024-11-28-managed-inference-added-new-models-support-nemotron-and.mdx
> feat(changelog): managed-inference-added-new-models-support-nemotron-and 2024-11-28

- changelog/november2024/2024-11-28-managed-inference-added-new-models-support-nemotron-and.mdx
> docs(changelog): fix

- tutorials/using-bucket-website-with-mkdocs/index.mdx
Small typo found in the content of the tutorial.
> fix(tutorials): fix typo in bucket website with mkdocs

- ai-data/managed-inference/concepts.mdx
- ai-data/managed-inference/how-to/create-deployment.mdx
- ai-data/managed-inference/index.mdx
Minor changes to reflect the evolutions of the product: 
- supporting beyond LLM
- changes in copy for anything network
> fix(ai): Updating documentations according to console copy

- changelog/november2024/2024-11-29-dedibox-added-dedibox-commitment-plans.mdx
> feat(changelog): dedibox-added-dedibox-commitment-plans 2024-11-29

- changelog/november2024/2024-11-29-elastic-metal-added-new-titanium-and-iridium-offers.mdx
> feat(changelog): elastic-metal-added-new-titanium-and-iridium-offers 2024-11-29

- changelog/november2024/2024-11-29-elastic-metal-added-new-titanium-and-iridium-offers.mdx
> fix(changelog): bug

- changelog/december2024/2024-12-03-public-gateways-added-new-public-gateway-xl-offer.mdx
> feat(changelog): public-gateways-added-new-public-gateway-xl-offer 2024-12-03

- changelog/december2024/2024-12-03-redistm-added-redis-2-node-ha-in-public-beta.mdx
> feat(changelog): redistm-added-redis-2-node-ha-in-public-beta 2024-12-03

- serverless/containers/concepts.mdx
> feat(containers): concepts improvements

- environmental-footprint/environmental-footprint/additional-content/environmental-footprint-calculator.mdx
- identity-and-access-management/audit-trail/quickstart.mdx
- identity-and-access-management/audit-trail/reference-content/index.mdx
- network/edge-services/how-to/create-pipeline-lb.mdx
- network/edge-services/how-to/subscribe-edge-services.mdx
- network/edge-services/reference-content/understanding-ga.mdx
- network/ipam/reference-content/ipv6.mdx
- tutorials/migrating-docker-workloads-to-kubernetes-kapsule/index.mdx
- tutorials/migrating-from-another-managed-kubernetes-service-to-scaleway-kapsule/index.mdx
Fix 404s found with checker script
> chore(docs): fix 404s

- changelog/december2024/2024-12-04-functions-fixed-access-fixed-for-logs-and-metrics.mdx
> feat(changelog): functions-fixed-access-fixed-for-logs-and-metrics 2024-12-04

- changelog/december2024/2024-12-04-containers-fixed-access-fixed-for-logs-and-metrics.mdx
> feat(changelog): containers-fixed-access-fixed-for-logs-and-metrics 2024-12-04

- changelog/december2024/2024-12-05-messaging-and-queuing-changed-messaging-and-queuing-is-.mdx
> feat(changelog): messaging-and-queuing-changed-messaging-and-queuing-is- 2024-12-05

- managed-databases/mongodb/index.mdx
We recently renamed illustration of `documentDB` to `mongoDB`
Related to https://github.com/scaleway/ultraviolet/releases/tag/%40ultraviolet%2Fillustrations%404.0.0
> feat(illustrations): use new name of illustration

- containers/kubernetes/how-to/monitor-cluster.mdx
Updated the how to monitor Kubernetes cluster with Cockpit, to reflect recent Cockpit's changes - retention period and console wording.
> fix(ckpt): update kapsule monitoring doc with new cockpit data retention

- ai-data/generative-apis/reference-content/supported-models.mdx
> fix(ai): model string

- bare-metal/apple-silicon/how-to/access-remote-desktop-mac-mini.mdx
- bare-metal/apple-silicon/quickstart.mdx
- bare-metal/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
> feat(aps): add port information for vnc connections

- ai-data/generative-apis/api-cli/using-chat-api.mdx
- ai-data/generative-apis/api-cli/using-embeddings-api.mdx
- compute/gpu/how-to/create-manage-gpu-instance.mdx
- compute/gpu/quickstart.mdx
- compute/instances/how-to/create-a-block-volume.mdx
- compute/instances/quickstart.mdx
- identity-and-access-management/iam/reference-content/users-groups-and-applications.mdx
> docs(gen): fixed typos

- console/account/how-to/download-scaleway-contracts.mdx
- menu/navigation.json
Types of Scaleway contracts + how to download them
Definitions provided by Legal team
> feat(acc): docs on contracts

- console/account/reference-content/products-availability.mdx
remove PAR3 from public gateway availability
> fix(console) remove PAR3 from public gateway availability

- dedibox/dedicated-servers/how-to/terminate-dedibox-server.mdx
> feat(dedibox): fix metadata category

- dedibox-console/account/how-to/create-a-dedibox-account.mdx
Adding information about mandatory payment method to be able to order
> feat(dedibox-console): additional information

- menu/navigation.json
> fix(menu): fix

- .github/workflows/link-check-schedule.yml
- ai-data/managed-inference/reference-content/llama-3.3-70b-instruct.mdx
> fix(gen): update schedule for linkcheck

- components/docs-editor.mdx
Put back navigation component in docs-editor
> docs(editor-components): add navigation component

- faq/dedibox.mdx
- faq/elastic-metal.mdx
> fix(bm): update windows pricing

- bare-metal/elastic-metal/troubleshooting/reset-admin-password-windows-server.mdx
- compute/instances/how-to/use-boot-modes.mdx
Fixed small typos for "rescue"
> docs(fix): fixed typo rescue

- ai-data/managed-inference/reference-content/mistral-7b-instruct-v0.3.mdx
- bare-metal/dedibox/reference-content/dedibox-datasheet.mdx
- bare-metal/elastic-metal/api-cli/elastic-metal-with-api.mdx
- bare-metal/elastic-metal/api-cli/elastic-metal-with-cli.mdx
- bare-metal/elastic-metal/how-to/activate-remote-access.mdx
- bare-metal/elastic-metal/how-to/get-use-loyalty-reward.mdx
- bare-metal/elastic-metal/how-to/shutdown-server.mdx
- bare-metal/elastic-metal/quickstart.mdx
- bare-metal/elastic-metal/reference-content/elastic-metal-datasheet.mdx
- bare-metal/elastic-metal/troubleshooting/replace-failed-drive-software-raid.mdx
- bare-metal/elastic-metal/troubleshooting/reset-admin-password-windows-server.mdx
- compute/gpu/troubleshooting/fix-driver-issues.mdx
- compute/instances/api-cli/attaching-a-volume.mdx
- compute/instances/api-cli/creating-a-volume.mdx
- compute/instances/api-cli/creating-backups.mdx
- compute/instances/api-cli/detaching-a-volume.mdx
- compute/instances/api-cli/using-cloud-init.mdx
- compute/instances/api-cli/using-routed-ips.mdx
- compute/instances/how-to/create-a-snapshot.mdx
- compute/instances/how-to/use-protected-instance.mdx
- compute/instances/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx
- compute/instances/troubleshooting/fix-cloud-init-debian12.mdx
Content review for 
- AI
- Bare Metal
- Instances
> feat(ins): compute content review 30/12/24

- bare-metal/dedibox/reference-content/dedibox-datasheet.mdx
> feat(ddx): add remaining gen 9 and 10 servers

- console/account/how-to/use-the-search-bar.mdx
- serverless/sql-databases/api-cli/import-data-to-serverless-sql-databases.mdx
- tutorials/snapshot-instances-jobs/index.mdx
> chore(gen): documentation review MTA-5404

- tutorials/easydeploy-gitlab-runner/index.mdx
- tutorials/install-openvpn/index.mdx
- tutorials/set-up-spf-dkim-for-dns-providers/index.mdx
- tutorials/waypoint-plugin-scaleway/index.mdx
> chore(tuto): tutorial content review

- changelog/january2025/2025-01-07-kubernetes-added-ip-whitelisting-for-kubernetes-kapsule.mdx
> feat(changelog): kubernetes-added-ip-whitelisting-for-kubernetes-kapsule 2025-01-07

- console/account/how-to/report-abuse.mdx
- menu/navigation.json
> fix(docs): abuse link and how to menu titles

- changelog/january2025/2025-01-08-iam-deprecated-deprecation-of-the-resellercustomerbilli.mdx
> feat(changelog): iam-deprecated-deprecation-of-the-resellercustomerbilli 2025-01-08

- ai-data/generative-apis/reference-content/supported-models.mdx
Adding llama-3.3-70b-instruct to supported models list
> fix(ai): update supported-models

- menu/navigation.json
Update SNS --> Topics and Events for TEM page in doc site menu
> fix(menu): update name

- dedibox/kvm-over-ip/how-to/supermicro.mdx
> fix(ddx): fix typo

- changelog/january2025/2025-01-09-cockpit-added-custom-retention-for-cockpits-datasources.mdx
> feat(changelog): cockpit-added-custom-retention-for-cockpits-datasources 2025-01-09

- managed-services/iot-hub/how-to/add-device.mdx
- managed-services/iot-hub/how-to/change-plan.mdx
- managed-services/iot-hub/how-to/connect-default-mqtt-network.mdx
- managed-services/iot-hub/how-to/connect-default-websocket-network.mdx
- managed-services/iot-hub/how-to/create-hub.mdx
- managed-services/iot-hub/how-to/create-route.mdx
- managed-services/iot-hub/how-to/delete-device.mdx
- managed-services/iot-hub/how-to/delete-hub.mdx
- managed-services/iot-hub/how-to/delete-route.mdx
- managed-services/iot-hub/how-to/enable-auto-provisioning.mdx
- managed-services/iot-hub/how-to/enable-disable-hub.mdx
- managed-services/iot-hub/how-to/provide-own-certificate-authority.mdx
- managed-services/iot-hub/how-to/provide-own-device-certificate.mdx
- managed-services/iot-hub/how-to/renew-device-certificate.mdx
- managed-services/iot-hub/how-to/setup-use-rest-network.mdx
- managed-services/iot-hub/how-to/setup-use-sigfox-network.mdx
- managed-services/iot-hub/how-to/simulate-event.mdx
- managed-services/iot-hub/how-to/trigger-functions-from-messages.mdx
- managed-services/iot-hub/how-to/understand-event-messages.mdx
- managed-services/iot-hub/how-to/use-mqtt-webclient.mdx
- managed-services/iot-hub/how-to/view-metrics.mdx
- managed-services/iot-hub/quickstart.mdx
- network/vpc/reference-content/vpc-migration.mdx
> fix(iot): doc review

- compute/gpu/how-to/use-mig-with-kubernetes.mdx
- compute/gpu/how-to/use-nvidia-mig-technology.mdx
- compute/gpu/how-to/use-preinstalled-env.mdx
- compute/gpu/how-to/use-scratch-storage-h100-instances.mdx
- containers/kubernetes/how-to/use-scratch-storage-h100.mdx
- managed-services/webhosting/how-to/configure-dns-webhosting.mdx
- managed-services/webhosting/how-to/migrate-webhosting-plan.mdx
- managed-services/webhosting/how-to/order-webhosting.mdx
- tutorials/manage-zigbee-devices-with-iot/index.mdx
> chore(gpu): review content

- network/load-balancer/concepts.mdx
> fix(lb): concepts (doc review)

- compute/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx
- faq/blockstorage.mdx
> feat(ins): add information for eol api

- bare-metal/apple-silicon/how-to/access-remote-desktop-mac-mini.mdx
> feat(aps): update remote access documentation

- network/load-balancer/concepts.mdx
> fix(faq): fix double : in description

- changelog/january2025/2025-01-13-containers-added-serverless-containers-console-improvem.mdx
> feat(changelog): containers-added-serverless-containers-console-improvem 2025-01-13

- changelog/january2025/2025-01-13-functions-added-serverless-functions-console-improvemen.mdx
> feat(changelog): functions-added-serverless-functions-console-improvemen 2025-01-13

- changelog/january2025/2025-01-14-jobs-fixed-cancel-queued-jobs.mdx
> feat(changelog): jobs-fixed-cancel-queued-jobs 2025-01-14

- menu/navigation.json
> fix(k8s): move file in correct section

- changelog/january2025/2025-01-13-jobs-added-serverless-jobs-console-improvements.mdx
> feat(changelog): jobs-added-serverless-jobs-console-improvements 2025-01-13

- changelog/january2025/2025-01-15-kubernetes-removed-container-storage-interface-csi-driv.mdx
> feat(changelog): kubernetes-removed-container-storage-interface-csi-driv 2025-01-15

- changelog/january2025/2025-01-16-postgresql-and-mysql-added-encryption-at-rest-general-a.mdx
> feat(changelog): postgresql-and-mysql-added-encryption-at-rest-general-a 2025-01-16

- menu/changelogs.json
> fix(changelog): fix mongodb

- bare-metal/dedibox/how-to/link-dedibox-account.mdx
> fix(ddx): fixed wrong requirements

- network/interlink/concepts.mdx
> fix(interlink): fix link

- compute/instances/reference-content/instances-bandwidth-overview.mdx
> fix(ins): fix typo in bandwidth table

- changelog/january2025/2025-01-16-mongodb-added-managed-mongodbr-in-public-beta.mdx
> fix(changelog): fixed title

- storage/object/api-cli/using-api-call-list.mdx
Reverts scaleway/docs-content#4274
> Revert "Update using-api-call-list.mdx"

- pages/environmental-footprint/additional-content/environmental-footprint-calculator-estimation.mdx
> fix(efp): fix markdown

- pages/apple-silicon/how-to/create-mac-mini.mdx
- pages/apple-silicon/index.mdx
- pages/apple-silicon/quickstart.mdx
- pages/organizations-and-projects/additional-content/organization-quotas.mdx
Added M4 offer to Apple silicon docs
> feat(aps): add m4 offer to documentation

- changelog/january2025/2025-01-22-containers-fixed-serverless-containers-test-tab-fix.mdx
> feat(changelog): containers-fixed-serverless-containers-test-tab-fix 2025-01-22

- pages/account/troubleshooting/cannot-erase-account.mdx
> fix(acc): fixed date typo

- changelog/january2025/2025-01-29-transactional-email-added-automatic-blocklist-for-bette.mdx
> feat(changelog): transactional-email-added-automatic-blocklist-for-bette 2025-01-29

- changelog/january2025/2025-01-27-apple-silicon-added-mac-mini-m4-now-available.mdx
> fix(aps): fixed typo

- changelog/january2025/2025-01-28-iam-added-iam-auto-generated-resources-are-available-fo.mdx
> fix(changelog): fix link to iam autogenerated resources

- faq/account.mdx
> feat(faq): add question signal spam

- faq/account.mdx
> feat(faq): add link to signal spam modules

- changelog/january2025/2025-01-29-transactional-email-fixed-periodic-report-duplication.mdx
> feat(changelog): transactional-email-fixed-periodic-report-duplication 2025-01-29

- changelog/january2025/2025-01-29-transactional-email-security-dkim-enhancement-stronger-.mdx
> feat(changelog): transactional-email-security-dkim-enhancement-stronger- 2025-01-29

- changelog/january2025/2025-01-29-transactional-email-security-dkim-enhancement-stronger-.mdx
> fix(tem): fix changelog

- tutorials/configure-plex-s3/index.mdx
> fix(tuto): update tutorial

- changelog/january2025/2025-01-30-environmental-footprint-added-environmental-footprint-c.mdx
> feat(changelog): environmental-footprint-added-environmental-footprint-c 2025-01-30

- tutorials/installation-uncomplicated-firewall/index.mdx
> fix(tuto): fix issue with protocol specification

- changelog/january2025/2025-01-15-kubernetes-removed-container-storage-interface-csi-driv.mdx
- pages/kubernetes/api-cli/managing-storage.mdx
> fix(k8s): fix eol date for csi v0.2

- tutorials/access-mac-mini-with-reemo/index.mdx
- tutorials/jitsi-docker/index.mdx
- tutorials/pihole-vpn/index.mdx
- tutorials/prometheus-monitoring-grafana-dashboard/index.mdx
- tutorials/traefik-v2-cert-manager/index.mdx
> chore(gen): review tutorials

- changelog/january2025/2025-01-30-environmental-footprint-added-environmental-footprint-c.mdx
> fix(changelog): env footprint fix

- changelog/january2025/2025-01-31-elastic-metal-added-new-ryzen-a610r-offer.mdx
> feat(changelog): elastic-metal-added-new-ryzen-a610r-offer 2025-01-31

- tutorials/manage-container-registry-images/index.mdx
- tutorials/use-container-registry-github-actions/index.mdx
> fix(srv): add serverless categories to tutorials MTA-5519

- pages/object-storage/api-cli/using-api-call-list.mdx
> fix(s3): uppdate using-api-call-list

- package.json
- pages/object-storage/api-cli/bucket-operations.mdx
> feat(object-storage): fix typo 22023 instead of 2023

- LICENSE.md
- README.md
- docs/DOC_PAGE_TEMPLATE.mdx
> fix(gen): update repo files

- menu/navigation.json
- pages/data-lab/troubleshooting/index.mdx
- pages/kubernetes/how-to/monitor-cluster.mdx
- pages/kubernetes/how-to/monitor-data-plane-with-cockpit.mdx
- pages/messaging/concepts.mdx
- pages/organizations-and-projects/additional-content/organization-quotas.mdx
- pages/serverless-containers/concepts.mdx
- pages/serverless-functions/how-to/create-a-function.mdx
Fixed some small issues with broken links and troubleshooting not added to navigation
> fix(gen): fixed some small issues

- menu/navigation.json
- pages/serverless-functions/how-to/package-function-dependencies-in-zip.mdx
- pages/serverless-functions/reference-content/functions-handlers.mdx
> docs(srv): update handler reference MTA-5521

- faq/edge-services.mdx
- pages/edge-services/reference-content/cname-record.mdx
- pages/edge-services/reference-content/ssl-tls-certificate.mdx
- pages/vpc/troubleshooting/private-dns-dhcp-not-working.mdx
> fix(docs): review docs

- menu/navigation.json
- pages/elastic-metal/troubleshooting/troubleshoot-access-issues.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-installation.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-remote-access-issues.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-ssh-issues.mdx
Troubleshooting guides for Elastic Metal
> feat(em): add troubleshoot guides

- faq/data-lab.mdx
> fix(dlb): update faq

- pages/index.mdx
Monthly update of doc's landing page suggested keywords to drive users to content with high volume of support tickets.
> docs(gen): suggested keywords update

- pages/components/docs-editor.mdx
Here we add display of all currently available product Icons for docs
Related to WDOC-986 request
> feat(components): add product icons in component listing

- pages/object-storage/how-to/manage-object-visibility.mdx
> fix: typo in manage-object-visibility.mdx

- pages/instances/reference-content/understanding-instance-pricing.mdx
> feat(ins): add savings plans

- pages/organizations-and-projects/additional-content/organization-quotas.mdx
> feat(em): update elastic metal quotas

- changelog/february2025/2025-02-11-key-manager-added-key-manager-is-in-general-availabilit.mdx
> feat(changelog): key-manager-added-key-manager-is-in-general-availabilit 2025-02-11

- .github/CODEOWNERS
Updated codeowners file to match new slugs
> fix(gen): update codeowners

- tutorials/easydeploy-argocd/index.mdx
- tutorials/easydeploy-gitlab-runner/index.mdx
- tutorials/easydeploy-gitlab-server/index.mdx
- tutorials/easydeploy-grafana/index.mdx
- tutorials/easydeploy-vault/index.mdx
- tutorials/enabling-encryption-in-kapsule-with-cilium/index.mdx
- tutorials/kubernetes-package-management-helm/index.mdx
> fix(gen): updated tutorials categories MTA-5601

- pages/elastic-metal/reference-content/shared-responsibility-model.mdx
> Added Dedibox GPU and Titanium Elastic Metal SLAs

- changelog/february2025/2025-02-14-generative-apis-added-new-models-preview-deepseek-r1-an.mdx
> feat(changelog): generative-apis-added-new-models-preview-deepseek-r1-an 2025-02-14

- changelog/february2025/2025-02-14-managed-inference-added-new-model-preview-deepseek-r1-d.mdx
> feat(changelog): managed-inference-added-new-model-preview-deepseek-r1-d 2025-02-14

- pages/dedibox-hardware/troubleshooting/diagnose-defective-disk.mdx
Upon request, I have added content that didn't show up on Marion Cherel's [PR](https://github.com/scaleway/docs-content/pull/4360) due to indentation issues.
> docs(dedibox-hardware): add missing content

- pages/partner-space/how-to/grant-access-to-partner-space.mdx
Removed the Guideflow from the tabs component
> fix(partners): moved guideflow

- menu/navigation.json
- pages/serverless-functions/troubleshooting/function-build-error.mdx
> fix(gen): fixed 404

- tutorials/configure-slack-alerting/index.mdx
> Fix small typo

- faq/account.mdx
- faq/billing.mdx
Added categories to Billing and Account FAQ pages to improve readability
> fix(core): added categories to faq

- tutorials/deploy-openwebui-with-generative-apis/index.mdx
> fix(tutorials): update tutorial category

- changelog/february2025/2025-02-21-transactional-email-added-new-permissions-for-email-cre.mdx
> feat(changelog): transactional-email-added-new-permissions-for-email-cre 2025-02-21

- pages/cockpit/troubleshooting/synchronize-grafana-data-sources.mdx
- Added the cause for the issue 
- Added more tags based on the support tickets
- Added more bullet points in the "Problem" section (taken from how the clients phrased the issue in their tickets)
- Added the command to synchronize data sources via the CLI
> feat(cockpit): add more info in troubleshooting

- changelog/february2025/2025-02-24-functions-fixed-functions-cron-trigger-validation-rules.mdx
> feat(changelog): functions-fixed-functions-cron-trigger-validation-rules 2025-02-24

- changelog/february2025/2025-02-24-mongodb-added-vpc-x-managed-mongodbr-integration.mdx
> feat(changelog): mongodb-added-vpc-x-managed-mongodbr-integration 2025-02-24

- changelog/february2025/2025-02-24-containers-fixed-container-cron-trigger-validation-rule.mdx
> feat(changelog): containers-fixed-container-cron-trigger-validation-rule 2025-02-24

- faq/vpc.mdx
- pages/vpc/how-to/manage-routing.mdx
- pages/vpc/reference-content/understanding-routing.mdx
Add limitation info for routing, and reorganise/expand VPC FAQ, in light of support ticket info
> fix(vpc): add limitations and faq

- pages/load-balancer/how-to/monitor-lb-cockpit.mdx
- pages/load-balancer/how-to/resize-lb.mdx
> fix(lb): doc review

- changelog/february2025/2025-02-25-kubernetes-added-data-plane-logs-in-cockpit.mdx
> feat(changelog): kubernetes-added-data-plane-logs-in-cockpit 2025-02-25

- changelog/february2025/2025-02-24-edge-services-deprecated-edge-services-v1alpha1-depreca.mdx
> feat(changelog): edge-services-deprecated-edge-services-v1alpha1-depreca 2025-02-24

- changelog/february2025/2025-02-25-kubernetes-added-data-plane-logs-in-cockpit.mdx
Fixed formatting for console use
> fix(changelog): fix changelog formatting

- changelog/february2025/2025-02-25-generative-apis-deprecated-deprecation-llama-31-70b.mdx
> feat(changelog): generative-apis-deprecated-deprecation-llama-31-70b 2025-02-25

- changelog/february2025/2025-02-26-postgresql-and-mysql-added-pg-v16-support.mdx
> feat(changelog): postgresql-and-mysql-added-pg-v16-support 2025-02-26

- changelog/february2025/2025-02-26-environmental-footprint-added-environmental-footprint-c.mdx
> feat(changelog): environmental-footprint-added-environmental-footprint-c 2025-02-26

- faq/generative-apis.mdx
> feat(genapi): add faq

- changelog/february2025/2025-02-26-containers-added-serverless-containers-new-autoscaling-.mdx
> feat(changelog): containers-added-serverless-containers-new-autoscaling- 2025-02-26

- changelog/february2025/2025-02-26-functions-fixed-function-pagination-fix.mdx
> feat(changelog): functions-fixed-function-pagination-fix 2025-02-26

- pages/object-storage/api-cli/bucket-policy.mdx
- Make clear that a value is a _default_ value
- Remove external link that adds no value
> docs(object-storage): clarification int-fix-object-storage

- faq/dedibox.mdx
Add question about IP assignment for Dedibox VPS
> feat(vps): add question to faq

- pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx
Add snippets example to configure Langchain client using Typescript.
> fix(genapi): update integrating-generative-apis-with-popular-tools

- pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx
> fix(genapi): fix small typo

- changelog/march2025/2025-03-05-generative-apis-changed-rate-limit-increase.mdx
> feat(changelog): generative-apis-changed-rate-limit-increase 2025-03-05

- pages/load-balancer/how-to/create-manage-routes.mdx
- pages/vpc/reference-content/getting-most-private-networks.mdx
> fix(network): doc review

- changelog/march2025/2025-03-05-kubernetes-deprecated-deprecation-of-kubernetes-version.mdx
> feat(changelog): kubernetes-deprecated-deprecation-of-kubernetes-version 2025-03-05

- pages/kubernetes/reference-content/version-support-policy.mdx
> fix(k8s): update version support table

- pages/secret-manager/api-cli/external-secrets.mdx
Removed tags to improve visibility on the Kubernetes doc
> docs(sem): remove tags

- menu/navigation.json
Adding new page to the navigation menu.
> fix(acc): add new page to navigation menu

- pages/generative-apis/index.mdx
Swap product logo to gernativeApi
> fix(genapi): fix product illustration

- pages/gpu/troubleshooting/index.mdx
> feat(gpu): add troubleshooting index

- pages/dedibox-hardware/troubleshooting/index.mdx
> feat(ddx): add hardware troubleshooting index

- pages/elastic-metal/troubleshooting/index.mdx
> fix(em): fix small typo

- changelog/march2025/2025-03-12-functions-added-improved-pricing-transparency.mdx
> feat(changelog): functions-added-improved-pricing-transparency 2025-03-12

- menu/navigation.json
Fixed broken link
fix: broken link in navigation.json
> fix(gen): fix broken link in navigation.json

- pages/account/reference-content/products-availability.mdx
> fix(aps): fix small typo

- pages/dedibox-network/troubleshooting/index.mdx
Fixed broken link in DDX hardware troubleshooting
> fix(ddx): fix broken link

- changelog/march2025/2025-03-17-transactional-email-added-tem-scale-plan-is-live.mdx
> feat(changelog): transactional-email-added-tem-scale-plan-is-live 2025-03-17

- pages/apple-silicon/troubleshooting/index.mdx
- pages/container-registry/troubleshooting/index.mdx
- pages/dedibox-hardware/troubleshooting/index.mdx
- pages/dedibox-network/troubleshooting/index.mdx
- pages/elastic-metal/troubleshooting/index.mdx
- pages/generative-apis/index.mdx
- pages/generative-apis/troubleshooting/index.mdx
- pages/gpu/troubleshooting/index.mdx
- pages/instances/troubleshooting/index.mdx
- pages/kubernetes/troubleshooting/index.mdx
Reduce description of troubleshooting pages to avoid text being cut off
> feat(gen): reduce description length

- docs/TROUBLESHOOTING_TEMPLATE.mdx
- pages/block-storage/troubleshooting/index.mdx
> fix(gen): revert frontmatter anchors

- menu/navigation.json
> docs(gen): change tb menu buttons to links

- menu/navigation.json
> fix(lb): remove tb pages from navigation

- pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx
Add Open WebUI to popular tools doc
> feat(genapi): add openwebui

- pages/partner-space/quickstart.mdx
Added a Guideflow to the Partner Space Quickstart page
> fix(partners): guideflow

- pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx
Add quickstart for Zed AI configuration with Generative APIs.
> feat(genapi): integrating generative apis with popular tools

- pages/components/docs-editor.mdx
Add docs-editor page content for new LinksList component on SupportHub
🛑 Wait for codebase review / merge / deploy
> feat(supporthub): links list component in docs-editor page - WDOC-1000

- pages/gpu/reference-content/understanding-nvidia-ngc.mdx
- pages/instances/reference-content/comaptibility-scw-os-images-flexible-ip.mdx
- pages/instances/reference-content/cost-optimized.mdx
- pages/managed-inference/how-to/delete-deployment.mdx
- pages/managed-inference/how-to/manage-allowed-ips.mdx
- pages/managed-inference/how-to/monitor-deployment.mdx
- pages/managed-inference/reference-content/llama-3-8b-instruct.mdx
- pages/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
- pages/managed-inference/reference-content/wizardlm-70b-v1.0.mdx
- tutorials/discourse-forum/index.mdx
- tutorials/load-testing-vegeta/index.mdx
- tutorials/wordpress-lemp-stack-ubuntu-jammy-jellyfish-22-04/index.mdx
Docs content review 2025-03-19
> docs(gen): review docs 2025-03-19

- changelog/march2025/2025-03-18-elastic-metal-added-proxmox-ve-80-available.mdx
> feat(changelog): elastic-metal-added-proxmox-ve-80-available 2025-03-18

- changelog/march2025/2025-03-20-jobs-fixed-pull-errors-fixed.mdx
> feat(changelog): jobs-fixed-pull-errors-fixed 2025-03-20

- changelog/march2025/2025-03-20-iam-added-iam-policies-with-conditions-on-rules.mdx
> feat(changelog): iam-added-iam-policies-with-conditions-on-rules 2025-03-20

- pages/vpc/faq.mdx
> fix(vpc): tidy up combined FAQ

- blocks/header.json
- add Troubleshooting page in header menu. I will let you change MR if you want to switch order
> feat(header): add troubleshooting in mobile nav

- pages/account/faq.mdx
- pages/account/troubleshooting/index.mdx
- pages/account/troubleshooting/quotas-exceeded-error-message.mdx
> fix(acc): docs update

- pages/troubleshooting/index.mdx
> fix(docs): fix 404s in TB hub

- pages/instances/reference-content/workload-optimized.mdx
> fix(ins): remove wrong info

- changelog/march2025/2025-03-24-kubernetes-added-kubernetes-version-132-is-now-availabl.mdx
> feat(changelog): kubernetes-added-kubernetes-version-132-is-now-availabl 2025-03-24

- changelog/march2025/2025-03-24-edge-services-added-new-feature.mdx
> feat(changelog): edge-services-added-new-feature 2025-03-24

- changelog/march2025/2025-03-25-instances-changed-volumes-and-snapshots-are-now-in-the-.mdx
> feat(changelog): instances-changed-volumes-and-snapshots-are-now-in-the- 2025-03-25

- pages/local-storage/how-to/attach-volume.mdx
> fix(lst): fix typo

- pages/components/docs-editor.mdx
update docs-editor
docs-editor was outdated
> feat(components): Update docs-editor.mdx

- pages/account/faq.mdx
> fix(acc): faq update

- pages/serverless-functions/reference-content/functions-runtimes.mdx
> feat(functions): update runtimes

- changelog/march2025/2025-03-25-iam-added-iam-members.mdx
> feat(changelog): iam-added-iam-members 2025-03-25

- changelog/november2024/2024-11-29-elastic-metal-added-new-titanium-and-iridium-offers.mdx
> fix(em): update links in changelog

- pages/audit-trail/faq.mdx
> docs(fix): remove beta mention

- pages/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx
- pages/generative-apis/reference-content/data-privacy.mdx
- pages/instances/faq.mdx
- pages/instances/reference-content/identify-devices.mdx
- pages/kubernetes/api-cli/changing-control-plane-offer.mdx
- pages/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
- pages/kubernetes/faq.mdx
- pages/managed-inference/reference-content/llama-3-8b-instruct.mdx
> docs(genapi): review docs content

- pages/instances/faq.mdx
> fix(ins): fix pricing typo

- docs/DOC_PAGE_TEMPLATE.mdx
> fix(gen): fix template validation dates

- changelog/march2025/2025-03-27-kubernetes-added-kubernetes-logs-in-audit-trail.mdx
> feat(changelog): kubernetes-added-kubernetes-logs-in-audit-trail 2025-03-27

- changelog/march2025/2025-03-27-console-added-notification-manager-is-now-available.mdx
> feat(changelog): console-added-notification-manager-is-now-available 2025-03-27

- changelog/march2025/2025-03-28-key-manager-added-key-manager-events-in-audit-trail.mdx
> feat(changelog): key-manager-added-key-manager-events-in-audit-trail 2025-03-28

- macros/audit-trail/secret-manager-endpoints.mdx
ADT Secret enable endpoint correction
Didn't try this endpoint, but from the description it looked incorrect.
> docs(Secrets Manager): Update endpoint as for enable action, it was the same as disable. Main branch

- changelog/march2025/2025-03-31-containers-fixed-cpu-metrics-fix-for-sandbox-v2.mdx
> feat(changelog): containers-fixed-cpu-metrics-fix-for-sandbox-v2 2025-03-31

- pages/dedibox-account/how-to/update-email.mdx
> docs(ddx): add information how to validate email address

- pages/elastic-metal/how-to/kubernetes-on-riscv.mdx
- pages/kubernetes/reference-content/using-load-balancer-annotations.mdx
- pages/managed-inference/how-to/create-deployment.mdx
- pages/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
- pages/managed-inference/reference-content/pixtral-12b-2409.mdx
- tutorials/migrate-data-rclone/index.mdx
- tutorials/nvidia-triton/index.mdx
> docs(gen): content review 2025-04-01

- README.md
This PR fix a typo in one of the links available in the README, section "Useful links", leading to a 404 page on Github. Quite a shame, indeed...
See you guys!
> fix(readme): broken link

- pages/generative-apis/reference-content/rate-limits.mdx
- pages/organizations-and-projects/additional-content/organization-quotas.mdx
Update quotas for Generative APIs, to have all rate limits in a single place.
> feat(genapi): update quotas and rate limits

- pages/serverless-containers/how-to/deploy-container.mdx
- pages/serverless-functions/how-to/create-a-function.mdx
> fix(srv): update description for HTTP to HTTPS redirection MTA-5837

- changelog/april2025/2025-04-01-messaging-and-queuing-added-undelivered-message-queue-f.mdx
> feat(changelog): messaging-and-queuing-added-undelivered-message-queue-f 2025-04-01

- menu/navigation.json
- pages/dedibox-kvm-over-ip/how-to/use-bmc.mdx
> feat(ddx): add bmc page

- tutorials/configure-nagios-monitoring/index.mdx
> docs(tuto): fix tutorial nagios

- pages/dedibox-kvm-over-ip/how-to/use-bmc.mdx
> fix(ddx): fix small typo

- pages/generative-apis/reference-content/supported-models.mdx
- pages/key-manager/api-cli/encrypt-decrypt-keys-with-streaming-aead-tink.mdx
- pages/managed-databases-for-postgresql-and-mysql/troubleshooting/index.mdx
> fix(gen): fix small typos

- menu/navigation.json
- pages/billing/additional-content/understanding-savings-plans.mdx
- pages/billing/faq.mdx
- pages/billing/how-to/purchase-savings-plan.mdx
- pages/instances/reference-content/understanding-instance-pricing.mdx
Added a guideflow + case update
> fix(bil): savings plan update

- tutorials/vaultwarden-serverless.mdx
> docs(srv): add vaultwarden x serverless tutorial MTA-5847

- menu/navigation.json
- pages/audit-trail/reference-content/resource-integration-with-adt.mdx
- pages/data-lab/concepts.mdx
- pages/data-lab/faq.mdx
- pages/data-lab/how-to/connect-to-data-lab.mdx
- pages/data-lab/how-to/create-data-lab.mdx
- pages/data-lab/how-to/index.mdx
- pages/data-lab/how-to/manage-delete-data-lab.mdx
- pages/data-lab/index.mdx
- pages/data-lab/quickstart.mdx
- pages/data-lab/troubleshooting/cannot-run-data-lab.mdx
- pages/data-lab/troubleshooting/index.mdx
- pages/faq/index.mdx
- pages/troubleshooting/index.mdx
> docs(dlb): update data lab product naming MTA-5845

- menu/navigation.json
> fix(pgw): add to menu

- changelog/april2025/2025-04-07-apple-silicon-added-introduction-of-a-new-monthly-confi.mdx
> feat(changelog): apple-silicon-added-introduction-of-a-new-monthly-confi 2025-04-07

- pages/cockpit/troubleshooting/resetting-grafana-password-via-the-api.mdx
> fix(cpt): fix broken title

- pages/object-storage/how-to/access-objects-via-https.mdx
- pages/serverless-containers/how-to/add-a-custom-domain-to-a-container.mdx
- pages/serverless-containers/reference-content/containers-concurrency.mdx
- pages/serverless-containers/reference-content/deploy-container.mdx
- pages/serverless-functions/faq.mdx
- pages/serverless-jobs/faq.mdx
- pages/serverless-jobs/reference-content/jobs-limitations.mdx
> chore(gen): content review MTA-5892

- changelog/april2025/2025-04-07-apple-silicon-added-introduction-of-a-new-monthly-confi.mdx
> fix(aps): fix monthly price for m1

- pages/cockpit/faq.mdx
Updated Cockpit's FAQ to remove deprecated questions and reflect a few changes.
> feat(ckpt): update FAQ

- pages/transactional-email/reference-content/tem-capabilities-and-limits.mdx
> docs(tem): update attachments mimetypes available

- pages/serverless-jobs/faq.mdx
- pages/serverless-jobs/how-to/reference-secret-in-job.mdx
> docs(srv): add notes on secret regionalization and jobs MTA-5912

- changelog/april2025/2025-04-10-transactional-email-added-support-for-svg-attachments.mdx
> feat(changelog): transactional-email-added-support-for-svg-attachments 2025-04-10

- changelog/april2025/2025-04-11-managed-inference-added-custom-models-deployment-availa.mdx
> feat(changelog): managed-inference-added-custom-models-deployment-availa 2025-04-11

- pages/account/how-to/recover-a-lost-password.mdx
- pages/account/how-to/use-2fa.mdx
- pages/account/troubleshooting/cannot-log-into-my-account.mdx
- pages/dedibox-account/how-to/recover-password-lost-email.mdx
> fix(ts): remove mailto link

- pages/managed-inference/how-to/import-custom-model.mdx
> feat(infr): add tip to doc

- pages/billing/faq.mdx
> fix(bil): update faq

- pages/dedibox-scaleway/how-to/activate-ipv6-block.mdx
- pages/gpu/reference-content/understanding-nvidia-nemo.mdx
- pages/instances/reference-content/add-instance-specific-ssh-keys-using-tags.mdx
- pages/instances/troubleshooting/fix-broken-vpn-when-switching-openvpn-vm-to-routed-ip.mdx
- pages/kubernetes/how-to/create-kosmos-cluster.mdx
- pages/kubernetes/reference-content/using-kapsule-autoheal-feature.mdx
> docs(gen): content review compute 2025-05-15

- pages/public-gateways/how-to/move-to-routed-ip.mdx
> fix(pgw): doc review

- changelog/april2025/2025-04-16-product-catalog-added-the-product-catalog-api-is-now-av.mdx
> feat(changelog): product-catalog-added-the-product-catalog-api-is-now-av 2025-04-16

- pages/kubernetes/how-to/access-kubernetes-dashboard.mdx
- pages/kubernetes/how-to/create-cluster.mdx
- pages/kubernetes/how-to/create-kosmos-cluster.mdx
- pages/kubernetes/how-to/delete-cluster.mdx
- pages/kubernetes/how-to/deploy-ingress-controller.mdx
- pages/kubernetes/how-to/edit-cluster.mdx
- pages/kubernetes/how-to/edit-kosmos-cluster.mdx
- pages/kubernetes/how-to/enable-easy-deploy.mdx
- pages/kubernetes/how-to/manage-allowed-ips.mdx
- pages/kubernetes/how-to/migrate-ent1-pools-to-pop2.mdx
- pages/kubernetes/how-to/upgrade-kubernetes-version.mdx
- pages/kubernetes/how-to/use-nvidia-gpu-operator.mdx
- pages/kubernetes/quickstart.mdx
> docs(k8s): add regional selector

- changelog/april2025/2025-04-23-sql-databases-changed-sql-request-size-limit-increased-.mdx
> feat(changelog): sql-databases-changed-sql-request-size-limit-increased- 2025-04-23

- changelog/april2025/2025-04-23-interlink-added-scaleway-interlink-is-now-available-in-.mdx
> feat(changelog): interlink-added-scaleway-interlink-is-now-available-in- 2025-04-23

- macros/console/create-account.mdx
- pages/billing/quickstart.mdx
Removed remaining magic code/validation code mentions
> fix(bil): remove validation code mentions

- pages/vpc/troubleshooting/vpc-pn-routing-connectivity-issues.mdx
> fix(vpc): fix limitation

- pages/iam/how-to/log-in-as-a-member.mdx
- pages/iam/how-to/manage-members.mdx
> fix(iam): dates

- pages/kubernetes/how-to/recover-space-etcd.mdx
> fix(k8s): fix broken header

- macros/iam/login-member.mdx
- pages/account/how-to/log-in-to-the-console.mdx
- pages/iam/how-to/log-in-as-a-member.mdx
Added a guideflow to the How to log in as an IAM Manager page to see if we can help guide users who are having trouble accessing their accounts as members.
> docs(iam): add guideflow to iam member login page

- pages/object-storage/faq.mdx
> fix(obj): remove asterisks in title

- changelog/may2025/2025-05-07-containers-added-request-timeout-up-to-1h.mdx
> feat(changelog): containers-added-request-timeout-up-to-1h 2025-05-07

- changelog/may2025/2025-05-07-functions-added-request-timeout-up-to-1h.mdx
> feat(changelog): functions-added-request-timeout-up-to-1h 2025-05-07

- pages/serverless-containers/reference-content/containers-limitations.mdx
- pages/serverless-functions/reference-content/functions-limitations.mdx
> docs(srv): update max request timeout MTA-6023

- changelog/may2025/2025-05-12-webhosting-removed-plesk-option-removed.mdx
> feat(changelog): webhosting-removed-plesk-option-removed 2025-05-12

- pages/serverless-containers/reference-content/containers-limitations.mdx
- pages/serverless-functions/reference-content/functions-limitations.mdx
> feat(sls): update req rate

- pages/gpu/reference-content/gpu-instances-bandwidth-overview.mdx
- pages/instances/reference-content/instances-bandwidth-overview.mdx
Updated available block bandwidth for Instances
> fix(ins): update block bandwidth

- pages/serverless-containers/faq.mdx
- pages/serverless-functions/faq.mdx
- pages/serverless-jobs/faq.mdx
> docs(srv): add link to billing alerts to serverless FAQs MTA-6018

- tutorials/deploy-openwebui-with-generative-apis/index.mdx
Increase serverless containers configuration as OpenWebUI requirements increased.
> fix(genapi): tutorial to deploy openwebui

- pages/elastic-metal/how-to/change-billing-period.mdx
- pages/serverless-functions/troubleshooting/function-clock-drift.mdx
> fix(gen): fix 404s

- pages/dedibox-scaleway/how-to/modify-server-options.mdx
> feat(ddx): add link to public bandwidth page

- pages/cockpit/reference-content/cockpit-limitations.mdx
- pages/domains-and-dns/concepts.mdx
- pages/domains-and-dns/how-to/manage-dns-records.mdx
- pages/domains-and-dns/reference-content/understanding-domains-and-dns.mdx
- pages/secret-manager/reference-content/data-encryption-with-secret-manager.mdx
> docs(review): product review

- changelog/may2025/2025-05-14-jobs-fixed-command-update-on-console.mdx
> feat(changelog): jobs-fixed-command-update-on-console 2025-05-14

- pages/managed-inference/quickstart.mdx
> docs(infr): remove beta mention

- changelog/may2025/2025-05-16-edge-services-added-waf-is-now-available-in-console.mdx
> feat(changelog): edge-services-added-waf-is-now-available-in-console 2025-05-16

- menu/navigation.json
- pages/account/reference-content/use-case-informational-website.mdx
> docs(AXP): add informational website use case MTA-5570

- changelog/may2025/2025-05-15-containers-added-new-cpu-tier-in-console.mdx
> feat(changelog): containers-added-new-cpu-tier-in-console 2025-05-15

- pages/nats/how-to/create-account.mdx
- pages/nats/how-to/create-credentials.mdx
- pages/nats/how-to/delete-account.mdx
- pages/nats/how-to/manage-credentials.mdx
- pages/nats/how-to/monitor-nats-cockpit.mdx
- pages/nats/quickstart.mdx
- pages/queues/how-to/create-credentials.mdx
- pages/queues/how-to/create-manage-queues.mdx
- pages/queues/how-to/manage-credentials.mdx
- pages/queues/how-to/monitor-queues-cockpit.mdx
- pages/queues/quickstart.mdx
- pages/topics-and-events/how-to/create-credentials.mdx
- pages/topics-and-events/how-to/create-manage-subscriptions.mdx
- pages/topics-and-events/how-to/create-manage-topics.mdx
- pages/topics-and-events/how-to/manage-credentials.mdx
- pages/topics-and-events/how-to/monitor-topics-cockpit.mdx
- pages/topics-and-events/quickstart.mdx
- tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx
Update M&Q doc for new category names.
> fix(mnq): new console category names

- pages/domains-and-dns/reference-content/understanding-dns-records.mdx
> fix(dns): reformat Domains & DNS records page

- changelog/may2025/2025-05-19-managed-inference-added-managed-inference-is-now-in-gen.mdx
> feat(changelog): managed-inference-added-managed-inference-is-now-in-gen 2025-05-19

- menu/navigation.json
> fix(nav): fix double entry in navigation

- pages/dedibox-hardware/reference-content/server-comparison-table.mdx
- pages/instances/how-to/create-image-from-snapshot.mdx
> docs(ins): content review

- pages/iot-hub/reference-content/certificate.mdx
- pages/iot-hub/reference-content/devices.mdx
- pages/iot-hub/reference-content/hubs.mdx
- pages/iot-hub/reference-content/networks.mdx
- pages/iot-hub/reference-content/overview.mdx
- pages/iot-hub/reference-content/routes.mdx
- pages/load-balancer/reference-content/sni-route-deprecation.mdx
- pages/nats/api-cli/nats-cli.mdx
> fix(docs): review

- pages/instances/how-to/use-standby-mode.mdx
> docs(ins): update standby mode documentation

- pages/managed-inference/how-to/import-custom-model.mdx
> docs(infr): add info about model import duration

- pages/kubernetes/reference-content/version-support-policy.mdx
remove old k8s versions, mentions to older CNIs and container runtimes
> chore(k8s): update version policy

- changelog/may2025/2025-05-22-apple-silicon-added-m4-m-and-m4-xl-now-available.mdx
> feat(changelog): apple-silicon-added-m4-m-and-m4-xl-now-available 2025-05-22

- changelog/may2025/2025-05-22-apple-silicon-added-m4-m-and-m4-xl-now-available.mdx
> fix(changelog): fix display bug in console

- tutorials/configure-dvc-with-object-storage/index.mdx
- tutorials/jump-desktop/index.mdx
> docs(tutorial): content review 2025-05-26

- changelog/may2025/2025-05-22-containers-added-tags-for-serverless-containers.mdx
> feat(changelog): containers-added-tags-for-serverless-containers 2025-05-22

- changelog/may2025/2025-05-22-functions-added-tags-for-serverless-functions.mdx
> feat(changelog): functions-added-tags-for-serverless-functions 2025-05-22

- changelog/may2025/2025-05-28-containers-fixed-serverless-containers-healthcheck.mdx
> feat(changelog): containers-fixed-serverless-containers-healthcheck 2025-05-28

- macros/network/lb-create-backend-2-traffic-mgnt.mdx
- pages/load-balancer/concepts.mdx
- pages/load-balancer/reference-content/configuring-backends.mdx
Add clarification for multi AZ backend servers
> fix(lb): clarify backend server rules

- pages/instances/api-cli/attaching-a-volume.mdx
> fix(ins): fix indentation

- pages/elastic-metal/quickstart.mdx
Added a console tour for Elastic Metal.
> docs(em): quickstart guideflow

- pages/apple-silicon/quickstart.mdx
Created and added a guideflow with a console overview to Apple silicon's quickstart page.
> docs(aps): console overview guideflow

- changelog/june2025/2025-06-10-iam-added-sso-for-members.mdx
> feat(changelog): iam-added-sso-for-members 2025-06-10

- changelog/june2025/2025-06-10-containers-added-logs-added-instance-details.mdx
> feat(changelog): containers-added-logs-added-instance-details 2025-06-10

- changelog/june2025/2025-06-10-mongodb-added-managed-mongodb-general-availability.mdx
> feat(changelog): mongodb-added-managed-mongodb-general-availability 2025-06-10

- tutorials/power-on-off-instances-jobs/index.mdx
- tutorials/snapshot-managed-databases/index.mdx
> docs(srv): add RDB backups using jobs MTA-6140

- pages/generative-apis/faq.mdx
> fix(faq): fix gen api formatting

- changelog/june2025/2025-06-18-data-lab-added-custom-persistent-volume-available.mdx
> feat(changelog): data-lab-added-custom-persistent-volume-available 2025-06-18

- changelog/june2025/2025-06-18-data-lab-added-cockpit-is-now-available.mdx
> feat(changelog): data-lab-added-cockpit-is-now-available 2025-06-18

- changelog/june2025/2025-06-17-managed-inference-added-new-models-support-devstral.mdx
> feat(changelog): managed-inference-added-new-models-support-devstral 2025-06-17

- pages/nats/troubleshooting/cant-delete-namespace.mdx
- pages/queues/troubleshooting/cant-delete-namespace.mdx
- pages/topics-and-events/troubleshooting/cant-delete-namespace.mdx
Added cli commands to the troubleshooting section, in order to delete phantom namespaces.
> docs(nats): add cli commands to troubleshooting int-add-nats

- pages/generative-apis/how-to/query-code-models.mdx
- pages/generative-apis/reference-content/rate-limits.mdx
- pages/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx
- pages/managed-inference/reference-content/function-calling-support.mdx
- pages/public-gateways/how-to/create-a-public-gateway.mdx
- pages/public-gateways/how-to/delete-a-public-gateway.mdx
- pages/public-gateways/how-to/use-flexible-ips.mdx
- pages/public-gateways/how-to/use-ssh-bastion.mdx
- pages/public-gateways/quickstart.mdx
- pages/public-gateways/troubleshooting/gw-limitations.mdx
> fix(doc): doc review

- changelog/june2025/2025-06-20-elastic-metal-changed-ryzen-em-a610r-nvme-new-price.mdx
> feat(changelog): elastic-metal-changed-ryzen-em-a610r-nvme-new-price 2025-06-20

- pages/index.mdx
- Updated suggested keywords for the search bar
- Updated tutorial links based on analytics data
> docs(gen): updating keywords and links of the landing page

- changelog/june2025/2025-06-24-domains-and-dns-added-be-tld-now-available.mdx
> feat(changelog): domains-and-dns-added-be-tld-now-available 2025-06-24

- pages/interlink/concepts.mdx
> fix(il): add new partner

- pages/object-storage/reference-content/supported-checksums.mdx
> docs(object): update checksums doc MTA-6196

- macros/block-storage/block-storage-volume-types.mdx
- macros/compute/instances-block-bandwidth-overview.mdx
- pages/block-storage/faq.mdx
- pages/block-storage/reference-content/advantages-migrating-to-sbs.mdx
- pages/block-storage/reference-content/differences-between-5kiops-volumes.mdx
- pages/block-storage/reference-content/instances-bandwidth-overview.mdx
> docs(BLK): add macros to reuse content MTA-6164

- changelog/july2025/2025-07-08-transactional-email-added-ipv6-support-enabled-on-smtp-.mdx
> feat(changelog): transactional-email-added-ipv6-support-enabled-on-smtp- 2025-07-08

- macros/audit-trail/account-endpoints.mdx
- macros/audit-trail/iam-endpoints.mdx
- macros/audit-trail/key-manager-endpoints.mdx
- macros/audit-trail/kubernetes-endpoints.mdx
- macros/audit-trail/secret-manager-endpoints.mdx
- pages/audit-trail/reference-content/adt-supported-endpoints.mdx
- pages/audit-trail/reference-content/resource-integration-with-adt.mdx
Same content as in this branch https://github.com/scaleway/docs-content/pull/5205 but updated with new components
> audit-trail(add): account endpoints

- pages/data-lab/quickstart.mdx
- pages/domains-and-dns/quickstart.mdx
- pages/nats/quickstart.mdx
- pages/public-gateways/quickstart.mdx
Guideflows added (console overview)
> fix(docs): added guideflows

- pages/elastic-metal/reference-content/elastic-metal-datasheet.mdx
> feat(em): add A410X-SSD availability in pl-waw-3

- changelog/july2025/2025-07-11-mongodb-added-managed-mongodb-v1-api.mdx
> feat(changelog): mongodb-added-managed-mongodb-v1-api 2025-07-11

- changelog/july2025/2025-07-11-mongodb-added-multi-user-management.mdx
> feat(changelog): mongodb-added-multi-user-management 2025-07-11

- pages/dedibox-rpn/how-to/find-rpn-gateway.mdx
- pages/partner-space/how-to/track-client-consumption.mdx
- pages/site-to-site-vpn/index.mdx
- pages/site-to-site-vpn/reference-content/index.mdx
- pages/site-to-site-vpn/reference-content/security-proposals.mdx
- pages/site-to-site-vpn/reference-content/statuses.mdx
- pages/site-to-site-vpn/reference-content/understanding-s2svpn.mdx
- pages/webhosting/faq.mdx
- pages/webhosting/how-to/manage-cpanel-webhosting.mdx
- tutorials/connect-generative-apis-sql/index.mdx
> fix(docs): fix metadata

- pages/block-storage/api-cli/increasing-volume-size.mdx
- tutorials/backup-mongodb-jobs/index.mdx
> fix(gen): remove frontmatter anchors

- pages/managed-databases-for-postgresql-and-mysql/how-to/change-volume-type.mdx
> fix(rdb): typo

- changelog/july2025/2025-07-16-partner-space-added-the-cost-manager-is-now-available-i.mdx
> feat(changelog): partner-space-added-the-cost-manager-is-now-available-i 2025-07-16

- changelog/july2025/2025-07-17-webhosting-removed-removal-of-redis-from-cpanel-platfor.mdx
Reporter: Lucas Neves Trindade
> feat(changelog): webhosting-removed-removal-of-redis-from-cpanel-platfor 2025-07-17

- pages/gpu/how-to/use-mig-with-kubernetes.mdx
- pages/gpu/how-to/use-nvidia-mig-technology.mdx
- pages/gpu/how-to/use-preinstalled-env.mdx
- pages/gpu/how-to/use-scratch-storage-h100-instances.mdx
- pages/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx
- pages/instances/how-to/send-emails-from-your-instance.mdx
- pages/kubernetes/api-cli/managing-storage.mdx
- pages/kubernetes/how-to/use-scratch-storage-h100.mdx
- tutorials/enabling-encryption-in-kapsule-with-cilium/index.mdx
- tutorials/manage-zigbee-devices-with-iot/index.mdx
- tutorials/s3cmd/index.mdx
- tutorials/waypoint-plugin-scaleway/index.mdx
> docs(ins): docs content review 2025-07-21

- pages/account/how-to/open-a-support-ticket.mdx
- pages/environmental-footprint/additional-content/environmental-footprint-integration.mdx
- pages/iam/how-to/create-group.mdx
- pages/iam/videos.mdx
- pages/managed-databases-for-postgresql-and-mysql/how-to/manage-permissions.mdx
- pages/managed-databases-for-postgresql-and-mysql/how-to/renew-tls-certificate.mdx
- pages/managed-databases-for-postgresql-and-mysql/how-to/upgrade-a-database.mdx
- pages/managed-databases-for-redis/quickstart.mdx
- pages/transactional-email/how-to/configure-bimi.mdx
- pages/transactional-email/reference-content/understanding-tem-reputation-score.mdx
Docs content review 2025-07-22
> docs(acc): docs content review 2025-07-22

- macros/serverless-jobs/automate-resources-management.mdx
- menu/navigation.json
- pages/scaleway-cli/how-to/automate-resources-management.mdx
- pages/scaleway-cli/quickstart.mdx
> docs(CLI): add how to & macro for Jobs automation MTA-6323

- changelog/july2025/2025-07-23-kubernetes-added-release-of-newer-kubernetes-patch-vers.mdx
> feat(changelog): kubernetes-added-release-of-newer-kubernetes-patch-vers 2025-07-23

- macros/serverless/cron-schedules.mdx
> fix(srv): fix indent in cron reference

- pages/apple-silicon/faq.mdx
> docs(aps): update faq

- changelog/july2025/2025-07-29-generative-apis-added-new-model-support-devstral-small.mdx
> feat(changelog): generative-apis-added-new-model-support-devstral-small 2025-07-29

- pages/object-storage/api-cli/managing-lifecycle-cliv2.mdx
> fix(obj): harmonize tabs labels

- changelog/august2025/2025-08-05-generative-apis-added-new-supported-model-qwen3-235b.mdx
> feat(changelog): generative-apis-added-new-supported-model-qwen3-235b 2025-08-05

- changelog/july2025/2025-07-24-key-manager-added-scheduled-deletion-of-key-manager-key.mdx
> feat(changelog): key-manager-added-scheduled-deletion-of-key-manager-key 2025-07-24

- changelog/august2025/2025-08-08-cockpit-added-cockpit-dashboard-for-managed-mongodb.mdx
> feat(changelog): cockpit-added-cockpit-dashboard-for-managed-mongodb 2025-08-08

- changelog/august2025/2025-08-08-mongodb-added-cockpit-dashboard-for-managed-mongodb.mdx
> feat(changelog): mongodb-added-cockpit-dashboard-for-managed-mongodb 2025-08-08

- changelog/august2025/2025-08-08-mongodb-added-multi-user-management-via-console.mdx
> feat(changelog): mongodb-added-multi-user-management-via-console 2025-08-08

- pages/dedibox-vps/faq.mdx
- pages/opensearch/faq.mdx
> fix(opensearch): product icon

- changelog/august2025/2025-08-11-jobs-added-serverless-network-metrics-are-evolving.mdx
> feat(changelog): jobs-added-serverless-network-metrics-are-evolving 2025-08-11

- changelog/august2025/2025-08-11-gpu-instances-changed-gpu-h100-sxm-instances-with-2-and.mdx
> feat(changelog): gpu-instances-changed-gpu-h100-sxm-instances-with-2-and 2025-08-11

- pages/dedibox-hardware/troubleshooting/diagnose-defective-disk.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-access-issues.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-installation.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-remote-access-issues.mdx
- pages/elastic-metal/troubleshooting/troubleshoot-ssh-issues.mdx
- pages/instances/how-to/enable-openssh-windows.mdx
- pages/instances/troubleshooting/fix-error-message-in-scw-fetch-ssh-keys.mdx
> docs(em): docs content review 2025-08-11

- pages/serverless-containers/faq.mdx
- pages/serverless-functions/faq.mdx
> chore(serverless): faq consistency

- pages/dedibox/faq.mdx
> docs(ddx): update faq commitment plan

- changelog/august2025/2025-08-28-functions-added-custom-domains-now-supports-websockets.mdx
> feat(changelog): functions-added-custom-domains-now-supports-websockets 2025-08-28

- changelog/august2025/2025-08-28-functions-added-custom-domains-now-supports-websockets.mdx
> fix(changelog): title

- menu/navigation.json
- pages/serverless-containers/reference-content/migrate-to-serverless-containers.mdx
> docs(srv): add migration guide for serverless containers MTA-6412

- changelog/september2025/2025-09-01-key-manager-changed-key-manager-is-now-in-general-avail.mdx
> feat(changelog): key-manager-changed-key-manager-is-now-in-general-avail 2025-09-01

- pages/key-manager/concepts.mdx
- pages/key-manager/reference-content/cryptographic-details-key-manager.mdx
- pages/secret-manager/concepts.mdx
Added triangle project for Key Manager and Secret Manager
> fix(gen): triangle project

- pages/managed-inference/reference-content/supported-models.mdx
> feat(managed-inf): update bring your own model documentation

- changelog/september2025/2025-09-23-iam-added-organization-aliases-and-dedicated-url-for-me.mdx
> feat(changelog): iam-added-organization-aliases-and-dedicated-url-for-me 2025-09-23

- changelog/september2025/2025-09-25-audit-trail-added-load-balancers-events-available-in-au.mdx
> feat(changelog): audit-trail-added-load-balancers-events-available-in-au 2025-09-25

- pages/kubernetes/how-to/monitor-data-plane-with-cockpit.mdx
> fix(typo): small typo in monitor data plane with cockpit

- changelog/september2025/2025-09-26-domains-and-dns-added-ai-now-available.mdx
> feat(changelog): domains-and-dns-added-ai-now-available 2025-09-26

- changelog/september2025/2025-09-30-environmental-footprint-added-access-raw-data-on-your-e.mdx
> feat(changelog): environmental-footprint-added-access-raw-data-on-your-e 2025-09-30

- changelog/october2025/2025-10-02-interlink-changed-scaleway-interlink-is-now-in-general-.mdx
> feat(changelog): interlink-changed-scaleway-interlink-is-now-in-general- 2025-10-02

- pages/elastic-metal/how-to/configure-disk-partitions.mdx
- pages/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx
- pages/instances/how-to/create-a-backup.mdx
- pages/instances/how-to/manage-storage.mdx
- pages/instances/reference-content/identify-devices.mdx
- pages/kubernetes/api-cli/changing-control-plane-offer.mdx
- pages/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
- pages/kubernetes/faq.mdx
> docs(ins): docs content review

- pages/elastic-metal/reference-content/elastic-metal-datasheet.mdx
- Add Electrical Reboot is available or not per offer.
- Add Hotswap is available or not per offer.
> feat(elastic-metal): datasheet add electrical reboot and hotswap per offer - ext-metal-scaleway-datasheet

- pages/instances/reference-content/instances-datasheet.mdx
> fix(ins): remove outdated information

- changelog/october2025/2025-10-07-transactional-email-fixed-dns-autoconfig-now-supports-d.mdx
> feat(changelog): transactional-email-fixed-dns-autoconfig-now-supports-d 2025-10-07
