network/load-balancer/how-to/use-with-private-network.mdx

Explain DHCP can be home-made or provided by a Public Gateway
Fix minor typo

fix(lb): detail DHCP usage

---

console/my-account/concepts.mdx
console/my-project/concepts.mdx

fix(my-project): editor roles

---

compute/functions/how-to/upload-using-serverless-framework.mdx

In serverless v3 format, some parts of the YAML file are changed : https://www.serverless.com/framework/docs/deprecations/

fix(functions): Fix serverless v3 deprecations

---

.husky/pre-commit
README.md
docs/CONTRIBUTING.md

Some users do not run `yarn` before push 🤦 
- Install procedure mention with link in README 
- Install prerequisite and minimal steps in CONTRIBUTING
- Remove `yarn` on husky pre-commit 
Note `yarn` is mentioned multiple times!

docs(readme): add prerequisite and yarn procedure

---

storage/object/api-cli/object-storage-aws-cli.mdx

fix(s3): edit endpoint plugin config

---

tutorials/setup-nginx-reverse-proxy-s3/index.mdx

fix(setup-nginx-reverse-proxy-s3): typo

---

storage/database/concepts.mdx
storage/database/how-to/create-a-database.mdx
storage/database/how-to/delete-a-database.mdx
storage/database/quickstart.mdx

fix: rdb typos

---

faq/objectstorage.mdx

Replace date by data

---

faq/serverless-functions.mdx

fix(functions-faq) - price typo

---

tutorials/setup-minecraft/index.mdx

Running into a screen error if not taken care of taking ownership of the shell : 
Cannot open your terminal '/dev/pts/0' - please check.

ext-add-tutorials

---

dedibox-console/my-account/how-to/accept-outsourcing.mdx
dedibox-console/my-account/how-to/resolve-abuse.mdx
dedibox-console/my-account/how-to/upload-an-ssh-key.mdx
dedibox-network/rpn/how-to/configure-jumboframes.mdx
dedibox-network/rpn/how-to/configure-rpnv2.mdx
menu/navigation.json
webhosting/classic/how-to/check-emails.mdx
webhosting/classic/how-to/configure-backup-option.mdx
webhosting/classic/how-to/configure-htaccess-file.mdx
webhosting/classic/how-to/configure-php.mdx
webhosting/classic/how-to/create-ftp-account.mdx
webhosting/classic/how-to/create-mysql-database.mdx
webhosting/classic/how-to/delete-subdomain.mdx
webhosting/classic/how-to/manage-email-filter.mdx
webhosting/classic/how-to/retrieve-headers-of-email.mdx
webhosting/classic/how-to/solve-email-account-connection-problems.mdx

As well as capitalisation, added some pages that were missing from side menu/nav and corrected other minor errors.

fix(docs): nav majuscules & other for dedicated servers MTA-1563

---

storage/object/api-cli/lifecycle-rules-api.mdx
tutorials/veeam-backup-replication-s3/index.mdx

Added info to lifecycle rules page and veeam tuto

fix(s3): add info MTA-1601 and MTA-1603 

---

menu/navigation.json

fix(navigation): instance slug

---

tutorials/run-python-flask-server-on-serverless-container/index.mdx

Need to fix python version to  python:3.9-alpine as later version has issues with Flasks
current version returns :
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

Update Dockerfile example

---

storage/object/api-cli/object-storage-aws-cli.mdx

I changed the sentence to clarify that we want to connect to Scaleway Object Storage, not the one from AWS.

Change sentence for better understanding.

---

webhosting/classic/how-to/create-postgresql-database.mdx

I propose the change PostGreSQL to PostgreSQL because the project named as PostgreSQL and community is very strict about it.

Changed PostGreSQL to PostgreSQL

---

compute/instances/api-cli/creating-managing-instances-with-cliv2.mdx

https://scaleway.slack.com/archives/C969L9C5U/p1644947987881969

fix(instances): fixed error in cli doc MTA-1767

---

compute/containers/how-to/deploy-a-container.mdx
compute/containers/how-to/manage-a-container.mdx
compute/containers/quickstart.mdx

The addition of Custom port implies change over several page. 
This is a proposition for 3 pages updates

docs(howto): Serverless Containers custom port

---

compute/containers/reference-content/containers-limitations.mdx

A recent support investigation has highlights ports that are forbidden to use with the custom port feature.

fix(serverless-containers): update blocked port

---

tutorials/install-pgbouncer/index.mdx

I wrote a tutorial about installing PgBouncer. I tried to follow the contributing guideline as I can. :)

docs(tutorials): install PgBouncer on Ubuntu/Debian ext-add-tutorials

---

tutorials/s3cmd/index.mdx

Removed trailing E (s/ACCESS_KEYE/ACCESS_KEY/).

small typo correction

---

compute/instances/concepts.mdx
compute/instances/how-to/create-an-instance.mdx
compute/instances/how-to/use-boot-modes.mdx
compute/instances/how-to/use-enterprise-instances.mdx
faq/instances.mdx
macros/storage/boot-on-block.mdx
storage/block/concepts.mdx

Added the notion of boot on block in existing Instance documentation

feat(block): boot on block MTA-1825

---

network/vpc/how-to/use-ssh-bastion.mdx

Added missing user into the ssh connection command line

Missing user on ssh command

---

compute/containers/how-to/add-a-custom-domain-to-a-container.mdx
compute/functions/how-to/add-a-custom-domain-name-to-a-function.mdx

Add warning that web sockets aren't yet supported on custom domains

doc(Serverless): custom domain web socket

---

menu/navigation.json
storage/object/api-cli/bucket-operations.mdx
storage/object/api-cli/bucket-policy.mdx
storage/object/api-cli/using-bucket-policies.mdx
tutorials/backup-dedicated-server-s3-duplicity/index.mdx
tutorials/restic-s3-backup/index.mdx

In this PR:
- new restic+S3 tutorial
- edits to bucket policy pages and menu

feat(tutorial): restic backups using S3 - MTA-1203

---

compute/instances/how-to/use-enterprise-instances.mdx

Enterprise instances are now available on PAR-1 and AMS-1 - let's be generic
Let's remove the restrictions on the OS images and InstantApps

feat(instances): update Enterprise instances documentation

---

menu/navigation.json
storage/object/api-cli/using-api-call-list.mdx

In this PR, I:
- changes the metadata title of the page
- added CORS rules to the menu

fix(s3): edit title

---

compute/containers/reference-content/containers-limitations.mdx

This PR aims to update the limitations for containers.
**Added**
Maximum RAM (Organization)
Secret Environment Variables (Container + Namespace)
Secret Environment Variables (Secret Environment Variable)
**Changed**
Namespaces (Project)
Containers (Namespace)
Containers (Organization)
Temporary disk size (Container): MB to Mi

feat(containers): update limitations

---

.github/ISSUE_TEMPLATE/doc_request.yaml

docs(issuetemplate): add info on issue template mta-1903

---

faq/database.mdx

docs(faq): database MTA-1928

---

console/my-account/how-to/open-a-support-ticket.mdx
faq/general.mdx

Added a message box and a FAQ question to make it clearer how users can regain access to their accounts.

fix(console): add mentions how to regain access MTA-1937

---

contribute.mdx

Removed CTA from contribute page

docs(fix): remove cta on contribute page

---

faq/coldstorage.mdx
faq/new-object-storage-classes.mdx
storage/object/api-cli/lifecycle-rules-api.mdx
storage/object/api-cli/migrating-buckets.mdx
tutorials/backup-dedicated-server-s3-duplicity/index.mdx
tutorials/migrate-data-rclone/index.mdx

Changed all mentions of C14 Cold Storage to Scaleway Glacier

fix(s3): glacier MTA-1938

---

compute/containers/how-to/add-a-custom-domain-to-a-container.mdx

Add details on supported CName
Add details on CName support

doc(serverless): add info on CName Flattening

---

compute/instances/concepts.mdx
compute/instances/how-to/create-an-instance.mdx
network/vpc/concepts.mdx
storage/block/api-cli/increasing-volume-size.mdx

Added missing nl-ams-2 and fr-par-3 to certain pages.

fix(az): update

---

faq/general.mdx

Added a link to the pricing page in the general faq

docs(faq): add link to pricing page MTA-1951

---

console/my-account/reference-content/account-quotas.mdx

fix(quotas): add new

---

ai/smart-labeling/how-to/access-annotation-server.mdx
ai/smart-labeling/how-to/create-labeling-workspace.mdx
ai/smart-labeling/how-to/delete-labeling-workspace.mdx
ai/smart-labeling/quickstart.mdx
compute/apple-silicon/how-to/connect-to-mac-mini-m1.mdx
compute/apple-silicon/how-to/reboot-mac-mini-m1.mdx
compute/apple-silicon/how-to/reinstall-mac-mini-m1.mdx
compute/apple-silicon/quickstart.mdx
dedibox/hardware/troubleshooting/diagnose-defective-disk.mdx
storage/object/api-cli/migrating-buckets.mdx

docs(chore): review content MTA-1692

---

compute/apple-silicon/concepts.mdx
faq/apple-silicon-m1-as-a-service.mdx
tutorials/object-storage-s3fs/index.mdx

Removed the mention of macOS Big Sur from the docs

docs(fix): remove big sur naming from docs MTA-1970

---

compute/instances/api-cli/creating-managing-instances-with-cliv2.mdx
compute/instances/how-to/use-private-networks.mdx
network/dns-cloud/concepts.mdx
network/vpc/concepts.mdx
storage/block/how-to/detach-a-volume.mdx
storage/database/how-to/add-users.mdx
storage/database/how-to/configure-advanced-settings.mdx
storage/database/how-to/connect-database-private-network.mdx
storage/database/how-to/delete-a-database.mdx
storage/database/how-to/enable-autobackup.mdx
storage/database/how-to/manage-allowed-ip-addresses.mdx
storage/database/how-to/manage-manual-backups.mdx
storage/database/how-to/manage-permissions.mdx
storage/database/how-to/manage-snapshots.mdx
storage/object/api-cli/managing-lifecycle-cliv2.mdx
storage/object/how-to/upload-files-into-a-bucket.mdx
storage/object/how-to/use-bucket-website.mdx
tutorials/connect-function-postgresql-database/index.mdx
tutorials/object-storage-s3fs/index.mdx
tutorials/odoo/index.mdx

- [x ] Check that the commit messages match our requested structure.
- [ x] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).
Fix broken links (links including an anchor should not finish with a trailing slash)

fix(docs): fix broken anchor links

---

console/my-project/how-to/create-ssh-key.mdx

Correct typos on the tutorial on creating SSH keys.

docs(fix): correct typos in SSH tutorial

---

compute/kubernetes/videos.mdx

Add new k8s video to video page

feat(compute): add k8s video to video page

---

console/my-project/how-to/create-ssh-key.mdx

Clarify doc following https://github.com/scaleway/docs-content/issues/602

fix(console): clarified SSH update instructions MTA-1973

---

tutorials/lb-ingress-controller/index.mdx

Updated the tutorial to use the new easy deploy feature of kapsule

docs(fix): update tuto LB and ingress

---

dedibox-network/rpn/reference-content/private-networks-overview.mdx
faq/enterprise.mdx

Removed mention of VPC Direct Connect from the docs

docs(fix): vpc direct connect MTA-1975

---

tutorials/install-serverless-framework/index.mdx

Adds missing step to update Scaleway API credentials in serverless.com setup, and explicitly mentions `handler.py` file as place to write function code.

docs(fix): credentials step in serverless setup

---

compute/elastic-metal/how-to/enable-smtp.mdx
compute/elastic-metal/how-to/use-private-networks.mdx

Fix broken link in previous/next navigation buttons

fix(elastic-metal): fix broken link

---

compute/elastic-metal/how-to/configure-flexible-ipv6.mdx

Fixed wrong product name in EM docs

docs(fix): fix typo in elastic metal docs

---

storage/database/how-to/connect-database-private-network.mdx
tutorials/configure-netbox-managed-postgresql-database/index.mdx
tutorials/deploy-nextcloud-s3/index.mdx
tutorials/installation-uncomplicated-firewall/index.mdx
tutorials/mutli-node-rocket-chat-community-private-network/index.mdx
tutorials/setup-mysql/index.mdx

Review docs and tutorials week 21/2022

docs(tutorials): review docs week 21/2022 MTA-1987

---

tutorials/get-started-deploy-kapsule/index.mdx

fix(k8s): typo link

---

compute/elastic-metal/how-to/add-virtual-mac-address.mdx
compute/elastic-metal/how-to/configure-ipv6-hypervisor.mdx
compute/elastic-metal/how-to/enable-smtp.mdx
compute/instances/api-cli/migrating-gp-to-pro.mdx
compute/instances/reference-content/preventing-outgoing-ddos.mdx
console/my-account/how-to/use-2fa.mdx
console/my-account/reference-content/account-quotas.mdx
dedibox-network/dns/how-to/add-dns-delegation.mdx
dedibox-network/domains/how-to/manage-dns-zones.mdx
dedibox-network/rpn/how-to/configure-rpnv2.mdx
faq/vpc.mdx
network/vpc/troubleshooting/gateway-services-not-working.mdx
storage/object/how-to/manage-lifecycle-rules.mdx
storage/object/how-to/upload-files-into-a-bucket.mdx
tutorials/discourse-forum/index.mdx

docs(fix): broken links MTA-1995

---

tutorials/ark-server/index.mdx
tutorials/configure-nagios-monitoring/index.mdx
tutorials/load-overflow-proxmox-and-elastic-metal/index.mdx
tutorials/load-testing-vegeta/index.mdx
tutorials/manage-k8s-logging-loki/index.mdx
tutorials/migrate-mysql-databases-postgresql-pgloader/index.mdx
tutorials/pihole-vpn/index.mdx

Review content tutorials week 22/2022

docs(tutorial): review tutorials week 22

---

ai/smart-labeling/quickstart.mdx

Salut @ofranc , j'ai trouvé une typo dans votre doc et j'ai testé le process de contribution.
:)

Fix (AI) : typo in quick start

---

tutorials/ruby-on-rails/index.mdx
tutorials/visualize-timeseries-data-timescaledb-grafana/index.mdx

docs(tutorials): fix broken links MTA-2002

---

compute/functions/how-to/create-a-function.mdx
compute/functions/quickstart.mdx
compute/functions/reference-content/functions-lifecycle.mdx

update runtime informations

---

tutorials/send-sms-iot-device-twilio/index.mdx

fix(tutorial): fix broken link

---

faq/instances.mdx

fix(faq): added instance pricing MTA-2007

---

compute/functions/how-to/package-function-in-zip.mdx

docs(serverless): updated file hierarchy MTA-1993

---

compute/instances/how-to/use-boot-modes.mdx
tutorials/send-sms-iot-device-twilio/index.mdx

docs(fix): fixed broken links MTA-2002

---

compute/elastic-metal/how-to/enable-smtp.mdx
compute/instances/how-to/send-emails-from-your-instance.mdx

fix(docs): smtp docs

---

network/vpc/how-to/configure-a-public-gateway.mdx

Update SMTP port for PGW

---

components.mdx

- Numa is updating Components page for Tabs

fix: update for tabs component

---

.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/doc_bug.yaml
.github/ISSUE_TEMPLATE/doc_request.yaml

docs(template): add some details info to issue template

---

compute/instances/how-to/create-image-from-snapshot.mdx

Removed useless bullet points from docs

docs(fix): removed bulletpoints MTA-2032

---

storage/object/how-to/upload-files-into-a-bucket.mdx
tutorials/bash-christmas-tree/index.mdx
tutorials/collecting-visualizing-logs-elastic-stack/index.mdx
tutorials/configure-chef-ubuntu-xenial/index.mdx
tutorials/deploy-ubuntu-20-04-instance-scaleway-elements/index.mdx
tutorials/installation-lemp-ubuntu-bionic/index.mdx
tutorials/installation-lemp-ubuntu-focal/index.mdx
tutorials/object-storage-s3fs/index.mdx
tutorials/s3cmd/index.mdx
tutorials/setup-nginx-reverse-proxy-s3/index.mdx
tutorials/wordpress-lemp-stack/index.mdx

docs(review): review tutorials week 24 - MTA-2031

---

compute/functions/reference-content/functions-lifecycle.mdx

Add deprecated functions to the list 
Specify end of service date

update(doc): Add deprecated functions

---

compute/dedibox/concepts.mdx
compute/functions/concepts.mdx
dedibox/dedicated-servers/concepts.mdx

- [x Check that the commit messages match our requested structure.
Fix concepts H2 bugs

fix(concepts): fix h2 errors

---

menu/navigation.json

docs(feat): restrucure menu

---

console/my-account/reference-content/account-quotas.mdx

Update account quotas from new info given by Cyril

fix(console): update quotas MTA-2005

---

console/my-account/reference-content/account-quotas.mdx

Updated account quotas for PRO2 and GPU instances

docs(update): updated account quotas - MTA-2043

---

tutorials/backup-postgresql-pgbackrest-s3/index.mdx

I wrote a tutorial on how to backup PostgreSQL databases with pgBackRest toScaleway's Object Storage. In the long run, I plan to add how to take backup from replication. :)

docs(tutorials): backup PostgreSQL databases with pgBackRest to Object Storage

---

storage/block/how-to/increase-block-volume.mdx

Add missing `growpart` steps to docs

docs(fix): incrrease block storage docs MTA-2041

---

storage/block/how-to/increase-block-volume.mdx
tutorials/gitlab-instant-app/index.mdx

Some missing line breaks or closing tags

fix(mdx): syntax correction

---

network/vpc/how-to/configure-a-public-gateway.mdx

Fixed broken link in VPC Public Gateway docs

docs(fix): fixed broken link

---

dedibox/kvm-over-ip/concepts.mdx
webhosting/classic/concepts.mdx

docs(concepts): add concepts

---

.github/ISSUE_TEMPLATE/config.yaml

docs(issue): typo MTA-2050b

---

compute/instances/concepts.mdx

Add dynamic IPs to Instances conepts

fix(instances): added dynamic ip

---

compute/kubernetes/api-cli/exposing-services.mdx

Updating remaining occurrence of `nginx-ingress` to `traefik-ingress`.
Fix a remaining occurrence of `nginx-ingress` instead of `traefik-ingress` for getting LB external IP.

docs(kubernetes): fix exposing services docs

---

compute/apple-silicon/how-to/connect-to-mac-mini-m1.mdx
compute/apple-silicon/how-to/delete-mac-mini-m1.mdx
compute/apple-silicon/quickstart.mdx
compute/apple-silicon/troubleshooting/cant-send-emails.mdx
compute/apple-silicon/troubleshooting/filevault-preventing-system-boot.mdx
compute/apple-silicon/troubleshooting/need-package-manager.mdx
compute/apple-silicon/troubleshooting/need-to-update-os.mdx
compute/container-registry/how-to/connect-docker-cli.mdx
compute/container-registry/how-to/create-namespace.mdx
compute/container-registry/how-to/delete-image.mdx
compute/container-registry/how-to/delete-namespace.mdx
compute/container-registry/how-to/display-image-versions.mdx
compute/container-registry/how-to/manage-image-privacy-settings.mdx
compute/container-registry/how-to/manage-namespace-privacy-policies.mdx
compute/container-registry/how-to/pull-images.mdx
compute/container-registry/how-to/push-images.mdx
compute/container-registry/quickstart.mdx
storage/block/how-to/attach-a-volume.mdx
storage/block/how-to/create-a-volume.mdx
storage/block/how-to/delete-a-volume.mdx
storage/block/how-to/detach-a-volume.mdx
storage/block/how-to/increase-block-volume.mdx
storage/block/how-to/mount-and-use-volume.mdx
storage/block/how-to/unmount-a-volume.mdx
storage/database/how-to/delete-a-database.mdx
storage/object/api-cli/using-bucket-policies.mdx
tutorials/install-serverless-framework/index.mdx

Reviewed docs calendar week 26/2022 part 1 of 2

docs(fix): review docs week 26/2022 1/2 - MTA-2058

---

tutorials/erpnext-13/index.mdx

Update ERPnext documenation according to [bug report](https://github.com/scaleway/docs-content/issues/693).

docs(fix): updated broken erpnext docs MTA-2054

---

compute/instances/api-cli/migrating-gp-to-pro.mdx
yarn.lock

docs(add): content on migrating a GP1 Instance to a PRO2 via the CLI MTA-2052

---

storage/object/api-cli/bucket-operations.mdx
storage/object/api-cli/bucket-policy.mdx
storage/object/api-cli/bucket-website-api.mdx
storage/object/api-cli/common-operations.mdx
storage/object/api-cli/generate-aws4-auth-signature.mdx
storage/object/api-cli/import-copy.mdx
storage/object/api-cli/installing-minio-client.mdx
storage/object/api-cli/installing-rclone.mdx
storage/object/api-cli/manage-bucket-permissions-IP.mdx
storage/object/api-cli/managing-lifecycle-cliv2.mdx
storage/object/api-cli/multipart-uploads.mdx
storage/object/api-cli/object-lock.mdx
storage/object/api-cli/object-operations.mdx
storage/object/api-cli/object-storage-aws-cli.mdx
storage/object/api-cli/post-object.mdx
storage/object/api-cli/setting-cors-rules.mdx
storage/object/api-cli/share-buckets-read-only.mdx
storage/object/how-to/create-a-bucket.mdx
storage/object/how-to/delete-a-bucket.mdx
storage/object/how-to/delete-an-object.mdx
storage/object/how-to/download-files-from-a-bucket.mdx
storage/object/how-to/enable-bucket-versioning.mdx
storage/object/how-to/manage-lifecycle-rules.mdx
storage/object/how-to/manage-object-visibility.mdx
storage/object/how-to/monitor-consumption.mdx
storage/object/how-to/use-bucket-website.mdx
storage/object/how-to/use-obj-stor-with-private-networks.mdx

Docs review calendar week 27/2022

docs(review): docs review calendar week 27/2022 MTA-2068

---

compute/dedibox/how-to/configure-ipv6-dedibox.mdx
compute/dedibox/how-to/connect-to-dedibox.mdx
compute/dedibox/how-to/install-dedibox.mdx
compute/dedibox/quickstart.mdx

Fixed broken links in DDX docs

docs(fix): fix broken links dedibox MTA-2072

---

network/load-balancer/api-cli/setting-up-ssl-offloading.mdx
network/vpc/how-to/configure-a-public-gateway.mdx
network/vpc/how-to/configure-instances-public-gw.mdx
network/vpc/how-to/create-a-public-gateway.mdx
network/vpc/how-to/delete-a-public-gateway.mdx
network/vpc/how-to/use-flexible-ips.mdx
network/vpc/how-to/use-private-networks.mdx
network/vpc/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx
network/vpc/troubleshooting/gateway-services-not-working.mdx
network/vpc/troubleshooting/gw-limitations.mdx
tutorials/mastodon-community/index.mdx

docs(review): docs review calendar week 28/2022 MTA-2077

---

databases/databases-for-redis/how-to/create-a-database-for-redis.mdx
databases/databases-for-redis/how-to/scale-up-a-database-for-redis.mdx
faq/databases-for-redis.mdx

fix(redis): typos

---

menu/navigation.json
network/load-balancer/api-cli/configuring-balancing-rules.mdx
network/load-balancer/concepts.mdx
network/load-balancer/how-to/manage-frontends-and-backends.mdx
network/load-balancer/quickstart.mdx

Add balancing rules concept to LB docs

feat(loadbalancer): add balancing rules MTA-2074

---

identity-and-access-management/iam/reference-content/users-groups-and-applications.mdx

fix(core): typo

---

compute/kubernetes/how-to/enable-easy-deploy.mdx

fix Lightbox in easy deploy tutorial

docs(fix): fix Lightbox in easy deploy tutorial

---

identity-and-access-management/iam/api-cli/managing-projects.mdx

Use the right parameter to list projects.

fix(iam): fix API command to list projects

---

tutorials/get-started-deploy-kapsule/index.mdx

Fix indentation issue for k8s tuto

fix(tutorial): fix indentation

---

compute/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx

Added minimum Instance type for Kapsule clusters

docs(fix): K8s add min Instance type

---

dedibox/kvm-over-ip/concepts.mdx
dedibox/kvm-over-ip/how-to/dell-idrac6.mdx
dedibox/kvm-over-ip/how-to/dell-idrac7.mdx
dedibox/kvm-over-ip/how-to/dell-idrac8.mdx
dedibox/kvm-over-ip/how-to/dell-idrac9.mdx
dedibox/kvm-over-ip/how-to/disable-boot-errors-idrac.mdx
dedibox/kvm-over-ip/how-to/hp-ilo.mdx
dedibox/kvm-over-ip/how-to/quanta-computer.mdx
dedibox/kvm-over-ip/how-to/quantaplex.mdx
dedibox/kvm-over-ip/how-to/supermicro.mdx
tutorials/manage-k8s-logging-loki/index.mdx
tutorials/mariadb-ubuntu-bionic/index.mdx
tutorials/mastodon-community/index.mdx
tutorials/matomo-analytics/index.mdx
tutorials/migrate-data-rclone/index.mdx
tutorials/migrate-databases-instance/index.mdx
tutorials/migrate-dedibox-to-elastic-metal/index.mdx
tutorials/migrate-mysql-databases-postgresql-pgloader/index.mdx
tutorials/minikube-elastic-metal/index.mdx

docs(review) docs review 2022-08-01 MTA-2109

docs(review) docs review 2022-08-01 MTA-2109

---

compute/dedibox/how-to/configure-ipv6-dedibox.mdx
compute/dedibox/how-to/connect-to-dedibox.mdx
compute/dedibox/how-to/install-dedibox.mdx
compute/dedibox/quickstart.mdx
dedibox-network/ipv6/quickstart.mdx

docs(fix): broken links MTA-2090

---

tutorials/scaleway-slack-community/index.mdx

fix(docs): update slack community link

---

tutorials/configuring-gitlab-scaleway-elements-database/index.mdx
tutorials/gitlab-instant-app/index.mdx
tutorials/k8s-github/index.mdx

Just fixed a typo where `GitLab` was written `Gitlab`
No other changes to the articles.

fix(tutorials): typo in the word GitLab

---

compute/instances/api-cli/migrating-gp-to-pro.mdx
compute/instances/concepts.mdx
compute/instances/how-to/create-an-instance.mdx
compute/instances/quickstart.mdx

docs(feat): play2

---

console/my-account/reference-content/account-quotas.mdx
faq/instances.mdx

add pro2 and play2 instances to faq

Int add faq instances play

---

tutorials/openvpn-instant-app/index.mdx

Fix tutorial openvpn instant app

docs(tutorial): fix openvpn instantapp tuto MTA-2107

---

managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx

docs(fix): fixed broken link MTA-2117

---

console/my-account/reference-content/account-quotas.mdx

Updated quotas for PRO instances

docs(instance): refernce quota update MTA-2116

---

faq/serverless-functions.mdx

- [?] Check that the commit messages match our requested structure.
- [?] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).
Minor documentation improvement, as "million" is usually seen as capital M (you meant millon, didn't you? :wink:)
Also, lowercase 'm' can be confused by "thousands" in some languages (eg. "mil" in Spanish).

docs(faqs) Use capital 'M' instead of 'm' for million.

---

tutorials/run-python-flask-server-on-serverless-container/index.mdx

In the Flask app containers tutorial:
- fix bad indentation
- upgrade Flask dependency

fix(containers): Flask app tutorial

---

tutorials/pulumi-quickstart/index.mdx

Fixed numbered list steps in pulumi tutorial

docs(fix): numbered list steps

---

compute/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx

Explicit disabled node-type
I will change this in developer docs as well (console already disable DEV1-S provisioning).

change: explicit disabled node-type in kapsule pool

---

compute/instances/api-cli/migrating-gp-to-pro.mdx

docs(howto): fix typo

---

changelog/documentation/august2022/2022-08-09-added-cli-cheatsheet.mdx
changelog/network/march2022/2022-03-01-private-networks-added-ssh-bastion.mdx

docs(changelog): fix categories

---

menu/changelogs.json

docs(changelog): fix redis title

---

managed-databases/postgresql-and-mysql/concepts.mdx
managed-databases/redis/concepts.mdx
menu/filters.json
tutorials/back-up-postgresql-barman/index.mdx
tutorials/configure-netbox-managed-postgresql-database/index.mdx
tutorials/configuring-gitlab-scaleway-elements-database/index.mdx
tutorials/connect-function-postgresql-database/index.mdx
tutorials/deploy-hasura-engine-database-postgresql/index.mdx
tutorials/deploy-wordpress-from-application-library/index.mdx
tutorials/deploy-wordpress-managed-database-mysql8/index.mdx
tutorials/migrate-mysql-databases-postgresql-pgloader/index.mdx
tutorials/odoo-easy-deploy/index.mdx
tutorials/postgis-managed-databases/index.mdx
tutorials/upgrade-managed-postgresql-database/index.mdx

fix(db): int fix database filters

---

tutorials/backup-dedicated-server-s3-duplicity/index.mdx

Make the duplicity tutorial work with the latest version: 0.8.23

feat(s3): Upgrade duplicity to 0.8.23 in tutorials

---

tutorials/deploy-remote-desktop-ubuntu-2204/index.mdx
tutorials/deploy-saas-application/index.mdx
tutorials/deploy-ubuntu-20-04-instance-scaleway-elements/index.mdx
tutorials/deploy-ubuntu-22-04-instance/index.mdx
tutorials/deploy-umami-on-serverless-containers/index.mdx
tutorials/deploy-wordpress-from-application-library/index.mdx
tutorials/discourse-forum/index.mdx
tutorials/django-ubuntu-focal-fossa/index.mdx
tutorials/docker-instantapp/index.mdx
tutorials/encrypt-s3-data-rclone/index.mdx
tutorials/migrate-data-minio-client/index.mdx

docs(tutorials): review content 20220811 MTA-2132

---

tutorials/scaleway-slack-community/index.mdx

docs(fix): broken slack link

---

compute/containers/api-cli/restricting-access-to-a-container.mdx
compute/containers/concepts.mdx
compute/containers/how-to/modify-container-privacy.mdx
compute/functions/concepts.mdx
compute/functions/how-to/modify-function-privacy.mdx

- remove references to functions in containers pages (and vice-versa)
- make the note on container privacy more visible because users don't seem to find this info easily

Fix references to functions in containers + make the container privacy note more visible

---

tutorials/access-mac-mini-with-reemo/index.mdx
tutorials/actility-lorawan-operator/index.mdx
tutorials/add-disk-configure-datastore-esxi/index.mdx
tutorials/ansible-bionic-beaver/index.mdx
tutorials/ansible-galaxy/index.mdx
tutorials/ark-server/index.mdx
tutorials/arqbackup-pc-mac/index.mdx
tutorials/automate-tasks-using-cron/index.mdx
tutorials/back-up-postgresql-barman/index.mdx
tutorials/deploy-wordpress-managed-database-mysql8/index.mdx

docs(review): review tutorials MTA-2158

---

compute/messaging/concepts.mdx

Creation of concepts page for Messaging beta.

feat(messaging): add concepts for Messaging MTA-2127

---

network/vpc/how-to/use-ssh-bastion.mdx

Update SSH bastion documentation re: FQDN and step clarity

fix(vpc): updated ssh bastion doc MTA-2162

---

tutorials/manage-instances-with-serverless-framework/index.mdx
tutorials/manage-instances-with-terraform-and-functions/index.mdx

Tutorial Manage Instances with Terraform and Serverless Functions

docs(tutorial): serverless terraform MTA-2120

---

faq/serverless-functions.mdx

add supported runtimes in the FAQ

faq(serverless-functions): add supported runtimes

---

tutorials/gpu-super-resolution/index.mdx
tutorials/hadoop/index.mdx
tutorials/hestiacp/index.mdx
tutorials/host-gitlab-runner/index.mdx
tutorials/install-apache-ansible/index.mdx
tutorials/install-cassandra/index.mdx
tutorials/install-configure-couchdb/index.mdx
tutorials/install-docker-ubuntu-bionic/index.mdx
tutorials/install-golang-ubuntu-bionic/index.mdx
tutorials/install-ispconfig/index.mdx

docs(tutorials): review tutorials

---

tutorials/set-up-yunohost-debian/index.mdx

docs(fix): tutorial yunohost

---

compute/instances/api-cli/snapshot-import-export-feature.mdx

docs(fix): broken formatting

---

tutorials/backup-dedicated-server-s3-duplicity/index.mdx

Duplicity's website has moved to Gitlab.
I Fixed link to new URL

docs(fix): broken links

---

compute/elastic-metal/troubleshooting/index.mdx
compute/elastic-metal/troubleshooting/replace-failed-drive-software-raid.mdx
menu/navigation.json
tutorials/remove-raid-elastic-metal/index.mdx

docs(tutorial): raid on em server MTA-2108

---

tutorials/pulumi-quickstart/index.mdx

Update the Pulumi quickstart guide to the new library location of pulumiverse

docs(fix): change pulumi library to new pulumiverse!

---

components.mdx

- Add table spanning management
- (wait the spanning table PR is merged in codebase docs side)
- go to components page, table section

feat(table): table spanning management

---

compute/messaging/api-cli/connect-aws-cli.mdx
compute/messaging/api-cli/index.mdx
compute/messaging/api-cli/python-node-sqs.mdx
compute/messaging/api-cli/using-aws-cli.mdx

Add Messaging API/CLI doc for SNS/SQS

feat(messaging): add api-cli docs for sns/sqs aws cli and python/node sdks

---

compute/messaging/reference-content/index.mdx
compute/messaging/reference-content/snssqs-overview.mdx

Add Messaging Reference Doc: SQS/SNS overview

feat(messaging): add reference content - sns/sqs overview

---

compute/messaging/reference-content/nats-overview.mdx

Add NATS Overivew to Reference content

feat(messaging): add reference content - nats overview

---

tutorials/install-ispconfig/index.mdx

Fix some typo

---

changelog/serverless/july2022/2022-07-01-added-funtions-runtimes.mdx
changelog/serverless/july2022/2022-07-01-changed-functions-framework.mdx
changelog/serverless/july2022/2022-07-01-deprecated-functions-runtimes.mdx
changelog/serverless/july2022/2022-07-01-fixed-functions-header.mdx

Add serverless functions changelogs

docs(changelog): add changelog entries

---

compute/messaging/api-cli/python-node-sns.mdx
compute/messaging/api-cli/python-node-sqs.mdx

Added python & node page for SNS (to complement existing equivalent for SQS)

feat(messaging): added python & node for sns page

---

compute/functions/reference-content/functions-lifecycle.mdx

Should not be merged for now;
update runtimes list to arrays, update runtimes status, change end of service to end of support and some fixes

feat(serverless): update doc for runtimes

---

storage/object/api-cli/managing-lifecycle-cliv2.mdx
tutorials/backup-dedicated-server-s3-duplicity/index.mdx

Fix fews typo on the storage pages

fix(tutorial): fews typos

---

webhosting/classic/how-to/configure-htaccess-file.mdx
webhosting/classic/how-to/configure-php.mdx

Fix fake URLs so they don't disturb the 404 check

fix(doc): fix example urls

---

compute/messaging/quickstart.mdx
tutorials/configure-realtime-alerting-slack/index.mdx

fix(docs): fixed 404s

---

changelog/instances/september2022/2022-09-06-instances-added-play2.mdx

Instances - Added - New generation of Dev Instances (PLAY2)

feat(changelog): added play2 log

---

compute/functions/how-to/package-function-in-zip.mdx

This PR fixes a minor typo in the serverless function handler section for go.

docs(functions): typo in go handler guide ext-fix-functions

---

changelog/index.mdx

- Internal code update for Changelog page description at head meta
- in file `changelog/index.mdx`
- update `description` from `Changelog` to `Keep up to date with Scaleway’s latest products and features!`

fix(changelog): update meta description WEB-330

---

compute/messaging/concepts.mdx
compute/messaging/quickstart.mdx
tutorials/get-started-kubernetes-loadbalancer/index.mdx

- [x Check that the commit messages match our requested structure.
Add namespace explanation to quickstart, and improve concept, after internal feedback

fix(messaging): add namespace information

---

storage/object/api-cli/post-object.mdx

fix(storage): fix aws-s3-form example

---

managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx

fix(redis): update scaling and ssl certificate

---

compute/gpu/troubleshooting/index.mdx
compute/gpu/troubleshooting/updating-gpu-instance-with-cloud-init.mdx
menu/navigation.json

Add a troubleshoot section for GPU Instances

docs(gpu-instances): add troubleshoot section - MTA-2228

---

tutorials/transform-images-using-faas-and-nodejs/index.mdx

- Added:
- Full code at the end of the tutorial
- Check Typos and errors

tuto(serverless) - update tuto

---

compute/kubernetes/videos.mdx

feat(compute): added k8s vid to relevant page

---

compute/instances/api-cli/creating-managing-instances-with-cliv2.mdx

fix(how-to): updated doc MTA-2234

---

compute/instances/quickstart.mdx

docs(quickstart): fixed order of steps MTA-2231

---

changelog/instances/september2022/2022-09-19-instances-changed-play2-par1.mdx
changelog/instances/september2022/2022-09-22-instances-added-pro2.mdx

fix(changelog): fix changelogs

---

compute/messaging/api-cli/go-sns.mdx
compute/messaging/api-cli/go-sqs.mdx

feat(messaging): added go doc

---

compute/instances/api-cli/managing-instance-snapshot-via-cli.mdx
menu/navigation.json

Add documentation for managing Instance snapshots via CLIv2

docs(api-cli): managing snapshots | MTA-2180

---

faq/dedibox-to-elements.mdx

faq(ddx2elts): update content

---

iot/iot-hub/concepts.mdx

fix(iot): fixed typo in concepts title

---

compute/kubernetes/videos.mdx
tutorials/get-started-kubernetes-loadbalancer/index.mdx

New version of video, with new animation/slide slogan - have to change link

fix(k8s): update video links

---

console/my-account/concepts.mdx

We need to add this concept so it can be linked to from the Learn More about Active Sessions in the console

fix(concepts): add active session concept

---

tutorials/s3-customize-url-cname/index.mdx

Without the dot, the CNAME will correspond to a subdomain of the domain.

fix(s3): the CNAME must end with a dot

---

tutorials/k8s-github/index.mdx

Branch name on value.yaml has been rename to main insteadof master

Update branch name for value.yaml

---

console/my-account/reference-content/account-quotas.mdx

Update quotas reference page with new quota information

fix(quotas): update quota info MTA-2272

---

changelog/console/october2022/2022-10-06-new-support-plans-changed.mdx
changelog/databases/october2022/2022-10-06-redis-ga-changed.mdx
changelog/elastic-metal/october2022/2022-10-06-elastic-metal-added-windows-datacenter-images.mdx
changelog/kubernetes/october2022/2022-10-06-deploying-ingress-controller-in-kubernetes-cluster-deprecated.mdx
changelog/kubernetes/october2022/2022-10-06-kubernetes-version-1.19-removed.mdx

- [ x] Check that the commit messages match our requested structure.
- [ x] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).

docs(changelog): new changelog entries MTA-2285

---

faq/elastic-metal.mdx

Update FAQ Elastic Metal servers - adding Windows Server to EM

docs(fix): update faq elastic metal MTA-2290

---

changelog/serverless/october2022/2022-10-13-containers-added-memory-cpu.mdx
changelog/serverless/october2022/2022-10-13-functions-added-memory-cpu.mdx
changelog/serverless/october2022/2022-10-13-functions-added-private-cron.mdx
changelog/serverless/october2022/2022-10-13-functions-changed-auth-system-v2.mdx

Add Changelog entries for Serverless products 2022-10-13

changelog(serverless): add changelog entries

---

compute/instances/api-cli/creating-managing-instances-with-cliv2.mdx

docs(instances): add link to API docs

---

observability/cockpit/how-to/retrieve-grafana-credentials.mdx

docs(observability): added how to retrieve your grafana credentials MTA-2253

---

observability/cockpit/quickstart.mdx

docs(observability): quickstart

---

observability/cockpit/how-to/activate-cockpit.mdx

docs(observability): how to activate cockpit MTA-2314

---

observability/cockpit/how-to/deactivate-cockpit.mdx

docs(observability): how to deactivate cockpit

---

observability/cockpit/how-to/create-token.mdx

docs(observability): create a token

---

compute/containers/how-to/create-auth-token-from-console.mdx
compute/containers/how-to/modify-container-privacy.mdx
iot/iot-hub/how-to/trigger-functions-from-messages.mdx

docs(fix): repaired broken links MTA-2322

---

compute/instances/how-to/snapshot-import-export-feature.mdx

Fixed wrong title for snapshot import/export docs

docs(fix): changed wrong title

---

compute/instances/how-to/connect-to-instance.mdx
compute/kubernetes/how-to/connect-cluster-kubectl.mdx
console/my-account/how-to/verify-identity.mdx
console/my-project/how-to/create-ssh-key.mdx
identity-and-access-management/iam/how-to/create-api-keys.mdx

Add tags to selected how-to guides.

docs(how-to): add tags to how-to

---

tutorials/configure-realtime-alerting-slack/index.mdx
tutorials/configure-ssl-load-balancer/index.mdx
tutorials/configure-virtual-machine-esxi/index.mdx
tutorials/configure-vm-hyperv/index.mdx
tutorials/configuring-gitlab-scaleway-elements-database/index.mdx
tutorials/configuring-loadbalancer-wordpress/index.mdx
tutorials/connect-function-postgresql-database/index.mdx
tutorials/create-esxi-cluster-dedibox/index.mdx
tutorials/create-models-django/index.mdx
tutorials/create-wordpress-instances-cli/index.mdx

docs(tutorials): review tutorials MTA-2327

---

compute/messaging/api-cli/connect-aws-cli.mdx
compute/messaging/api-cli/go-sns.mdx
compute/messaging/api-cli/go-sqs.mdx
compute/messaging/api-cli/python-node-sns.mdx
compute/messaging/api-cli/python-node-sqs.mdx

Mnq is more secured and now use https by default, we need to edit api-cli and how-to to match this update

doc(mnq): add https to sqs doc

---

compute/kubernetes/api-cli/cluster-monitoring.mdx
compute/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
compute/kubernetes/api-cli/exposing-services.mdx
compute/kubernetes/api-cli/managing-storage.mdx
compute/kubernetes/api-cli/managing-tags.mdx
compute/kubernetes/api-cli/using-load-balancer-annotations.mdx
compute/kubernetes/api-cli/using-scaleway-operator.mdx
compute/kubernetes/how-to/connect-cluster-kubectl.mdx
compute/kubernetes/how-to/create-cluster.mdx
compute/kubernetes/how-to/create-kosmos-cluster.mdx
compute/kubernetes/reference-content/version-support-policy.mdx

docs(kubernetes): review k8s docs - MTA-2326

---

faq/support.mdx

fix(faq): added support plan question

---

dedibox-network/rpn/how-to/configure-rpnv1.mdx
dedibox-network/rpn/how-to/configure-rpnv2.mdx
menu/navigation.json

docs(rpn): add RPNv1 documentation - Mta-2315

---

compute/instances/concepts.mdx
faq/databases-for-postgresql-and-mysql.mdx
managed-databases/redis/concepts.mdx
network/vpc/concepts.mdx
storage/block/api-cli/increasing-volume-size.mdx

fix(docs): added pl-waw-2 az

---

compute/elastic-metal/how-to/activate-remote-access.mdx

add additional information for remote access feature on elastic metal servers

docs(em): add information for remote access

---

tutorials/veeam-backup-replication-s3/index.mdx

removed object storage limitations (outdated)

docs(tutorial): update veeam tutotrial

---

observability/cockpit/how-to/create-token.mdx
observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx

docs(obs): fixed indentation

---

observability/cockpit/index.mdx

docs(obs): added cockpit index

---

tutorials/create-openwrt-image-for-scaleway/index.mdx

- [x ] Check that the commit messages match our requested structure.
- [x ] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).
Fix typo in command ("name" instead of "ame")

docs(instances): fix typo int-fix-instances

---

changelog/observability/october2022/2022-11-03-cockpit.mdx
menu/changelogs.json

docs(changelog): added observability

---

storage/object/api-cli/using-api-call-list.mdx

Fix broken tables in Object Storage content

fix(docs): fix broken table

---

README.md

Added info to readme to avoid confusion

fix(docs): added readme content

---

faq/dns.mdx
faq/vpc.mdx

docs(faq): fix broken FAQ icons

---

compute/containers/how-to/add-a-custom-domain-to-a-container.mdx
managed-services/transactional-email/how-to/add-mx-record-to-your-domain.mdx
managed-services/transactional-email/how-to/add-spf-dkim-records-to-your-domain.mdx
network/domains-and-dns/how-to/configure-dns-zones.mdx

docs(fix): fix 404

---

changelog/databases/november2022/2022-11-10-redis-new-availability-zone.mdx
changelog/kubernetes/november2022/2022-11-03-dedicated-control-plane-offer.mdx
changelog/managed-services/november2022/2022-11-10-transactional-email.mdx
menu/changelogs.json

docs(changelog): added weekly entries

---

compute/functions/how-to/add-a-custom-domain-name-to-a-function.mdx
managed-services/transactional-email/how-to/generate-api-keys-for-api-and-smtp-sending.mdx

docs(404): fix broken links

---

tutorials/pulumi-quickstart/index.mdx

This PR changes the location of the Pulumi Scaleway community provider.

docs(fix): change pulumi community library to new location!

---

console/my-account/reference-content/account-quotas.mdx

docs(tem): added tem quotas

---

tutorials/install-kvm-elastic-metal/index.mdx
tutorials/install-mattermost/index.mdx
tutorials/install-openlitespeed-wordpress/index.mdx
tutorials/install-openvpn/index.mdx
tutorials/install-parse-server/index.mdx
tutorials/install-pgbouncer/index.mdx
tutorials/install-php-composer/index.mdx
tutorials/install-postgresql/index.mdx
tutorials/install-rkhunter/index.mdx
tutorials/install-serverless-framework/index.mdx
tutorials/install-wireguard/index.mdx

docs(tutorials): review content

---

tutorials/setup-minecraft/index.mdx

Update tutorial Minecraft to use the latest version of OpenJDK

docs(tutorial): update tuto minecraft

---

compute/instances/api-cli/migrating-gp-to-pro.mdx
compute/instances/concepts.mdx
compute/instances/how-to/use-security-groups.mdx
console/my-account/how-to/manage-billing-information.mdx
console/my-account/how-to/recover-a-lost-password.mdx
dedibox-network/dns/concepts.mdx
dedibox-network/ip-failover/concepts.mdx
dedibox-network/network/troubleshooting.mdx
dedibox/kvm-over-ip/concepts.mdx
faq/instances.mdx
faq/new-object-storage-classes.mdx
managed-databases/postgresql-and-mysql/concepts.mdx
managed-databases/redis/concepts.mdx
network/domains-and-dns/how-to/manage-dns-records.mdx
network/vpc/concepts.mdx
observability/cockpit/concepts.mdx
storage/object/concepts.mdx
storage/object/how-to/monitor-consumption.mdx
tutorials/configure-failover-proxmox/index.mdx
tutorials/configure-virtual-machine-esxi/index.mdx
tutorials/deploy-umami-on-serverless-containers/index.mdx
tutorials/ruby-on-rails/index.mdx
webhosting/classic/how-to/check-emails.mdx

Updated/added tags to the relevant pages to remove as much of the no-results tags as possible.
https://jira.infra.online.net/browse/MTA-2372

update(docs) tags added for search optimization

---

managed-databases/postgresql-and-mysql/how-to/create-a-database.mdx
managed-databases/postgresql-and-mysql/quickstart.mdx
managed-databases/redis/how-to/create-a-database-for-redis.mdx
managed-databases/redis/quickstart.mdx

docs(content): updated content MTA-2380

---

components.mdx

Related to https://github.com/scaleway/docs/pull/1581

feat(message): add iam to doc

---

managed-services/transactional-email/how-to/add-spf-dkim-records-to-your-domain.mdx
managed-services/transactional-email/how-to/configure-domain-with-transactional-email.mdx
managed-services/transactional-email/how-to/delete-tem-domain.mdx
managed-services/transactional-email/how-to/manage-email-activity.mdx
managed-services/transactional-email/quickstart.mdx
managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

docs(tem): content update MTA-2392

---

compute/functions/api-cli/fun-uploading-with-serverless-framework.mdx
compute/functions/reference-content/code-examples.mdx
compute/functions/reference-content/functions-lifecycle.mdx

Prepare for 3 new beta runtimes for serverless function.

docs(serverless): add new runtimes

---

faq/dedibox-to-elements.mdx

Update FAQs Dedibox to Elements product

docs(faq): update faqs ddx2elts

---

managed-services/transactional-email/how-to/manage-email-activity.mdx

docs(tem): added missing title in how-to

---

compute/functions/api-cli/fun-uploading-with-serverless-framework.mdx
compute/functions/how-to/package-function-in-zip.mdx

functions(doc) - Add Rust packaging

---

changelog/serverless/november2022/2022-11-01-functions-new-runtime.mdx

Changelog new Serverless Functions runtimes

docs(changelog): serverless funct runtimes

---

observability/cockpit/concepts.mdx
observability/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
observability/cockpit/quickstart.mdx

docs(obs): added information and concept MTA-2404

---

tutorials/lb-firewall-haproxy-pfsense/index.mdx

fix(tutorials): fix typo

---

changelog/databases/november2022/2022-11-18-mysqlpgsql-changed-read-replica.mdx

Updated changelog to announce GA of the Read Replica feature for PostgreSQL and MySQL

docs(changelog): read replica in ga

---

dedibox-console/my-account/concepts.mdx
dedibox-console/my-account/how-to/accept-outsourcing.mdx
dedibox-console/my-account/how-to/add-payment-method.mdx
dedibox-console/my-account/how-to/contact-support.mdx
dedibox-console/my-account/how-to/create-a-dedibox-account.mdx
dedibox-console/my-account/how-to/disable-two-factor-authentication.mdx
dedibox-console/my-account/how-to/enable-two-factor-authentication.mdx
dedibox-console/my-account/how-to/manage-data-settings.mdx
dedibox-console/my-account/how-to/outsource-dedibox.mdx
dedibox-console/my-account/how-to/outsource-ip-failover.mdx
dedibox-console/my-account/how-to/recover-password-lost-email.mdx
dedibox-console/my-account/how-to/report-incident.mdx
dedibox-console/my-account/how-to/resolve-abuse.mdx
dedibox-console/my-account/how-to/revoke-outsourcing.mdx
dedibox-console/my-account/how-to/update-email.mdx
dedibox-console/my-account/how-to/update-password.mdx
dedibox-console/my-account/how-to/upload-an-ssh-key.mdx
dedibox-console/my-account/quickstart.mdx

Updated tags and categories on all Dedibox Console pages (content optimization project).

docs(dedibox-console): updated tags and categories

---

observability/cockpit/concepts.mdx
observability/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
observability/cockpit/how-to/activate-cockpit.mdx
observability/cockpit/how-to/create-token.mdx
observability/cockpit/how-to/deactivate-cockpit.mdx
observability/cockpit/how-to/retrieve-grafana-credentials.mdx
observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx
observability/cockpit/quickstart.mdx

Updated tags and categories on all Observability  pages (content optimization project).

docs(observability): updated tags and categories

---

docs/PULL_REQUEST_TEMPLATE.md

Fix broken link in PR template, as described here https://github.com/scaleway/docs-content/pull/1017#issuecomment-1322031207

fix(docs): correct link in PR template

---

network/load-balancer/how-to/create-load-balancer.mdx

Fix for IAM test box getting into LB doc

fix(lb): remove iam box

---

managed-databases/postgresql-and-mysql/concepts.mdx
managed-databases/postgresql-and-mysql/how-to/add-users.mdx
managed-databases/postgresql-and-mysql/how-to/change-volume-type.mdx
managed-databases/postgresql-and-mysql/how-to/clone-a-database-instance.mdx
managed-databases/postgresql-and-mysql/how-to/configure-advanced-settings.mdx
managed-databases/postgresql-and-mysql/how-to/connect-database-private-network.mdx
managed-databases/postgresql-and-mysql/how-to/create-a-database.mdx
managed-databases/postgresql-and-mysql/how-to/create-read-replica.mdx
managed-databases/postgresql-and-mysql/how-to/delete-a-database.mdx
managed-databases/postgresql-and-mysql/how-to/enable-autobackup.mdx
managed-databases/postgresql-and-mysql/how-to/manage-allowed-ip-addresses.mdx
managed-databases/postgresql-and-mysql/how-to/manage-manual-backups.mdx
managed-databases/postgresql-and-mysql/how-to/manage-permissions.mdx
managed-databases/postgresql-and-mysql/how-to/manage-read-replica.mdx
managed-databases/postgresql-and-mysql/how-to/manage-snapshots.mdx
managed-databases/postgresql-and-mysql/how-to/upgrade-a-database.mdx
managed-databases/postgresql-and-mysql/quickstart.mdx
managed-databases/redis/concepts.mdx
managed-databases/redis/how-to/configure-advanced-settings-redis.mdx
managed-databases/redis/how-to/create-a-database-for-redis.mdx
managed-databases/redis/how-to/delete-a-database-for-redis.mdx
managed-databases/redis/how-to/manage-allowed-ip-addresses-redis.mdx
managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx
managed-databases/redis/quickstart.mdx

Updated tags and categories on all Managed Databases pages (content optimization project).

docs(m.databases): updated tags and categories

---

datacenters/datacenter-as-a-service/brochures.mdx

Updated tags and categories on the Datacenters page (content optimization project).

docs(datacenters): updated tags and categories

---

storage/object/how-to/restore-an-object-from-glacier.mdx

docs(object-storage): Adding how-to to restore all files from GLACIER in a bucket

---

changelog/instances/november2022/2022-11-23-instances-fixed-debian-bullseye-os-image.mdx

Add fix for Debian Bulleye OS to changelog

docs(changelog): instances - fixed debian bullseye

---

tutorials/upgrade-managed-postgresql-database/index.mdx

Update EoL message of PostgreSQL to version 10.

docs(tutorial): update PGSQL EoL date

---

console/my-account/reference-content/account-quotas.mdx

Add quota information for ENT1-XXS and XS offers

docs(reference): add quota info for ENT1 XXS - XS

---

compute/containers/reference-content/containers-limitations.mdx

Fix serverless containers documentation (about blocked ports). The blocked ports list should be the same as serverless functions (25, 465). We probably forgot to update the containers doc when we updated the functions doc :(

fix(containers): add blocked port (465)

---

console/my-account/reference-content/account-quotas.mdx

Added A315X SSD offer to quota listing

docs(quotas): add A315X SSD offer to quota listing

---

network/load-balancer/how-to/create-load-balancer.mdx
network/load-balancer/quickstart.mdx

fix(lb): add waw2

---

tutorials/deploy-clickhouse-database/index.mdx

docs(tutorials): clickhouse

---

tutorials/installation-lemp-ubuntu-focal/index.mdx
tutorials/jitsi-debian/index.mdx
tutorials/jitsi-docker/index.mdx
tutorials/lb-ingress-controller/index.mdx
tutorials/librenms-monitoring/index.mdx
tutorials/load-overflow-proxmox-and-elastic-metal/index.mdx
tutorials/load-testing-vegeta/index.mdx
tutorials/loriot-lorawan-network-server/index.mdx
tutorials/magento-ubuntu/index.mdx
tutorials/mailtrain-ubuntu-bionic/index.mdx
tutorials/manage-container-registry-images/index.mdx
tutorials/manage-database-instance-pgadmin4/index.mdx
tutorials/manage-instances-with-serverless-framework/index.mdx

docs(tutorials): review tutorials week 48/2022

---

tutorials/mongodb-ubuntu-1604/index.mdx

Fixed step issue when building

docs(fix): broken steps

---

compute/gpu/troubleshooting/fix-driver-issues.mdx
menu/navigation.json

Add troubleshooting information for `nvidia-driver` packages installed on GPU Instances

docs(gpu): add troubleshooting for nvidia-driver

---

compute/functions/api-cli/fun-uploading-with-serverless-framework.mdx
compute/functions/reference-content/code-examples.mdx

According to the other documentation and examples, this PR refreshed available examples in documentation for best practices.

feat(serverless): add headers to examples

---

identity-and-access-management/iam/videos.mdx

Fix wrong date on IAM video page.

fix(iam): fix date

---

identity-and-access-management/iam/how-to/activate-iam.mdx

fix(iam): fix typo

---

.github/ISSUE_TEMPLATE/doc_bug.yaml
.github/ISSUE_TEMPLATE/doc_request.yaml

docs(issues): updated documentation request template MTA-2457

---

compute/containers/reference-content/containers-limitations.mdx
compute/functions/reference-content/functions-limitations.mdx

docs(serverless): update serverless quotas

---

console/my-account/reference-content/account-quotas.mdx

Updated Serverless Containers quotas

docs(quotas): updated quotas containers

---

compute/kubernetes/videos.mdx

Correct wrong title for video on k8s video page

fix(compute): fix wrong title

---

compute/containers/reference-content/containers-limitations.mdx
compute/functions/reference-content/functions-limitations.mdx

Fixes a formatting error: an asterisk is shown as a bullet point on the functions and containers limitations pages.

docs(serverless): fix formatting of asterisk

---

identity-and-access-management/iam/api-cli/managing-projects.mdx
identity-and-access-management/iam/how-to/accept-invitation-to-orga.mdx
identity-and-access-management/iam/how-to/create-api-keys.mdx
identity-and-access-management/iam/how-to/create-application.mdx
identity-and-access-management/iam/how-to/create-group.mdx
identity-and-access-management/iam/how-to/create-policy.mdx
identity-and-access-management/iam/how-to/invite-user-to-orga.mdx
identity-and-access-management/iam/how-to/manage-api-keys.mdx
identity-and-access-management/iam/how-to/manage-applications.mdx
identity-and-access-management/iam/how-to/manage-groups.mdx
identity-and-access-management/iam/how-to/manage-policies.mdx
identity-and-access-management/iam/how-to/manage-users.mdx
identity-and-access-management/iam/quickstart.mdx

Review docs IAM - Docs review week 50/2022

docs(iam): update iam docs

---

compute/functions/how-to/connect-function-to-object-storage.mdx

Add note about IAM API keys to doc, as requested by user.

fix(functions): add note about IAM api keys

---

faq/databases-for-postgresql-and-mysql.mdx

Hello,
I have seen in slack community multiple times this question, so I think answer should be in FAQ. Work base on @abarbare [answer](https://scaleway-community.slack.com/archives/CJBLQUR5J/p1663254445427059?thread_ts=1663252967.000239&cid=CJBLQUR5J)
Best

docs(FAQ): question about the second node in rdb ext-add-faq_rdb

---

compute/elastic-metal/how-to/shutdown-server.mdx
compute/elastic-metal/how-to/use-commitment-fee-payback.mdx
faq/elastic-metal.mdx
menu/navigation.json

Documentation commitment fee payback

docs(elastic-metal): commitment fee payback

---

faq/databases-for-postgresql-and-mysql.mdx

Added extensions that are available for RDB PostgreSQL and were missing from the FAQ extensions list.

docs(FAQ): add missing extensions to RDB PostgreSQL extensions list

---

changelog/console/december2022/2022-12-12-dark-mode.mdx
changelog/observability/december2022/2022-12-15-grafana-cold-start.mdx
changelog/observability/december2022/2022-12-15-grafana-v2.mdx

docs(changelog): changelog 2022-12-15

---

tutorials/deploy-static-website-with-hugo-and-github-runners-to-object-storage/index.mdx

Tutorial Hugo on Object Storage with GitHub Actions

docs(tutorial): hugo with github actions

---

components.mdx
editor-components.mdx

- noindex meta for components pages
- add noindex in meta frontmatter

chore: noindex components pages WDOC-381

---

docs/CONTRIBUTING.md
tutorials/mongodb-ubuntu-1604/index.mdx

chore: remove steps WDOC-365

---

changelog/serverless/october2022/2022-10-13-containers-added-memory-cpu.mdx
compute/containers/concepts.mdx
faq/serverless-containers.mdx
styles/Vocab/Scaleway/accept.txt
tutorials/deploy-umami-on-serverless-containers/index.mdx

Serverless Containers & Functions: Renamed mCPU to mVCPU

docs(serverless): renamed mCPU to mVCPU

---

compute/instances/how-to/create-an-instance.mdx

fix(instances): fix steps bug

---

faq/elastic-metal.mdx

Update FAQ Elastic Metal Server

docs(faq): update faq elastic metal

---

compute/container-registry/how-to/pull-images.mdx
compute/container-registry/quickstart.mdx

Add rate limit information to container registry docs

docs(registry): add rate limit

---

changelog/load-balancers/december2022/2022-12-21-load-balancers-added-tls-backend.mdx
changelog/serverless/december2022/2022-12-21-containers-added-observability.mdx
changelog/serverless/december2022/2022-12-21-functions-added-observability.mdx

docs(changelog): changelog entries 2022-12-21

---

storage/object/api-cli/using-api-call-list.mdx

Hello,
Just to make life easy and click.
Merry christmas

docs(storage/api): add missing link

---

tutorials/deploy-penpot-with-docker-instantapp/index.mdx

There was a mismatch between file names within the tutorial. This updates the first mention of the file name in order to make it match the following steps.

fix(tutorials): file name

---

observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx

docs(obs): added how to push logs and metrics MTA-2473b

---

.github/workflows/changelog-contribution.yml

feat(changelog): workflow action for contribution

---

compute/functions/reference-content/functions-runtimes-configuration.mdx
menu/navigation.json

Serverless Functions runtimes configuration information MTA-2550

docs(functions): Serverless Functions runtimes configuration information MTA-2550

---

managed-services/iot-hub/reference-content/networks.mdx

docs(fix): fixed typo

---

compute/container-registry/how-to/connect-docker-cli.mdx
compute/container-registry/how-to/create-namespace.mdx
compute/container-registry/how-to/delete-image.mdx
compute/container-registry/how-to/delete-namespace.mdx
compute/container-registry/how-to/display-image-versions.mdx
compute/container-registry/how-to/manage-image-privacy-settings.mdx
compute/container-registry/how-to/manage-namespace-privacy-policies.mdx
compute/container-registry/how-to/pull-images.mdx
compute/container-registry/how-to/push-images.mdx
compute/container-registry/quickstart.mdx
compute/instances/how-to/create-an-instance.mdx
console/my-account/reference-content/account-quotas.mdx

Review docs content week 52/2022

docs(registry): review content MTA-2553

---

changelog/observability/december2022/2022-12-22-added-object-storage.mdx
changelog/serverless/december2022/2022-12-21-functions-added-php82.mdx
changelog/storage/december2022/2022-12-22-added-observability.mdx

docs(changelog): changelog 2022-12-29

---

faq/serverless-functions.mdx

feat(serverless): complete faq with runtimes and limits

---

compute/functions/api-cli/fun-uploading-with-serverless-framework.mdx
compute/functions/how-to/add-a-custom-domain-name-to-a-function.mdx
compute/functions/how-to/connect-function-to-object-storage.mdx
compute/functions/how-to/create-a-function.mdx
compute/functions/how-to/create-a-functions-namespace.mdx
compute/functions/how-to/create-auth-token-from-console.mdx
compute/functions/how-to/delete-a-function.mdx
compute/functions/how-to/delete-a-functions-namespace.mdx
compute/functions/how-to/manage-a-function.mdx
compute/functions/how-to/manage-a-functions-namespace.mdx
compute/functions/how-to/modify-function-privacy.mdx
compute/functions/how-to/package-function-in-zip.mdx
compute/functions/quickstart.mdx
compute/functions/reference-content/code-examples.mdx
compute/functions/reference-content/functions-lifecycle.mdx
compute/functions/reference-content/functions-limitations.mdx
compute/functions/reference-content/functions-runtimes-configuration.mdx

Review Serverless Functions documentation

docs(functions): review documentation

---

compute/elastic-metal/api-cli/elastic-metal-with-cli.mdx
compute/instances/api-cli/cli-cheatsheet.mdx
compute/instances/api-cli/creating-managing-instances-with-cliv2.mdx
compute/kubernetes/api-cli/cluster-monitoring.mdx
compute/kubernetes/api-cli/managing-storage.mdx
compute/messaging/reference-content/nats-overview.mdx
console/my-account/quickstart.mdx
dedibox-network/domains/how-to/transfer-domain.mdx
faq/coldstorage.mdx
faq/objectstorage.mdx
storage/object/api-cli/managing-lifecycle-cliv2.mdx
storage/object/api-cli/object-lock.mdx
tutorials/configure-realtime-alerting-slack/index.mdx
tutorials/deploy-wordpress-managed-database-mysql8/index.mdx
tutorials/installation-uncomplicated-firewall/index.mdx
tutorials/pulumi-quickstart/index.mdx
webhosting/classic/how-to/configure-php.mdx

Added the queries listed as -no results- to their relevant pages to fix doc search results.

fix(doc): tags updates no fix no results

---

managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

docs(tem): added mime attachments MTA-2563

---

compute/instances/how-to/power-off-instance.mdx

fix(how-to): fix numbering 

---

compute/messaging/reference-content/limitations.mdx

Add limitations page for messaging

fix(messaging): add limitations document

---

managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

fix(docs): improved table for mime types

---

console/my-account/reference-content/products-availability.mdx
menu/navigation.json

docs(account): availability overview

---

changelog/january2023/2023-01-06-load-balancers-added-load-balancers-now-support.mdx

feat(changelog): load-balancers-added-load-balancers-now-support 2023-01-06

---

changelog/january2023/2023-01-06-redistm-added-managed-database-for-redis™.mdx

feat(changelog): redistm-added-managed-database-for-redis™ 2023-01-06

---

changelog/january2023/2023-01-06-load-balancers-added-load-balancers-now-support.mdx
changelog/january2023/2023-01-06-redistm-added-managed-database-for-redis™.mdx

docs(changelog): fix dates

---

tutorials/transform-images-using-faas-and-nodejs/index.mdx

- change secret name to be useful
- Add env size

tutorial(serverless functions)- fix typos

---

managed-databases/redis/how-to/create-a-database-for-redis.mdx

Update the redis documentation

fix: Update redis available regions

---

observability/cockpit/how-to/retrieve-grafana-credentials.mdx
observability/cockpit/quickstart.mdx

docs(obs): added info on grafana users

---

dedibox-console/my-account/how-to/accept-outsourcing.mdx
dedibox-console/my-account/how-to/add-payment-method.mdx
dedibox-console/my-account/how-to/contact-support.mdx
dedibox-console/my-account/how-to/create-a-dedibox-account.mdx
dedibox-console/my-account/how-to/manage-data-settings.mdx
dedibox-console/my-account/how-to/outsource-dedibox.mdx
dedibox-console/my-account/how-to/outsource-ip-failover.mdx
dedibox-console/my-account/how-to/recover-password-lost-email.mdx
dedibox-console/my-account/how-to/report-incident.mdx
dedibox-console/my-account/how-to/resolve-abuse.mdx
dedibox-console/my-account/how-to/revoke-outsourcing.mdx
dedibox-console/my-account/how-to/update-email.mdx
dedibox-console/my-account/how-to/update-password.mdx
dedibox-console/my-account/how-to/upload-an-ssh-key.mdx
dedibox-console/my-account/quickstart.mdx

docs(review): review dedibox console docs

---

serverless/containers/reference-content/containers-limitations.mdx

This limitation was not present for containers, it was just a bad copy-paste from the functions limitations page.

fix(containers): remove payload size limitation

---

changelog/january2023/2023-01-18-instances-changed-ent1-range-is-extended.mdx

feat(changelog): instances-changed-ent1-range-is-extended 2023-01-18

---

changelog/january2023/2023-01-18-instances-changed-pro2-and-play2-instances.mdx

feat(changelog): instances-changed-pro2-and-play2-instances 2023-01-18

---

compute/instances/reference-content/preventing-outgoing-ddos.mdx
tutorials/create-esxi-cluster-dedibox/index.mdx

docs(fix): fixed 404

---

managed-databases/redis/how-to/manage-allowed-ip-addresses-redis.mdx

fix: Update Redis Allowed IPs documentation

---

faq/billing.mdx

docs(faq): add billing question to faq

---

tutorials/access-mac-mini-with-reemo/index.mdx

As a developer with very low experience using MacOS, the path of reemo.ini files would have saved me time while installing and configuring Reemo. About the personal key, this is the vocabulary that is used on Reemo portal, which is also confusing because Reemo uses **private key** on each one of their client applications. So, having the two words clearly defined here, helps the user to identify easily the Reemo actions.

docs(tutorials appleminireemo): add details to help new users

---

changelog/january2023/2023-01-19-transactional-email-added-tem.mdx

feat(changelog): transactional-email-added-tem 2023-01-19

---

changelog/january2023/2023-01-19-billing-added-billing-api-.mdx

feat(changelog): billing-added-billing-api- 2023-01-19

---

changelog/january2023/2023-01-19-transactional-email-changed-tem.mdx

feat(changelog): transactional-email-changed-tem 2023-01-19

---

faq/instances.mdx

Update pricing after Dec 1st, 2022 increase on the Instance FAQ page

int-fix-instances - Update pricing after Dec 1st, 2022 increase

---

serverless/containers/how-to/create-auth-token-from-console.mdx
serverless/containers/how-to/modify-container-privacy.mdx
serverless/functions/how-to/create-auth-token-from-console.mdx
serverless/functions/how-to/modify-function-privacy.mdx

The console has been updated with a new "Security" Tab

doc(serverless) - match console update

---

changelog/january2023/2023-01-19-billing-added-billing-api-.mdx
faq/support.mdx

Two edits to the support FAQ as requested by Lucas

fix(faq): edit support faq

---

menu/navigation.json
serverless/messaging/api-cli/nats-cli.mdx
serverless/messaging/reference-content/nats-overview.mdx

feat(serverless): added nats cli doc

---

serverless/messaging/api-cli/nats-cli.mdx

fix(nats): fix slashes

---

observability/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
observability/cockpit/quickstart.mdx

docs(obs): quickstart rework

---

containers/kubernetes/how-to/enable-easy-deploy.mdx
containers/kubernetes/quickstart.mdx

Updated category for K8s products in the documentation.

docs(fix): updated: k8s into Containers category

---

serverless/functions/reference-content/code-examples.mdx

fixed broken PHP code example for Serverless Functions

docs(fix): broken php code example

---

serverless/functions/reference-content/functions-lifecycle.mdx

Updated list of available runtimes for Serverless Functions

docs(functions): fix runtime listing

---

containers/container-registry/how-to/connect-docker-cli.mdx
containers/container-registry/how-to/create-namespace.mdx
containers/container-registry/how-to/delete-image.mdx
containers/container-registry/how-to/delete-namespace.mdx
containers/container-registry/how-to/display-image-versions.mdx
containers/container-registry/how-to/manage-image-privacy-settings.mdx
containers/container-registry/how-to/manage-namespace-privacy-policies.mdx
containers/container-registry/how-to/pull-images.mdx
containers/container-registry/quickstart.mdx

updated container registry product category

docs(fix): updated cont. registry product category

---

serverless/functions/api-cli/fun-uploading-with-serverless-framework.mdx

Updated the documentation to match the current system state

doc(functions): update serverless yml parameters list

---

tutorials/deploying-a-documentation-website-with-docusaurus-on-scaleway/index.mdx

docs(tutorials): docusaurus

---

tutorials/proxy-protocol-v2-load-balancer/index.mdx

Tutorial to setup the `ingress-nginx` to accept `proxy-protocol-v2` communication
Further details : https://github.com/scaleway/docs-content/issues/1231

feat(tutorial): proxy-protocol-v2 ingress-nginx configuration

---

managed-services/transactional-email/how-to/add-mx-record-to-your-domain.mdx

docs(tem): fixed error

---

storage/block/how-to/increase-block-volume.mdx

Added a message box to highlight to go to the volumes tab to increase volume size of an Instance.

docs(instance): add tip for volume increase

---

managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

docs(tem): added new mime types

---

observability/cockpit/concepts.mdx

docs(obs): add infos in concepts

---

compute/dedibox/how-to/link-dedibox-account.mdx
faq/dedibox-in-scaleway-console.mdx
faq/support.mdx

docs(dedibox): update faq

---

changelog/february2023/2023-02-01-elastic-metal-added-🇳🇱-ams-1-opening.mdx

feat(changelog): elastic-metal-added-🇳🇱-ams-1-opening 2023-02-01

---

menu/navigation.json
serverless/containers/how-to/create-auth-token-from-console.mdx
serverless/containers/how-to/delete-a-container.mdx
serverless/containers/how-to/secure-a-container.mdx
serverless/functions/how-to/create-auth-token-from-console.mdx
serverless/functions/how-to/delete-a-function.mdx
serverless/functions/how-to/secure-a-function.mdx

How to secure your function/container

docs(serverless): secure your function/container

---

containers/kubernetes/reference-content/version-support-policy.mdx

Updated K8s version information. Do not merge before go.

docs(k8s): updated version information

---

serverless/containers/how-to/deploy-a-container.mdx
serverless/containers/how-to/manage-a-container.mdx
serverless/containers/quickstart.mdx

docs(containers): add external registry - MTA-2675

---

changelog/february2023/2023-02-03-object-storage-added-improved-user-experience-for.mdx

feat(changelog): object-storage-added-improved-user-experience-for 2023-02-03

---

serverless/functions/reference-content/functions-lifecycle.mdx

Upgrade the status of Runtimes to match latest releases

feat(serverless): upgrade FaaS runtimes status

---

managed-services/transactional-email/quickstart.mdx

docs(tem): edited mx record configuration in quickstart

---

tutorials/manage-container-registry-images/index.mdx

Update tutorial manage Container Registry with Functions

docs(tutorial): update content tutorial

---

tutorials/access-mac-mini-with-reemo/index.mdx

Add screen recording access to Reemo in MacOS

int-add-m1 Add screen recording access to Reemo in MacOS

---

serverless/containers/reference-content/containers-limitations.mdx
serverless/functions/reference-content/functions-limitations.mdx

doc(serverless) add logs rate limiting

---

changelog/february2023/2023-02-07-kubernetes-added-kubernetes-versions-1.25-and.mdx

feat(changelog): kubernetes-added-kubernetes-versions-1.25-and 2023-02-07

---

changelog/february2023/2023-02-07-containers-added-deploy-containers-from-public.mdx

feat(changelog): containers-added-deploy-containers-from-public 2023-02-07

---

changelog/february2023/2023-02-07-kubernetes-changed-pro2-and-play2-instances.mdx

feat(changelog): kubernetes-changed-pro2-and-play2-instances 2023-02-07

---

changelog/february2023/2023-02-07-containers-added-deploy-containers-from-public.mdx

fix(changelog): fix typo

---

changelog/february2023/2023-02-07-kubernetes-removed-flannel-weave.mdx

docs(changelog): fix typo

---

containers/kubernetes/reference-content/version-support-policy.mdx

docs(kapsule): quick edits in version policy page

---

containers/kubernetes/videos.mdx

removed double listing of introduction to kubernetes video

docs(fix): removed doublon video

---

observability/cockpit/api-cli/configuring-grafana-agent.mdx
observability/cockpit/how-to/send-metrics-logs-to-cockpit.mdx
observability/cockpit/quickstart.mdx

docs(obs): rework observability documentation

---

faq/messaging-and-queuing.mdx
serverless/messaging/api-cli/nats-cli.mdx
serverless/messaging/reference-content/nats-overview.mdx

Add links towards Terraform for M&Q

fix(messaging): add links to terraform

---

storage/object/api-cli/post-object.mdx

The current example doesn't work:
- I changed all single quotes for double ones
- same key in `conditions` and `object_name`
- all fields present in `fields` should be copied in `conditions` otherwise it cause an error
- I also added another print at the end to show the error message in case of errors.

fix(storage): fix boto3 example for post-objet 

---

menu/navigation.json
serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx
serverless/containers/how-to/manage-a-container.mdx
serverless/containers/how-to/manage-a-containers-namespace.mdx

Now that we support external container registry, it is worth dividing the original (deploy your container) into two separate pages

Doc(Serverlss Container) Deploy From public Registry

---

console/my-project/how-to/create-ssh-key.mdx
console/my-project/quickstart.mdx
serverless/functions/reference-content/code-examples.mdx

Fix PHP formatting and some minor issues MTA-2784

docs(serverless): fix php formatting

---

identity-and-access-management/iam/reference-content/permission-sets.mdx

fixed the list of permission sets (some were not correctly labelled, some were missing, some were deleted in the meantime

fix(IAM) permission sets

---

compute/dedibox/how-to/connect-to-dedibox.mdx
compute/dedibox/quickstart.mdx
compute/elastic-metal/how-to/connect-to-server.mdx
compute/instances/concepts.mdx
compute/instances/troubleshooting/cant-connect-ssh.mdx
console/my-project/concepts.mdx
console/my-project/how-to/create-ssh-key.mdx
console/my-project/quickstart.mdx
containers/kubernetes/api-cli/exposing-services.mdx
faq/instances.mdx
identity-and-access-management/iam/concepts.mdx
identity-and-access-management/iam/quickstart.mdx
managed-services/webhosting/reference-content.mdx
tutorials/install-kvm-elastic-metal/index.mdx
tutorials/lb-ingress-controller/index.mdx
tutorials/mastodon-community/index.mdx
tutorials/postgis-managed-databases/index.mdx
tutorials/protect-server-using-crowdsec/index.mdx
tutorials/upgrade-managed-postgresql-database/index.mdx
webhosting/cpanel/reference-content.mdx

Added queries from January list of no results to improve search results.

fix(doc): added tags

---

serverless/functions/reference-content/functions-lifecycle.mdx

* Rust beta -> available
* Added Node19

feat(serverless): rust to ga and node19 beta

---

changelog/databases/february2022/2022-02-02-postgresql-and-mysql-added-block-volume.mdx
changelog/network/march2022/2022-03-01-private-networks-added-ssh-bastion.mdx
compute/dedibox/how-to/link-dedibox-account.mdx
compute/instances/how-to/use-flexips.mdx
containers/kubernetes/api-cli/cluster-monitoring.mdx
faq/databases-for-redis.mdx
faq/vpc.mdx
managed-services/iot-hub/how-to/add-device.mdx
managed-services/webhosting/how-to/configure-dns-webhosting.mdx
managed-services/webhosting/how-to/manage-webhosting.mdx
managed-services/webhosting/how-to/order-webhosting.mdx
managed-services/webhosting/how-to/terminate-webhosting.mdx
network/load-balancer/api-cli/setting-up-ssl-offloading.mdx
network/vpc/concepts.mdx
serverless/containers/how-to/add-a-custom-domain-to-a-container.mdx
serverless/containers/how-to/create-auth-token-from-console.mdx
serverless/containers/how-to/delete-a-container.mdx
serverless/containers/how-to/manage-a-container.mdx
serverless/containers/how-to/modify-container-privacy.mdx
serverless/containers/how-to/secure-a-container.mdx
storage/object/api-cli/manage-bucket-permissions-IP.mdx
storage/object/concepts.mdx
tutorials/run-python-flask-server-on-serverless-container/index.mdx
tutorials/setup-postfix-ubuntu-bionic/index.mdx
tutorials/vpc-public-gateway-autoconfiguration/index.mdx

docs(fix): fixed 404's

---

network/vpc/api-cli/vpc-private-beta.mdx

- [ X] Check that the commit messages match our requested structure.
Change into Regional VPC migration endpoints examples.

docs(vpc): correct regional PN migration endpoints MTA-2600

---

console/my-account/reference-content/products-availability.mdx

docs(fix): em product availability

---

console/my-account/reference-content/products-availability.mdx

docs(my-account): update product categories

---

tutorials/install-wireguard/index.mdx

Mistake in the RFC number
Change RFC Number 19198 to 1918

fix(doc) Mistake in the RFC number

---

serverless/functions/reference-content/functions-lifecycle.mdx

feat(serverless): add go1.20 bet

---

console/my-account/reference-content/account-quotas.mdx
identity-and-access-management/secret-manager/reference-content/secret-manager-capabilities-limits.mdx

docs(sem): fixed quota information

---

menu/filters.json

fix(tutorials): fixed icon container category

---

serverless/messaging/api-cli/python-node-sns.mdx
serverless/messaging/reference-content/sns-support.mdx
serverless/messaging/reference-content/sqs-support.mdx

docs(mnq): Update the compatibility matrix int-fix-mnq

---

changelog/february2023/2023-02-23-documentation-added-the-sdk-js-1.0-has.mdx

feat(changelog): documentation-added-the-sdk-js-1.0-has 2023-02-23

---

changelog/february2023/2023-02-23-documentation-added-the-sdk-js-1.0-has.mdx
tutorials/remote-desktop-with-xrdp/index.mdx

fix(changelog): date typo

---

tutorials/deploy-clickhouse-database/index.mdx
tutorials/get-started-python/index.mdx
tutorials/manage-instances-with-terraform-and-functions/index.mdx

docs(fix): added hero + date

---

compute/instances/concepts.mdx
compute/instances/how-to/create-an-instance.mdx
compute/instances/how-to/migrate-instances.mdx
compute/instances/quickstart.mdx
compute/instances/reference-content/choosing-instance-type.mdx
menu/navigation.json

Added reference content: Choosing an Instance type

Draft: feat(compute): Choosing an Instance type

---

compute/instances/reference-content/cost-optimized.mdx
compute/instances/reference-content/learning.mdx
compute/instances/reference-content/production-optimized.mdx
menu/navigation.json

Added three reference pages, one for each range of Instances

feat(compute): the right Instance for learning/development/production purposes

---

compute/instances/how-to/create-an-instance.mdx

Added info about creating Instances via the API and CLI to the how to

feat(instances): add api-cli info to how to

---

tutorials/sentry-error-tracking/index.mdx

Updated docs sentry to latest version available

docs(tutorials): sentry

---

tutorials/ark-server/index.mdx
tutorials/deploy-awstats/index.mdx
tutorials/setup-jupyter-notebook/index.mdx
tutorials/setup-minecraft/index.mdx

docs(tutos): Cost-Optimized tutos

---

menu/navigation.json
serverless/functions/how-to/package-function-dependencies-in-zip.mdx

docs(serverless): upd. functions dependencies zip

---

changelog/february2023/2023-02-24-functions-added-runtimes-update.mdx

feat(changelog): functions-added-runtimes-update 2023-02-24

---

storage/object/quickstart.mdx

It looks like Amazon changed this URL.

fix(storage): update link to AWS S3 naming guidelines

---

tutorials/configure-nagios-monitoring/index.mdx

docs(tutorials): nagios updated tags

---

network/load-balancer/how-to/create-load-balancer.mdx

Add explanation of multi cloud to LB

fix(lb): add multicloud explanation

---

compute/instances/how-to/create-an-instance.mdx

Fix small issues with How to Create an Instance

fix(instances): fix small issues in how to create an instance

---

identity-and-access-management/iam/reference-content/permission-sets.mdx
identity-and-access-management/iam/reference-content/policy.mdx

Added clarifications to doc based on user questions

fix(iam): added clarification to doc

---

compute/instances/how-to/power-off-instance.mdx

docs(instance): add how to power on from standby

---

containers/kubernetes/how-to/delete-cluster.mdx
containers/kubernetes/how-to/enable-disable-ssh.mdx
menu/navigation.json

This new how-to document describes how to enable or disable the SSH server of the nodes of a Kubernetes Kapsule cluster.
As this is a new feature that only works on nodes created recently, it also describes how to make sure this feature is available.

docs(k8s): how to enable or disable SSH int-add-k8s

---

faq/elastic-metal.mdx

Fixed broken formatting in Elastic Metal FAQ

doc(faq): fix broken formatting elastic-metal

---

faq/elastic-metal.mdx

Updated link to new how-to (to avoid redirection)

docs(faq): em - updated link

---

changelog/march2023/2023-03-02-cockpit-added-devtools-for-cockpit-!.mdx

feat(changelog): cockpit-added-devtools-for-cockpit-! 2023-03-02

---

compute/instances/reference-content/cost-optimized.mdx
index.mdx
serverless/functions/how-to/connect-function-to-object-storage.mdx
serverless/functions/how-to/create-a-function.mdx
serverless/functions/how-to/delete-a-function.mdx
serverless/functions/how-to/manage-a-function.mdx
serverless/functions/how-to/package-function-dependencies-in-zip.mdx
serverless/functions/reference-content/code-examples.mdx
tutorials/connect-function-postgresql-database/index.mdx
tutorials/focalboard-project-management/index.mdx
tutorials/manage-instances-with-serverless-framework/index.mdx
tutorials/setup-postfix-ubuntu-bionic/index.mdx
tutorials/transform-images-using-faas-and-nodejs/index.mdx

docs(fix): fixed broken links (404)

---

identity-and-access-management/iam/reference-content/permission-sets.mdx

Hey there, 
this is a new permission set for Kosmos, deployed today.
Its name has been validated by us, and its description by y'all

new(iam): new permission set KubernetesExternalNodeRegister

---

tutorials/external-secrets/index.mdx

fix(secret_manager): missing field target to create kubernetes secret

---

faq/kubernetes.mdx

Add Kosmos definition to K8s FAQ

docs(faq): kubernetes add kosmos definition

---

serverless/functions/how-to/connect-function-postgresql-database.mdx

broken link to package function in zip

tutorial(serverless): fix broken link

---

managed-services/transactional-email/how-to/add-mx-record-to-your-domain.mdx
managed-services/transactional-email/quickstart.mdx

docs(tem): added info about mx record

---

tutorials/get-started-containers-docker/index.mdx

Small fixes spotted by Kai on Slack

fix(tuto): fix tuto getting started with Kube

---

menu/navigation.json

fix(docs): fix menu

---

menu/changelogs.json

docs(changelog): fixed category

---

network/domains-and-dns/how-to/delete-external-domain.mdx
network/domains-and-dns/how-to/manage-external-domain.mdx

docs(domains): added info

---

changelog/march2023/2023-03-06-iam-added-secret-manager-is-available.mdx

feat(changelog): iam-added-secret-manager-is-available 2023-03-06

---

serverless/functions/reference-content/code-examples.mdx

feat(serverless): remove EOL ide suggestion

---

changelog/march2023/2023-03-09-object-storage-fixed-slowness-issues-are-fixed.mdx

feat(changelog): object-storage-fixed-slowness-issues-are-fixed 2023-03-09

---

serverless/containers/reference-content/containers-limitations.mdx

feat(serverless): containers architecture limitation note

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx

feat(serverless): treeview consistency zip doc

---

serverless/functions/how-to/connect-function-to-object-storage.mdx

fix(serverless): format code in object-storage how-to

---

serverless/functions/how-to/connect-function-to-object-storage.mdx
serverless/functions/reference-content/code-examples.mdx

…hon code
Some improvements to Python code samples of Serverless Functions.

fix(serverless-functions): python code samples improvements

---

serverless/functions/reference-content/code-examples.mdx

Some superficial changes to the Node code samples.

feat(serverless): node code-sample improvements

---

menu/navigation.json

fix(menu): whitespaces

---

serverless/messaging/reference-content/sns-support.mdx

Update the compatibility matrix according to last updates

doc(mnq): Update the compatibility matrix int-fix-mnq

---

menu/navigation.json
serverless/functions/how-to/create-a-function.mdx
serverless/functions/reference-content/deploy-function.mdx

docs(functions): add deployment information

---

containers/kubernetes/how-to/edit-kosmos-cluster.mdx

docs(k8s): update kosmos doc

---

faq/kubernetes.mdx

docs(k8s): add faq for kapsule-agent

---

tutorials/pulumi-functions/index.mdx

docs(tutorials): removed hero illustration

---

serverless/functions/how-to/connect-function-to-object-storage.mdx

fix(Serverless Functions) S3 URL mis explanation

---

changelog/march2023/2023-03-16-functions-added-serverless-offline-testing-for.mdx

feat(changelog): functions-added-serverless-offline-testing-for 2023-03-16

---

compute/elastic-metal/how-to/create-server.mdx
compute/elastic-metal/how-to/reboot-server.mdx
compute/elastic-metal/how-to/shutdown-server.mdx
compute/elastic-metal/how-to/use-private-networks.mdx
compute/elastic-metal/quickstart.mdx
managed-databases/postgresql-and-mysql/how-to/add-users.mdx
managed-databases/postgresql-and-mysql/how-to/clone-a-database-instance.mdx
managed-databases/postgresql-and-mysql/how-to/configure-advanced-settings.mdx
managed-databases/postgresql-and-mysql/how-to/connect-database-private-network.mdx
managed-databases/postgresql-and-mysql/how-to/create-a-database.mdx
managed-databases/postgresql-and-mysql/how-to/delete-a-database.mdx
managed-databases/postgresql-and-mysql/how-to/manage-manual-backups.mdx
managed-databases/postgresql-and-mysql/quickstart.mdx

Fix(Doc): RDB and Elastic Metal documentation update

---

managed-services/webhosting/quickstart.mdx

docs(webhosting): Typo fixes

---

compute/dedibox/how-to/activate-ipv6-block.mdx
compute/elastic-metal/how-to/connect-to-server.mdx
dedibox/hardware/how-to/configure-dell-perc-h200.mdx
dedibox/hardware/how-to/configure-dell-perc-h310.mdx
dedibox/hardware/how-to/configure-dell-perc-h700.mdx
dedibox/hardware/how-to/configure-dell-perc-h800.mdx
dedibox/hardware/how-to/configure-hardware-raid-console.mdx
dedibox/hardware/how-to/configure-hp-smart-array-p410.mdx
dedibox/hardware/how-to/configure-hp-smart-array-p420.mdx
dedibox/hardware/how-to/configure-raid-kvm-h200.mdx
dedibox/hardware/how-to/configure-raid-kvm-h310.mdx
dedibox/hardware/how-to/configure-raid-kvm-p410.mdx
dedibox/hardware/how-to/configure-raid-kvm-p420.mdx
dedibox/hardware/reference-content/server-comparison-table.mdx
dedibox/hardware/troubleshooting/diagnose-defective-disk.mdx
tutorials/deploy-nextcloud-s3/index.mdx
tutorials/flask/index.mdx
tutorials/get-started-containers-docker/index.mdx
tutorials/get-started-deploy-kapsule/index.mdx
tutorials/glusterfs/index.mdx
tutorials/self-hosted-repository-gitea/index.mdx

Docs review calendar week 12/2023

docs(review): review docs content week 12/2023

---

tutorials/external-secrets/index.mdx

fix(secret_manager): crd's installation is simpler now

---

menu/navigation.json
observability/cockpit/reference-content/cockpit-limitations.mdx
observability/cockpit/reference-content/index.mdx

docs(observability): added reference content

---

serverless/functions/reference-content/deploy-function.mdx

feat(serverless): doc deploy paragraph

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx

On this documentation page, it's never precisely clear which folder you are supposed to zip. In fact, the folder being zipped in is inconsistent across languages. This PR removes the `src/` directory to avoid unnecessary nesting.

feat(serverless): add zip commands in package function

---

serverless/containers/reference-content/containers-image-configuration.mdx

Remove deprecated auth information from container image configuration.

fix(serverless): remove deprecated auth information

---

compute/dedibox/how-to/attach-detach-failover-ip.mdx
compute/dedibox/how-to/configure-failover-ip.mdx
compute/dedibox/how-to/configure-ipv6-dedibox.mdx
compute/dedibox/how-to/configure-reverse-failover-ip.mdx
compute/dedibox/how-to/connect-to-dedibox.mdx
compute/dedibox/how-to/install-dedibox.mdx
compute/dedibox/how-to/link-dedibox-account.mdx
compute/dedibox/how-to/modify-server-options.mdx
compute/dedibox/how-to/order-dedibox.mdx
compute/dedibox/how-to/order-failover-ip.mdx
compute/dedibox/how-to/reinstall-dedibox.mdx
compute/dedibox/how-to/terminate-dedibox.mdx
compute/dedibox/how-to/use-rescue-mode.mdx
compute/gpu/troubleshooting/updating-gpu-instance-with-cloud-init.mdx
compute/instances/api-cli/managing-instance-snapshot-via-cli.mdx
tutorials/backup-dedicated-server-s3-duplicity/index.mdx
tutorials/setup-lamp-stack-ubuntu2204/index.mdx
tutorials/setup-moodle/index.mdx
tutorials/setup-mysql/index.mdx
tutorials/setup-nginx-reverse-proxy-s3/index.mdx
tutorials/sharelatex/index.mdx
tutorials/sinatra/index.mdx
tutorials/socket-io/index.mdx

docs(review): review docs - week 13/2023

---

tutorials/pulumi-functions/index.mdx

Fix metadata for pulumi tutorial

docs(tutorials): fix metadata

---

tutorials/getting-started-with-kops-on-scaleway/index.mdx

Getting started with kOps on SCW

docs(tutorials): kOps

---

changelog/march2023/2023-03-30-private-networks-added-regional-private-networks-is.mdx

feat(changelog): private-networks-added-regional-private-networks-is 2023-03-30

---

serverless/functions/reference-content/code-examples.mdx

feat(serverless): standardize handler names

---

tutorials/setup-nomad-cluster/index.mdx

fix(tutorials): update setup nomad cluster title

---

serverless/functions/api-cli/fun-uploading-with-serverless-framework.mdx
serverless/functions/reference-content/deploy-function.mdx
serverless/functions/reference-content/local-testing.mdx

Add disclaimer for external links

docs(functions): add disclaimer

---

faq/serverless-functions.mdx

feat(serverless): faq read build errors

---

faq/kubernetes.mdx

Add question to Kubernetes FAQ

docs(k8s): add faq entry

---

serverless/containers/how-to/add-a-custom-domain-to-a-container.mdx
serverless/functions/how-to/add-a-custom-domain-name-to-a-function.mdx

There are some special steps for setting up custom domains for functions and containers with Cloudflare DNS which trip up lots of users. I have added notes to both the "how to" guides that should help.

docs(serverless): add note on Cloudflare DNS to function and container custom domains

---

menu/navigation.json
observability/cockpit/troubleshooting/index.mdx
observability/cockpit/troubleshooting/pusher-does-not-support-custom-http-headers.mdx
observability/cockpit/troubleshooting/resetting-grafana-password-via-the-api.mdx

docs(obs): add information from api doc MTA-3012

---

tutorials/lb-ingress-controller/index.mdx

Fixed Ingress controller tutorial by removing outdated part

docs(tutorials): fix ingress tuto

---

compute/gpu/how-to/use-gpu-with-docker.mdx

The sentence about data redundancy was itself redundant.

docs: Remove redundancy redundancy

---

tutorials/get-started-kubernetes-loadbalancer/index.mdx

Fixed broken steps in tutorial

docs(tutorials): fix broken steps

---

managed-services/webhosting/concepts.mdx
managed-services/webhosting/how-to/configure-dns-webhosting.mdx
managed-services/webhosting/how-to/index.mdx
managed-services/webhosting/how-to/manage-webhosting.mdx
managed-services/webhosting/how-to/order-webhosting.mdx
managed-services/webhosting/how-to/terminate-webhosting.mdx
managed-services/webhosting/index.mdx
managed-services/webhosting/quickstart.mdx
managed-services/webhosting/reference-content.mdx
menu/navigation.json

Updated docs for Web Hosting products

docs(webhosting): update docs webhosting product

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx

Add additional content from api docs

functions(api): add api information

---

compute/instances/troubleshooting/bootscript-eol.mdx

Add bootscript EOL warning to docs

docs(instances): add bootscript eol warning

---

changelog/april2023/2023-04-11-instances-added-initial-support-for-ansible.mdx

feat(changelog): instances-added-initial-support-for-ansible 2023-04-11

---

changelog/april2023/2023-04-11-containers-added-initial-support-for-waypoint.mdx

feat(changelog): containers-added-initial-support-for-waypoint 2023-04-11

---

changelog/april2023/2023-04-11-instances-added-initial-support-for-crossplane.mdx

feat(changelog): instances-added-initial-support-for-crossplane 2023-04-11

---

console/my-account/how-to/close-account.mdx

fix(my-account): update close-account

---

changelog/april2023/2023-04-12-instances-added-terraform-scaleway-provider-v2.16.3.mdx

feat(changelog): instances-added-terraform-scaleway-provider-v2.16.3 2023-04-12

---

console/my-account/reference-content/account-quotas.mdx
menu/navigation.json
network/domains-and-dns/reference-content/index.mdx
network/domains-and-dns/reference-content/understanding-domains-and-dns.mdx
observability/cockpit/how-to/create-token.mdx

docs(domains&dns): migrate content from API documentation website

---

serverless/functions/reference-content/functions-lifecycle.mdx

- Updated node19 runtime status from `beta` to `deprecated`

feat(serverless): add node19 deprecated status

---

serverless/functions/quickstart.mdx

feat(serverless): improve quickstart

---

observability/cockpit/concepts.mdx
observability/cockpit/reference-content/cockpit-limitations.mdx

docs(cockpit): added mimir limits and mimir concept

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx

feat(serverless): package zip functions

---

tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx

fix(tutorial): typo

---

storage/object/api-cli/bucket-operations.mdx
storage/object/api-cli/object-operations.mdx
storage/object/api-cli/using-api-call-list.mdx

fix(s3): updates api

---

serverless/containers/reference-content/containers-limitations.mdx
serverless/functions/reference-content/functions-limitations.mdx

feat(serverless): add a note for limits overflow

---

console/my-account/how-to/change-console-appearance.mdx
dedibox/hardware/how-to/configure-hp-smart-array-p420.mdx
observability/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
observability/cockpit/quickstart.mdx
serverless/containers/how-to/create-auth-token-from-console.mdx
tutorials/configure-chef-ubuntu-xenial/index.mdx
tutorials/visualize-timeseries-data-timescaledb-grafana/index.mdx
tutorials/vuls-security-scanner/index.mdx
tutorials/wordpress-lemp-stack-focal/index.mdx
tutorials/wordpress-lemp-stack/index.mdx
tutorials/zabbix-monitoring/index.mdx
tutorials/zimbra-elastic-metal/index.mdx
tutorials/zulip/index.mdx

docs(review): docs review week 16/2023

---

changelog/april2023/2023-04-18-instances-added-new-os-images-available.mdx

feat(changelog): instances-added-new-os-images-available 2023-04-18

---

serverless/functions/reference-content/local-testing.mdx

doc(functions) add node local testing

---

tutorials/wordpress-lemp-stack-ubuntu-jammy-jellyfish-22-04/index.mdx

A part of the text was written two times

fix(tutorial): text written in double

---

changelog/april2023/2023-04-20-functions-changed-golang-runtimes.mdx
serverless/functions/reference-content/functions-lifecycle.mdx

feat(serverless): update go runtimes

---

changelog/april2023/2023-04-19-cockpit-added-observability---documentation--.mdx

feat(changelog): cockpit-added-observability---documentation-- 2023-04-19

---

changelog/april2023/2023-04-19-functions-added-it-is-now-easier.mdx

feat(changelog): functions-added-it-is-now-easier 2023-04-19

---

changelog/april2023/2023-04-19-functions-added-serverless-offline-testing-for.mdx

feat(changelog): functions-added-serverless-offline-testing-for 2023-04-19

---

menu/navigation.json
serverless/functions/reference-content/code-examples.mdx

feat(serverless): container missing link in menu

---

serverless/containers/quickstart.mdx
serverless/functions/quickstart.mdx

feat(serverless): containers & functions improve quickstart

---

faq/serverless-functions.mdx

feat(serverless): functions improve faq

---

faq/serverless-containers.mdx

feat(serverless): containers improve faq

---

serverless/functions/reference-content/local-testing.mdx

feat(serverless): improve local testing with examples

---

dedibox-network/rpn/how-to/find-rpn-gateway.mdx

docs(rpn): update rpn docs

---

compute/dedibox/how-to/link-dedibox-account.mdx

docs(dedibox): update link dedibox docs

---

serverless/containers/how-to/add-a-custom-domain-to-a-container.mdx
serverless/containers/how-to/create-a-containers-namespace.mdx
serverless/containers/how-to/create-auth-token-from-console.mdx
serverless/containers/how-to/delete-a-container.mdx
serverless/containers/how-to/delete-a-containers-namespace.mdx
serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx
serverless/containers/how-to/manage-a-container.mdx
serverless/containers/how-to/manage-a-containers-namespace.mdx
serverless/containers/how-to/modify-container-privacy.mdx
serverless/containers/how-to/secure-a-container.mdx
serverless/containers/quickstart.mdx
serverless/containers/reference-content/containers-image-configuration.mdx
serverless/containers/reference-content/containers-limitations.mdx

docs(containers): review categories

---

tutorials/configure-plex-s3/index.mdx

Hello guysss, just adding more infos on some steps of this tuto!
Keep up the good work
See u
BBH 
🐰

feat(tutorials): update on configure-plex-s3

---

serverless/functions/reference-content/code-examples.mdx

feat(serverless): functions improve examples

---

storage/object/api-cli/object-lock.mdx

fix(s3): mauvais rebase

---

compute/dedibox/how-to/link-dedibox-account.mdx
faq/dedibox-in-scaleway-console.mdx

docs(dedibox): update faq ddx2elts

---

serverless/functions/reference-content/functions-lifecycle.mdx

feat(serverless): add runtime node20 in beta

---

dedibox-network/network/reference-content/dedibox-network-info.mdx

docs(dedibox): update dedibox network information

---

serverless/messaging/api-cli/python-node-sns.mdx

messaging(doc) - update code sample nodeJS

---

changelog/april2023/2023-04-27-functions-changed-nodejs-20-is-available.mdx

feat(changelog): functions-changed-nodejs-20-is-available 2023-04-27

---

changelog/april2023/2023-04-28-secret-manager-added-secret-manager-is-generally.mdx

feat(changelog): secret-manager-added-secret-manager-is-generally 2023-04-28

---

changelog/april2023/2023-04-27-transactional-email-added-domain-reputation-management-policy.mdx

feat(changelog): transactional-email-added-domain-reputation-management-policy 2023-04-27

---

changelog/april2023/2023-04-27-transactional-email-added-addition-of-smtp-host.mdx

feat(changelog): transactional-email-added-addition-of-smtp-host 2023-04-27

---

changelog/april2023/2023-04-27-transactional-email-added-sending-serverless-emails-with.mdx

feat(changelog): transactional-email-added-sending-serverless-emails-with 2023-04-27

---

changelog/april2023/2023-04-27-transactional-email-added-new-email-alerts-from.mdx

feat(changelog): transactional-email-added-new-email-alerts-from 2023-04-27

---

changelog/april2023/2023-04-27-transactional-email-added-new-iam-permissions-set.mdx

feat(changelog): transactional-email-added-new-iam-permissions-set 2023-04-27

---

faq/serverless-functions.mdx
serverless/functions/reference-content/functions-lifecycle.mdx

feat(serverless): functions add note to runtime migration

---

compute/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
managed-services/iot-hub/reference-content/certificate.mdx
managed-services/iot-hub/reference-content/twins.mdx
menu/navigation.json

cf: https://docs.google.com/document/d/1hSUzQbto86y3_6ZR2igdxV-vonjND_80odeP9RtXplg/edit

add(refcont): IoT Hub CA change MTA-3016

---

compute/instances/how-to/create-a-backup.mdx
network/load-balancer/how-to/add-certificate.mdx
observability/cockpit/how-to/activate-cockpit.mdx
tutorials/configure-apache-kafka/index.mdx
tutorials/create-openwrt-image-for-scaleway/index.mdx
webhosting/classic/how-to/access-logcenter.mdx
webhosting/classic/how-to/access-statistics.mdx
webhosting/classic/how-to/change-email-account-password.mdx
webhosting/classic/how-to/change-ftp-account-password.mdx
webhosting/classic/how-to/change-password-mysql-database.mdx
webhosting/classic/how-to/change-password-postgresql-database.mdx
webhosting/classic/how-to/check-emails.mdx
webhosting/classic/how-to/configure-backup-option.mdx
webhosting/classic/how-to/configure-htaccess-file.mdx
webhosting/classic/how-to/configure-outlook.mdx
webhosting/classic/how-to/configure-php.mdx
webhosting/classic/how-to/connect-via-ftp.mdx
webhosting/classic/how-to/create-alias.mdx
webhosting/classic/how-to/create-email-account.mdx

docs(review): review docs week 18/2023

---

changelog/may2023/2023-05-02-kubernetes-added-kubernetes-version-1.27-now.mdx

feat(changelog): kubernetes-added-kubernetes-version-1.27-now 2023-05-02

---

containers/kubernetes/reference-content/version-support-policy.mdx
faq/kubernetes.mdx

docs(k8s): add information for k8s v1.27

---

containers/kubernetes/how-to/delete-cluster.mdx
containers/kubernetes/how-to/enable-disable-ssh.mdx
menu/navigation.json

Kubernetes Kapsule: Enable/Disable SSH on Kapsule nodes

docs(k8s): enable disable ssh

---

compute/instances/troubleshooting/change-rescue-mode.mdx
menu/navigation.json

docs(instances): change rescue mode

---

console/my-account/reference-content/account-quotas.mdx

add(refcont): Update quota doc MTA-3156

---

tutorials/get-started-deploy-kapsule/index.mdx

fix(how-tos): Fix typo in k8s tutorial part 2

---

changelog/may2023/2023-05-10-transactional-email-changed-tem-in-ga.mdx

feat(changelog): transactional-email-changed-tem-in-ga 2023-05-10

---

menu/navigation.json
serverless/functions/how-to/add-a-custom-domain-name-to-a-function.mdx
serverless/functions/how-to/add-trigger-to-a-function.mdx
serverless/functions/how-to/manage-a-function.mdx

docs(serverless): functions triggers

---

faq/serverless-containers.mdx
serverless/containers/concepts.mdx

feat(serverless): containers update protocols doc

---

managed-services/transactional-email/how-to/generate-api-keys-for-tem-with-iam.mdx

I am suggesting this because a client had an unexpected 403 when testing this doc and it took me some time to understand what the issue was. 
Maybe with even more information on Project ID, it will be easier to identify this as a possible cause of 403

new(tem): add a precision on TEM due to misunderstanding by clients

---

serverless/messaging/reference-content/sns-support.mdx
serverless/messaging/reference-content/sqs-support.mdx

Update permission requirement to reflect code change

doc(mnq): Update permission requirement to reflect code change int-fix-mnq

---

changelog/may2023/2023-05-12-functions-added-serverless-python-api-framework.mdx

feat(changelog): functions-added-serverless-python-api-framework 2023-05-12

---

tutorials/traefik-v2-cert-manager/index.mdx

docs(tutorials): update traefik tuto

---

storage/block/how-to/increase-block-volume.mdx

docs(storage): update block storage increase doc

---

changelog/may2023/2023-05-15-kubernetes-changed-enable-or-disable-ssh.mdx

feat(changelog): kubernetes-changed-enable-or-disable-ssh 2023-05-15

---

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx

docs(k8s): add q/a how to allow inbound traffic

---

changelog/may2023/2023-05-15-cockpit-added-using-your-own-grafana.mdx

feat(changelog): cockpit-added-using-your-own-grafana 2023-05-15

---

containers/kubernetes/how-to/enable-disable-ssh.mdx

docs(k8s): add warning sec groups for ssh access

---

faq/dedibox-in-scaleway-console.mdx

fix(dedibox): Typo in dedibox-in-scaleway-console.mdx

---

compute/instances/troubleshooting/cant-connect-ssh.mdx

Remove a block which is not up to date with Kapsule current state

fix(k8s): remove outdated block

---

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx

docs(k8s): add terraform warning

---

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx

According to people on slack's channel, documentation lacks of warning message.
This one just add a warning message in front of Terraform example.

docs(kapsule): Add a warning message

---

containers/kubernetes/api-cli/using-load-balancer-annotations.mdx
faq/loadbalancer.mdx
network/load-balancer/api-cli/configuring-balancing-rules.mdx
network/load-balancer/api-cli/setting-up-ssl-offloading.mdx
network/load-balancer/concepts.mdx
network/load-balancer/how-to/create-load-balancer.mdx
network/load-balancer/how-to/manage-frontends-and-backends.mdx
network/load-balancer/reference-content/configuring-load-balancer.mdx

Fix 404s pointing to old LB URL

fix(doc): fix 404s LB api

---

compute/instances/how-to/use-private-networks.mdx

Modify steps for configuring PN on an Instance, to take into account need to delete DHCP files there for PGW

fix(instances): modify pn doc

---

changelog/may2023/2023-05-22-load-balancers-deprecated-regional-api-is-deprecated.mdx

feat(changelog): load-balancers-deprecated-regional-api-is-deprecated 2023-05-22

---

serverless/messaging/api-cli/python-node-sqs.mdx

MnQ(doc) - update sqs node code sample

---

serverless/messaging/how-to/create-manage-queues.mdx

Wrong image in one part of doc, and it doesn't really need an image anyway - delete.

fix(mnq): delete bad image

---

components.mdx
containers/kubernetes/how-to/enable-disable-ssh.mdx
containers/kubernetes/how-to/upgrade-kubernetes-version-using-cli.mdx
menu/navigation.json

CLI oriented way of doing things.
I wrote this file after an incident we had with a client. It shed light on the need for such documentation. Here it is.

feat(k8s): explain thoroughly how to upgrade

---

serverless/messaging/how-to/create-manage-queues.mdx
tutorials/deploy-chatwoot-self-care/index.mdx
tutorials/manage-k8s-logging-loki/index.mdx

fix(docs): fix 404

---

observability/cockpit/api-cli/configuring-grafana-agent.mdx

Thes latest version of grafana agent have now the bin named grafana-agent instead of agent.

fix(cockpit): Fix entrypoint for grafana/agent

---

serverless/functions/reference-content/use-cases.mdx

Revision of Serverless Functions - Use cases

docs(revision): serverless functions - use cases

---

containers/container-registry/how-to/connect-docker-cli.mdx
containers/container-registry/how-to/create-namespace.mdx
containers/container-registry/how-to/delete-image.mdx
containers/container-registry/how-to/delete-namespace.mdx
containers/container-registry/how-to/display-image-versions.mdx
containers/container-registry/how-to/manage-image-privacy-settings.mdx
containers/container-registry/how-to/manage-namespace-privacy-policies.mdx
containers/container-registry/how-to/pull-images.mdx
containers/container-registry/how-to/push-images.mdx
containers/container-registry/quickstart.mdx

Revision of Container Registry product documentation

docs(revision): container registry

---

faq/serverless-containers.mdx

docs(containers) - remove memory/vcpu packages from how-to

---

serverless/functions/how-to/manage-a-functions-namespace.mdx

Updated "How to manage a functions namespace" following review against console wording

fix(functions): updated manage namespace procedure following review MTA-3236

---

tutorials/secret-manager-generate-password/index.mdx

Add tutorial to generate a password with the Scaleway Secret Manager

docs(secret-manager): add tutorial to generate password int-add-secret-manager-generate-password

---

serverless/functions/how-to/manage-a-function.mdx

Revision of Serverless Functions - Manage Function

docs(revision): serverless functions - manage fctn

---

identity-and-access-management/secret-manager/api-cli/generate-secret-password.mdx
identity-and-access-management/secret-manager/api-cli/index.mdx
menu/navigation.json

- Fixed indentation 
- Added API/CLI category
- Deleted tuto from tutorials and added it to API/CLI
- Fixed a few typos

fix(secret-manager): reviewed tuto

---

serverless/functions/how-to/create-a-function.mdx

Updated doc following review against console wording

fix(functions): update create function doc following review MTA-3237

---

docs/CONTRIBUTING.md

- Added link to show how to fork the repository

fix(docs): updated contributing file

---

serverless/functions/quickstart.mdx

Update content following review

fix(serverless functions): update reviewed doc MTA-3234

---

changelog/may2023/2023-05-25-kubernetes-changed-new-program-to-add.mdx

feat(changelog): kubernetes-changed-new-program-to-add 2023-05-25

---

menu/navigation.json

fix(prettier): format error

---

labs/ipfs/api-cli/ipfs-cli.mdx
labs/ipfs/api-cli/ipfs-desktop.mdx
labs/ipfs/api-cli/ipfs-get-content.mdx
labs/ipfs/api-cli/ipfs-operations.mdx
labs/ipfs/api-cli/volumes-operations.mdx
labs/ipfs/concepts.mdx
labs/ipfs/quickstart.mdx

- [ X] Check that the commit messages match our requested structure.
Some fix, add and ajustments for IPFS pinning documentation

docs(ipfs): typography and more explaination

---

serverless/functions/reference-content/deploy-function.mdx

Revision Serverless Functions - Deploy Function

docs(revision): serverless functions - deploy fct

---

faq/private-networks.mdx
network/vpc/how-to/attach-resources-to-pn.mdx
network/vpc/troubleshooting/vpc-limitations.mdx

Update max resources per PN to 512

docs(vpc): update number of resources per PN

---

console/my-account/reference-content/account-quotas.mdx

Added quota information for POP2 Instances

docs(my-account): add quotas for pop2 instances

---

faq/elastic-metal.mdx

docs(em): add em ranges to faq

---

compute/instances/api-cli/using-ip-mobility.mdx

docs(instances): fix typo ipmob

---

changelog/may2023/2023-05-30-elastic-metal-added-em-i210e-nvme-launch.mdx

feat(changelog): elastic-metal-added-em-i210e-nvme-launch 2023-05-30

---

labs/ipfs/api-cli/ipfs-cli.mdx
labs/ipfs/api-cli/ipfs-desktop.mdx
labs/ipfs/api-cli/ipfs-get-content.mdx
labs/ipfs/api-cli/ipfs-operations.mdx
labs/ipfs/quickstart.mdx

- [ X] Check that the commit messages match our requested structure.
- IPFS CLI update
- Add disclaimer for data visibility

feat(ipfs): update CLI + disclaimer

---

changelog/june2023/2023-06-01-instances-added-new-production-optimized-and-workload-optimized.mdx

feat(changelog): instances-added-new-production-optimized-and-workload-optimized 2023-06-01

---

changelog/june2023/2023-06-01-cockpit-added-cockpit-launch.mdx

feat(changelog): cockpit-added-cockpit-launch 2023-06-01

---

network/load-balancer/reference-content/sni-route-deprecation.mdx

fix(lb): fix typo

---

containers/kubernetes/how-to/edit-kosmos-cluster.mdx

docs(k8s): add mention for debian + arm support

---

tutorials/configure-dvc-with-object-storage/index.mdx

PROCEDURE MUST BE TESTED BEFORE APPROVAL!

docs(tutorial) create DVC x Object storage tutorial MTA-3182

---

compute/instances/api-cli/using-ip-mobility.mdx

Add examples regarding the use of the new IP Mobility feature with IPv6 only and multiple IPs

docs(instance): ipmob multiple IPs or IPv6 only examples

---

compute/instances/api-cli/using-ip-mobility.mdx
compute/instances/concepts.mdx

docs(intstances): fix ipmob wording

---

tutorials/k8s-fluentbit-observability/index.mdx

- Fixed typos 
- Specify why we need to increase the scrape interval

fix(cockpit): add specifications

---

tutorials/transform-images-using-faas-and-nodejs/index.mdx

tutorial(functions): update intro to guide more users

---

tutorials/scaleway-packer-plugin/index.mdx

docs(tutorial): packer plugin

---

managed-services/webhosting/how-to/migrate-webhosting-plan.mdx

Add a placeholder page for Web Hosting migration

docs(webhosing): add placeholder page

---

labs/ipfs/api-cli/ipfs-cli.mdx
labs/ipfs/api-cli/ipfs-desktop.mdx
labs/ipfs/api-cli/ipfs-operations.mdx
labs/ipfs/api-cli/volumes-operations.mdx
labs/ipfs/quickstart.mdx

refactor(ipfs): endpoint and flag Scaleway CLI Labs

---

labs/ipfs/api-cli/ipfs-desktop.mdx
labs/ipfs/api-cli/ipfs-get-content.mdx
labs/ipfs/api-cli/ipfs-operations.mdx
labs/ipfs/api-cli/volumes-operations.mdx
labs/ipfs/quickstart.mdx

Miscellaneous fix in IPFS pinning documentation.

fix(ipfs): cli

---

menu/navigation.json
observability/cockpit/reference-content/understanding-cockpit-usage.mdx

- Added  ref content to explain how to pricing for Cockpit works and how to configure it to pay less

add(cockpit): added reference content

---

dedibox/hardware/reference-content/server-comparison-table.mdx

Add information about HW RAID controller for DDX offers

docs(dedibox): add information for hw raid

---

serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx

fix(containers): Update doc following review MTA-3311

---

managed-databases/postgresql-and-mysql/how-to/manage-allowed-ip-addresses.mdx
managed-databases/redis/concepts.mdx
managed-databases/redis/how-to/configure-advanced-settings-redis.mdx
managed-databases/redis/how-to/create-a-database-for-redis.mdx
managed-databases/redis/how-to/delete-a-database-for-redis.mdx
managed-databases/redis/how-to/manage-allowed-ip-addresses-redis.mdx
managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx
managed-databases/redis/quickstart.mdx

- Fixed some typos;
- Checked and fixed inconsistencies between Doc and Console content.

fix(redis): wording review and correction

---

compute/instances/reference-content/production-optimized.mdx
compute/instances/reference-content/workload-optimized.mdx

Fix SLA for Production Optimized and Workload Optimized Instances

docs(instances): fix sla

---

menu/navigation.json

feat(Sss functions) add content reference on triggers MTA-3326

---

serverless/functions/how-to/add-trigger-to-a-function.mdx
serverless/functions/how-to/configure-trigger-inputs.mdx
serverless/functions/reference-content/configure-trigger-inputs.mdx

- [ x] Check that the commit messages match our requested structure.
- [ x] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).

add(functions): add how-to retention for function triggers SRVLESS-9134

---

changelog/june2023/2023-06-13-containers-changed-serverless-containers-in-cockpit.mdx

feat(changelog): containers-changed-serverless-containers-in-cockpit 2023-06-13

---

changelog/june2023/2023-06-13-functions-changed-serverless-functions-logs-and.mdx

feat(changelog): functions-changed-serverless-functions-logs-and 2023-06-13

---

compute/instances/troubleshooting/bootscript-eol.mdx

Update bootscript EOL documetnation

docs(instances): update bootscript eol docs

---

changelog/june2023/2023-06-14-elastic-metal-added-debian-12-bookworm-is.mdx

feat(changelog): elastic-metal-added-debian-12-"bookworm"-is 2023-06-14

---

changelog/june2023/2023-06-13-containers-changed-set-resources-independently.mdx

feat(changelog): containers-changed-set-resources-independently 2023-06-13

---

network/domains-and-dns/how-to/configure-dns-zones.mdx
network/domains-and-dns/how-to/manage-dns-records.mdx
network/domains-and-dns/how-to/manage-external-domain.mdx
network/domains-and-dns/how-to/manage-nameservers-internal-domain.mdx
network/domains-and-dns/how-to/register-internal-domain.mdx
network/domains-and-dns/how-to/unlock-internal-domain.mdx
network/domains-and-dns/quickstart.mdx
network/domains-and-dns/reference-content/understanding-domains-and-dns.mdx

fix(domains&dns): update doc following review MTA-3334

---

changelog/june2023/2023-06-13-instances-added-debian-bookworm-is-now.mdx

feat(changelog): instances-added-debian-"bookworm"-is-now 2023-06-13

---

containers/kubernetes/reference-content/secure-cluster-with-private-network.mdx

I've changed tf provider doc as well

docs(k8s): update tf provider behaviour

---

menu/changelogs.json

fix(content): format bug

---

containers/kubernetes/quickstart.mdx

docs(k8s): update quickstart

---

menu/navigation.json
serverless/containers/reference-content/containers-billing.mdx

feat(Containers): Add ref content for billing linked to FAQ MTA-3307

---

menu/navigation.json
serverless/functions/reference-content/functions-billing.mdx

feat(Functions): Add ref content for billing with link to FAQ MTA-3306

---

bare-metal/apple-silicon/how-to/connect-to-mac-mini-m1.mdx
bare-metal/apple-silicon/how-to/create-mac-mini-m1.mdx
bare-metal/apple-silicon/how-to/reboot-mac-mini-m1.mdx
bare-metal/apple-silicon/how-to/reinstall-mac-mini-m1.mdx
bare-metal/apple-silicon/quickstart.mdx
bare-metal/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
bare-metal/apple-silicon/troubleshooting/filevault-preventing-system-boot.mdx
bare-metal/apple-silicon/troubleshooting/need-package-manager.mdx

Wording review and update to ensure consistency across pages.

fix(a.silicon): wording review

---

identity-and-access-management/secret-manager/how-to/create-secret.mdx
identity-and-access-management/secret-manager/how-to/create-version.mdx
identity-and-access-management/secret-manager/quickstart.mdx

Updated SEM documentation (creation buttons).

fix(sem): doc content update | MTA-3349

---

dedibox/dedicated-servers/how-to/monitor-server.mdx

docs(dedibox): add warning to monitoring feature

---

menu/navigation.json
network/vpc/concepts.mdx
network/vpc/reference-content/index.mdx
network/vpc/reference-content/vpc-migration.mdx

Add doc to prepare users for VPC GA and associated migration

feat(vpc): doc to explain migration

---

tutorials/waypoint-plugin-scaleway/index.mdx

docs(tutorial): waypoint plugin for scaleway

---

changelog/june2023/2023-06-22-dedibox-added-proxmox-8-now-available.mdx

feat(changelog): dedibox-added-proxmox-8-now-available 2023-06-22

---

changelog/june2023/2023-06-22-elastic-metal-added-proxmox-8-now-available.mdx

feat(changelog): elastic-metal-added-proxmox-8-now-available 2023-06-22

---

changelog/june2023/2023-06-22-instances-fix-wrong-user-cloud-init-config.mdx

- [ x] Check that the commit messages match our requested structure.
Add new entry

feat(changelog): Add new bookworm image with fix to previous

---

changelog/january2023/2023-01-18-instances-changed-pro2-and-play2-instances.mdx
compute/instances/reference-content/cost-optimized.mdx
compute/instances/reference-content/production-optimized.mdx
compute/instances/reference-content/workload-optimized.mdx
console/my-account/reference-content/products-availability.mdx
faq/instances.mdx

docs(instances): add AMS3

---

console/my-account/how-to/create-an-account.mdx
console/my-account/how-to/sign-in-with-magic-link.mdx

docs(console): update create account

---

serverless/containers/reference-content/containers-image-configuration.mdx
serverless/containers/reference-content/containers-limitations.mdx

fix(containers): http/https  distinction in content ref MTA-3325

---

compute/instances/api-cli/using-ip-mobility.mdx

docs(instance): clarify the ipmob documentation

---

managed-services/webhosting/concepts.mdx
managed-services/webhosting/how-to/manage-webhosting.mdx
managed-services/webhosting/how-to/order-webhosting.mdx

Updated Web Hosting documentation

fix(wh): wording update

---

console/my-account/how-to/recover-a-lost-password.mdx

docs(fix): fix broken date

---

labs/ipfs/reference-content/index.mdx
labs/ipfs/reference-content/install-ipfs-desktop.mdx

https://jira.infra.online.net/browse/MTA-3376?filter=-1

docs(ref-content): using scw ipfs with ipfs desktop MTA-3376

---

identity-and-access-management/iam/concepts.mdx
identity-and-access-management/iam/quickstart.mdx

fix(iam): wording

---

managed-services/transactional-email/how-to/delete-tem-domain.mdx

docs(tem): update link

---

faq/serverless-containers.mdx

docs(serverless): fix grammar and formatting in containers FAQ

---

compute/instances/api-cli/creating-backups.mdx
compute/instances/api-cli/migrating-gp-to-pro.mdx
compute/instances/api-cli/migrating-instances.mdx
menu/navigation.json

docs(instances): update instance upgrade docs

---

managed-services/iot-hub/api-cli/iot-hub-routes.mdx

https://jira.infra.online.net/browse/MTA-3391?filter=-1

docs(api-cli): added info MTA-3391

---

containers/container-registry/quickstart.mdx
tutorials/proxmox-softraid/index.mdx
tutorials/proxy-protocol-v2-load-balancer/index.mdx
tutorials/remote-desktop-with-xrdp/index.mdx
tutorials/restic-s3-backup/index.mdx
tutorials/ruby-on-rails/index.mdx
tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
tutorials/s3-customize-url-cname/index.mdx
tutorials/s3cmd/index.mdx

docs(review): tutorials

---

faq/general.mdx

docs(faq): update faq general

---

compute/instances/reference-content/workload-optimized.mdx

docs(instances): add par3 to workload optimzed

---

serverless/functions/how-to/create-a-function.mdx
serverless/functions/how-to/create-a-functions-namespace.mdx
serverless/functions/how-to/manage-a-function.mdx
serverless/functions/quickstart.mdx
serverless/functions/reference-content/deploy-function.mdx

fix(functions): update quickstart and move ref content MTA-3384

---

changelog/july2023/2023-07-06-kubernetes-removed-kubernetes-1.21-is-no.mdx

feat(changelog): kubernetes-removed-kubernetes-1.21-is-no 2023-07-06

---

changelog/july2023/2023-07-06-secret-manager-added-secret-manager-metrics-in.mdx

feat(changelog): secret-manager-added-secret-manager-metrics-in 2023-07-06

---

changelog/packer/semptember2022/2022-09-05-packer-added-support-unified-snapshots.mdx
faq/play2-instances.mdx

docs(fix): fixed broken links

---

console/my-account/reference-content/products-availability.mdx
labs/ipfs/reference-content/install-ipfs-desktop.mdx

docs(fix): fix 404s

---

compute/instances/concepts.mdx
compute/instances/quickstart.mdx

https://jira.infra.online.net/browse/MTA-3413

docs(instances): fix AZ/region confusion MTA-3413

---

dedibox-network/ipv6/how-to/configure-ipv6-networkd.mdx

fix(dedibox): fix typos in documentation MTA-3429

---

dedibox-network/ip-failover/how-to/assign-failover-ip.mdx
dedibox-network/ip-failover/how-to/configure-centos.mdx
dedibox-network/ip-failover/how-to/configure-debian-ubuntu.mdx
dedibox-network/ip-failover/how-to/configure-freebsd.mdx
dedibox-network/ip-failover/how-to/configure-multiip-virtualmac.mdx
dedibox-network/ip-failover/how-to/configure-network-virtual-machine.mdx
dedibox-network/ip-failover/how-to/configure-reverse-dns.mdx
dedibox-network/ip-failover/how-to/configure-windows.mdx
dedibox-network/ip-failover/how-to/create-virtual-mac.mdx
serverless/messaging/api-cli/connect-aws-cli.mdx
serverless/messaging/api-cli/python-node-sns.mdx
serverless/messaging/reference-content/limitations.mdx
serverless/messaging/reference-content/snssqs-overview.mdx
serverless/messaging/reference-content/sqs-support.mdx
tutorials/deploying-a-documentation-website-with-docusaurus-on-scaleway/index.mdx

docs(review): content review

---

network/vpc/reference-content/vpc-migration.mdx

Add info about managed DNS to migration doc

fix(vpc): add info to migration doc

---

bare-metal/elastic-metal/how-to/configure-flexible-ip.mdx

Fix YAML indentation in configure-flexible-ip.mdx

---

network/vpc/quickstart.mdx

fix(vpc): fix typo

---

network/vpc/troubleshooting/autoconfig-not-working.mdx

PR to replace this one now that destination content has moved: https://github.com/scaleway/docs-content/pull/1875

fix(vpc): added code line

---

network/vpc/concepts.mdx
network/vpc/how-to/attach-resources-to-pn.mdx

Add info about IP address format, to address a user's question

fix(vpc): add more info about IP format

---

faq/vpc.mdx
network/vpc/concepts.mdx
network/vpc/how-to/attach-resources-to-pn.mdx
network/vpc/reference-content/vpc-migration.mdx

Add info about IP addresses remaining stable with managed DHCP

feat(vpc): added info about ip stability

---

containers/kubernetes/how-to/use-kubernetes-gpu-operator.mdx
menu/navigation.json

docs(k8s): add gpu operator docs

---

bare-metal/elastic-metal/how-to/use-private-networks.mdx
network/vpc/concepts.mdx
network/vpc/how-to/attach-resources-to-pn.mdx
network/vpc/troubleshooting/resource-attached-no-ip.mdx

Add info about EM virtualization not being compatible with DHCP, and correct/enhance existing EM info and formatting.

feat(vpc): added info about em virtualization

---

serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx
serverless/containers/how-to/manage-a-container.mdx
serverless/containers/how-to/manage-a-containers-namespace.mdx
serverless/containers/quickstart.mdx

No breaking errors, but quite important

fix(containers): fix recurring error in Sls containers doc MTA-3467

---

.vscode/settings.json
serverless/sql-databases/quickstart.mdx

feat(SDB): create Serverless DB Quickstart MTA3452

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx

Simplify the documentation to just show how to zip files with one handler + add a section for mutiple handler support

feat(serverless): simplify zip documentation

---

changelog/july2023/2023-07-18-private-networks-changed-virtual-private-cloud-is.mdx

feat(changelog): private-networks-changed-virtual-private-cloud-is 2023-07-18

---

changelog/july2023/2023-07-18-public-gateways-changed-the-public-gateway-is.mdx

feat(changelog): public-gateways-changed-the-public-gateway-is 2023-07-18

---

containers/kubernetes/how-to/change-container-runtime-interface.mdx
containers/kubernetes/how-to/delete-cluster.mdx
containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx
menu/navigation.json

docs(k8s): update navigation

---

containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx

docs(k8s): fix typo in navi

---

changelog/july2023/2023-07-18-kubernetes-added-new-kubernetes-operator-to.mdx

docs(k8s): fix changelog link

---

changelog/july2023/2023-07-19-kubernetes-added-kapsule-and-kosmos-control.mdx

feat(changelog): kubernetes-added-kapsule-and-kosmos-control 2023-07-19

---

changelog/july2023/2023-07-20-kubernetes-added-new-availability-zone-ams-3.mdx

feat(changelog): kubernetes-added-new-availability-zone-ams-3 2023-07-20

---

console/my-account/how-to/verify-identity.mdx

docs(console): add sentence on ID verif MTA-3439

---

network/vpc/troubleshooting/autoconfig-not-working.mdx

Updated information for manual installation of `scaleway-ecosystem` package

docs(vpc): update troubleshooting information

---

tutorials/python-for-loops/index.mdx
tutorials/python-lists-dicts/index.mdx

Add third Python tutorial - for loops

feat(tutorial): add third python tutorial

---

serverless/messaging/concepts.mdx

feat(mnq): update AMQP concept
Relieving "exactly once delivery" from AMQP concept as we cannot guarantee such delivery. 
Moreover, AMQP is not yet a protocol we support so it could raise questions to user.

docs(messaging): feat(mnq) update AMQP concept in-rm-messaging

---

serverless/messaging/reference-content/snssqs-overview.mdx

Typos and re-ordering SQS/SNS to fit the title
Changing typos and taking the SQS first before SNS so it can fit the main title SQS/SNS

docs(messaging): fix(mnq) update Reference in-fix-messaging

---

changelog/july2023/2023-07-25-instances-added-new-availability-zone-ams-3.mdx

feat(changelog): instances-added-new-availability-zone-ams-3 2023-07-25

---

serverless/containers/how-to/add-trigger-to-a-container.mdx

docs(serverless-containers) - specify how triggers messages are sent

---

changelog/july2023/2023-07-26-containers-added-triggers-for-serverless-containers.mdx

feat(changelog): containers-added-triggers-for-serverless-containers 2023-07-26

---

console/my-project/concepts.mdx

https://jira.infra.online.net/browse/MTA-3511

docs(project): added concept info MTA-3511

---

serverless/functions/reference-content/deploy-function.mdx

feat(serverless): missing nodejs as testing framework

---

changelog/july2023/2023-07-28-instances-fixed-zenbleed-incident-response.mdx

feat(changelog): instances-fixed-zenbleed-incident-response 2023-07-28

---

index.mdx

Rename "Scaleway Ideas" to "Request a feature"

docs(index): rename feature request link

---

dedibox-console/cpanel-hosting/reference-content.mdx
managed-services/webhosting/reference-content.mdx
network/vpc/reference-content/vpc-migration.mdx
serverless/containers/how-to/add-trigger-to-a-container.mdx
serverless/functions/how-to/secure-a-function.mdx
tutorials/python-for-loops/index.mdx
tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx

docs(gen): fixed broken links

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/changelog-contribution.yml
.github/workflows/do-not-merge.yml
.github/workflows/draft.yml
.github/workflows/labeler.yml
.github/workflows/remove-draft.yml
docs/PULL_REQUEST_TEMPLATE.md

- Added CODENAMES list to enable tagging of people whenever a PR is opened to edit one of the files listed.
- Added `labeler.yml` to automatically label PRs when they touch specific files
- Added `do-not-merge.yml` workflow
- Updated the pull request template

feat(github): improvements labels

---

.github/labeler.yml
.github/workflows/draft.yml
.github/workflows/remove-draft.yml
changelog/console/october2022/2022-10-06-new-support-plans-changed.mdx

fix(gen): labels

---

.github/workflows/draft.yml
.github/workflows/remove-draft.yml

fix(gen): test

---

.github/workflows/draft.yml
.github/workflows/remove-draft.yml
network/load-balancer/troubleshooting/load-balancer-limitations.mdx

fix(lb): test

---

.github/workflows/draft.yml
.github/workflows/remove-draft.yml
changelog/console/october2022/2022-10-06-new-support-plans-changed.mdx

fix(gen): final one i hope

---

menu/navigation.json
serverless/sql-databases/how-to/add-users.mdx
serverless/sql-databases/how-to/configure-autoscaling.mdx
serverless/sql-databases/how-to/connect-to-a-database.mdx
serverless/sql-databases/how-to/create-a-database.mdx
serverless/sql-databases/how-to/delete-a-database.mdx
serverless/sql-databases/how-to/index.mdx
serverless/sql-databases/how-to/manage-permissions.mdx
serverless/sql-databases/quickstart.mdx

feat(SDB): create how tos ServerlessDB MTA-3455
