docs/FUNDING.yml

Sponsor button is not functional
FUNDING.yml has a sponsor that do not exist and that will never exist
Remove `FUNDING.yml`
---

docs: remove useless funding file

---

storage/block/quickstart.mdx

The persistant mounting command displayed an echo and quotes which created an error if these items are copied as is to fstab.
*Sorry if the format not comply with the requirements, first contribution here*

fix(quickstart block storage) Update command for persistent mounting 

---

tutorials/lb-ingress-controller/index.mdx

The target backend that redirect to coffee-svc was misspelled.
_**Note :** It's late (at the time i do this PR) and I spent a "little bit" of time on it, if that can prevent someone else to live the same..._

fix(tutorials): coffee service name misspelled on lb host rule

---

compute/kubernetes/api-cli/exposing-services.mdx

* fix spec.type to LoadBalancer for nginx, traefik manifests
* fix yaml indentation

docs(kubernetes): fix nginx, traefik service manifests ext-fix-kubernetes

---

compute/containers/reference-content/containers-limitations.mdx
compute/functions/reference-content/functions-limitations.mdx

Limits indicated in the document reference-content/functions-limitations/ and reference-content/containers-limitations/ were not taken into account T&S quotas.
I made a fix proposition

fix(containers/functions): add quotas information on limits

---

compute/functions/how-to/package-function-in-zip.mdx

to match the tutorial on postgres I add psycopg2 to the list of Python Libraries which required C dependecies

add psycopg2 to python C dependencies

---

storage/object/api-cli/object-storage-aws-cli.mdx

The maximum number of requests is one thousand, 100 is the maximum of concurrent ones.

fix(docs): fix multiplication in comment

---

README.md
docs/CONTRIBUTING.md

- missed `HowToStep` type in frontmatter contributing example
- link from README to `frontmatter` anchor was broken

docs(frontmatter): fix step and link

---

.husky/pre-commit
bin/count-invalid-slugs
bin/list-invalid-slugs
bin/slug-regex
commitlint.config.js
docs/CONTRIBUTING.md
package.json

https://jira.infra.online.net/browse/WDOC-223
---
If slugs are not `kebab-case` valid, prod is break
- Add scripts for slugs validation
- use scripts in pre-commit husky hook
- git commit is stopped on slug error!
- set yarn command to manually check slugs
- change slugs with a mix of no "kebab-case" valid formats
- space before/middle/after
- special chars
- uppercase
- `git add . && git commit -m "fake commit"`
- Error should pop, list of no valid slugs should print and husky stop
- `yarn check-slugs` for manual check
- fix slugs
- do manual check again > nothing output
- do fake commit again > linter & conventional commit should run
---

chore: check slugs - WDOC-223

---

.husky/pre-commit
bin/check-pre-commit
bin/count-invalid-slugs
bin/list-invalid-slugs

- Script sh error on Linux (Ubuntu)
- `husky` is calling `pre-commit` script with `sh`. Bash syntax does not work for Linux when it is sh that called the script, even if the hashbang specify bash 
- force check slugs script to be called by `bash` in pre-commit script
- check if Mac OS still right with commit, and the same with an error in `navigation.json` for slug
- check the same under Linux (@RoRoJ 😄 )

chore(precommit): fix error on linux

---

tutorials/traefik-v2-cert-manager/index.mdx

Cert-manager v1.1.0 has trouble managing k8s clusters in 1.23 version.
I updated the documentation to use the v1.6.0 of cert-manager. It implies the solvers.http01.ingress.class must exist in IngressClass
Upgrading from an existing installed v1.1.0 should be done following the documentation, and more importantly, the CRD replacement https://cert-manager.io/docs/installation/upgrading/upgrading-1.1-1.2/

update documentation to use cert-manager v1.6.0

---

tutorials/traefik-v2-cert-manager/index.mdx

I have corrected the errors in the documentation to get your example working on a Kapsule cluster. (Fully tested on a fresh Kapsule cluster with Traefik2 deployed by Kapsule)
I updated the use of a standard Ingress instead of Traefik's IngressRoute.
All these modifications allow your example to work correctly

fix: Make the example work

---

tutorials/self-hosted-repository-gitea/index.mdx

Fix typo for SSH port in tutorial.

docs(fix): typo in tutorial gitea MTA-1932

---

compute/kubernetes/api-cli/using-load-balancer-annotations.mdx

When trying to control the AZ in which a load balancer was created, I had to guess the annotation based on the structure of other documented annotations and it worked.
I propose to add the annotation to the documentation.

docs(kubernetes): document loadbalancer zone annotation

---

tutorials/deploy-nextcloud-s3/index.mdx

It links to ssh key creation, but it should link to API key generation tutorial

fix(tutorial): API key link

---

compute/functions/api-cli/fun-uploading-with-serverless-framework.mdx
compute/functions/reference-content/code-examples.mdx

Doc about Go runtimes >= 1.17 (differs from the old Go runtimes `go113` and `golang`).

feat(functions): add doc about new Go runtimes (1.17 and 1.18)

---

compute/containers/api-cli/restricting-access-to-a-container.mdx

tokens generated from Scaleway API will contain an application_id in its claims, not container_id

docs(container-privacy): fix tokens claims name

---

compute/functions/how-to/package-function-in-zip.mdx

In the `Additional dependencies` python example code block `mkdir` command was mixed with the project directory structure and the indentation  of the file hierarchy was incorrect.
By the way you might want to take a look at the Go examples, the layout seems to differ from the file hierarchy representation for Python and JS examples introduced in #642, as I don't know Go I wasn't able to fix them.

docs(functions): Reformat python code blocks

---

compute/kubernetes/api-cli/managing-storage.mdx

- [ x] Check that the commit messages match our requested structure.
- [ x] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).
Following discution with some customers seeing the "alpha" on this doc, i asked the Kapsule team if the CSI was still in alpha but they confirmed it is now stable and used widely with no known bugs.

docs(kubernetes): "remove alpha from csi" int-rm-kubernetes

---

identity-and-access-management/iam/concepts.mdx
identity-and-access-management/iam/how-to/create-policy.mdx
identity-and-access-management/iam/quickstart.mdx
identity-and-access-management/iam/reference-content/policy.mdx

links within pages that were not indexed in the menu were broken, and therefore not found by the 404 crawl.

fix(core): broken links

---

.github/workflows/changelog-contribution.yml

- Add a github action to automatically generate a pr when a contributor submit a new changelog
- Don't forget to add the `GITHUB_TOKEN` secret, the key is `GH_TOKEN`, follow these [instructions](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)  if you don't know how to do it
- Then use this url `https://api.github.com/repos/scaleway/docs-content/actions/workflows/changelog-contribution.yml/dispatches` and make a post request. You'll need to add the `Bearer Token` (use the github token) (e.g: Authorization: Bearer {GH_TOKEN}) and this line `Accept: application/vnd.github+json`, to the head. Check this [doc](https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event) for more …

ci(POC): add changelog-contribution

---

editor-components.mdx

- Add doc for changelog use in `/editor-component` page
- `yarn clean && yarn develop`
- open http://localhost:8003/editor-components/#log-(changelog)

docs(changelog): howto in editor page WDOC-322

---

compute/messaging/api-cli/python-node-sns.mdx
compute/messaging/api-cli/python-node-sqs.mdx

Hi,
Just a few fixes:
- SQS queue names cannot contain spaces
- the dead letter attribute was missing
It's not tested but I am pretty sure the proposed changes are good.

fix(messaging): few mistakes / typo

---

tutorials/s3cmd/index.mdx

The doc contain this line :
```
host_bucket = %(bucket)s.s3.nl-ams.scw.cloud
```
There is a small typo with a s after bucket variable.

fix(docs): Small typo in s3cmd config

---

compute/containers/how-to/deploy-a-container.mdx

Currently, this link points to the page it is already on, which doesn't help people learn how to upload and then deploy a container.

fix: deploy page should link to upload page, not itself NOPROJECT-XXX

---

tutorials/create-openwrt-image-for-scaleway/index.mdx

Tutorial how to create custom images using the snapshot import feature

docs(tutorial): how to create a custom openWRT image for SCW Instances

---

compute/instances/api-cli/migrating-gp-to-pro.mdx
compute/instances/concepts.mdx

Removing the definition of Backup, and updating the Image definition to match recent changes in the console.

fix(concepts): updated concepts instances

---

compute/instances/troubleshooting/reboot-from-faulty-kernel.mdx

Fixed small display error in command line style formatting

docs(instances): fixed style typo in command line

---

tutorials/traefik-v2-cert-manager/index.mdx

The URL for the cafe example service in the traefik2 tutorial have changed, this is the new url

docs(Kapsule): URL of cafe example for traefik have changed ext-fix-kapsule

---

compute/apple-silicon/how-to/connect-to-mac-mini-m1.mdx

Add instructions for connecting to Mac mini via Remmina

fix(apple): add instructions for Remmina

---

dedibox/kvm-over-ip/how-to/quanta-computer.mdx

Fixed a typo in the how-to for Quanta Computer KVM-over-IP devices

docs(how-to): fix typo quanta kvm

---

network/load-balancer/how-to/create-load-balancer.mdx
network/load-balancer/how-to/set-up-s3-failover.mdx
network/load-balancer/how-to/setup-ssl-offloading.mdx
network/load-balancer/quickstart.mdx

Make it clearer that the S3 failover link for Load Balancer has to be the bucket website URL, not the bucket endpoint

fix(lb): improve bucket website doc

---

index.mdx

Fixed broken slack community link on docs landing page

docs(fix): fixed broken slack community link

---

compute/messaging/reference-content/sns-support.mdx
compute/messaging/reference-content/sqs-support.mdx

Add the tables of which actions are supported by SCW Messaging and Queuing. (Currently/previously hosted on the developers doc)

fix(messaging): add supported actions tables

---

dedibox-network/ipv6/how-to/configure-ipv6-linux.mdx

Hi,
If use pre-up, dhclient might end up with a no current iface found error. Use post-up might be better.

docs(dedibox-configure-ipv6-linux): update document

---

containers/kubernetes/how-to/create-cluster.mdx
containers/kubernetes/quickstart.mdx

Kubernetes console do not offer an "advanced options" button anymore, tags and description have moved under name step.

docs(kapsule): no more advanced options on cluster create page int-fix-k8s

---

compute/instances/api-cli/creating-backups.mdx

The URL to backup an instance was missing the `/servers` part, cf. the API documentation: https://developers.scaleway.com/en/products/instance/api/#post-049a5b

fix(instances): wrong URL to backup an instance

---

changelog/january2023/2023-01-25-kubernetes-removed-kubernetes-1.20-is-no.mdx

feat(changelog): kubernetes-removed-kubernetes-1.20-is-no 2023-01-25

---

containers/kubernetes/how-to/create-cluster.mdx
containers/kubernetes/how-to/create-kosmos-cluster.mdx
containers/kubernetes/how-to/delete-cluster.mdx
containers/kubernetes/how-to/deploy-ingress-controller.mdx
containers/kubernetes/how-to/edit-cluster.mdx
containers/kubernetes/how-to/edit-kosmos-cluster.mdx
containers/kubernetes/how-to/enable-easy-deploy.mdx
containers/kubernetes/how-to/monitor-cluster.mdx
containers/kubernetes/how-to/upgrade-kubernetes-version.mdx

Our tutorials still mentionned COMPUTE, but k8s moved under CONTAINERS not so long ago.

docs(k8s): k8s moved from compute to containers in console Int-fix-k8s

---

compute/instances/how-to/use-boot-modes.mdx

updated information about cloud-init and marked bootscripts as deprecated

docs(instances): updated information about cloud-init and marked bootscripts as deprecated 

---

serverless/messaging/api-cli/connect-aws-cli.mdx

Files needs to have proper indentation, otherwise CLI gives error `Unable to parse config file`

docs(messaging): fix indents for AWS config file

---

dedibox/kvm-over-ip/quickstart.mdx

1 - rename HP by HPE
2 - see a copy/paste problem between IDRAC and ILO I just renamed HPE instead of DELL in the HPE part and I corrected IDRAC to ILO

fix(doc): copy paste problem with ILO part

---

tutorials/proxy-protocol-v2-load-balancer/index.mdx

Refers to https://github.com/scaleway/docs-content/pull/1232.
Just noticed that the indentation isn't correct for the `ingress-nginx` `values.yaml` file ([docs](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml))

fix(docs): helm values indentation

---

managed-services/transactional-email/how-to/generate-api-keys-for-api-and-smtp-sending.mdx
managed-services/transactional-email/how-to/generate-api-keys-for-tem-with-iam.mdx

Hello,
At this time the only Authentification method supported by the smtp server are AUTH PLAIN.
Confirmed by an answer on scaleway community slack,(https://scaleway-community.slack.com/archives/C0358JE0XEK/p1675681143135959?thread_ts=1675618137.698359&cid=C0358JE0XEK)
Regards,

docs(TEM): add important block on supported auth method main

---

changelog/february2023/2023-02-07-kubernetes-removed-container-runtimes-docker-and.mdx

feat(changelog): kubernetes-removed-container-runtimes-docker-and 2023-02-07

---

containers/kubernetes/reference-content/version-support-policy.mdx

Due to an incompatibility of Docker + Cilium, we noticed many clusters with this setup do not work properly on versions 1.21+. That's not something we can patch.
We thus have deprecated Docker from 1.20. 
Clusters on Docker won't be able to migrate to 1.21 any further.

doc(kapsule): docker now deprecated from 1.20

---

menu/navigation.json
serverless/messaging/api-cli/connect-aws-cli.mdx
serverless/messaging/api-cli/sqs-sns-aws-cli.mdx

Create a new API/CLI document for SQS/SNS to contain some of the detailed tutorial information for creating queues/sending messages etc using the AWS CLI that was previously on the developers' website.

fix(messaging): added doc from api

---

serverless/messaging/api-cli/connect-aws-cli.mdx

The example credentials use the wrong format for profile name.
Lookup [format of the files](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-format) for reference. Blocks in credentials file do not have `profile` in it, only the profile name.

fix(messaging): aws cli crendentials profile format

---

serverless/containers/reference-content/containers-limitations.mdx

With the new feature of flexible resources for containers, users will be able to choose memory and CPU limits separately. A criteria on CPU and memory limits is added.

feat(serverless-containers): add CPU and memory limits criteria

---

tutorials/get-started-containers-docker/index.mdx

There are several inconsistencies between kubernetes Part 1 and Part 2:
- Part 2 references a whoami-image, which does not yet exist after part 1 (we push the testapp, but not the whoami app to the registry)
- Hint for Apple Silicons seems to be necessary, since an old whoami-image is used as a base, which does not support arm-architectures
- Use COPY instead of ADD, because ADD can have side effects, which is not intended in this case
- Local-bound docker ports can be accessed via `localhost` instead of the computer's IP-address (which does not give more information at this point in this tutorial, just more confusion)

fix(how-tos): Repair inconsistencies in k8s tutorial part 1

---

storage/object/api-cli/object-storage-aws-cli.mdx

show comment in ~/.aws/config on several lines
Currently the comment is hidden, it requires to scroll horizontally, which is not convenient:
> ![image](https://github.com/scaleway/docs-content/assets/2071331/b90125b6-9cda-408e-93f6-3f2c4bfacaa5)

fix(s3): update object-storage-aws-cli

---

compute/instances/troubleshooting/bootscript-eol.mdx

Specify that the instance should be in the same that as the volume (otherwise the user won't be able to attach the volume and might be confused as to why)
Following Ticket 00509271

Clarify the migration process

---

observability/cockpit/api-cli/configuring-grafana-agent.mdx

The idea is to scrape every minute instead of every 15s to reduce cost of using this example.

docs(cockpit): Increase scrape_timeout to 60s

---

console/my-account/reference-content/account-quotas.mdx

Replaced "Identity validated" with "Payment and identity validated" to clear confusion

fix(docs): added specifications on account quotas

---

.husky/pre-commit
bin/check-pre-commit
observability/index.mdx

- When commit, if no node_modules installed => it will print "⚠️ You must fix slugs in 'menu/navigation.json' before commit"
- First delete your content/node_modules directory
- Delete randomly some stuff in the `menu/navigation.json` (to create error), and try to commit ==> it should tell you to install node-modules
- Install it : `yarn`
- Retry to commit ==> > it should tell you you have to fix you menu/navigation.json
- Fix it and do other modification
- Try to commit ==> should be good

fix(bin): add node_modules check

---

dedibox-network/rpn/how-to/configure-rpnv2.mdx

Configure RPNv2 for Rocky Linux 9 with nmcli
Is a : How to configure Rocky Linux 9 with nmcli to use RPNv2 ?
I have tested the server configuration on both servers.

docs(add): review docs , Configure RPNv2 for Rocky Linux 9 with nmcli

---

changelog/june2023/2023-06-01-load-balancers-removed-sni-routes-to-http.mdx

feat(changelog): load-balancers-removed-sni-routes-to-http 2023-06-01

---

tutorials/k8s-fluentbit-observability/index.mdx

Add Kubernetes category to Fluent Bit tutorial

docs(tutorials): add k8s categories fluentbit tuto

---

storage/block/how-to/mount-and-use-volume.mdx

Fix boot failure issue on Debian with kernel >= 5.3 caused by the fellowing command : 
`echo '/dev/sda /mnt/block-volume ext4 defaults 0 0' >> /etc/fstab`
The boot process on Debian with Kernel >= 5.3 can experience failures due to random volume naming, resulting in intermittent boot issues.
Introduce UID assignment in FSTAB line to ensure consistent volume naming at boot with this command : 
`echo "UUID=$(blkid --output value /dev/sda | head -n1) /mnt/block-volume ext4 defaults 0 0" >> /etc/fstab`

docs(storage): Address potential boot failure on Debian caused by FSTAB command

---

storage/block/how-to/increase-block-volume.mdx

The partition in the example was `sda1` not `sdb1` (simple typo fix)

fix(storage): Disk name was incorrect when increasing object partition

---

console/my-account/reference-content/account-quotas.mdx

Changing the API quotas in the doc because we changed them today in production from 50 to 100

fix(iam): change API key quotas - update made in prod today

---

containers/kubernetes/reference-content/version-support-policy.mdx

Remove v1.21 from supported versions as it is deprecated

docs(k8s): remove deprecated version 1.21

---

compute/instances/troubleshooting/fix-cloud-init-debian12.mdx
menu/navigation.json

Steps to fix the wrong user configuration of cloud-init for Debian 12

docs(instances): fix cloud-init on debian 12

---

network/vpc/api-cli/standalone-pgw-rpn.mdx

Fix typo in shell export command in PGW / RPN howto.

docs(pgw): shell export cmd typo

---

containers/kubernetes/api-cli/exposing-services.mdx

Load Balancer only handle TCP and HTTP service, trying to expose another type of service is not possible using this method.

docs(k8s): add exposed service type information

---

containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx

changed 'Kubernetes' to 'NVIDIA' where appropriate

nit: appropriate naming for operator

---

changelog/september2023/2023-09-01-kubernetes-changed-bumped-images-to-ubuntu.mdx

feat(changelog): kubernetes-changed-bumped-images-to-ubuntu 2023-09-01

---

blocks/header.json

- Testing add new link for Scaleway Learning 
- Just check the link target `/en/learning/`

feat(header): add link

---

changelog/october2023/2023-10-02-apple-silicon-changed-macos-ventura-13-now.mdx

feat(changelog): apple-silicon-changed-macos-ventura-13-now 2023-10-02

---

network/vpc/troubleshooting/autoconfig-not-working.mdx
network/vpc/troubleshooting/private-dns-dhcp-not-working.mdx

Add Troubleshooting information for when debian bullseye instance has no no default route

docs(vpc): Troubleshooting debian bullseye no default route int-add-vpc

---

changelog/october2023/2023-10-18-kubernetes-deprecated-kapsule-clusters-with-only-public.mdx

feat(changelog): kubernetes-deprecated-kapsule-clusters-with-only-public 2023-10-18

---

serverless/containers/how-to/add-trigger-to-a-container.mdx
serverless/functions/how-to/add-trigger-to-a-function.mdx

It is now possible to call private functions and containers from SQS and NATS triggers!
I've also added the "note" in the functions page (it was already in the containers page); and it's valid for both products.
Thanks!

feat(serverless): call private functions and containers from triggers

---

serverless/containers/reference-content/configure-trigger-inputs.mdx
serverless/functions/reference-content/configure-trigger-inputs.mdx

On the "Considerations to configure event retention for trigger inputs" page:
- make an explicit reference to SQS (this is only valid for SQS)
- copy the page to containers (it's also valid for containers)
Thanks!

fix(serverless): update and copy configure event retention page

---

changelog/october2023/2023-10-26-kubernetes-removed-kubernetes-122-is-no-longer-supporte.mdx

feat(changelog): kubernetes-removed-kubernetes-122-is-no-longer-supporte 2023-10-26

---

changelog/february2023/2023-02-07-kubernetes-removed-container-runtimes-docker-and.mdx
containers/kubernetes/how-to/change-container-runtime-interface.mdx
containers/kubernetes/how-to/upgrade-kubernetes-version.mdx
containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx
containers/kubernetes/reference-content/version-support-policy.mdx
menu/navigation.json

Removed outdated CRI migration documentation

docs(k8s): removed outdated documentation

---

faq/databases-for-postgresql-and-mysql.mdx

Remove extensions `chkpass` (deprecated from PG11) and `tsearch2` (deprecated from PG10) from RDB Postgres extensions list in the FAQ.

docs(FAQ): remove deprecated extensions from RDB PostgreSQL extensions list

---

changelog/november2023/2023-11-08-apple-silicon-deprecated-fr-par-1-is-disabled-in-the-ap.mdx

feat(changelog): apple-silicon-deprecated-fr-par-1-is-disabled-in-the-ap 2023-11-08

---

changelog/november2023/2023-11-14-kubernetes-changed-bumped-linux-kernel-to-620-36.mdx

feat(changelog): kubernetes-changed-bumped-linux-kernel-to-620-36 2023-11-14

---

tutorials/deploy-laravel-on-serverless-containers/index.mdx

Remove that comment in Deploying Laravel 10.x on Serverless Containers tutorial : 
`# stubs/php/php-fpm.d/zz-docker.conf`
PHP don't appreciate the "#" and the container crash on launch

docs(tutorial): remove comment that produce error on container launch

---

editor-components.mdx

- Add `HelpBanner` to editor-components.mdx
---
---

docs(help-banner): update editor components

---

changelog/november2023/2023-11-27-object-storage-added-deleteobjects-is-now-applicable-to.mdx

feat(changelog): object-storage-added-deleteobjects-is-now-applicable-to 2023-11-27

---

console/account/reference-content/organization-quotas.mdx
managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

Removed all mentions of hourly quota in the relevant docs, as TEM no longer applies it.

docs(tem): remove mention of hourly quota in docs

---

macros/storage/important-bucket-policy.mdx

fix(s3): update bucket policy warning MTA-3983

---

changelog/december2023/2023-12-19-kubernetes-removed-managed-ingress-controllers-at-clust.mdx

feat(changelog): kubernetes-removed-managed-ingress-controllers-at-clust 2023-12-19

---

containers/kubernetes/how-to/create-cluster.mdx
containers/kubernetes/quickstart.mdx
tutorials/install-cockroachdb-scaleway-instances/index.mdx

Remove all references to "regional Private Network" - no longer necessary to add the regional caveat since this is the new norm.

fix(vpc): remove refs to regional

---

menu/navigation.json
serverless/jobs/reference-content/deploy-job.mdx

docs(srv): add methods to deploy job MTA-4018

---

changelog/january2024/2024-01-04-secret-manager-added-secrets-can-be-set-as-ephemeral.mdx

feat(changelog): secret-manager-added-secrets-can-be-set-as-ephemeral 2024-01-04

---

console/index.mdx
menu/navigation.json

Change "Console" category label to "Account & Billing"

fix(menu): change Console category label 

---

compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx
menu/navigation.json

Fixing DNS resolution with a routed IPv6-only setup on Debian Bullseye

ins(fix): add dns ipv6 only fixing guide

---

compute/instances/troubleshooting/fix-lost-ip-connectivity-on-debian-buster.mdx

- [ x] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).
Add a document describing how to fix loss of IPv6  connectivity on old debian buster instances when they have been migrated to use routed IP.

docs(instances): Fix Buster IPV6 connectivity when routed IP used

---

components.mdx

The idea of this pull request is to let docs team be able to know which product logo is available currently in docs in order to let them choose for `ProductHeader` or `ClickableBanner`

docs(components): add illustration list examples

---

network/load-balancer/reference-content/configuring-backends.mdx

Reformat and rephrase the existing information on balancing methods, so that it's more clear for users.

fix(lb): reformat balancing method info

---

network/load-balancer/concepts.mdx
network/load-balancer/reference-content/configuring-backends.mdx
network/load-balancer/reference-content/configuring-health-checks.mdx

In response to user testing showing that Proxy Protocol confused users (especially the different versions, and what happens if they activate it or not), enrich the doc about Proxy Protocol.
Also, Proxy Protocol should always be capitalized as a specific named protocol - correct this in the doc.
After doc is enriched, look at how to better integrate this doc/explanation in the console.

fix(es): add more info about proxy protocol

---

changelog/july2023/2023-07-18-private-networks-changed-virtual-private-cloud-is.mdx
changelog/march2023/2023-03-30-private-networks-added-regional-private-networks-is.mdx
changelog/network/june2022/2022-06-13-private-networks-added-smtp-public-gw.mdx
menu/changelogs.json
network/vpc/index.mdx

Modify the changelog category so that it's "VPC" (vpc) instead of "Private Networks" (private-networks)

fix(docs): modify changelog vpc category

---

observability/cockpit/concepts.mdx
observability/cockpit/how-to/configure-alerts-for-scw-resources.mdx

The Grafana alert manager is inactive in Grafana, and users should select the **Scaleway Alerting** alert manager. I have added this information in the relevant documentation pages

feat(cockpit): add information about the alert manager

---

faq/cockpit.mdx

A user has raised a question about whether pricing plans are scoped per Project or Organization. I have added the relevant information in the documentation.

add(cockpit): added info on pricing plan pricing

---

containers/kubernetes/reference-content/version-support-policy.mdx

Delayed 1.23 EOS due to temp upgrade deactivation.

chore(k8s): delayed 1.23 EOS

---

changelog/february2024/2024-02-28-kubernetes-removed-scaleway-kubernetes-products-no-long.mdx

feat(changelog): kubernetes-removed-scaleway-kubernetes-products-no-long 2024-02-28

---

compute/instances/how-to/identify-devices.mdx
compute/instances/reference-content/manual-configuration-private-ips.mdx

Add a how-to regarding the identification of devices in an instance :
- attached Instance block storage `b_ssd` devices
- attached VPC Private Networks

feat(instances): add how-to on devices identification in instance

---

menu/changelogs.json

Changing the value of the "Security and Identity" icon so it fits the value of the Ultraviolet `<CategoryIcon />` component.
https://storybook.ultraviolet.scaleway.com/?path=/docs/icons-categoryicon--docs
Preview of the filters in the future changelog page :

style(icon): change iam icon to match UV component

---

changelog/march2024/2024-03-25-postgresql-and-mysql-added-ability-to-remove-public-end.mdx

feat(changelog): postgresql-and-mysql-added-ability-to-remove-public-end 2024-03-25

---

faq/cockpit.mdx

Added an FAQ question to announce that Grafana dashboards for Scaleway resources created before April of 2024 will need to be updated.

feat(cpt): add faq question

---

containers/kubernetes/reference-content/using-kapsule-autoheal-feature.mdx
containers/kubernetes/reference-content/using-kubernetes-autoheal-feature.mdx
menu/navigation.json

feat(k8s): doc autoheal feature

---

changelog/march2024/2024-03-26-kubernetes-changed-routed-ips-are-now-default-on-kubern.mdx

feat(changelog): kubernetes-changed-routed-ips-are-now-default-on-kubern 2024-03-26

---

console/billing/index.mdx

The wrong links were displaying on the billing homepage, this PR corrects them.

fix(billing): fix links

---

bare-metal/elastic-metal/reference-content/elastic-metal-understanding-rv1-usage.mdx

Recommended boot partition filesystem on RV1 was changed to FAT32 because of a bug with the bootloader on highly fragmented EXT4 partitions. EXT4 will keep working as before (incl. the bugs), so it's not a breaking change.

fix(bare-metal): boot filesystem for RV1 was changed to FAT32

---

changelog/april2024/2024-04-26-apple-silicon-changed-macos14-sonoma-is-now-available.mdx

feat(changelog): apple-silicon-changed-macos14-sonoma-is-now-available 2024-04-26

---

labs/ipfs-pinning/api-cli/ipfs-get-content.mdx

Change of library that allows communication with the local ipfs api to use the kubo client directly.
This pull request follows the opening of this issue: #3121.

fix(ipfs): died lib ipfs retrieve content

---

changelog/may2024/2024-05-14-jobs-added-serverless-jobs-max-timeout-increased-to-24h.mdx

feat(changelog): jobs-added-serverless-jobs-max-timeout-increased-to-24h 2024-05-14

---

ai-data/managed-inference/how-to/create-deployment.mdx
ai-data/managed-inference/how-to/delete-deployment.mdx
ai-data/managed-inference/how-to/monitor-deployment.mdx
ai-data/managed-inference/quickstart.mdx
ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
ai-data/managed-inference/reference-content/openai-compatibility.mdx
ai-data/managed-inference/reference-content/wizardlm-70b-v1.0.mdx

- Since shire/console release 3.306.0, users can add and remove public or private endpoints to a deployment after creation. This was the main intent of this pull request. Users can also create a new private network if none was in their organization already.
- Noticed some odd tags or missing ones, added some here and there
- Removed hardcoded list of models because it has been, and will continue to expand fast

feat(ifr): network settings are not immutable anymore

---

changelog/may2024/2024-05-17-apple-silicon-changed-macos-14-is-now-available-on-all-.mdx

feat(changelog): apple-silicon-changed-macos-14-is-now-available-on-all- 2024-05-17

---

storage/block/quickstart.mdx

Specified that we can only attach volumes to Instances vs cloud products which was confusing

docs(block-storage): clarify quickstart

---

changelog/may2024/2024-05-22-kubernetes-removed-kapsule-clusters-with-only-public-ip.mdx

feat(changelog): kubernetes-removed-kapsule-clusters-with-only-public-ip 2024-05-22

---

containers/kubernetes/reference-content/version-support-policy.mdx

chore(k8s): remove 1.24 from version support

---

changelog/may2024/2024-05-22-kubernetes-removed-scaleway-kubernetes-products-no-long.mdx

feat(changelog): kubernetes-removed-scaleway-kubernetes-products-no-long 2024-05-22

---

containers/kubernetes/how-to/use-nvidia-gpu-operator.mdx

The doc stated only 2 GPU types. Since end 2023, three new GPU instances have been introduced: H100 PCIe, L40s, L4. 
The revised doc clarifies the current scope.

chore(k8s): expanding support of GPU operator

---

serverless/messaging/reference-content/sns-support.mdx

SNS RedrivePolicies are disabled for now, we will work on making them work later, after GA.

fix(messaging): support for SNS RedrivePolicy is disabled for now

---

bare-metal/elastic-metal/how-to/use-private-networks.mdx

Added optional step to explain how to persist the adding of a private network configuration for elastic metal servers with netplan.
Source page: https://www.scaleway.com/en/docs/bare-metal/elastic-metal/how-to/use-private-networks/#how-to-configure-the-network-interface-on-your-elastic-metal-server-for-private-networks

docs(elastic-metal): added step to persist private network configuration across reboots

---

tutorials/strapi-app-serverless-containers-sqldb/index.mdx

docs(tutorials): Add SDB x Containers x Strapi tutorial MTA-4593

---

bare-metal/elastic-metal/how-to/use-private-networks.mdx
menu/navigation.json
partners/index.mdx
partners/partner-space/concepts.mdx
partners/partner-space/how-to/add-client.mdx
partners/partner-space/how-to/edit-client-information.mdx
partners/partner-space/how-to/index.mdx
partners/partner-space/how-to/lock-client-organization.mdx
partners/partner-space/how-to/unlock-client-organization.mdx
partners/partner-space/index.mdx
partners/partner-space/quickstart.mdx

Added a new category: Partners
+ Sub-category: Partner Space
This documentation explains how to use the upcoming Partner Space. In the future, this category will also include general information about Partners (e.g., how to become a Scaleway Partner). 
Do not merge until the Partner Center is released

feat(acc): partner space doc

---

menu/navigation.json
storage/object/troubleshooting/api-key-does-not-work.mdx
storage/object/troubleshooting/cannot-access-data.mdx
storage/object/troubleshooting/cannot-delete-bucket.mdx
storage/object/troubleshooting/cannot-restore-glacier.mdx
storage/object/troubleshooting/lost-bucket-access-bucket-policy.mdx
storage/object/troubleshooting/low-performance.mdx

docs(s3): add troubleshooting pages MTA-4640

---

bare-metal/elastic-metal/api-cli/elastic-metal-with-cli.mdx

The command `scw account ssh-key list` does not seem to exist anymore.
Therefore this commit makes use of the new `scw iam` command.

fix(bare-metal): Use iam ssh-key instead of account ssh-key

---

serverless/sql-databases/api-cli/secure-connection-ssl-tls.mdx

docs(sdb): add new frameworks to SSL/TLS MTA-4594

---

bare-metal/elastic-metal/reference-content/elastic-metal-understanding-rv1-usage.mdx

Add documentation on how to upgrade EM-RV1 Linux kernel.

feat(bare-metal): document kernel upgrades on EM-RV1 servers

---

changelog/june2024/2024-06-28-sql-databases-changed-serverless-sql-database-is-now-in.mdx

feat(changelog): sql-databases-changed-serverless-sql-database-is-now-in 2024-06-28

---

serverless/sql-databases/reference-content/known-differences.mdx

Adding limitations of the product regarding pg_advisory_lock and discard all commands.

fix(rdb): update known-differences

---

compute/gpu/index.mdx

The links of the index page of GPU Instances were all leading to Instances pages. Links updated to lead users to GPU Instances content.

fix(gpu): correction of index page links

---

changelog/july2024/2024-07-02-functions-added-python-312-runtime-now-available.mdx

feat(changelog): functions-added-python-312-runtime-now-available 2024-07-02

---

bare-metal/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx
menu/navigation.json

- rename RV1 page
- document kernel update options

fix(bare-metal): rename RV1 page and document kernel update options

---

serverless/sql-databases/reference-content/known-differences.mdx

Added that Serverless SQL Database does not support installing PostgreSQL extensions yet.

fix:known-differences.mdx

---

blocks/header.json

- Link in mobile navigation to Scaleway Learning is not correct
- This MR change link in a configuration JSON

fix(header): fix header link to scaleway-learning

---

ai-data/managed-inference/reference-content/llama-3-70b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3-8b-instruct.mdx

- Llama3 70B is now available in FP8 quantization, INT8 is deprecated.
- Llama3 8b is now available in FP8 quantization, BF16 remains default.

feat(inference): FP8 quantizations

---

changelog/july2024/2024-07-23-managed-inference-changed-models-now-support-longer-and.mdx

feat(changelog): managed-inference-changed-models-now-support-longer-and 2024-07-23

---

compute/instances/api-cli/attaching-a-volume.mdx

As explained [here](https://www.scaleway.com/en/developers/api/instance/#technical-information), the `volumes` field is
> a dictionary with a minimum of one key ("0") whose value is another object setting parameters for that volume. Additional keys for additional volumes should increment by 1 each time (the second volume would have a key of 1.)
Futhermore, a block storage volume (the low latency block volume, not the legacy block volume) has the type `sbs_volume`.

fix: wrong volumes field in curl examples ext-fix-instances

---

network/ipam/index.mdx
network/load-balancer/index.mdx
network/public-gateways/index.mdx
network/vpc/index.mdx
serverless/messaging/index.mdx

For some reason network products (and M&Q) were using the wrong illustration on product homepages for the API banner. This PR fixes to use the correct illustration.

fix(doc): illustrations

---

bare-metal/elastic-metal/how-to/configure-flexible-ipv6.mdx
bare-metal/elastic-metal/how-to/configure-ipv6-hypervisor.mdx
dedibox-network/ip-failover/how-to/configure-network-virtual-machine.mdx
dedibox-network/ipv6/how-to/debug-ipv6.mdx
dedibox-network/network/how-to/configure-network-netplan.mdx
tutorials/configure-ipv6-virtual-machine-esxi/index.mdx

docs(em): fix netplan ipv6 config

---

ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx

- Mixtral 8x7B is now available in FP8 quantization, INT8 is deprecated.

docs(inference): Mixtral 8x7B switch to FP8 quantization int-ai-fp8

---

bare-metal/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx

Mention ghostwrite attack on EM-RV1.

fix(bare-metal): mention ghostwrite attack on EM-RV1

---

console/account/quickstart.mdx

After testing in my Scaleway console, I realized the workflow changed. 
There is only one workflow now, i.e., close account. There is not a separate workflow for deactivating an Organization.
Consequently, we can embed the existing content, How To Close An Account.

fix(account): streamline section about closing an account

---

faq/apple-silicon.mdx

Removed an unnecessary trailing space from the Apple Silicon FAQ for testing purposes.

docs(apple-silicon): removed space

---

faq/serverless-containers.mdx

While looking into something for a client, I noticed a section in the Serverless Containers FAQ is slightly out-of-date since it's now possible to switch the protocol via the console. See screenshot:
(It's a very minor point, but I figure I might as well submit a PR to update it)
Cheers have a great day!

fix(serverless): remove note about protocol switching not being available in the console

---

faq/billing.mdx

Old wording could be understood as all European B2B customers are exempted from VAT, which is not the case for French customers

fix(faq): clarify VAT exemption for french customers

---

observability/cockpit/how-to/send-metrics-with-grafana-alloy.mdx

The standard extension for alloy configuration file is now .alloy

chore(cockpit): use alloy extension for alloy agent

---

partners/partner-space/how-to/grant-access-to-partner-space.mdx

Added a Guideflow demo
Do not merge until the Guideflow component is fixed

fix(partners): docs update

---

console/billing/how-to/add-payment-method.mdx

Added a Guideflow to explain how to validate a payment method

fix(bil): test guideflow

---

bare-metal/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx
compute/instances/how-to/migrate-routed-ips.mdx
compute/instances/reference-content/identify-devices.mdx
containers/kubernetes/api-cli/changing-control-plane-offer.mdx
containers/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
faq/instances.mdx
faq/kubernetes.mdx

Docs content review for Elastic Metal, Instances and Kubernetes products

docs(chore): review documentations

---

ai-data/managed-inference/how-to/managed-inference-with-private-network.mdx

Nitpick: a user told me most of our product docs refer to ED keys and not RSA type, for the sake of consistency, switching to this type.

fix(ai): moving command from RSA to ED key

---

changelog/september2024/2024-09-18-managed-inference-added-json-mode-and-structured-output.mdx

feat(changelog): managed-inference-added-json-mode-and-structured-output 2024-09-18

---

ai-data/generative-apis/how-to/use-structured-outputs.mdx
ai-data/managed-inference/how-to/create-deployment.mdx
bare-metal/elastic-metal/how-to/kubernetes-on-riscv.mdx
containers/kubernetes/reference-content/version-support-policy.mdx
menu/navigation.json
tutorials/migrate-data-rclone/index.mdx

Documentation content review for 
- Managed Inference
- Elastic Metal
- Kubernetes
- Tutorial

chore(gen): docs content review 2024-09-23

---

faq/serverless-containers.mdx
faq/serverless-jobs.mdx

feat(serverless): note about ephemeral storage pricing

---

serverless/containers/reference-content/containers-limitations.mdx
serverless/containers/troubleshooting/common-errors.mdx
serverless/jobs/reference-content/jobs-limitations.mdx
serverless/jobs/troubleshooting/common-errors.mdx

fix(serverless): improve architecture documentation

---

bare-metal/elastic-metal/how-to/create-server.mdx

Added public bandwidth option to order Elastic Metal documentation

docs(em): update order elastic metal doc

---

faq/databases-for-redis.mdx
managed-databases/redis/api-cli/managing-username-and-password.mdx
managed-databases/redis/api-cli/using-pub-sub-feature.mdx
managed-databases/redis/concepts.mdx
managed-databases/redis/how-to/configure-advanced-settings-redis.mdx
managed-databases/redis/how-to/connect-to-redis-database-instance.mdx
managed-databases/redis/how-to/create-a-database-for-redis.mdx
managed-databases/redis/how-to/delete-a-database-for-redis.mdx
managed-databases/redis/how-to/manage-allowed-ip-addresses-redis.mdx
managed-databases/redis/how-to/scale-up-a-database-for-redis.mdx
managed-databases/redis/quickstart.mdx
managed-databases/redis/reference-content/default-user-permissions.mdx
managed-databases/redis/reference-content/ensuring-data-persistence.mdx

Add this mention in all Redis pages (as per Redis guidelines)
```
Redis is a trademark of Redis Labs Ltd. Any rights therein are reserved to Redis Labs Ltd. Any use by Scaleway is for referential purposes only and does not indicate any sponsorship, endorsement or affiliation between Redis and Scaleway.
```

fix(red): add note

---

ai-data/generative-apis/api-cli/using-chat-api.mdx
ai-data/generative-apis/api-cli/using-generative-apis.mdx
ai-data/generative-apis/how-to/query-text-models.mdx
ai-data/generative-apis/quickstart.mdx

- CURL script is missing a backslash to interpret the --data payload properly
- clarity and consistency around API key (users tend to use their key id instead of expected secret key, leading to 403 errors)

fix(ai): edited per beta tests feedbacks

---

faq/loadbalancer.mdx
faq/messaging-and-queuing.mdx
faq/private-networks.mdx
faq/public-gateways.mdx

fix(faq): review faqs

---

serverless/sql-databases/reference-content/known-differences.mdx

Fix and align wording on PostgreSQL commands which cannot be performed. Add a workaround snippet regarding SET/RESET features inside a transaction.

Serverless SQL Database: Update known-differences.mdx

---

serverless/sql-databases/troubleshooting/connection-errors.mdx

Add documentation on several unsupported features from Serverless SQL Database leading to errors when performed.

Serverless SQL Database - Update connection-errors.mdx

---

ai-data/managed-inference/reference-content/llama-3-70b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3-8b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3.1-70b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
ai-data/managed-inference/reference-content/mistral-7b-instruct-v0.3.mdx
ai-data/managed-inference/reference-content/mistral-nemo-instruct-2407.mdx
ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
ai-data/managed-inference/reference-content/openai-compatibility.mdx
ai-data/managed-inference/reference-content/sentence-t5-xxl.mdx
ai-data/managed-inference/reference-content/wizardlm-70b-v1.0.mdx

In order to enable a playground UI we change the domain name we use for public endpoints in all new deployments starting from today October 30th 2024.
This change is backwards compatible with deployments using a public endpoint in scw.cloud.

feat(ai): changed domain from scw.cloud to scaleway.com

---

observability/cockpit/concepts.mdx

Replace "managed alerts" with "preconfigured alerts".

docs(cpt): update wording for alerts

---

tutorials/install-github-actions-runner-mac/index.mdx

feat(aps): add survey banner

---

tutorials/using-bucket-website-with-mkdocs/index.mdx

The anchor did not work so I removed it.

docs(tuto): fix

---

ai-data/generative-apis/how-to/use-structured-outputs.mdx

Adding a missing param for OpenAI compatibility

fix(ai): add properties for OpenAI compat

---

serverless/containers/concepts.mdx
serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/reference-content/containers-limitations.mdx

feat(containers): details on port variable

---

bin/check-review-dates.py
tutorials/ceph-cluster/index.mdx
tutorials/create-deploy-staging-site-cpanel/index.mdx
tutorials/deploy-big-blue-button/index.mdx
tutorials/easydeploy-argocd/index.mdx
tutorials/easydeploy-gitlab-server/index.mdx
tutorials/easydeploy-grafana/index.mdx
tutorials/easydeploy-vault/index.mdx
tutorials/getting-started-with-kops-on-scaleway/index.mdx
tutorials/install-cockroachdb-scaleway-instances/index.mdx
tutorials/install-golang-ubuntu-bionic/index.mdx
tutorials/install-php-composer/index.mdx
tutorials/installation-jekyll/index.mdx
tutorials/jitsi-debian/index.mdx
tutorials/jitsi-ubuntu-bionic/index.mdx
tutorials/lb-firewall-haproxy-pfsense/index.mdx
tutorials/matomo-analytics/index.mdx
tutorials/minikube-elastic-metal/index.mdx
tutorials/proxmox-softraid/index.mdx
tutorials/run-messaging-platform-with-rocketchat/index.mdx
tutorials/run-nodejs-express-server-on-serverless-containers/index.mdx
tutorials/run-python-flask-server-on-serverless-container/index.mdx
tutorials/setup-ampere-ai-framework-arm-instances/index.mdx
tutorials/stop-outgoing-spam/index.mdx
tutorials/transform-bucket-images-triggers-functions-set-up/index.mdx

Fix validation_frequency problem

fix(docs): fix validation bot check for frequency

---

changelog/october2024/2024-10-09-apple-silicon-added-macos-sequoia-15-available.mdx

feat(changelog): apple-silicon-added-macos-sequoia-15-available 2024-10-09

---

tutorials/deploy-awstats/index.mdx
tutorials/get-started-containers-docker/index.mdx
tutorials/get-started-deploy-kapsule/index.mdx
tutorials/getting-started-with-kops-on-scaleway/index.mdx
tutorials/hadoop/index.mdx
tutorials/hestiacp/index.mdx
tutorials/migrate-mysql-databases-postgresql-pgloader/index.mdx
tutorials/python-lists-dicts/index.mdx
tutorials/self-hosted-repository-gitea/index.mdx
tutorials/send-sms-iot-device-twilio/index.mdx
tutorials/setup-elastic-metal-proxmox-cluster-with-private-networks/index.mdx
tutorials/setup-nomad-cluster/index.mdx
tutorials/use-container-registry-github-actions/index.mdx
tutorials/zammad-ticketing/index.mdx

chore(tuto): tutorials content review 2024-10-08

---

serverless/containers/reference-content/containers-limitations.mdx
serverless/containers/troubleshooting/common-errors.mdx
serverless/functions/reference-content/functions-limitations.mdx
serverless/functions/troubleshooting/common-errors.mdx

Add a section about versioning and rollback for serverless functions and containers in reference content

docs(serverless): add Versioning and rollback section

---

bare-metal/elastic-metal/how-to/configure-disk-partitions.mdx
bare-metal/elastic-metal/how-to/create-server.mdx
menu/navigation.json

feat(em): add custom partitioning

---

tutorials/how-to-implement-rag-generativeapis/index.mdx
tutorials/processing-images-structured-outputs-pixtral/index.mdx

fix(ai): fix categories

---

compute/instances/how-to/migrate-volumes-snapshots-to-sbs.mdx

Added details for SBS migration using the CLI

feat(ins): add sbs migration with cli

---

faq/serverless-sql-databases.mdx
serverless/sql-databases/reference-content/known-differences.mdx

docs(sdb): add links to supported extension doc MTA-5139

---

developer-tools/scaleway-cli/quickstart.mdx
developer-tools/scaleway-cli/reference-content/environment-variables.mdx
developer-tools/scaleway-sdk/reference-content/environment-variables.mdx
developer-tools/terraform/reference-content/environment-variables.mdx
faq/serverless-sql-databases.mdx
macros/developer-tools/scaleway-environment-variables.mdx
serverless/functions/how-to/test-a-function.mdx
serverless/functions/reference-content/deploy-function.mdx

chore(gen): documentation review MTA-5126

---

managed-services/transactional-email/how-to/add-spf-dkim-records-to-your-domain.mdx

fix(tem): fix spf record example

---

network/ipam/concepts.mdx
network/ipam/index.mdx
network/vpc/how-to/create-private-network.mdx
network/vpc/index.mdx

Add links to new best practice guides

fix(nw): add links to new docs

---

tutorials/how-to-implement-rag/index.mdx

fix(inference): env variable

---

compute/instances/reference-content/add-instance-specific-ssh-keys-using-tags.mdx
faq/transactional-email.mdx

fix(gen): fix 404s

---

compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye.mdx

Fixed some typos in troubleshooting article : [Fixing DNS resolution with a routed IPv6-only setup on Debian Bullseye](https://www.scaleway.com/en/docs/compute/instances/troubleshooting/fix-dns-routed-ipv6-only-debian-bullseye/)

fix(instances): fix typos

---

network/domains-and-dns/how-to/manage-dns-records.mdx
tutorials/backup-dedicated-server-s3-duplicity/index.mdx
tutorials/create-wordpress-instances-cli/index.mdx
tutorials/deploy-nextcloud-s3/index.mdx
tutorials/foreman-puppet/index.mdx
tutorials/glusterfs/index.mdx
tutorials/powerdns-ubuntu-bionic/index.mdx
tutorials/pushing-metrics-logs-from-scw-instance/index.mdx
tutorials/setup-lamp-stack-ubuntu2204/index.mdx
tutorials/setup-moodle/index.mdx
tutorials/setup-postfix-ubuntu-bionic/index.mdx
tutorials/socket-io/index.mdx
tutorials/strapi/index.mdx

chore(tutorial): content review

---

managed-services/transactional-email/reference-content/smtp-configuration.mdx

The documentation does not clearly stipulate that the connection must be TTL/SSL encrypted.

doc(tem): fix indicates encryption is mandatory

---

managed-services/transactional-email/reference-content/tem-capabilities-and-limits.mdx

Update information about Transactional Email capabilities and limits

feat(tem): update quota information

---

observability/cockpit/api-cli/configuring-grafana-agent.mdx
observability/cockpit/reference-content/cockpit-limitations.mdx
serverless/containers/how-to/add-trigger-to-a-container.mdx
serverless/functions/how-to/add-trigger-to-a-function.mdx
serverless/functions/how-to/test-a-function.mdx
serverless/functions/reference-content/functions-handlers.mdx
serverless/messaging/api-cli/connect-aws-cli.mdx
serverless/messaging/api-cli/nats-cli.mdx
serverless/messaging/api-cli/python-node-sns.mdx
serverless/messaging/how-to/monitor-mnq-cockpit.mdx
serverless/messaging/reference-content/nats-overview.mdx
serverless/messaging/reference-content/sns-overview.mdx
serverless/messaging/reference-content/sqs-overview.mdx

chore(gen): review documentation MTA-5152

---

containers/kubernetes/how-to/edit-kosmos-cluster.mdx

https://feature-request.scaleway.com/posts/973/be-able-to-upgrade-kosmos-node-in-place

feat: add warning about limitations of kosmos upgrade

---

faq/serverless-containers.mdx
faq/serverless-functions.mdx

Add two new entries in serverless functions/containers FAQ

docs(serverless): add entries in serverless FAQ

---

faq/containerregistry.mdx
faq/serverless-containers.mdx
faq/serverless-jobs.mdx
macros/serverless/container-registry-note.mdx
serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/quickstart.mdx
serverless/containers/troubleshooting/common-errors.mdx
serverless/jobs/how-to/create-job-from-external-registry.mdx
serverless/jobs/quickstart.mdx
serverless/jobs/troubleshooting/common-errors.mdx

docs(SRV): add note on external container registries MTA-5165

---

ai-data/managed-inference/how-to/managed-inference-with-private-network.mdx
ai-data/managed-inference/reference-content/llama-3-70b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3-8b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3.1-70b-instruct.mdx
ai-data/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
ai-data/managed-inference/reference-content/mistral-7b-instruct-v0.3.mdx
ai-data/managed-inference/reference-content/mistral-nemo-instruct-2407.mdx
ai-data/managed-inference/reference-content/mixtral-8x7b-instruct-v0.1.mdx
ai-data/managed-inference/reference-content/pixtral-12b-2409.mdx
ai-data/managed-inference/reference-content/sentence-t5-xxl.mdx
ai-data/managed-inference/reference-content/wizardlm-70b-v1.0.mdx

For incoming inference requests, we used to accept partial names: owner/model, owner/model:quant, or just model.
This has to change to a unique `owner/model:quant` format
The doc is evolving accordingly to avoid any bad practice in future.

fix(inference): changed to full names everywhere

---

network/public-gateways/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx

fix(pgw): note recommended solution

---

serverless/functions/how-to/package-function-dependencies-in-zip.mdx
serverless/messaging/api-cli/python-node-sqs.mdx
serverless/messaging/api-cli/sqs-sns-aws-cli.mdx
serverless/messaging/reference-content/limitations.mdx

chore(GEN): documentation review MTA-5176

---

identity-and-access-management/iam/reference-content/permission-sets.mdx

I added the permission sets that were not documented for products that in GA or soon in GA, and that will not disappear soon. 
For the time being, I did not add:
Audit Trail
Interlink
DDL
AI products
IPFS

feat(IAM): Add undocumented permission sets

---

bare-metal/apple-silicon/troubleshooting/cant-create-apple-account.mdx
menu/navigation.json
tutorials/install-github-actions-runner-mac/index.mdx

feat(aps): add troubleshooting apple id

---

managed-services/webhosting/reference-content/php-version-overview.mdx
menu/navigation.json

feat(wbh): add php version overview

---

containers/kubernetes/reference-content/modifying-kernel-parameters-kubernetes-cluster.mdx
menu/navigation.json

feat(k8s): add modifying kernel documentation

---

observability/cockpit/index.mdx

Fixing link towards DCGM exporter tutorial in Cockpit Overview Documentation page

fix(cockpit): Link to DCGM exporter tutorial

---

changelog/october2024/2024-10-25-managed-inference-added-support-for-function-calling.mdx

feat(changelog): managed-inference-added-support-for-function-calling 2024-10-25

---

serverless/containers/how-to/deploy-a-container-from-external-container-registry.mdx
serverless/containers/how-to/deploy-a-container-from-scaleway-container-registry.mdx
serverless/containers/troubleshooting/common-errors.mdx
serverless/functions/how-to/create-a-function.mdx
serverless/functions/troubleshooting/common-errors.mdx
serverless/jobs/how-to/create-job-from-external-registry.mdx
serverless/jobs/how-to/create-job-from-scaleway-registry.mdx
serverless/jobs/troubleshooting/common-errors.mdx

docs(srv): add notes and troubleshooting on encoding secrets MTA-5183

---

faq/serverless-containers.mdx
faq/serverless-functions.mdx
faq/serverless-jobs.mdx

fix(serverless): faq title level

---

faq/serverless-jobs.mdx
menu/navigation.json
serverless/jobs/concepts.mdx
serverless/jobs/how-to/create-job-from-external-registry.mdx
serverless/jobs/how-to/create-job-from-scaleway-registry.mdx
serverless/jobs/how-to/reference-secret-in-job.mdx
serverless/jobs/quickstart.mdx

docs(srv): add SEM x Jobs documentation MTA-5199

---

serverless/containers/how-to/secure-a-container.mdx
tutorials/create-serverless-scraping/index.mdx
tutorials/deploy-laravel-on-serverless-containers/index.mdx
tutorials/encode-videos-using-serverless-jobs/index.mdx
tutorials/large-messages/index.mdx
tutorials/manage-instances-with-terraform-and-functions/index.mdx
tutorials/snapshot-instances-jobs/index.mdx
tutorials/strapi-app-serverless-containers-sqldb/index.mdx

feat(serverless): fix somesyntax highlighting

---

serverless/containers/concepts.mdx
serverless/functions/concepts.mdx

feat(serverless): advanced cold starts doc

---

compute/instances/reference-content/add-instance-specific-ssh-keys-using-tags.mdx
compute/instances/reference-content/understanding-automatic-network-hot-reconfiguration.mdx
compute/instances/reference-content/understanding-qemu-guest-agent.mdx
menu/navigation.json

added: Understanding the QEMU Guest Agent in Scaleway Instances

feat(instances): understanding qga

---

managed-services/webhosting/concepts.mdx
tutorials/configure-chef-ubuntu-xenial/index.mdx
tutorials/configure-failover-proxmox/index.mdx
tutorials/configure-ipv6-virtual-machine-esxi/index.mdx
tutorials/configure-netbox-managed-postgresql-database/index.mdx
tutorials/configure-nextcloud-ubuntu/index.mdx
tutorials/configure-nginx-lets-encrypt/index.mdx
tutorials/configure-tem-smtp-with-wordpress-plugin/index.mdx
tutorials/deploy-penpot-with-docker-instantapp/index.mdx
tutorials/sinatra/index.mdx
tutorials/store-s3-cyberduck/index.mdx
tutorials/store-wp-mediacloud-s3/index.mdx
tutorials/systemd-essentials/index.mdx
tutorials/terraform-quickstart/index.mdx
tutorials/trigger-ifttt-actions/index.mdx
tutorials/wordpress-lemp-stack-focal/index.mdx

chore(tutorials): review

---

serverless/jobs/quickstart.mdx
storage/object/concepts.mdx

fix(s3): fix rebase error

---

tutorials/building-ai-application-function-calling/index.mdx

- Missed an export for an env variable used in tutorial
- Better examples

fix(ai): missing export in function calling tutorial

---

changelog/october2024/2024-10-30-managed-inference-added-terraform-support.mdx

feat(changelog): managed-inference-added-terraform-support 2024-10-30

---

developer-tools/scaleway-cli/quickstart.mdx

feat(cli): add information for cli installation

---

ai-data/managed-inference/reference-content/moshika-0.1-8b.mdx
ai-data/managed-inference/reference-content/moshiko-0.1-8b.mdx

Add new models to reference content of managed inference products.

docs(ifr): add documentation for moshi

---

ai-data/generative-apis/api-cli/understanding-errors.mdx
ai-data/generative-apis/api-cli/using-chat-api.mdx
ai-data/generative-apis/how-to/query-embedding-models.mdx
ai-data/generative-apis/how-to/query-language-models.mdx
ai-data/generative-apis/how-to/query-vision-models.mdx
ai-data/generative-apis/how-to/use-function-calling.mdx
ai-data/generative-apis/how-to/use-structured-outputs.mdx
ai-data/generative-apis/quickstart.mdx
ai-data/generative-apis/reference-content/rate-limits.mdx
ai-data/generative-apis/reference-content/supported-models.mdx
menu/navigation.json

feat(genapi): public beta launch

---

console/account/how-to/log-in-to-the-console.mdx
console/account/troubleshooting/cannot-log-into-my-account.mdx

Added GitHub to the list of external providers that can be used for SSO login

fix(acc): update sso login docs

---

console/account/how-to/change-console-appearance.mdx
developer-tools/scaleway-cli/reference-content/scaleway-configuration-file.mdx
developer-tools/scaleway-sdk/reference-content/scaleway-configuration-file.mdx
developer-tools/terraform/reference-content/scaleway-configuration-file.mdx
macros/developer-tools/scaleway-configuration-file.mdx
serverless/containers/how-to/create-auth-token-from-console.mdx
serverless/containers/how-to/monitor-container.mdx
serverless/containers/reference-content/configure-trigger-inputs.mdx
serverless/functions/how-to/monitor-function.mdx

chore(gen): documentation review MTA-5202

---

changelog/november2024/2024-11-07-edge-services-changed-edge-services-redirects-http-to-h.mdx

feat(changelog): edge-services-changed-edge-services-redirects-http-to-h 2024-11-07

---

index.mdx

docs(gen): renew tutorial showcase on index

---

tutorials/get-started-kubernetes-storage/index.mdx

Simple fix : 
- "stateless" has been replaced by "stateful" in description for what are **stateful** applications

ext-fix-tutorial

---

ai-data/generative-apis/how-to/query-vision-models.mdx

Added GenAPI error code for vision models like Pixtral
Clarified limit

fix(ai): vision FAQ

---

changelog/november2024/2024-11-12-functions-changed-incoming-change-for-dns-resolution.mdx

Fix date formatting in changelog

fix(changelog): fix formatting

---

compute/instances/how-to/create-a-block-volume.mdx
compute/instances/how-to/create-an-instance.mdx
compute/instances/how-to/manage-volumes.mdx
storage/block/how-to/attach-a-volume.mdx
storage/block/how-to/create-a-volume.mdx

docs(ins): add information for block 15k

---

menu/navigation.json
serverless/containers/api-cli/migrate-external-image-to-scaleway-registry.mdx
serverless/jobs/api-cli/index.mdx
serverless/jobs/api-cli/migrate-external-image-to-scaleway-registry.mdx

docs(srv): add registry migration procedure MTA-5186

---

network/load-balancer/reference-content/sni-route-deprecation.mdx

fix(lb): doc review

---

ai-data/generative-apis/how-to/use-function-calling.mdx

New warning regarding importance of system prompt in the context of function calling. The sentence was reduced to the bare minimum.

fix(genapi): added warning regarding system prompt

---

changelog/september2024/2024-09-19-containers-changed-containers-vcpu-and-ram-relation.mdx
changelog/serverless/october2022/2022-10-13-containers-added-memory-cpu.mdx
faq/serverless-containers.mdx
faq/serverless-jobs.mdx
serverless/containers/concepts.mdx
serverless/functions/concepts.mdx
serverless/jobs/concepts.mdx
serverless/jobs/how-to/monitor-job.mdx
serverless/jobs/reference-content/jobs-limitations.mdx
serverless/sql-databases/concepts.mdx
styles/Vocab/Scaleway/accept.txt
tutorials/deploy-umami-on-serverless-containers/index.mdx
tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx

chore(gen): doc review + typos MTA-5259

---

tutorials/abort-multipart-upload-minio/index.mdx
tutorials/backup-synology-nas-s3-hyper-backup/index.mdx
tutorials/bind-dns-server/index.mdx
tutorials/configure-apache-kafka/index.mdx
tutorials/configure-dvc-with-object-storage/index.mdx
tutorials/configure-nodemcu-iot-hub/index.mdx
tutorials/configure-realtime-alerting-slack/index.mdx
tutorials/configure-vm-hyperv/index.mdx
tutorials/configuring-loadbalancer-wordpress/index.mdx
tutorials/create-openwrt-image-for-scaleway/index.mdx
tutorials/create-valheim-server/index.mdx
tutorials/deploy-angular-application/index.mdx
tutorials/deploy-hasura-engine-database-postgresql/index.mdx
tutorials/dhcpcd-dedibox/index.mdx
tutorials/encode-videos-using-serverless-jobs/index.mdx
tutorials/get-started-crossplane-kubernetes/index.mdx
tutorials/jitsi-debian-stretch/index.mdx
tutorials/jump-desktop/index.mdx
tutorials/prestashop-dedibox/index.mdx

feat(tutorial): content refresh tutorials

---

bare-metal/elastic-metal/how-to/use-private-networks.mdx

You can now use a reserved IP address when attaching an EM server to a Private Network.

fix(em): add info for reserved IP

---

network/ipam/how-to/reserve-ip.mdx

fix(em): correction

---

containers/container-registry/quickstart.mdx

It's insecure to use `docker login ... -u nologin -p SCW_SECRET_KEY` as the secret will be written to the shell history.

docs(container): add secure Docker login instructions int-feat-containers

---

compute/instances/how-to/create-a-block-volume.mdx
compute/instances/how-to/create-an-instance.mdx
compute/instances/how-to/manage-volumes.mdx
compute/instances/reference-content/instances-bandwidth-overview.mdx
menu/navigation.json
storage/block/how-to/attach-a-volume.mdx
storage/block/how-to/create-a-volume.mdx

feat(ins): add instance bandwidth overview

---

faq/serverless-containers.mdx

fix(srv): replace snippet with link to dedicated doc

---

serverless/containers/concepts.mdx
serverless/containers/reference-content/containers-concurrency.mdx

docs(srv): update doc on container concurrency MTA-5283

---

macros/vpc/network-resource-naming.mdx
macros/vpc/pn-naming.mdx
network/public-gateways/how-to/create-a-public-gateway.mdx
network/public-gateways/quickstart.mdx
network/vpc/how-to/create-vpc.mdx

Add guidance for resource naming for NW core products

fix(nw): add guidance for resource naming

---

tutorials/deploy-hasura-engine-database-postgresql/index.mdx
tutorials/get-started-crossplane-kubernetes/index.mdx
tutorials/upgrade-managed-postgresql-database/index.mdx

fix(tutorials): batch one

---

network/ipam/reference-content/ipv6.mdx

Add doc about IPv6 at Scaleway, based on user demand in search terms

feat(ipam): add doc about IPv6

---

faq/cockpit.mdx
macros/cockpit/plan-deprecation.mdx
menu/navigation.json
observability/cockpit/concepts.mdx
observability/cockpit/how-to/change-data-retention.mdx
observability/cockpit/reference-content/cockpit-limitations.mdx

What changed:
- Added "retention" concept + a table with minimum, maximum and default retention time for each data source
- Added "how to change data retention" page
- Added a macro to warn about plan deprecation (that is reused in different pages)
- Added the macro about plan deprecation in the FAQ page
- Added a question in the FAQ to explain why plans are being deprecated
- Added the macro in the Cockpit Capabilities and limits page
@sfinet-scw Je viens de mettre à jour en implémentant tes commentaires, j'ai re-généré une capture de la page How-to ci-dessus ! (la typo "botch" dans la box tip après la 3ème étape vient d'être corrigée par ailleurs)

docs(cpt): add pricing plans info

---

managed-databases/postgresql-and-mysql/api-cli/import-data-to-managed-postgresql-databases.mdx
serverless/sql-databases/api-cli/import-data-to-serverless-sql-databases.mdx
tutorials/migrate-databases-instance/index.mdx

docs(sdb): add cross links between db migration procedures MTA-5240

---

console/account/reference-content/products-availability.mdx
faq/audit-trail.mdx
identity-and-access-management/audit-trail/concepts.mdx
identity-and-access-management/audit-trail/how-to/configure-audit-trail-permissions.mdx
identity-and-access-management/audit-trail/how-to/index.mdx
identity-and-access-management/audit-trail/how-to/use-audit-trail.mdx
identity-and-access-management/audit-trail/index.mdx
identity-and-access-management/audit-trail/quickstart.mdx
identity-and-access-management/audit-trail/reference-content/product-integration-with-adt.mdx
identity-and-access-management/audit-trail/reference-content/resource-integration-with-adt.mdx
identity-and-access-management/audit-trail/troubleshooting/cannot-see-events.mdx
identity-and-access-management/iam/reference-content/permission-sets.mdx
menu/navigation.json

Index page
Concepts
How-Tos
FAQ
Reference content (Product integration with Audit Trail)
Troubleshooting
Menu 
The product icon in the menu is missing, will update here again when it is available. (need to update in menu and FAQ)

feat(audit-trail): add audit trail documentation

---

ai-data/managed-inference/reference-content/molmo-72b-0924.mdx
menu/navigation.json

- Described Molmo-72B for Managed Inference
- Edited nav

feat(ifr): support Molmo-72b

---

serverless/containers/concepts.mdx
serverless/functions/concepts.mdx

fix(serverless): instance number

---

compute/instances/how-to/migrate-routed-ips.mdx

Add details about routed IPv6 and minimal packages version for the best experience.

fix(ins): details about routed IPv6

---

console/account/troubleshooting/cannot-erase-account.mdx
console/account/troubleshooting/cannot-log-into-my-account.mdx
developer-tools/scaleway-sdk/go-sdk.mdx
developer-tools/scaleway-sdk/js-sdk.mdx
developer-tools/scaleway-sdk/python-sdk.mdx
developer-tools/terraform/quickstart.mdx
serverless/containers/reference-content/use-cases.mdx
serverless/functions/reference-content/use-cases.mdx
serverless/jobs/how-to/run-job.mdx
serverless/jobs/how-to/stop-job.mdx
serverless/jobs/quickstart.mdx
storage/object/api-cli/combining-iam-and-object-storage.mdx
storage/object/api-cli/create-bucket-policy.mdx
storage/object/concepts.mdx
storage/object/troubleshooting/lost-bucket-access-bucket-policy.mdx
tutorials/strapi-app-serverless-containers-sqldb/index.mdx

chore(gen): doc review MTA-5305

---

storage/object/api-cli/create-bucket-policy.mdx
storage/object/concepts.mdx

fix(object): bugs

---

partners/partner-space/concepts.mdx
partners/partner-space/how-to/add-client.mdx
partners/partner-space/how-to/edit-client-information.mdx
partners/partner-space/how-to/grant-access-to-partner-space.mdx
partners/partner-space/how-to/lock-client-organization.mdx
partners/partner-space/how-to/unlock-client-organization.mdx
partners/partner-space/quickstart.mdx

Partner Space documentation review

fix(partners): docs review

---

network/ipam/concepts.mdx
network/load-balancer/how-to/manage-frontends-and-backends.mdx
network/load-balancer/quickstart.mdx
network/vpc/concepts.mdx
network/vpc/how-to/manage-routing.mdx
network/vpc/reference-content/understanding-routing.mdx

Documentation review for network docs

fix(network): doc review

---

containers/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2.mdx
containers/kubernetes/concepts.mdx
index.mdx

- Updated suggested keywords from the landing page, based on past trimester's data. 
- Fixed a casing error for `kubeconfig`.

docs(gen): update landing page keywords

---

changelog/december2024/2024-12-05-load-balancers-removed-static-attachment-is-no-longer-a.mdx

feat(changelog): load-balancers-removed-static-attachment-is-no-longer-a 2024-12-05

---

containers/kubernetes/reference-content/version-support-policy.mdx

Added information on version 1.31 release

docs(k8s): version release 1.31

---

ai-data/generative-apis/api-cli/using-chat-api.mdx
ai-data/generative-apis/how-to/query-language-models.mdx
ai-data/generative-apis/how-to/query-vision-models.mdx

- Supporting Stream_options param
- Edited docs to avoid `list index out of range` issue in stream

fix(ai): update matching OpenAI specs

---

ai-data/generative-apis/how-to/query-code-models.mdx

Small improvements for better readability.

fix(ai): better display

---

compute/instances/reference-content/identify-devices.mdx

Changing section titles from H1s to H2s so they are featured on the 'Jump to' menu.
Fixed some typos.

docs(ins): fixed titles

---

serverless/sql-databases/api-cli/secure-connection-ssl-tls.mdx
storage/object/troubleshooting/cannot-access-data.mdx
storage/object/troubleshooting/cannot-delete-bucket.mdx
storage/object/troubleshooting/cannot-restore-glacier.mdx
storage/object/troubleshooting/low-performance.mdx
tutorials/install-parse-server/index.mdx
tutorials/install-pgbouncer/index.mdx
tutorials/installation-lemp-ubuntu-bionic/index.mdx
tutorials/installation-uncomplicated-firewall/index.mdx
tutorials/jitsi-ubuntu-jammy-jellyfish/index.mdx
tutorials/restic-s3-backup/index.mdx
tutorials/sem-terraform/index.mdx

chore(gen): doc review MTA-5351

---

containers/kubernetes/reference-content/version-support-policy.mdx

correct deprecation date for kapsule 1.31, it is 2025 not 2024.

fix: correct deprecation date for kapsule 1.31

---

dedibox-console/classic-hosting/how-to/terminate-online-classic-hosting.mdx
menu/navigation.json

Adding tunnel termination Classic hosting ddx

feat(dedibox): adding a Web Hosting classic termination

---

faq/elastic-metal.mdx
tutorials/deploy-saas-application/index.mdx

Edits in response to client feedback

fix(docs): respond to client feedback

---

faq/vpc.mdx
network/load-balancer/how-to/create-manage-flex-ips.mdx
network/load-balancer/reference-content/public-private-accessibility.mdx

fix(docs): nw docs review

---

network/load-balancer/reference-content/configuring-health-checks.mdx

fix(lb): fix mysql health check info

---

containers/kubernetes/how-to/manage-allowed-ips.mdx
menu/navigation.json

DRAFT: feat(k8s): add acl docs

---

serverless/jobs/troubleshooting/missing-metrics.mdx

feat(jobs): troubleshooting missing metrics

---

serverless/jobs/how-to/delete-job.mdx
serverless/jobs/how-to/monitor-job.mdx
serverless/sql-databases/troubleshooting/connection-timeout.mdx
storage/object/api-cli/bucket-policy.mdx
storage/object/api-cli/lifecycle-rules-api.mdx
storage/object/api-cli/multipart-uploads.mdx
storage/object/api-cli/setting-cors-rules.mdx
storage/object/quickstart.mdx
storage/object/videos.mdx

chore(gen): documentation review MTA-5394

---

containers/kubernetes/api-cli/external-secrets-kubernetes.mdx
menu/navigation.json

Added the existing External Secrets doc in the Kubernetes section upon request

docs(add): add external secrets in k8s

---

bare-metal/elastic-metal/reference-content/elastic-metal-rv1-guidelines.mdx

kernel/kheaders_data.tar.xz requires xz-utils

fix(riscv): xz-utils required

---

faq/serverless-containers.mdx
faq/serverless-functions.mdx
faq/serverless-jobs.mdx
serverless/containers/concepts.mdx
serverless/containers/reference-content/containers-limitations.mdx
serverless/functions/concepts.mdx
serverless/functions/reference-content/functions-limitations.mdx
serverless/jobs/concepts.mdx

feat(serverless): update concepts

---

compute/instances/how-to/migrate-routed-ips.mdx
compute/instances/troubleshooting/fix-broken-vpn-when-switching-openvpn-vm-to-routed-ip.mdx
compute/instances/troubleshooting/fix-lost-ip-connectivity-on-debian-buster.mdx
compute/instances/troubleshooting/fix-unreachable-focal-with-two-public-ips.mdx
compute/instances/troubleshooting/fix-unreachable-ipv6-rhel-based-instance.mdx
faq/instances.mdx

fix(ins): crosslink routed ip docs

---

dedibox/dedicated-servers/how-to/use-dedibackup-ftp-backup.mdx

fix(ddx): add detailed connection information for dedibackup

---

menu/navigation.json
network/vpc/concepts.mdx
network/vpc/how-to/attach-resources-to-pn.mdx
network/vpc/reference-content/dns.mdx
network/vpc/reference-content/getting-most-private-networks.mdx

Add DNS info based on user request

feat(vpc): add info on DNS

---

faq/serverless-containers.mdx
faq/serverless-functions.mdx

feat(serverless): edge faq

---

tutorials/easydeploy-gitlab-server/index.mdx
tutorials/install-ispconfig/index.mdx
tutorials/k8s-gitlab/index.mdx
tutorials/k8s-velero-backup/index.mdx
tutorials/librenms-monitoring/index.mdx
tutorials/manage-database-instance-pgadmin4/index.mdx
tutorials/manage-k8s-logging-loki/index.mdx
tutorials/mist-streaming-server/index.mdx
tutorials/mlx-array-framework-apple-silicon/index.mdx
tutorials/monitor-k8s-grafana/index.mdx
tutorials/object-storage-s3fs/index.mdx
tutorials/scaleway-packer-plugin/index.mdx
tutorials/waypoint-plugin-scaleway/index.mdx

feat(tuto): tutorial reviews 30/12

---

tutorials/enabling-encryption-in-kapsule-with-cilium/index.mdx

feat(k8s): add tuto cilium

---

tutorials/enabling-encryption-in-kapsule-with-cilium/index.mdx

fix(k8s): tutorial fix headline

---

ai-data/managed-inference/how-to/managed-inference-with-private-network.mdx
bare-metal/dedibox/reference-content/dedibox-datasheet.mdx
bare-metal/elastic-metal/how-to/adjust-available-bandwidth.mdx
compute/instances/how-to/send-emails-from-your-instance.mdx
compute/instances/reference-content/learning.mdx
compute/instances/troubleshooting/reboot-from-faulty-kernel.mdx
containers/kubernetes/how-to/enable-disable-ssh.mdx
containers/kubernetes/reference-content/exposing-services.mdx
containers/kubernetes/reference-content/managed-kubernetes-service-definition.mdx
managed-services/webhosting/how-to/manage-webhosting.mdx

docs(gen): review content 2025-01-06

---

compute/gpu/reference-content/gpu-instances-bandwidth-overview.mdx
compute/instances/reference-content/instances-bandwidth-overview.mdx
menu/navigation.json

Added missing PRO2 and POP2-HN-5 Instance types to bandwidth overview

fix(ins): add PRO2 instance range to bandwidth overview

---

tutorials/overleaf/index.mdx

chore(tuto): review content overleaf

---

containers/kubernetes/how-to/upgrade-kubernetes-version.mdx

Document Kapsule API behaviour during cluster upgrade

docs(k8s): add mention that pool scaling not available during upgrade

---

containers/kubernetes/api-cli/managing-storage.mdx

Int feat k8s add warning 20250115

---

macros/serverless/difference-jobs-functions-containers.mdx
serverless/containers/concepts.mdx
serverless/containers/reference-content/containers-limitations.mdx
serverless/functions/concepts.mdx
serverless/functions/reference-content/functions-limitations.mdx

feat(serverless): precision on timeout

---

serverless/functions/concepts.mdx

fix(gen): 404s

---

console/account/how-to/open-a-support-ticket.mdx

Added "how to write an effective support ticket" section.

fix(acc): doc update - how to write a support ticket

---

ai-data/generative-apis/troubleshooting/fixing-common-issues.mdx
ai-data/generative-apis/troubleshooting/index.mdx
menu/navigation.json

Added troubleshooting guide for Generative APIs

feat(ai): added troubleshooting for generative apis

---

compute/instances/how-to/use-boot-modes.mdx

fix(ins): removed invalid content types

---

network/vpc/reference-content/use-case-basic.mdx

fix(vpc): use case typo

---

serverless/sql-databases/reference-content/planned-maintenance.mdx
serverless/sql-databases/troubleshooting/maximum-prepared-statements-reached.mdx

chore(gen): content review 21/01 MTA-5416

---

observability/cockpit/how-to/send-log-from-k8s-to-cockpit.mdx
observability/cockpit/how-to/send-metrics-from-k8s-to-cockpit.mdx

Adding a documentation on how to send custom metrics from a k8s cluster to Cockpit using a custom datasource 
with either Kubernetes or Terraform

docs(cockpit): added documentation on how to add custom metrics from k8s cluster to cockpit int-add-observability

---

containers/kubernetes/api-cli/managing-storage.mdx

fix(k8s): fix cli command

---

pages/dedibox-hardware/how-to/configure-hardware-raid-console.mdx
pages/dedibox-hardware/index.mdx

- do a search to verify there is no missed occurence
- check new url is ok

fix(content): dedibox-hardware URL update in content

---

changelog/january2025/2025-01-27-apple-silicon-added-mac-mini-m4-now-available.mdx

feat(changelog): apple-silicon-added-mac-mini-m4-now-available 2025-01-27

---

pages/iam/how-to/create-api-keys.mdx

Preferred project impacts all actions on Object Storage, not only Creates and Lists. This MR fixes that on the "Create API Key" page

fix(iam): preferred project fix

---

pages/vpc/how-to/activate-dhcp.mdx
pages/vpc/troubleshooting/autoconfig-not-working.mdx
pages/vpc/troubleshooting/resource-attached-no-ip.mdx

fix(vpc): doc review

---

pages/serverless-containers/concepts.mdx
pages/serverless-functions/concepts.mdx
pages/serverless-jobs/concepts.mdx

fix(serverless): concepts missing and order fix

---

pages/apple-silicon/how-to/access-remote-desktop-mac-mini.mdx

feat(aps): update table to ensure a11y standards

---

faq/serverless-containers.mdx
faq/serverless-jobs.mdx

docs(srv): add info on no ssh connection to caas/jobs MTA-5535

---

pages/messaging/concepts.mdx
pages/messaging/reference-content/sqs-support.mdx
pages/organizations-and-projects/additional-content/organization-quotas.mdx

feat(messaging): documentation for dead letter queue limits

---

pages/apple-silicon/how-to/access-remote-desktop-mac-mini.mdx
pages/apple-silicon/how-to/connect-to-mac-mini-ssh.mdx
pages/apple-silicon/how-to/install-package-manager-mac-mini.mdx
pages/apple-silicon/how-to/shutdown-mac-mini.mdx
pages/apple-silicon/how-to/update-os-mac-mini.mdx
pages/apple-silicon/how-to/upgrade-macos-to-beta.mdx
pages/apple-silicon/quickstart.mdx
pages/dedibox-ip-failover/how-to/assign-failover-ip.mdx
pages/dedibox-ip-failover/how-to/configure-debian-ubuntu.mdx
pages/dedibox-ip-failover/how-to/configure-network-virtual-machine.mdx
pages/dedibox-ip-failover/how-to/configure-reverse-dns.mdx
pages/dedibox-ip-failover/how-to/configure-windows.mdx
pages/elastic-metal/how-to/configure-ipv6-hypervisor.mdx
pages/elastic-metal/how-to/create-virtual-mac-group.mdx
pages/instances/troubleshooting/fix-unreachable-focal-with-two-public-ips.mdx

chore(ddx): review bare metal docs

---

pages/ipam/concepts.mdx
pages/ipam/how-to/reserve-ip.mdx
pages/ipam/quickstart.mdx

fix(ipam): correct address

---

bin/check-review-dates.py

Update review bot for new repo structure.
- Addition of a new import statement (json) used in new method.
- Addition of FILEPATH constant, since this is now used in two separate methods.
- Addition and integration of a new method get_prod_cat_ref to create a dictionary where products are mapped to categories, as this can no longer be inferred from the filepath alone.

fix(review-bot): update review bot for new repo structure

---

changelog/serverless/january2023/2023-01-11-added-functions-php-extensions.mdx
changelog/serverless/september2022/2022-09-08-functions-changed-nodejs.mdx
changelog/serverless/september2022/2022-09-08-functions-deprecated-go.mdx
changelog/serverless/september2022/2022-09-08-functions-deprecated-nodejs.mdx
changelog/serverless/september2022/2022-09-08-functions-deprecated-python.mdx
faq/serverless-functions.mdx
macros/serverless/difference-jobs-functions-containers.mdx
menu/navigation.json
pages/serverless-functions/api-cli/deploy-function-cli.mdx
pages/serverless-functions/how-to/create-a-function.mdx
pages/serverless-functions/quickstart.mdx
pages/serverless-functions/reference-content/functions-runtimes.mdx

docs(srv): update how to create function and reorg pages MTA-5477

---

pages/serverless-containers/how-to/test-a-container.mdx
pages/serverless-functions/how-to/add-trigger-to-a-function.mdx
pages/serverless-functions/reference-content/deploy-function.mdx
pages/serverless-jobs/concepts.mdx
pages/serverless-jobs/quickstart.mdx

fix(serverless): some qa on links

---

pages/instances/how-to/use-flexips.mdx

Add some documentation on how to configure a custom IPv6 within the provided routed IPv6 prefixes.

feat(instance): new how-to configure a custom IPv6 within a given prefix

---

menu/navigation.json
pages/kubernetes/how-to/access-kubernetes-dashboard.mdx
pages/kubernetes/how-to/monitor-cluster.mdx
pages/kubernetes/how-to/monitor-data-plane-with-cockpit.mdx

docs(k8s): add observability docs

---

faq/data-lab.mdx
pages/data-lab/how-to/manage-delete-data-lab.mdx
pages/data-lab/troubleshooting/cannot-run-data-lab.mdx

docs(DLB): update FAQ/create troubleshooting on cluster scaling MTA-5133

---

compute/instances/troubleshooting/fix-common-issues.mdx
menu/navigation.json

feat(ins): add instances troubleshooting

---

menu/navigation.json
pages/apple-silicon/troubleshooting/cant-connect-using-ssh.mdx
pages/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx
pages/apple-silicon/troubleshooting/cant-create-apple-account.mdx
pages/apple-silicon/troubleshooting/cant-delete-mac-mini.mdx
pages/apple-silicon/troubleshooting/filevault-preventing-system-boot.mdx
pages/apple-silicon/troubleshooting/mac-mini-inaccessible.mdx
pages/apple-silicon/troubleshooting/mac-mini-installation-issues.mdx

feat(aps): rework troubleshooting

---

menu/navigation.json
pages/apple-silicon/troubleshooting/cant-connect-using-vnc.mdx

fix(aps): fix small bugs

---

menu/navigation.json
pages/webhosting/troubleshooting/cant-access-website-mail.mdx
pages/webhosting/troubleshooting/cant-connect-ftp.mdx
pages/webhosting/troubleshooting/index.mdx
pages/webhosting/troubleshooting/troubleshooting-access-issues-cpanel-plesk.mdx
pages/webhosting/troubleshooting/troubleshooting-dns-issues.mdx
pages/webhosting/troubleshooting/troubleshooting-email.mdx

feat(wbh): add troubleshooting

---

pages/instances/how-to/migrate-routed-ips.mdx

feat(ins): add info that routed ip migration is complete

---

faq/serverless-containers.mdx
faq/serverless-functions.mdx
faq/serverless-jobs.mdx
pages/serverless-containers/concepts.mdx
pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-functions/concepts.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx
pages/serverless-jobs/concepts.mdx
pages/serverless-jobs/reference-content/jobs-limitations.mdx

docs(srv): add info on pn compatibility MTA-5526

---

pages/managed-inference/reference-content/bge-multilingual-gemma2.mdx
pages/managed-inference/reference-content/deepseek-r1-distill-llama-8b.mdx
pages/managed-inference/reference-content/llama-3-70b-instruct.mdx
pages/managed-inference/reference-content/llama-3-8b-instruct.mdx
pages/managed-inference/reference-content/llama-3.1-8b-instruct.mdx
pages/managed-inference/reference-content/mistral-7b-instruct-v0.3.mdx
pages/managed-inference/reference-content/mistral-nemo-instruct-2407.mdx
pages/managed-inference/reference-content/pixtral-12b-2409.mdx

Update model documentation with support for L40S GPUs in Managed Inference

Add L40S to Managed Inference models

---

menu/navigation.json
pages/serverless-functions/troubleshooting/function-build-error.mdx

docs(srv): add function build error troubleshooting MTA-5554

---

tutorials/export-audit-trail-to-datadog/index.mdx

Add tutorial to build, deploy and run an OpenTelemetry Collector to export Audit Trail events to DataDog.

docs(audit-trail): add tutorial to export audit trail to datadog

---

pages/instances/reference-content/instances-bandwidth-overview.mdx

fix(ins): add pop2-win bandwidth

---

pages/managed-mongodb-databases/how-to/connect-database-instance.mdx

fix(mongodb): Update documentation about connection string

---

pages/apple-silicon/index.mdx
pages/billing/index.mdx
pages/classic-hosting/index.mdx
pages/data-lab/index.mdx
pages/dedibox-account/index.mdx
pages/dedibox-dns/index.mdx
pages/dedibox-domains/index.mdx
pages/dedibox-hardware/index.mdx
pages/dedibox-ip-failover/index.mdx
pages/dedibox-ipv6/index.mdx
pages/dedibox-kvm-over-ip/index.mdx
pages/dedibox-rpn/index.mdx
pages/dedibox-scaleway/index.mdx
pages/dedibox-vps/index.mdx
pages/dedibox/index.mdx
pages/elastic-metal/index.mdx
pages/environmental-footprint/environmental-footprint/index.mdx
pages/environmental-footprint/index.mdx
pages/generative-apis/index.mdx
pages/gpu/index.mdx
pages/instances/index.mdx
pages/iot-hub/index.mdx
pages/kubernetes/index.mdx
pages/managed-inference/index.mdx
pages/webhosting/index.mdx

Fixed concepts info icon for several pages

fix(gen): fix missing concepts icon for overview pages

---

pages/guidelines.mdx
tutorials/dagster-serverless-jobs/index.mdx
tutorials/deploy-meilisearch-instance/index.mdx
tutorials/deploying-a-documentation-website-with-docusaurus-on-scaleway/index.mdx
tutorials/get-started-kubernetes-storage/index.mdx
tutorials/pihole-vpn/index.mdx
tutorials/run-manage-linux-vm-on-apple-silicon-tart/index.mdx
tutorials/send-emails-with-serverless-and-tem/index.mdx
tutorials/use-cockpit-with-terraform/index.mdx

Content review tutorials 2024-02-11

chore(tuto): review tutorial content

---

tutorials/traefik-v2-cert-manager/index.mdx

First, I just copied the URL from the wizard and got v1.0.0 that was incompatible with the following steps.

Specify a recent version of cert-manager

---

pages/instances/api-cli/migrating-instances.mdx

feat(ins): add warning hardcoded interfaces

---

menu/changelogs.json

- icon names in changelog menu should be in _camelCase_ format.

fix(changelog): fix icon name format for efp

---

pages/serverless-functions/reference-content/local-testing.mdx

docs(srv): update local testing functions doc MTA-5558

---

pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx
pages/serverless-jobs/reference-content/jobs-limitations.mdx

feat(serverless): dedicated ip info

---

pages/dedibox-ip-failover/how-to/configure-debian-ubuntu.mdx

Updated documentation for failover IP config on DDX

fix(ddx): netplan

---

tutorials/deploy-openproject-database-postgresql/index.mdx
tutorials/get-started-python/index.mdx
tutorials/install-docker-ubuntu-jammy-jellyfish/index.mdx
tutorials/install-mattermost/index.mdx
tutorials/send-emails-tem-serverless-framework/index.mdx

chore(gen): review tutorials

---

faq/billing.mdx
pages/billing/additional-content/reading-an-invoice.mdx
pages/billing/how-to/add-payment-method.mdx

Billing documentation update following support ticket analysis ([see summary](https://docs.google.com/spreadsheets/d/1HCN96ZFw1aHeuCTtIVY3itNyVDlUv-s4LxUOZ2O7KTY/edit?usp=sharing))

fix(bil): doc update

---

pages/vpc/concepts.mdx

fix(vpc): update concept

---

tutorials/deploy-openwebui-with-generative-apis/index.mdx

Add tutorial Open WebUI with Gen APIs

feat(genapi): add tuto openwebui

---

pages/serverless-functions/reference-content/code-examples.mdx

- Remove duplicate code
- Standardize indentation to 4 spaces (PEP-8)
- Fix a capitalization for better readability

style: update style of code-examples.mdx

---

menu/navigation.json
pages/serverless-containers/reference-content/containers-autoscaling.mdx
pages/serverless-functions/reference-content/functions-autoscaling.mdx

docs(srv): add content reference on autoscaling MTA-5516

---

tutorials/deploy-istio-kapsule-proxy-protocol/index.mdx
tutorials/proxy-protocol-v2-load-balancer/index.mdx

Add tutorial for setting up Istio with ProxyProtocol via a SCW Load Balancer, based on tuto from SA.

feat(tutorial): add tuto for istio and k8s

---

pages/kubernetes/how-to/create-kosmos-cluster.mdx

Update Kosmos cluster creation documentation

---

menu/navigation.json
pages/generative-apis/reference-content/adding-ai-to-intellij-using-continue.mdx
pages/generative-apis/reference-content/adding-ai-to-vscode-using-continue.mdx
pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx

docs(genapi): add docs

---

faq/vpc.mdx
pages/vpc/troubleshooting/vpc-pn-routing-connectivity-issues.mdx

fix(vpc): minor modifs

---

macros/serverless/cron-schedules.mdx

feat(serverles): add more cron in cheatsheet

---

pages/edge-services/concepts.mdx
pages/edge-services/how-to/configure-custom-domain.mdx
pages/edge-services/how-to/create-pipeline-bucket.mdx
pages/edge-services/how-to/create-pipeline-lb.mdx
pages/edge-services/reference-content/cname-record.mdx
pages/edge-services/reference-content/ssl-tls-certificate.mdx

fix(es): change endpoint format

---

menu/navigation.json
pages/serverless-containers/how-to/configure-alerts-containers.mdx
pages/serverless-containers/reference-content/containers-autoscaling.mdx
pages/serverless-functions/how-to/configure-alerts-function.mdx
pages/serverless-functions/reference-content/functions-autoscaling.mdx
pages/serverless-jobs/how-to/configure-alerts-jobs.mdx

docs(srv): add how to create alerts for srv ressources MTA-5503

---

faq/managed-inference.mdx

Add FAQ for Managed Inference product.

feat(infr): add faq

---

pages/key-manager/api-cli/configuring-tink.mdx

Add a link to the Tink cryptography library

docs(key-manager): add a link to the Tink cryptography library

---

pages/serverless-functions/concepts.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx

fix(srv): add info on function concurrency

---

pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx

fix(genapi): fix  indention

---

tutorials/deploying-hubble-add-on-scaleway-kubernetes-clusters/index.mdx

Add tutorial Hubble with Scaleway Kubernetes clusters

feat(k8s): add tutorial hubble with kubernetes

---

menu/navigation.json
pages/block-storage/api-cli/increasing-volume-size.mdx
pages/instances/api-cli/increasing-volume-size.mdx

docs(bls): added API doc on volume increase MTA-5706

---

macros/console/create-account.mdx

- Removed some alerts (too many on the same page)
- Simplified step 1

fix(acc): macro update

---

pages/dedibox-kvm-over-ip/how-to/dell-idrac6.mdx

fix(ddx): fix indent

---

changelog/march2025/2025-03-05-kubernetes-removed-end-of-support-kubernetes-versions-1.mdx

feat(changelog): kubernetes-removed-end-of-support-kubernetes-versions-1 2025-03-05

---

pages/kubernetes/reference-content/version-support-policy.mdx

fix(k8s): remove deprecated versions

---

tutorials/collecting-visualizing-logs-elastic-stack/index.mdx
tutorials/configure-graphite/index.mdx
tutorials/configure-smtp-relay-tem/index.mdx
tutorials/deploy-phpmyadmin-with-docker/index.mdx
tutorials/deploy-ubuntu-20-04-instance-scaleway-elements/index.mdx
tutorials/deploy-ubuntu-22-04-instance/index.mdx
tutorials/focalboard-project-management/index.mdx
tutorials/mariadb-ubuntu-bionic/index.mdx
tutorials/mastodon-community/index.mdx
tutorials/migrate-databases-instance/index.mdx
tutorials/migrate-dedibox-to-elastic-metal/index.mdx
tutorials/nextcloud-instantapp/index.mdx
tutorials/plausible-analytics-ubuntu/index.mdx
tutorials/scaleway-slack-community/index.mdx
tutorials/setup-k8s-cluster-rancher/index.mdx

docs(gen): tutorial content review

---

tutorials/back-up-postgresql-barman/index.mdx
tutorials/backup-postgresql-pgbackrest-s3/index.mdx
tutorials/bash-christmas-tree/index.mdx
tutorials/configure-failover-proxmox/index.mdx
tutorials/get-started-kubernetes-loadbalancer/index.mdx
tutorials/how-to-implement-rag-generativeapis/index.mdx
tutorials/install-apache-ansible/index.mdx
tutorials/install-github-actions-runner-mac/index.mdx
tutorials/install-pgbouncer/index.mdx
tutorials/install-wireguard/index.mdx
tutorials/jump-desktop/index.mdx
tutorials/load-testing-vegeta/index.mdx
tutorials/nginx-reverse-proxy/index.mdx
tutorials/overleaf/index.mdx
tutorials/proxy-protocol-v2-load-balancer/index.mdx
tutorials/python-for-loops/index.mdx
tutorials/setup-nginx-reverse-proxy-s3/index.mdx
tutorials/veeam-backup-replication-s3/index.mdx
tutorials/wireguard-mesh-vpn/index.mdx

Following our last Inday, we are testing account creations from the docs. 
CTAs have been added to the most viewed tutorials: 50% at the top and 50% at the bottom. 
See the recap and examples here: [Gsheet](https://docs.google.com/spreadsheets/d/1JGLyCDux5cRioDF9so3iRay27shAmuvBkZ7aVQ--nSs/edit?gid=0#gid=0)
To be reviewed: title for each CTA

fix(docs): cta in tutorials

---

menu/navigation.json
pages/container-registry/troubleshooting/common-errors-when-pushing-images-to-container-registry.mdx
pages/container-registry/troubleshooting/troubleshooting-container-registry-image-push-issues.mdx

Add troubleshooting guide to Container Registry docs

feat(cr): add troubleshooting

---

menu/navigation.json
pages/cockpit/concepts.mdx
pages/cockpit/how-to/access-grafana-and-managed-dashboards.mdx
pages/cockpit/how-to/retrieve-grafana-credentials.mdx
pages/cockpit/how-to/send-logs-from-k8s-to-cockpit.mdx
pages/cockpit/how-to/send-metrics-from-k8s-to-cockpit.mdx
pages/cockpit/how-to/send-metrics-with-grafana-alloy.mdx
pages/managed-inference/how-to/monitor-deployment.mdx

Replaced wording "managed dashboards" with "preconfigued dashboards"

docs(fix): replace managed dashboard with preconfigured

---

pages/elastic-metal/api-cli/elastic-metal-with-api.mdx
pages/elastic-metal/api-cli/elastic-metal-with-cli.mdx

fix(em): remove old offer

---

faq/apple-silicon.mdx
pages/dedibox-account/how-to/resolve-abuse.mdx
pages/dedibox-hardware/concepts.mdx
pages/dedibox-ipv6/concepts.mdx
pages/dedibox-kvm-over-ip/concepts.mdx
pages/dedibox-kvm-over-ip/quickstart.mdx
pages/dedibox/reference-content/basic-linux-commands.mdx
pages/generative-apis/api-cli/using-chat-api.mdx
pages/generative-apis/api-cli/using-embeddings-api.mdx
pages/generative-apis/api-cli/using-models-api.mdx
pages/generative-apis/reference-content/model-lifecycle.mdx
pages/gpu/how-to/create-manage-gpu-instance.mdx
pages/gpu/quickstart.mdx
pages/instances/api-cli/increasing-volume-size.mdx
pages/instances/how-to/create-a-backup.mdx
pages/instances/how-to/power-off-instance.mdx
pages/instances/troubleshooting/fix-unreachable-ipv6-rhel-based-instance.mdx
pages/kubernetes/how-to/access-audit-logs.mdx
pages/kubernetes/how-to/deploy-x86-arm-images.mdx
pages/kubernetes/troubleshooting/containers-not-starting-arm-instances.mdx

Docs content review compute 2025-03-11

docs(gen): docs content review

---

pages/container-registry/troubleshooting/index.mdx

feat(cr): add troubleshooting index

---

menu/navigation.json
pages/kubernetes/troubleshooting/index.mdx

Add Kubernetes troubleshooting index

feat(k8s): add troubleshooting index

---

menu/navigation.json
pages/instances/troubleshooting/index.mdx

Add troubleshooting index for Instances compute

feat(ins): add troubleshooting index

---

menu/navigation.json
pages/elastic-metal/troubleshooting/index.mdx

feat(em): add troubleshooting index

---

faq/public-gateways.mdx
pages/kubernetes/reference-content/kubernetes-load-balancer.mdx
pages/kubernetes/reference-content/using-load-balancer-annotations.mdx
pages/load-balancer/reference-content/public-private-accessibility.mdx
pages/messaging/api-cli/nats-cli.mdx
pages/public-gateways/concepts.mdx
pages/vpc/reference-content/vpc-migration.mdx

Updated `devtools` wording to more formal `developer tools` in some documentations.

docs(gen): update devtools wording

---

faq/ipam.mdx
pages/ipam/how-to/list-ips.mdx
pages/ipam/how-to/manage-ips.mdx
pages/ipam/how-to/reserve-ip.mdx
pages/ipam/quickstart.mdx
pages/public-gateways/how-to/upgrade-public-gateway.mdx

Doc reviews for IPAM + one PGW doc

fix(ipam): reviews

---

tutorials/deploy-istio-kapsule-proxy-protocol/index.mdx

feat(tuto): update tutorial istio

---

tutorials/deploy-automate-mkdocs-site/index.mdx

Added a tutorial to show how to build and deploy an MkDocs static website with GitHub Actions CI/CD.

feat(docs): mkdocs tutorial part two

---

tutorials/deploy-librechat-with-generative-apis/index.mdx

feat(genapi): add tutorial librechat

---

pages/vpc/troubleshooting/index.mdx

Add troubleshooting index for VPC

feat(vpc): add troubleshooting index

---

pages/public-gateways/troubleshooting/index.mdx

feat(pgw): add troubleshooting index

---

pages/block-storage/troubleshooting/index.mdx
pages/data-lab/troubleshooting/index.mdx
pages/object-storage/troubleshooting/index.mdx
pages/serverless-containers/troubleshooting/index.mdx
pages/serverless-functions/troubleshooting/index.mdx
pages/serverless-jobs/troubleshooting/index.mdx
pages/serverless-sql-databases/troubleshooting/index.mdx

docs(gen): add troubleshooting indexes MTA-5747

---

faq/ipam.mdx
pages/ipam/how-to/list-ips.mdx
pages/ipam/how-to/reserve-ip.mdx

fix(ipam): doc review

---

menu/navigation.json
pages/instances/how-to/configure-reverse-dns.mdx
pages/ipam/api-cli/index.mdx
pages/ipam/api-cli/set-ip-reverse.mdx

Add doc for how to configure reverse IPv6 DNS via IPAM, after request from Instances team based on support tickets and IEs

fix(ipam): add doc for reverse IPv6

---

menu/navigation.json
pages/load-balancer/troubleshooting/configuration.mdx
pages/troubleshooting/index.mdx

Add ES troubleshooting to index and to menu, remove erroneous troubleshooting from LB

fix(edge): add troubleshooting indexes

---

pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx
pages/generative-apis/reference-content/supported-models.mdx
pages/managed-inference/reference-content/qwen2.5-coder-32b-instruct.mdx

Fix Qwen Coder maximum context size

fix(genapi): supported models

---

pages/generative-apis/troubleshooting/fixing-common-issues.mdx

Add troubleshooting section for forbidden error.

feat(genapi): add troubleshooting section for forbidden error

---

menu/navigation.json
pages/block-storage/how-to/identify-api-managing-volumes.mdx

docs(bls): add doc on identifying API managing resources MTA-5817

---

pages/kubernetes/reference-content/version-support-policy.mdx

feat(k8s): add Kubernetes 1.32 to version support policy

---

pages/block-storage/how-to/identify-api-managing-volumes.mdx
pages/local-storage/how-to/create-volume-from-snapshot.mdx
pages/local-storage/how-to/delete-snapshot.mdx
pages/local-storage/how-to/delete-volume.mdx
pages/local-storage/how-to/detach-volume.mdx
pages/local-storage/how-to/index.mdx
tutorials/load-overflow-proxmox-and-elastic-metal/index.mdx

fix(gen): fix broken links

---

pages/kubernetes/api-cli/managing-storage.mdx

Add precisions on what the migration technically does

nit: details CSI migration

---

changelog/march2025/2025-03-25-functions-changed-functions-runtimes-update.mdx

feat(changelog): functions-changed-functions-runtimes-update 2025-03-25

---

menu/navigation.json
pages/account/how-to/manage-notifications.mdx

Added documentation on how to use the notification manager.

feat(account): notification manager docs

---

pages/cockpit/how-to/activate-push-traces.mdx

Updated information on how to retrieve traces' push path

fix(ckpt): update traces push path information

---

tutorials/actility-lorawan-operator/index.mdx
tutorials/add-disk-configure-datastore-esxi/index.mdx
tutorials/automate-tasks-using-cron/index.mdx
tutorials/back-up-postgresql-barman/index.mdx
tutorials/deploy-saas-application/index.mdx
tutorials/deploy-wordpress-from-application-library/index.mdx
tutorials/django-ubuntu-focal-fossa/index.mdx
tutorials/encrypt-s3-data-rclone/index.mdx
tutorials/nextjs-app-serverless-functions-sqldb/index.mdx
tutorials/nvidia-triton/index.mdx
tutorials/proxy-protocol-v2-load-balancer/index.mdx
tutorials/rtmp-self-hosted-streaming/index.mdx
tutorials/setup-minecraft/index.mdx

docs(gen): content review 2025-03-27

---

pages/serverless-functions/faq.mdx

feat(functions): runtime migration

---

pages/vpc/how-to/create-private-network.mdx

fix(vpc): fix number of available IPs

---

pages/iot-hub/faq.mdx

fix(iot): review faq

---

pages/edge-services/how-to/configure-custom-domain.mdx
pages/edge-services/quickstart.mdx
pages/instances/how-to/use-private-networks.mdx
pages/object-storage/reference-content/s3-iam-permissions-equivalence.mdx
pages/public-gateways/how-to/configure-a-public-gateway.mdx

Replaced emojis with words for some doc pages to improve accessibility.

docs(gen): removing emojis from some doc pages

---

pages/cockpit/how-to/send-logs-from-k8s-to-cockpit.mdx
pages/cockpit/how-to/send-metrics-from-k8s-to-cockpit.mdx

ext-fix-cockpit
The k8s-monitoring config proposed only works with v2.x, so we should suggest to install the 2.x Helm Chart, otherwise the installation will fail.

docs(cockpit): fix k8s-monitoring Chart version ext-fix-cockpit

---

menu/navigation.json
pages/kubernetes/how-to/recover-space-etcd.mdx

chore(k8s): add new page to menu

---

pages/serverless-containers/faq.mdx

docs(srv): add new entries to FAQ MTA-5829

---

pages/object-storage/faq.mdx
pages/object-storage/how-to/edit-storage-class.mdx
pages/scaleway-cli/reference-content/cli-reference.mdx
pages/serverless-containers/faq.mdx
pages/serverless-sql-databases/api-cli/postgrest-row-level-security.mdx
pages/serverless-sql-databases/how-to/use-row-level-security.mdx

chore(gen): content review MTA-5858

---

pages/vpc/how-to/attach-resources-to-pn.mdx
pages/vpc/troubleshooting/private-dns-dhcp-not-working.mdx

Based on user feedback from the Scaleway Community Slack, add a mention of the .internal part of private network resource hostnames to troubleshooting.

fix(vpc): add troubleshooting info for dns

---

pages/kubernetes/api-cli/managing-storage.mdx

fix(k8s): fix small typo

---

changelog/may2024/2024-05-24-cockpit-added-cockpit-available-in-all-region.mdx
macros/cockpit/plan-deprecation.mdx
pages/cockpit/concepts.mdx
pages/cockpit/faq.mdx
pages/cockpit/how-to/change-data-retention.mdx
pages/cockpit/how-to/create-external-data-sources.mdx
pages/cockpit/how-to/create-token.mdx
tutorials/pushing-metrics-logs-from-scw-instance/index.mdx
tutorials/use-cockpit-with-terraform/index.mdx

- Added new retention periods (from 1 day to 5 years) in the "concepts" page under the "Retention" concept
- Added new FAQ questions => "What is Scaleway data?" and "What is custom data?" with explanation for both
- Added info banner about new pricing updates in FAQ, and "How to change data retention period"
- Added question in FAQ "How am I billed for increasing data retention period" with custom retention pricing examples for 10 days and 3 months in a collapsable bar.
- Added info that Scaleway does not support the Grafana agent
- Added new concepts: "custom data" and "Scaleway data"
- Changed wording from "Tokens" to "Cockpit tokens"
- Deleted concepts previously agreed upon with @sfinet-scw 
I am adding a screenshot of how the banner looks below:
This is a screen recording of how the …

feat(cockpit): retention updates

---

pages/generative-apis/troubleshooting/fixing-common-issues.mdx

Fixed broken links on troubleshooting page.

docs(genapi): fix broken links

---

pages/elastic-metal/troubleshooting/troubleshoot-rescue-your-data.mdx
pages/elastic-metal/troubleshooting/troubleshoot-ssh-issues.mdx

feat(elastic-metal): add page for rescue data for EM in rescue mode and troubleshoot ssh issues

---

menu/navigation.json
pages/serverless-containers/how-to/build-push-container-image.mdx
pages/serverless-jobs/how-to/build-push-container-image.mdx

docs(SRV): add build push image doc for cass & jobs MTA-5835

---

tutorials/configure-apache-lets-encrypt/index.mdx
tutorials/deploy-instances-packer-terraform/index.mdx
tutorials/encrypt-volumes/index.mdx
tutorials/erpnext/index.mdx
tutorials/flask/index.mdx
tutorials/get-started-kubernetes-loadbalancer/index.mdx
tutorials/glpi/index.mdx
tutorials/gpu-super-resolution/index.mdx
tutorials/host-github-runner/index.mdx
tutorials/install-cassandra/index.mdx
tutorials/install-configure-couchdb/index.mdx
tutorials/install-docker-ubuntu-bionic/index.mdx
tutorials/odoo-easy-deploy/index.mdx
tutorials/postgis-managed-databases/index.mdx
tutorials/postman-api/index.mdx
tutorials/protect-server-fail2ban/index.mdx
tutorials/protect-server-using-crowdsec/index.mdx
tutorials/set-up-yunohost-debian/index.mdx
tutorials/setting-up-tunnel/index.mdx
tutorials/setup-mysql/index.mdx

docs(tutorials): content review

---

menu/navigation.json
pages/managed-inference/how-to/create-deployment.mdx
pages/managed-inference/quickstart.mdx
pages/managed-inference/reference-content/supported-models.mdx

docs(inference): update supported model information

---

menu/navigation.json
pages/managed-inference/how-to/import-custom-model.mdx

feat(ai): byom

---

pages/queues/faq.mdx
pages/queues/reference-content/queues-overview.mdx
pages/topics-and-events/faq.mdx
pages/topics-and-events/reference-content/topics-and-events-overview.mdx

Add info based on customer request

feat(mnq): add info about independence from sqs and sns

---

pages/dedibox-rpn/how-to/use-rpn-san-esxi-v7.mdx

fix(rpn): fix rpn-san doc for esxi

---

pages/serverless-containers/troubleshooting/502-error-when-scaling.mdx
pages/serverless-containers/troubleshooting/cannot-create-namespace.mdx
pages/serverless-containers/troubleshooting/cannot-inject-secret-variable.mdx
pages/serverless-containers/troubleshooting/tests-fail-on-container.mdx
pages/serverless-functions/troubleshooting/cannot-create-namespace.mdx
pages/serverless-functions/troubleshooting/cannot-inject-secret-variable.mdx
pages/serverless-functions/troubleshooting/tests-fail-on-function.mdx
pages/serverless-functions/troubleshooting/timeout-error.mdx
pages/serverless-jobs/troubleshooting/cannot-inject-secret-variable.mdx

fix(srv): harmonize H2/H3 in serverless troubleshootings MTA-5945

---

tutorials/configure-plex-s3/index.mdx

fix(S3): update ssh connection to plex server

---

menu/navigation.json
pages/instances/reference-content/choosing-instance-type.mdx
pages/instances/reference-content/choosing-shared-vs-dedicated-cpus.mdx

feat(ins): add doc shared vs dedicated cpu

---

pages/serverless-sql-databases/reference-content/serverless-sql-databases-overview.mdx
pages/serverless-sql-databases/troubleshooting/maximum-prepared-statements-reached.mdx

docs(sdb): update maximum query size MTA-5949

---

pages/guidelines.mdx
pages/iam/reference-content/users-groups-and-applications.mdx
pages/interlink/faq.mdx
pages/managed-inference/how-to/import-custom-model.mdx
pages/public-gateways/reference-content/understanding-v2.mdx
pages/serverless-containers/concepts.mdx

docs(fix): fix broken links

---

pages/serverless-containers/faq.mdx
pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-jobs/reference-content/jobs-limitations.mdx

feat(srvless): image size tips

---

macros/serverless/container-registry-note.mdx
pages/billing/troubleshooting/index.mdx
pages/block-storage/troubleshooting/index.mdx
pages/edge-services/troubleshooting/index.mdx
pages/iam/troubleshooting/index.mdx
pages/load-balancer/troubleshooting/index.mdx
pages/managed-databases-for-postgresql-and-mysql/troubleshooting/index.mdx
pages/object-storage/troubleshooting/index.mdx
pages/serverless-containers/troubleshooting/index.mdx
pages/serverless-functions/troubleshooting/index.mdx
pages/serverless-jobs/troubleshooting/index.mdx
pages/transactional-email/troubleshooting/index.mdx
tutorials/discourse-forum/index.mdx

Fixed some incorrect links. Some were generating 404s on Algolia.

docs(gen): fix links that generated 404s

---

tutorials/create-wordpress-instances-cli/index.mdx
tutorials/foreman-puppet/index.mdx
tutorials/get-started-containers-docker/index.mdx
tutorials/hadoop/index.mdx
tutorials/hestiacp/index.mdx
tutorials/migrate-mysql-databases-postgresql-pgloader/index.mdx
tutorials/processing-images-structured-outputs-pixtral/index.mdx
tutorials/pushing-metrics-logs-from-scw-instance/index.mdx
tutorials/python-lists-dicts/index.mdx
tutorials/send-sms-iot-device-twilio/index.mdx
tutorials/setup-cockroachdb-cluster/index.mdx
tutorials/setup-lamp-stack-ubuntu2204/index.mdx
tutorials/setup-moodle/index.mdx
tutorials/setup-nomad-cluster/index.mdx
tutorials/socket-io/index.mdx
tutorials/using-bucket-website-with-mkdocs/index.mdx

docs(gen): review tutorials 2025-04-22

---

pages/object-storage/how-to/get-started-edge-services.mdx
pages/serverless-containers/how-to/add-trigger-to-a-container.mdx
pages/serverless-functions/how-to/add-trigger-to-a-function.mdx
pages/serverless-functions/reference-content/functions-handlers.mdx

chore(gen): content review MTA-5964

---

tutorials/backup-dedicated-server-s3-duplicity/index.mdx

fix(tuto): update tutorial duplicity

---

pages/serverless-containers/faq.mdx
pages/serverless-containers/how-to/create-manage-delete-containers-namespace.mdx
pages/serverless-functions/faq.mdx
pages/serverless-functions/how-to/create-manage-delete-functions-namespace.mdx

docs(srv): add content on serverless / CR namespaces behavior MTA-5959

---

pages/edge-services/concepts.mdx
pages/edge-services/how-to/configure-cache.mdx
pages/edge-services/how-to/configure-custom-domain.mdx
pages/edge-services/how-to/create-pipeline-bucket.mdx
pages/edge-services/how-to/create-pipeline-lb.mdx
pages/edge-services/how-to/delete-pipeline.mdx
pages/edge-services/how-to/monitor-cockpit.mdx
pages/edge-services/how-to/subscribe-edge-services.mdx
pages/edge-services/how-to/terminate-edge-services.mdx
pages/edge-services/quickstart.mdx
pages/edge-services/reference-content/understanding-ga.mdx
pages/edge-services/reference-content/understanding-pricing.mdx
pages/vpc/troubleshooting/vpc-limitations.mdx

fix(docs): review network docs

---

pages/serverless-containers/faq.mdx
pages/serverless-functions/faq.mdx

docs(srv): add faq entry on cron MTA-5983

---

pages/dedibox-ipv6/how-to/configure-ipv6-linux.mdx
pages/dedibox-scaleway/how-to/configure-failover-ip.mdx
pages/dedibox-scaleway/how-to/configure-reverse-failover-ip.mdx
pages/dedibox-scaleway/how-to/install-dedibox.mdx
pages/dedibox-scaleway/how-to/terminate-dedibox.mdx
pages/instances/troubleshooting/fix-long-delays-booting-without-public-ip.mdx
pages/kubernetes/reference-content/modifying-kernel-parameters-kubernetes-cluster.mdx
tutorials/deploying-qdrant-vectordb-kubernetes/index.mdx
tutorials/monitor-gpu-instance-cockpit/index.mdx
tutorials/sns-instances-notification-system/index.mdx

docs(gen): docs content review compute 2025-04-30

---

tutorials/deploy-istio-kapsule-proxy-protocol/index.mdx

Small indentation issues on the k8s resources for the envoy filters.

docs(kapsule): wrong identation ext-fix-kapsule

---

pages/serverless-functions/troubleshooting/go-function-version-error.mdx

feat(functions):troubleshoot go version

---

pages/generative-apis/troubleshooting/fixing-common-issues.mdx

feat(genapi): add json body invalid troubleshooting

---

pages/edge-services/concepts.mdx
pages/edge-services/quickstart.mdx
pages/public-gateways/troubleshooting/cant-connect-to-instance-with-pn-gateway.mdx
tutorials/get-started-deploy-kapsule/index.mdx

fix(doc): doc review

---

menu/navigation.json
pages/cockpit/faq.mdx
pages/cockpit/reference-content/understanding-cockpit-usage.mdx

The title of this page was confusing for users who thought this page was about Cockpit pricing.

docs(cpt): rename Understanding Cockpit usage and pricing page

---

pages/generative-apis/reference-content/integrating-generative-apis-with-popular-tools.mdx

- Add a langchain integration for function calling
- Update bolt.diy integration to warn customers about compatible models

docs(genapi): add a langchain integration and update bolt.diy integration using GenAPIs

---

pages/instances/reference-content/choosing-shared-vs-dedicated-cpus.mdx

Updated documentation with feedback received from squad

docs(ins): update doc shared/dedicated cpu

---

tutorials/k8s-kapsule-multi-az/index.mdx

fix(tuto): update tuto

---

pages/queues/api-cli/python-node-queues.mdx
pages/topics-and-events/api-cli/python-node-topics-events.mdx

docs(fix): broken links

---

tutorials/cicd-github-action-object-storage-sync/index.mdx

fix(obj): update CICD tutorial with correct env vars MTA-6039

---

pages/object-storage/api-cli/setting-cors-rules.mdx

docs(obj): update CORS doc MTA-6026

---

pages/managed-inference/reference-content/model-catalog.mdx
pages/managed-inference/reference-content/supported-models.mdx

docs(infr): update docs managed inference

---

pages/generative-apis/api-cli/understanding-errors.mdx
pages/generative-apis/how-to/query-embedding-models.mdx
pages/generative-apis/how-to/query-language-models.mdx
pages/generative-apis/how-to/query-vision-models.mdx
pages/generative-apis/how-to/use-structured-outputs.mdx
pages/generative-apis/quickstart.mdx
pages/instances/reference-content/understanding-automatic-network-hot-reconfiguration.mdx
pages/instances/reference-content/understanding-qemu-guest-agent.mdx
pages/kubernetes/reference-content/kubernetes-load-balancer.mdx
pages/kubernetes/reference-content/managing-load-balancer-ips.mdx
pages/kubernetes/reference-content/multi-az-clusters.mdx
pages/kubernetes/reference-content/wildcard-dns.mdx
tutorials/configure-failover-proxmox/index.mdx
tutorials/configure-ipv6-virtual-machine-esxi/index.mdx
tutorials/deploy-k3s-cluster-with-cilium/index.mdx
tutorials/how-to-implement-rag-generativeapis/index.mdx
tutorials/load-overflow-proxmox-and-elastic-metal/index.mdx
tutorials/setup-elastic-metal-proxmox-cluster-with-private-networks/index.mdx
tutorials/wordpress-lemp-stack/index.mdx

docs(gen): docs content review 2025-05-12

---

menu/navigation.json
pages/apple-silicon/how-to/remove-public-ip.mdx
pages/apple-silicon/how-to/use-private-networks.mdx

How to remove public IP address from mac mini

feat(aps): remove public ip

---

pages/key-manager/index.mdx

There was a small mistake in product description in the doc page Key Manager overview, this fixes it

feat(km): replacing product description

---

menu/navigation.json
pages/instances/reference-content/migrating-vms-vmware-scaleway.mdx

Documentation migration VMware virtual machine -> Scaleway Instance

docs(ins): add documentation vmware migration

---

pages/serverless-containers/quickstart.mdx
pages/serverless-functions/quickstart.mdx

Added Guideflows on Quickstart pages

fix(serverless): added guideflow

---

pages/instances/reference-content/choosing-instance-type.mdx

feat(ins): add use cases

---

tutorials/deploy-openwebui-with-generative-apis/index.mdx

Add a fixed version for openwebui deployment with serverless container to ensure cpu and memory limits are right, and deployment will work.

fix(genapi): add fixed version for openwebui deployment

---

pages/vpc/reference-content/dns.mdx

Add info about managing VPC DNS via CLI, for advanced users

fix(vpc): add info about cli dns

---

tutorials/backup-dedicated-server-s3-duplicity/index.mdx

Small error in the sample variable values that were switched

docs(tutorials): Fix typo in duplicity backup tutorial

---

tutorials/send-emails-tem-serverless-framework/index.mdx

fix(srvless): slsfw version

---

pages/container-registry/quickstart.mdx
pages/managed-databases-for-postgresql-and-mysql/quickstart.mdx
pages/managed-databases-for-redis/quickstart.mdx
pages/managed-mongodb-databases/quickstart.mdx
pages/serverless-jobs/quickstart.mdx
pages/serverless-sql-databases/quickstart.mdx

Add Guideflows to Quickstart pages.
In this PR: 
- Container Registry - console overview
- PostgreSQL and MySQL - console overview
- Redis - console overview
- MongoDB - console overview
- SQL Databases - console overview
- Jobs - console overview
[Guideflow tracking](https://docs.google.com/spreadsheets/d/1rQZzpgAB7O57TMb5aHpS5_2EnOAeSt8knIZacMHfn1U/edit?gid=0#gid=0)

fix(db): guideflow in quickstarts

---

pages/instances/api-cli/managing-instance-snapshot-via-cli.mdx
tutorials/building-ai-application-function-calling/index.mdx
tutorials/configure-nginx-lets-encrypt/index.mdx
tutorials/create-openwrt-image-for-scaleway/index.mdx
tutorials/create-serverless-scraping/index.mdx
tutorials/deploy-laravel-on-serverless-containers/index.mdx
tutorials/deploy-mdbooks-serverless-containers/index.mdx
tutorials/deploy-penpot-with-docker-instantapp/index.mdx
tutorials/dhcpcd-dedibox/index.mdx
tutorials/install-github-actions-runner-mac/index.mdx
tutorials/large-messages/index.mdx
tutorials/migrating-docker-workloads-to-kubernetes-kapsule/index.mdx
tutorials/migrating-from-another-managed-kubernetes-service-to-scaleway-kapsule/index.mdx
tutorials/prestashop-dedibox/index.mdx
tutorials/store-s3-cyberduck/index.mdx
tutorials/store-s3-transmit/index.mdx
tutorials/store-wp-mediacloud-s3/index.mdx
tutorials/systemd-essentials/index.mdx
tutorials/terraform-quickstart/index.mdx
tutorials/transform-bucket-images-triggers-functions-deploy/index.mdx
tutorials/vuls-security-scanner/index.mdx
tutorials/wordpress-lemp-stack-focal/index.mdx
tutorials/zabbix-monitoring/index.mdx
tutorials/zammad-ticketing/index.mdx

docs(gen): tutorials content review 2025-05-19

---

pages/edge-services/faq.mdx
pages/edge-services/how-to/configure-waf.mdx
pages/edge-services/reference-content/understanding-waf.mdx

Add info about WAF Object Storage limitation

fix(edge): add info re waf and object storage

---

pages/billing/how-to/use-billing-alerts.mdx

fix(bil): info about alerts

---

menu/navigation.json
pages/elastic-metal/how-to/delete-server.mdx

Added missing deletion documentation for EM

feat(em): add em deletion documentation

---

tutorials/snapshot-instances-jobs/index.mdx

feat(jobs): simplify snapshot tutorial

---

pages/dedibox-dns/how-to/configure-secondary-dns.mdx

docs(ddx): update secondary dns test

---

menu/navigation.json
pages/account/reference-content/use-case-informational-website.mdx
pages/instances/faq.mdx
pages/managed-mongodb-databases/how-to/manage-users.mdx

fix(gen): fix 404

---

pages/serverless-containers/how-to/create-manage-delete-containers-namespace.mdx
pages/serverless-containers/how-to/deploy-container.mdx
pages/serverless-functions/how-to/create-a-function.mdx
pages/serverless-functions/how-to/create-manage-delete-functions-namespace.mdx

docs(srv): add step for tags in faas caas creation docs MTA-6017b

---

menu/navigation.json
pages/nats/faq.mdx
pages/nats/how-to/monitor-nats-cockpit.mdx
pages/nats/troubleshooting/cant-delete-namespace.mdx
pages/nats/troubleshooting/index.mdx
pages/nats/troubleshooting/nats-message-counting.mdx
pages/queues/troubleshooting/approximate-messages-unexpected.mdx
pages/queues/troubleshooting/cant-delete-namespace.mdx
pages/queues/troubleshooting/index.mdx
pages/topics-and-events/how-to/create-manage-subscriptions.mdx
pages/topics-and-events/troubleshooting/cant-confirm-subscription.mdx
pages/topics-and-events/troubleshooting/cant-delete-namespace.mdx
pages/topics-and-events/troubleshooting/index.mdx

Add troubleshooting pages for NATS, Queues and Topics & Events

feat(messaging): add troubleshooting

---

tutorials/connect-generative-apis-sql/index.mdx

Tutorial on how to create an intelligent agent that can analyze Serverless SQL data using natural language queries through Model Context Protocol. See https://github.com/scaleway/docs-content/issues/4961

feat(tutorial): connect generative apis to sql with mcp

---

pages/instances/api-cli/attaching-a-volume.mdx
pages/instances/api-cli/creating-a-volume.mdx
pages/instances/api-cli/creating-backups.mdx
pages/instances/api-cli/detaching-a-volume.mdx
pages/instances/api-cli/increasing-volume-size.mdx
pages/instances/api-cli/managing-instance-snapshot-via-cli.mdx
pages/instances/api-cli/snapshot-import-export-feature.mdx
pages/instances/how-to/create-image-from-snapshot.mdx
pages/instances/how-to/snapshot-import-export-feature.mdx

Update Instances documentation to ensure everything that has moved to Block Storage API is still working

docs(ins): update snapshot documentation

---

pages/audit-trail/faq.mdx

Audit Trail is now available in Warsaw. This MR removes mentions of Audit Trail not being present in Warsaw.

feat(audittrail): adding warsaw in audit trail doc

---

pages/managed-inference/reference-content/model-catalog.mdx

Add maximum context sizes by instances, and add more details to gemma 3 supported image sizes.

fix(inference): add maximum context size by instances

---

pages/managed-inference/how-to/create-deployment.mdx
pages/managed-inference/how-to/delete-deployment.mdx
pages/managed-inference/how-to/import-custom-model.mdx
pages/managed-inference/how-to/manage-allowed-ips.mdx
pages/managed-inference/how-to/managed-inference-with-private-network.mdx
pages/managed-inference/how-to/monitor-deployment.mdx
pages/managed-inference/quickstart.mdx

Add region selector step to Managed Inference documentation

feat(infr): add region selector step

---

pages/troubleshooting/index.mdx

fix(gen): update tb hub list with LinksList component

---

pages/apple-silicon/how-to/access-remote-desktop-mac-mini.mdx

fix(aps): inverse windows vnc clients

---

pages/dedibox-ipv6/how-to/configure-ipv6-windows.mdx
pages/dedibox-ipv6/how-to/enable-ipv6-slaac.mdx
pages/dedibox-ipv6/how-to/request-prefix.mdx
pages/kubernetes/how-to/use-nvidia-gpu-operator.mdx

Compute content review 2025-06-09

docs(compute): review content

---

tutorials/abort-multipart-upload-minio/index.mdx
tutorials/backup-synology-nas-s3-hyper-backup/index.mdx
tutorials/create-openwrt-image-for-scaleway/index.mdx
tutorials/create-valheim-server/index.mdx
tutorials/dhclient-dedibox/index.mdx
tutorials/encode-videos-using-serverless-jobs/index.mdx
tutorials/strapi-app-serverless-containers-sqldb/index.mdx
tutorials/veeam-backup-replication-s3/index.mdx

docs(tutorials): content review 2025-06-09

---

tutorials/power-on-off-instances-jobs/index.mdx
tutorials/snapshot-instances-jobs/index.mdx

docs(srv): Jobs x Instances power cycle tuto MTA-6097

---

macros/compute/serverless-jobs.mdx
pages/organizations-and-projects/additional-content/organization-quotas.mdx

docs(srv): add quotas for Jobs MTA-6094

---

pages/ipam/concepts.mdx
pages/load-balancer/how-to/manage-frontends-and-backends.mdx
pages/load-balancer/quickstart.mdx
pages/vpc/how-to/manage-routing.mdx
pages/vpc/reference-content/understanding-nacls.mdx
pages/vpc/reference-content/understanding-routing.mdx

fix(nw): doc review

---

tutorials/flask/index.mdx

fix missing categories for flask tutorial

---

menu/navigation.json
pages/scaleway-cli/quickstart.mdx
pages/serverless-jobs/how-to/automate-resources-management.mdx

docs(srv): how to automate scw resource mgmt w/ jobs MTA-6074

---

pages/secret-manager/how-to/create-secret.mdx
pages/secret-manager/quickstart.mdx

docs(add): encryption key step

---

pages/block-storage/quickstart.mdx
pages/local-storage/quickstart.mdx

Created and added a guideflow to the Local Storage and Block Storage quickstart pages.

docs(gen): block and local storage guideflows

---

pages/kubernetes/reference-content/lb-ingress-controller.mdx
pages/kubernetes/reference-content/wildcard-dns.mdx

docs(k8s): update documentation

---

pages/elastic-metal/how-to/use-private-networks.mdx

docs(em): update doc for win 2022

---

changelog/june2025/2025-06-25-kubernetes-removed-end-of-support-kubernetes-versions-1.mdx

feat(changelog): kubernetes-removed-end-of-support-kubernetes-versions-1 2025-06-25

---

menu/navigation.json
pages/instances/how-to/use-private-networks.mdx
pages/serverless-containers/concepts.mdx
pages/serverless-containers/faq.mdx
pages/serverless-containers/how-to/create-manage-delete-containers-namespace.mdx
pages/serverless-containers/how-to/use-private-networks.mdx
pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-functions/concepts.mdx
pages/serverless-functions/faq.mdx
pages/serverless-functions/how-to/create-manage-delete-functions-namespace.mdx
pages/serverless-functions/how-to/use-private-networks.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx

feat(srv): add faas/caas x VPC doc MTA-6202

---

pages/account/reference-content/scaleway-network-information.mdx

Fix info on page - see thread on #product-documentation

fix(account): fix network info page

---

pages/data-warehouse/how-to/connect-bi-tools.mdx

docs(dwh): add data warehouse powerBI connection info MTA-6169

---

pages/cockpit/how-to/federate-scaleway-metrics.mdx
pages/cockpit/reference-content/cockpit-supported-endpoints.mdx

Add a new documentation "How-to" on how to federate Scaleway product metrics with the new /federate endpoint on Cockpit datasources.
Also add the endpoint in the `supported endpoint` documentation with precision about beta phase

docs(Cockpit): add new federation documentation for Cockpit - int-add-observability-federate-doc

---

pages/managed-inference/how-to/create-deployment.mdx

feat(infr): add quantization configuration for custom model deployment

---

menu/navigation.json
pages/instances/how-to/migrate-local-storage-to-sbs.mdx

feat(ins): add how-to migrate to sbs

---

pages/object-storage/troubleshooting/cannot-access-data.mdx
pages/object-storage/troubleshooting/error-messages-access.mdx
pages/object-storage/troubleshooting/issues-dns-edge-services.mdx
pages/object-storage/troubleshooting/request-rate-error.mdx
pages/serverless-containers/troubleshooting/cannot-deploy-image.mdx
pages/serverless-containers/troubleshooting/container-error-state.mdx
pages/serverless-functions/troubleshooting/function-build-error.mdx
pages/serverless-sql-databases/troubleshooting/database-unavailable.mdx

docs(gen): add troubleshooting pages MTA-5446

---

menu/navigation.json
pages/serverless-containers/concepts.mdx
pages/serverless-containers/reference-content/serverless-overview.mdx
pages/serverless-functions/concepts.mdx
pages/serverless-functions/quickstart.mdx
pages/serverless-functions/reference-content/serverless-overview.mdx
pages/serverless-jobs/concepts.mdx
pages/serverless-jobs/quickstart.mdx
pages/serverless-jobs/reference-content/serverless-overview.mdx

Add https://github.com/scaleway/docs-content/pull/5018/files to Jobs and Functions

feat(serverless): add overview to jobs and functions

---

pages/elastic-metal/how-to/use-private-networks.mdx
pages/instances/how-to/use-private-networks.mdx
pages/load-balancer/how-to/use-with-private-network.mdx
pages/public-gateways/how-to/configure-a-public-gateway.mdx
pages/vpc/concepts.mdx
pages/vpc/faq.mdx
pages/vpc/how-to/create-vpc.mdx
pages/vpc/how-to/delete-vpc.mdx
pages/vpc/quickstart.mdx
pages/vpc/troubleshooting/cant-delete-vpc-pn.mdx

Two new behaviours are coming:
- Possibility to delete default VPCs, and removal of the whole concept of default VPCs from the console
- Possibliity to create a new VPC "inline" while attaching a resource to a new Private Network

fix(vpc): update for deletion of default VPC, and lazy-VPC-create

---

menu/navigation.json
pages/partner-space/how-to/track-client-consumption.mdx

Added a new page on how Resellers can track their clients' consumption

feat(partners): track client consumption

---

pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx

docs(srv): remove sandbox limitation for VPC MTA-6287

---

pages/serverless-containers/troubleshooting/cannot-access-container.mdx
pages/serverless-containers/troubleshooting/index.mdx
pages/serverless-containers/troubleshooting/known-dns-containers-errors.mdx

feat(srv): add troubleshooting pages MTA-5446

---

pages/serverless-sql-databases/troubleshooting/connection-errors.mdx

fix(srv): fix broken table

---

tutorials/migrate-databases-instance/index.mdx

fix(dbaas): specify postgresql client version

---

tutorials/power-on-off-instances-jobs/index.mdx
tutorials/snapshot-instances-jobs/index.mdx

fix(srv): add missing env var for jobs x cli tuto MTA-6305

---

pages/file-storage/how-to/mount-file-system.mdx
pages/file-storage/how-to/unmount-file-system.mdx
pages/file-storage/index.mdx
pages/file-storage/quickstart.mdx

fix(fls): fix link to API doc + other fixes

---

pages/public-gateways/how-to/use-ssh-bastion.mdx
pages/public-gateways/troubleshooting/index.mdx
pages/public-gateways/troubleshooting/ssh-key-format.mdx

Add troubleshooting doc for checking SSH bastion keys in Cockpit vs console

feat(pgw): add troubleshooting doc for ssh bastion keys

---

pages/iot-hub/concepts.mdx
pages/iot-hub/faq.mdx

fix(iot): add mqtt version limitation

---

pages/vpc/faq.mdx
pages/vpc/reference-content/understanding-routing.mdx
pages/vpc/troubleshooting/vpc-limitations.mdx

Add speifications re: Serverless x VPC routing

Int fix serverless routing

---

menu/navigation.json
pages/organizations-and-projects/additional-content/organization-quotas.mdx
pages/serverless-containers/how-to/use-private-networks.mdx
pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-containers/reference-content/containers-private-networks.mdx
pages/serverless-functions/how-to/use-private-networks.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx
pages/serverless-functions/reference-content/functions-private-networks.mdx

docs(srv): add srv x vpc ref content

---

menu/navigation.json
pages/key-manager/concepts.mdx
pages/key-manager/faq.mdx
pages/key-manager/how-to/delete-km-keys.mdx
pages/key-manager/how-to/recover-deleted-keys.mdx

- Added FAQ question "What happens if I delete a key?" 
- Updated deletion page
- Added "How to recover keys scheduled for deletion" page
- Added "Scheduled deletion" concept

key-manager(add): scheduled deletion docs

---

pages/public-gateways/reference-content/understanding-v2.mdx
pages/vpc/how-to/activate-dhcp.mdx
pages/vpc/troubleshooting/autoconfig-not-working.mdx
pages/vpc/troubleshooting/resource-attached-no-ip.mdx

fix(review): review doc

---

tutorials/metabase-postgre-containers-private-networks/index.mdx

docs(srv): add Metabase x VPC x CaaS tutorial MTA-6298

---

pages/organizations-and-projects/additional-content/organization-quotas.mdx

fix(nats): fix quotas

---

pages/serverless-jobs/how-to/monitor-job.mdx

doc(jobs): add network metrics

---

pages/key-manager/how-to/create-km-key.mdx

feat(km): add available algorithms

---

macros/serverless-jobs/automate-resources-management.mdx
menu/navigation.json
pages/serverless-jobs/how-to/execute-complex-commands.mdx
pages/serverless-jobs/troubleshooting/index.mdx
pages/serverless-jobs/troubleshooting/job-startup-command-fails.mdx

docs(srv): how to run complex commands with Jobs and Secrets MTA-6354

---

menu/navigation.json
pages/apple-silicon/how-to/adjust-available-bandwidth.mdx
pages/apple-silicon/how-to/create-mac-mini.mdx

feat(aps): add more bandwidth feature

---

pages/serverless-containers/concepts.mdx
pages/serverless-containers/faq.mdx
pages/serverless-containers/reference-content/containers-limitations.mdx
pages/serverless-containers/troubleshooting/http1-errors.mdx
pages/serverless-containers/troubleshooting/index.mdx
pages/serverless-functions/concepts.mdx
pages/serverless-functions/faq.mdx
pages/serverless-functions/reference-content/functions-limitations.mdx
pages/serverless-functions/troubleshooting/http1-errors.mdx
pages/serverless-functions/troubleshooting/index.mdx

docs(srv): add info on supported http protocols MTA-6409

---

pages/dedibox-account/how-to/create-a-dedibox-account.mdx
pages/dedibox-account/how-to/outsource-failover-ip.mdx
pages/dedibox-dns/how-to/add-dns-delegation.mdx
pages/dedibox-hardware/how-to/configure-raid-kvm-p410.mdx
pages/dedibox-hardware/how-to/configure-raid-kvm-p420.mdx
pages/dedibox-ip-failover/how-to/configure-multiip-virtualmac.mdx
pages/dedibox-ipv6/how-to/create-subnet.mdx
pages/dedibox-network/how-to/subscribe-to-jmrp.mdx
pages/dedibox-rpn/how-to/connect-rpn-san-windows.mdx
pages/dedibox-rpn/how-to/connect-rpn-san.mdx
pages/dedibox-rpn/how-to/use-rpn-san-esxi-v7.mdx
pages/dedibox-rpn/how-to/use-rpn-san-esxi.mdx
pages/dedibox-rpn/how-to/use-rpn-vpn.mdx
pages/dedibox-scaleway/concepts.mdx
pages/dedibox/how-to/manage-packages.mdx
pages/elastic-metal/concepts.mdx
pages/elastic-metal/how-to/create-server.mdx
pages/elastic-metal/how-to/install-server.mdx
pages/elastic-metal/how-to/use-rescue-mode.mdx
pages/instances/reference-content/manual-configuration-private-ips.mdx
pages/instances/reference-content/preventing-outgoing-ddos.mdx
pages/instances/reference-content/understanding-differences-x86-arm.mdx
pages/kubernetes/how-to/monitor-cluster.mdx

docs(ddx): content review 2025-08-27

---

pages/kubernetes/how-to/manage-allowed-ips.mdx

Note is wrong, feature is also available on classic kapsule

chore(k8s): remove note about allowed IP configuration

---

pages/elastic-metal/troubleshooting/troubleshoot-remote-access-issues.mdx
tutorials/protect-server-fail2ban/index.mdx

docs(em): update doc fail2ban

---

pages/kubernetes/api-cli/managing-storage.mdx

remove deprecated documentation

chore(kapsule): remove part on SBS CSI migration

---

pages/apple-silicon/how-to/manage-commitment-plan.mdx
pages/dedibox-account/how-to/resolve-abuse.mdx
pages/dedibox-hardware/concepts.mdx
pages/dedibox-kvm-over-ip/concepts.mdx
pages/dedibox-kvm-over-ip/quickstart.mdx
pages/dedibox-network/troubleshooting/network-troubleshooting.mdx
pages/dedibox/reference-content/basic-linux-commands.mdx
pages/elastic-metal/how-to/change-billing-period.mdx
pages/gpu/how-to/create-manage-gpu-instance.mdx
pages/gpu/quickstart.mdx
pages/gpu/reference-content/understanding-nvidia-nvlink.mdx
pages/instances/api-cli/migrating-instances.mdx
pages/instances/how-to/power-off-instance.mdx
pages/kubernetes/how-to/access-audit-logs.mdx
pages/kubernetes/how-to/deploy-x86-arm-images.mdx
pages/kubernetes/troubleshooting/containers-not-starting-arm-instances.mdx

chore(gen): docs content review

---

pages/managed-inference/reference-content/supported-models.mdx

Several links only have "https:/" instead of "https://" following this MR: https://github.com/scaleway/docs-content/commit/22f3cbbb787996c62d7925ec9c52e1cba95d6a0e

feat(inference): fix external links

---

pages/instances/troubleshooting/cant-connect-ssh.mdx

docs(ins): fix wrong doc

---

pages/object-storage/api-cli/bucket-operations.mdx

fix(obj): update DeleteBucket doc

---

pages/block-storage/how-to/create-a-volume.mdx
pages/block-storage/troubleshooting/index.mdx
pages/object-storage/troubleshooting/index.mdx
pages/serverless-containers/troubleshooting/index.mdx
pages/serverless-functions/reference-content/functions-sandbox.mdx
pages/serverless-functions/troubleshooting/index.mdx
pages/serverless-jobs/troubleshooting/index.mdx

chore(gen): content review MTA-6514

---

pages/object-storage/api-cli/setting-cors-rules.mdx

fix(obj): Add info on Cors IAM permissions 

---

pages/guidelines.mdx

Add guidance for slugs and product names in URLs

fix(guidelines): add for urls

---

pages/file-storage/concepts.mdx

fix(blk): remove unrelated concepts MTA-6577

---

pages/cockpit/how-to/send-metrics-from-k8s-to-cockpit.mdx

ext-fix-cockpit
alloy-metric agent looks at annotation at the Pod level, not deployment.
Changed the deployment example and added a little warning in the preceding explanation.
You can refer here for the original helm chart [documentation](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-annotation-autodiscovery) which clearly state : 
> With this feature enabled, any Kubernetes Pods or Services with the k8s.grafana.com/scrape annotation set to true will be automatically discovered and scraped by the collector.

docs(cockpit): k8s-monitoring autodiscovery annotations placement. ext-fix-cockpit

---

pages/nats/concepts.mdx
pages/nats/faq.mdx
pages/nats/how-to/create-account.mdx
pages/nats/how-to/create-credentials.mdx
pages/nats/how-to/delete-account.mdx
pages/nats/how-to/manage-credentials.mdx
pages/nats/how-to/monitor-nats-cockpit.mdx
pages/nats/quickstart.mdx
pages/queues/api-cli/connect-aws-cli.mdx
pages/queues/api-cli/queues-aws-cli.mdx
pages/queues/concepts.mdx
pages/queues/how-to/create-credentials.mdx
pages/queues/how-to/create-manage-queues.mdx
pages/queues/how-to/manage-credentials.mdx
pages/queues/how-to/monitor-queues-cockpit.mdx
pages/queues/quickstart.mdx
pages/queues/reference-content/limitations.mdx

fix(docs): review
